#!/usr/bin/env python

import numpy as np

pi = "stat.dat"
po = "traj.dat"

vv = ['t', 'm2', 'c2x', 'c2y', 'c2z', 'v2x', 'v2y', 'v2z', 
        'vlmx', 'vlmy', 'vlmz', 'vl2x', 'vl2y', 'vl2z', 'pd']

d = np.genfromtxt(pi, names=True)

fo = open(po, 'w')

def W(s):
    fo.write(s + '\n')

W(' '.join(vv))

for i in range(len(d)):
    W(' '.join([str(d[i][v]) for v in vv]))
