#!/usr/bin/env python

c = {}
exec(open("../par.py").read(), None, c)

o="par.conf"

c['vels'] = "{:} {:} {:}".format(*(c['vel']))

c['loc'] = 1 if c["np"] == 1 else 0

c['mu2'] = c['mu0'] * c['mu']
c['rho2'] = c['rho0'] * c['rho']

t = '''set double tmax {tmax}
set double dump_field_dt {dumpdt}
set double dump_part_dt {dumpdt}
set double sigma {sig}
set double mu1 {mu0}
set double mu2 {mu2}
set double rho1 {rho0}
set double rho2 {rho2}
set int vfsmooth {chsm}
set vect vel {vels}
set int loc {loc}
set int dim {dim}
'''.format(**c)

if c['pois']:
    t += '''
set string vel_init pois
set double poisvel {poisvel}
set vect force {pgrad} 0 0 
    '''.format(**c)

if c['meshvel']:
    t += '''
set string meshvel_auto v
set double meshvel_weight 0.5
set vect meshvel_mask 1 0 0
    '''.format(**c)

dim = c['dim']

for d in ['x', 'y', 'z'][0:dim]:
    if c['wall' + d]:
        t += ''' 
set int hypre_periodic_{d} 0
set string bc_{d}m wall 0 0 0
set string bc_{d}p wall 0 0 0
    '''.format(d=d)

open(o, 'w').write(t)

