#!/bin/bash

cat > par.py << EOF
Lnarrow = 1.5
Lwide = 1.
np = 256
nx = 512
bs = 16

dim = 3
dump_field_dt = 0.05
tmax = 10.
Hnarrow = 0.1
thickness = 0.05

EOF

./gen
#killall ap.mfer &> /dev/null || true
nice make cleanrun
