#!/bin/bash

cat > par.py << EOF
Lnarrow = 0.6
Lwide = 3
np = 8192
nx = 1024
bs = 16
Ca = 0.5
rho = 0.1
Re = 100.

dt0 = 0.0001
dim = 3
dump_field_dt = 0.02
tmax = 100.
bublength = 4.
#Hnarrow = 0.1
#thickness = 0.05

EOF

#killall ap.mfer &> /dev/null || true
#make cleanall
#make conf
make cleanrun
