#!/bin/bash -l

(cd ../ && make install) > /dev/null

r () {
  echo $1
  t=tmp
  sh -c "
    make -C ../../ install
    ch.conf . -DEXTRA='-grid=multigrid3D $1'
    make clean
    make
    ba.env ba.run main.s
  " &> $t
  if [ $? ] ; then
    #grep "warning Using" $t
    grep "time elapsed" $t
    grep "cstats" $t
  else
    cat $t
  fi
}

r "-DCURV_ORIG"
r "-DCURV_PARTSTR -DPS_itermax=20 -DPS_eps=0"
r "-DCURV_LEARN -DLEARN_N80"
r "-DCURV_LEARN -DLEARN_N10"
