#!/bin/bash

set -eu

ev () {
  echo "$@"
  eval "$@"
}

a=a.png

f=b.pdf

w=184
h=192
x0=23
y0=27
dx=188.5
dy=205

# Fig. 2
qq="0 50 100 150 250 350 500 650 950 1350 1750 2200"

nx=6
ny=2
j=0
for iy in `seq 0 $(($ny-1))` ; do
  for ix in `seq 0 $(($nx-1))` ; do
    x=`bc -l <<< "$x0+$ix*$dx"`
    y=`bc -l <<< "$y0+$iy*$dy"`
    q=`cut -d ' ' -f $(($j+1)) <<< "$qq"`
    q=$(($q / 50))
    f=a`printf "%02d" "$q"`.png
    ev convert "'$a' -crop ${w}x${h}+${x}+${y} +repage '$f'"
    let "j=$j+1"
  done
done
