#!/bin/bash

set -eu

for _i ; do
  export "${_i}"
  export -n "${_i}"
done

_cmd="$0"
for _i ; do
  _k="${_i%%=*}"
  _v="${_i##*=}"
  if echo "$_v" | grep -q '[ \t]' ; then _v="\"${_v}\"" ; fi
  _cmd="${_cmd} ${_k}=${_v}"
done


: ${np=64}
: ${nx=064}
: ${r=0.01}
: ${ns=3}
: ${symm=0}
: ${nfr=40}
: ${ba=1}
: ${bap=1}
: ${bal=1}
: ${ch=1}
: ${suff=}
: ${tmax=0.4}
: ${wall=0}
: ${tl=1440}
: ${Oh=0.005}
: ${vert=0}
: ${dumplist="vf"}

d="nx${nx}"

[ "$symm" == "1" ] && d=${d}s

d="${d}_oh${Oh}_wall${wall}_tmax${tmax}"
[ $ch == "1" ] && runch= || runch="echo > r_ch"
[ $ba == "1" ] && runba= || runba="echo > r_ba"
[ $bap == "1" ] && runbap= || runbap="echo > r_bap"
[ $bal == "1" ] && runbal= || runbal="echo > r_bal"


if [ "$wall" == "1" ] ; then
  bcod=-0.5
  bcor=1
else
  bcod=0
  bcor=0
fi

if [ "$vert" == "1" ] ; then
  d=${d}_vert
  b2xr="0 0 2"
  [ "$wall" == "1" ] && bcor=2
else
  b2xr="2 0 0"
fi

d=$d$suff

echo $d
mkdir $d

rsync -aL dummy/. $d

cd $d

o=gen1

cat > $o << EOG
#!/bin/bash

set -eu

echo $np > np
echo $tl > tl

# ${_cmd}
# np=$np
# nx=$nx
# r=$r
# ns=$ns
# symm=$symm
# nfr=$nfr
# ba=$ba
# bap=$bap
# bal=$bal
# ch=$ch
# tmax=$tmax
# wall=$wall
# Oh=$Oh

./gen -nx $nx -np $np -mode osc -dim 3 -pos center \\
  -We 0 -Oh $Oh -tmax $tmax -br 0.15 \\
  -mu $r -rho $r \\
  -symmxy $symm -wallz $wall \\
  -bcod 0 0 $bcod -bcor 0 0 $bcor \\
  -b2xr $b2xr -b2rr 1 \\
  -nb 2 -nfr $nfr -part_ns $ns


cat > ch/add.conf << EOF
set string dumpformat default
set string dumplist $dumplist
EOF

$runch
$runba
$runbap
$runbal

EOG

chmod +x $o

./$o
