#!/bin/bash

set -eu

for d in nx* ; do
  for s in bap bal ; do
    o=$d/$s
    fu="$o/u_000000.vtk"
    if [ ! -f "$fu" ] ; then
      echo "skip non existing $fu"
      continue
    fi
    f=$o/a.mp4
    if [ -f "$f" ] ; then
      echo "skip existing $f"
      continue
    fi
    e="vis3ba.py"
    [ "$s" == "ch" ] && e="vis3chvf.py"
    [ "$s" == "bap" ] && e="vis3bap.py"
    [ "$s" == "bal" ] && e="vis3bap.py"
    c="(cd $d/$s ; ../$e . || true ; r.pngmp4 || true)"
    echo "$c"
    eval "$c"
  done
done
