#!/bin/bash

set -eu

np=512
nx=64
r=0.01

echo $np > np
echo 1440 > tl

./gen -nx $nx -np $np -mode osc -dim 3 -pos center\
  -We 0 -La 12000 -tmax 10 -br 0.15\
  -mu $r -rho $r -wally 0 -wallz 0\
  -bcod 0 0 0 -bcor 0 0 0 -bcoh 0 0 0 \
   -b2xr 2.25 0 0 -b2rr 1 \
   -nb 2 -nfr 100


cat > ch/add.conf << EOF
set string dumpformat default
set string dumplist

set vect force_mov 0.01 0 0
set vect force_mov_x0 0.18 0.5 0.5
set vect force_mov_x1 0.3 0.5 0.5
set double force_mov_t0 1
set double force_mov_t1 3
set vect force_mov_sig 0.05 0.2 0.2

set vect force_mov2 -0.01 0 0
set vect force_mov2_x0 0.82 0.5 0.5
set vect force_mov2_x1 0.7 0.5 0.5
set double force_mov2_t0 1
set double force_mov2_t1 3
set vect force_mov2_sig 0.05 0.2 0.2

set string conv exp
set int max_iter 2
#set double prelax 1
#set double vrelax 1

EOF
