#!/bin/bash

t0=0
t1=3
f1x="0.3 0.5 0.5"
f2x="0.7 0.5 0.5"
cat > par.conf << EOF
set string dumpformat default
set string dumplist

set vect force_mov 0.005 0 0
set vect force_mov_x0 0.12 0.5 0.5
set vect force_mov_x1 $f1x
set double force_mov_t0 0
set double force_mov_t1 $t1
set vect force_mov_sig 0.05 0.2 0.2

set vect force_mov2 -0.005 0 0
set vect force_mov2_x0 0.88 0.5 0.5
set vect force_mov2_x1 $f2x
set double force_mov2_t0 0
set double force_mov2_t1 $t1
set vect force_mov2_sig 0.05 0.2 0.2

EOF

cat > vofm.conf << EOF
setnext string ev $t1 set vect force_mov_x0 $f1x
setnext string ev $t1 set double force_mov_t0 $t1
setnext string ev $t1 set double force_mov_t1 1e10

setnext string ev $t1 set vect force_mov2_x0 $f2x
setnext string ev $t1 set double force_mov2_t0 $t1
setnext string ev $t1 set double force_mov2_t1 1e10

set double cflst 0.5
set string advection_solver vofm
EOF

nx=64
bs=8
cat > par.make << EOF
m = $nx $nx $nx 
bs = $bs $bs $bs
np = 512
tl = 1440
EOF

cat > b.dat << EOF
0.33125 0.5 0.5 0.15 0.15 0.15
0.66875 0.5 0.5 0.15 0.15 0.15
EOF
