#!/bin/bash

set -eu

. ap.setenv
. ../util

instfnd applycopyright
instfnd argmax
instfnd argmaxall
instfnd cawk
instfnd copyright
instfnd deriv
instfnd diff
instfnd diffnum
instfnd downsample
instfnd downsampleall
instfnd findsource
instfnd format
instfnd genxmf
instfnd genxmfall
instfnd getcol
instfnd gettraj
instfnd gettrajcol
instfnd gettrajm
instfnd gettrajsh
instfnd getval
instfnd hist
instfnd histbin
instfnd intcol
instfnd kedr
instfnd line
instfnd makearg
instfnd order
instfnd part
instfnd part0
instfnd plain2vtk
instfnd scale
instfnd spawn
instfnd statcopy
instfnd task
instfnd trajaxes
instfnd vtkcolorall

cp -rvf aphros "$BB/" || true
cp -vf paratools.py "$BB/" || true

