#!/bin/bash 

set -eu

. ch.prefix
. ../util

instfnd getcol
instfnd gettraj
instfnd gettrajsh
instfnd deriv
instfnd scale
instfnd kedr
instfnd statcopy
instfnd part0
instfnd part
instfnd diff
instfnd diffnum
instfnd makearg
instfnd spawn
instfnd task

cp -rvf ch "$BB/"

