#!/bin/bash

set -eu

. ap.setenv
. ../util


instfnd applycopyright
instfnd argmax
instfnd argmaxall
instfnd cawk
instfnd conf
instfnd confdeb
instfnd copyright
instfnd deriv
instfnd diff
instfnd diffnum
instfnd downsample
instfnd downsampleall
instfnd findsource
instfnd format
instfnd genxmf
instfnd genxmfall
instfnd getcol
instfnd gettraj
instfnd gettrajcol
instfnd gettrajm
instfnd gettrajsh
instfnd getval
instfnd hausdorff
instfnd hist
instfnd histbin
instfnd intcol
instfnd job
instfnd job0
instfnd kedr
instfnd kill 
instfnd line
instfnd makearg
instfnd mpirun
instfnd order
instfnd part
instfnd part0
instfnd plain2vtk
instfnd run
instfnd run0
instfnd scale
instfnd spawn
instfnd statcopy
instfnd submit
instfnd submit0
instfnd sysinfo
instfnd task
instfnd trajaxes
instfnd vtkcolorall
instfnd writearg

cp -rvf aphros "$BB/" || true
cp -rvf paratools "$BB/" || true

