#!/bin/sh

set -eu

if [ "$#" != "1" ] ; then
  echo "usage: $0 FILE
Adds copyright notice to FILE if 'Copyright' if not found in first 10 lines
"
  exit 1
fi

file=$1

if head -n 10 "$file" | grep -qi "copyright" ; then
  exit 1
fi

echo "adding copyright to '$file'" 1>&2

head=$(ap-copyright "$file")
text=$(cat "$file")

echo "$head" > $file
echo "$text" >> $file
