#!/bin/sh

set -eu

if [ "$#" != "1" ] ; then
  echo "usage: $0 FILE
Adds copyright notice to FILE if 'Copyright' if not found in first 10 lines
"
  exit 1
fi

file=$1

tmp=/tmp/copyrightapply.tmp.$$
trap 'rm -f $tmp; exit 2' 1 2 3 4 15

if head -n 10 "$file" | grep -q "Copyright" ; then
  exit 1
fi

echo "adding copyright to '$file'" 1>&2

ap-copyright "$file" > $tmp
echo >> $tmp
cat "$file" >> $tmp

cat $tmp > "$file"

status=$?
rm -f $tmp
exit $status
