#!/bin/sh

set -eu

if [ "$#" != "1" ] || [ "$1" = "-h" ] ; then
  cat << EOF
usage: $(basename "$0") [-h] FILE
Adds copyright notice to FILE if 'copyright' if not found in first 10 lines.
EOF
  exit 1
fi

file=$1

head=$(head -n 10 -- "$file" )
if echo "$head" | grep -qi "copyright" ; then
  exit 1
fi

echo "adding copyright to '$file'" 1>&2

head=$(ap-copyright "$file")
text=$(cat "$file")

echo "$head" > $file
echo "$text" >> $file
