#!/usr/bin/env python

# Compute derivative du/dt 
# Input:
# u,t: ascii columns
# Output:
# du/dt: ascii column

import numpy as np
import sys
import os

# compute derivative, forward difference, extrapolate at last point
# u: function, 1d array
# t: intependent variable, 1d array
def GetDeriv(u, t):
  dt = np.roll(t, -1) - t
  dt[-1] = dt[-2]
  du = np.roll(u, -1) - u
  du[-1] = du[-2]
  return du / dt

ut = np.loadtxt(sys.stdin)

dudt = GetDeriv(ut[:,0], ut[:,1])

np.savetxt(sys.stdout, dudt)
