#!/bin/bash

set -eu

e () {
  echo "$@" 1>&2
  eval "$@"
}

if [ "${1:-x}" == "-h" ] ; then
  echo "usage: $0 [-y]
Finds C/C++ source files recursively from current directory.
"
  exit 1
fi

list=/tmp/findsource.$$
tmp=/tmp/tmp.$$
trap 'rm -f $list $tmp; exit 2' 1 2 3 4 15

eval "find . -type f \
-name '*.h' -or \
-name '*.hpp' -or \
-name '*.ipp' -or \
-name '*.cpp' -or \
-name '*.c' | grep -v CMake > $list"

# 'clang-format -i' replaces symlinks with regular files
rm -f "$tmp"
while read line ; do
  if [ -L "$line" ] ; then
    echo "$line"
  else
    echo "$line" >> "$tmp"
  fi
done < "$list"
mv "$tmp" "$list"

cat $list

status=$?
rm -f $list
exit $status
