#!/bin/bash

set -eu

e () {
  echo "$@"
  eval "$@"
}

if [ "${1:-x}" == "-h" ] ; then
  echo "usage: $0 [-y]
Run clang-format for C/C++ files found recursively from current directory.
Options:
  -y
      Force 'yes' to all questions.
      "
  exit 1
fi

force=0
if [[ "${1:-x}" == "-y" ]] ; then
  force=1
fi

list=/tmp/clang-format-list.$$
tmp=/tmp/tmp.$$
trap 'rm -f $list $tmp; exit 2' 1 2 3 4 15

e "find . -type f \
-name '*.h' -or \
-name '*.hpp' -or \
-name '*.ipp' -or \
-name '*.cpp' -or \
-name '*.c' | grep -v CMake > $list"

# 'clang-format -i' replaces symlinks with regular files
echo "Excluded symlinks:"
rm -f "$tmp"
while read line ; do
  if [ -L "$line" ] ; then
    echo "$line"
  else
    echo "$line" >> "$tmp"
  fi
done < "$list"
mv "$tmp" "$list"

echo "Remaining files:"
cat $list

cmd="clang-format -i"
echo "Running '$cmd' for these files."

re=
if [ "$force" == "1" ] ; then
  re='y'
else
  read -r -p "Proceed? [y/N] " re
fi

if [[ "$re" == "y" ]] ; then
    cat "$list" | xargs $cmd
    rm -v "$list"
    echo Done
    exit 0
else
    rm -v "$list"
    echo Abort
    exit -1
fi

status=$?
rm -f $list
exit $status
