#!/usr/bin/env python3

import scipy
import argparse

import aphros

parser = argparse.ArgumentParser(
    description="Computes the Hausdorff distance between two sm_*.vtk files")
parser.add_argument('vtk_a', type=str)
parser.add_argument('vtk_b', type=str)
args = parser.parse_args()

xa, _, _ = aphros.ReadVtkPoly(args.vtk_a)
xb, _, _ = aphros.ReadVtkPoly(args.vtk_b)

d = scipy.spatial.distance.directed_hausdorff(xa, xb)[0]

print(d)
