#!/usr/bin/env python

import numpy as np
import sys
import os


av = sys.argv

if len(av) > 1 and av[1] == '-h':
  print("usage: {:} [--density]".format(os.path.basename(av[0])))
  print('''
print histogram of STDIN as columns [center,density,left,right]
''')
  exit(1)

d = np.loadtxt(sys.stdin)
density = "--density" in av
val,edge = np.histogram(d, bins='auto', density=density)
left = edge[:-1]
right = edge[1:]
center = (left + right) * 0.5
np.savetxt(sys.stdout, np.transpose([center, val, left, right]))
