#!/usr/bin/env python

# Returns args for sim/base.makefile from par.conf
# $1: directory containing par.conf (defaults to '.')

import ch
import sys

v = sys.argv

b = '.' if len(v) < 2 else v[1]
c = ch.ReadPar(b)

print(ch.GetMakeArg(c))
