#!/usr/bin/env python

import sys
import numpy as np
import os

fin = sys.stdin
av = sys.argv

if len(av) > 1 and av[1] == '-h':
  print('''Prints convergence order from accuracy estimates on to meshes.
STDIN: 
  nx_A  error1_A error2_A
  nx_B  error2_B error2_B
''')
  exit(1)

va = np.array(fin.readline().split()).astype(float)
vb = np.array(fin.readline().split()).astype(float)
order = -np.log(va[1:] / vb[1:]) / np.log(va[0] / vb[0])
print(" ".join(map(str, order)))

