#!/bin/bash

# Partition based on files: mesh bs np
#   mesh contains mesh size: 
#   bs contains block size: bsx, bsy, bsz
#   np contains number of processors
# Create mesh.conf

n=`cat mesh`
bs=`cat bs`
np=`cat np`

a="`ch.part0 $n $bs $np`"

IFS=' ' read px py pz bx by bz <<< $a
IFS=' ' read bsx bsy bsz <<< $bs

o="mesh.conf"

echo "set int px $px
set int py $py
set int pz $pz

set int bx $bx
set int by $by
set int bz $bz

set int bsx $bsx
set int bsy $bsy
set int bsz $bsz
" > $o
