#!/bin/bash

set -eu

if [ "$#" -lt "1" ] || [ "$1" == "-h" ] ; then
    cat << EOF
usage: `basename $0` [-h] TASKDIR
TASKDIR: directory containing executables.
Creates new working directory 'w_NN' with minimal unique NN.
While TASKDIR not empty, moves an executable to w_NN and runs.

EOF
    exit 1
fi

t=$(realpath "$1")
echo "watching tasks in '$t'"

nw=`ls -d w_* 2> /dev/null | wc -w || true`
nw=$(printf "%02d" "$nw")

w="w_$nw"

echo "creating working directory '$w'"
mkdir "$w"

cd "$w"
while true ; do
  f=$(find "$t" -maxdepth 1 -type f -executable | head -n 1)
  if [ -z "$f" ] ; then
    break
  fi
  fb=$(basename "$f")
  echo "$fb"
  mv "$f" .
  ./$fb
  sleep 1
done

echo "done '$w'"
