#!/usr/bin/env python

import os
import sys

def sh(s, fatal=True, silent=True):
    if not silent:
        print(s)
    r = os.system(s)
    assert not fatal or r == 0

av = sys.argv

# current directory
cd = os.getcwd()

if len(av) < 2 or av[1] == "-h":
    print("""usage: {:} DATOUT
Creates task to generate config and compute.
Base simulation setup is the content of current directory.
The task can be executed from any directory.
It copies the base setup to its working directory,
runs commands to generate config and executes './run'.
Output expected in 'dat' is moved to DATOUT
STDIN: commands to generate config
DATOUT: suffix for output

STDOUT: task
""".format(os.path.basename(av[0])))
    exit(1)

od = os.path.realpath(av[1])  # output dir

dm = cd  # dummy

cmd = sys.stdin.read()  # commands to generate config

# log
l = "out"
sys.stdout.write("""#!/bin/bash

set -eu

if [ -e "{od}" ] ; then
  echo "skip existing '{od}'"
  exit 0
fi

rsync -a "{dm}/." .
{cmd}
./run &>> {l}
mv dat "{od}"
""".format(**locals()))
