#!/bin/bash

set -eu

trajr=$1
cl=$(basename "$trajr")
cl=${cl#*_}
cl=${cl%.csv}
: ${vtkin=../sm_%04d.vtk}
: ${vtkout=smcl_${cl}_%.vtk}

ch.cawk -v vtkin="$vtkin" -v vtkout="$vtkout" '
  {
    s = sprintf("ch.filter -f cl -p %%s %%d -- %s", vtkin)
    s = sprintf(s, vtkout, $cl, $n)
    print s | "cat >&2"
    #err=system(s) 
    if (err) {
      print "error: " , s | "cat >&2"
      exit 2
    }
  }
' "$trajr"
