#!/usr/bin/env python3

import aphros

var = aphros.Var()
var["key0"] = 0
var["key5"] = 0
var["key5"] = 2
var["key1"] = 0.
var["key2"] = "str"
var["key3"] = [0, 1, 2]
print(var.Generate())
print()

geom = aphros.Geometry()
geom.Box(center=[0,0,0], halfsize=[1,1,1], rotation_z=5)
geom.Box(center=[0,2,2], halfsize=[1,1,1], rotation_z=5)
geom.Box([0,3,0], [4,1,1], intersect=1, invert=0)
geom.Box([0,3,0], [4,1,1], intersect=0, invert=1)
geom.Box([0,3,0], [4,1,1], intersect=1, invert=1)
geom.Sphere([0,3,0], [4,1,1], intersect=1, invert=1)
geom.Cylinder(center=[0,3,0], normal=[4,1,1], radius=4, normalrange=[-1,1])
print(geom.Generate())
print()

geom = aphros.Geometry()
geom.Box([0,0,0], [1,1,1])
geom.Sphere([0,0,0], [1,1,1])
bc = aphros.Bc()
bc.Wall(geom, velocity=[1,0,0])
bc.SlipWall(geom)
bc.Inlet(geom, velocity=[1,0,0])
bc.InletFlux(geom, velocity=[1,0,0], index=0)
bc.Outlet(geom)
bc.Symm(geom)
print(bc.Generate())
