#!/usr/bin/env python3

import h5py
import numpy as np
import sys
import cv2

me = "hdf2shape"
def usg():
    sys.stderr.write("%s -i HDF5\n" % me)
    sys.exit(2)
input = output = None
while True:
    sys.argv.pop(0)
    if sys.argv and len(sys.argv[0]) > 1 and sys.argv[0][0] == '-':
        if sys.argv[0][1] == 'h':
            usg()
        elif sys.argv[0][1] == 'i':
            sys.argv.pop(0)
            input = sys.argv[0]
        else:
            sys.stderr.write("%s: unknown option '%s'\n" % (me, sys.argv[0]))
            sys.exit(2)
    else:
        break

if input == None:
    sys.stderr.write("%s: -i is not set\n" % me)
    sys.exit(2)

try:
    i = h5py.File(input, "r")
except OSError:
    sys.stderr.write("%s: fail to open hdf file '%s'\n" % (me, input))
    sys.exit(2)

u = np.array(i["data"])
i.close()
s = u.shape
print("{:} {:} {:}".format(s[2], s[1], s[0]))

