#!/usr/bin/env python3

import h5py
import numpy as np
import sys
import cv2

me = "raw2img"
def usg():
    sys.stderr.write("%s -i HDF5 -o IMG\n" % me)
    sys.exit(2)
input = output = None
while True:
    sys.argv.pop(0)
    if sys.argv and len(sys.argv[0]) > 1 and sys.argv[0][0] == '-':
        if sys.argv[0][1] == 'h':
            usg()
        elif sys.argv[0][1] == 'i':
            sys.argv.pop(0)
            input = sys.argv[0]
        elif sys.argv[0][1] == 'o':
            sys.argv.pop(0)
            output = sys.argv[0]
        else:
            sys.stderr.write("%s: unknown option '%s'\n" % (me, sys.argv[0]))
            sys.exit(2)
    else:
        break

if input == None:
    sys.stderr.write("%s: -i is not set\n" % me)
    sys.exit(2)
if output == None:
    sys.stderr.write("%s: -o is not set\n" % me)
    sys.exit(2)

with open(input, "rb") as file:
    buffer = file.read()
u = np.ndarray((256, 256), np.uint16, buffer, order = 'F')
lo = np.min(u)
hi = np.max(u)
u = 255 * (u - lo + 0.0) / (hi - lo)
u = u.astype("int")
u[u < 2] = 0
u[u > 253] = 255
cv2.imwrite(output, u)
