#!/bin/sh

set -eu

base=$(dirname $(readlink -f $0))
: ${cfl=0.5}
: ${steps=5}
: ${np=1}

i=$1
o=$2
shift 2

input=/tmp/input.$$.raw
xmf=/tmp/input.$$.xmf
output=/tmp/output.$$.raw
trap 'rm $input $output $xmf; exit 1' 1 2 3 4 15

$base/img2raw -i $i -o $input
shape=`awk 'sub(/^           <DataItem Dimensions="/, "") && sub(/" Seek=.*/, "") {print $2, $3}' $xmf`
ap.sharpen "$@" --cfl $cfl --steps $steps --outtype UShort $input $output
$base/raw2img -d $shape -i $output -o $o
status=$?

rm $input $output $xmf
exit $status
