#!/bin/sh

set -eu

base=$(dirname $(readlink -f $0))
: ${cfl=0.5}
: ${steps=5}
: ${np=1}

i=$1
o=$2
shift 2

input=/tmp/input.$$.raw
output=/tmp/output.$$.raw
trap 'rm $input $output; exit 1' 1 2 3 4 15

shape=`identify -format "%w %h" "$i"`

$base/img2raw -i $i -o $input
mpirun -n 4 ap.sharpen "$@" -v --cfl $cfl --steps $steps --outtype UShort $input $output
$base/raw2img -d 256 256 -i $output -o $o
status=$?

rm $input $output
exit $status
