#!/bin/bash

set -eu

echo 1 > np
echo 1440 > tl

# ./gencase
# np=64
# nx=128
# r=0.01
# ns=3
# symm=0
# nfr=200
# ba=0
# bap=0
# bal=1
# ch=0
# tmax=2
# wall=1
# Oh=0.005

./gen -nx 128 -np 64 -mode osc -dim 3 -pos center \
  -We 0 -Oh 0.005 -tmax 2 -br 0.15 \
  -mu 0.01 -rho 0.01 \
  -symmxy 0 -wallz 1 \
  -bcod 0 0 -0.5 -bcor 0 0 1 \
  -b2xr 2 0 0 -b2rr 1 \
  -nb 2 -nfr 200 -part_ns 3 \
  -baextra "'-DLEARN_N10'"
