#!/bin/bash

set -eu

r=0.01
nx=128
np=256

echo $np > np
echo 1440 > tl


./gen -nx $nx -np $np -mode pois -dim 3 -pos center\
   -Ca 0.01 -Reh 234 -bryk 1. -tmax 5 -br 0.093\
   -mu $r -rho $r -pois 1 -wally 1 -wallz 1\
   -bcod -0.5 0.5 0 -bcor 4 -1.3 0 -nfr 400 \
   -b2xr 2.15 0.2 0 -b2rr 0.71 \
   -nb 2

cat > b.dat << EOF
0.85 0.96 0.15 0.035
0.35 0.9 0.15 0.09
0.15 0.89 0.15 0.095
EOF

cat > ch/add.conf << EOF
set string dumpformat default
EOF
