#!/usr/bin/env python3

import aphros


class Test(aphros.TestBase):
    def __init__(self):
        super().__init__(cases=["main", "manager", "manager_seq", "rank_cubism", "rank_native"])

    def run(self, case):
        if case == "main":
            self.runcmd("./t.commmap > out")
            return ["out"]
        elif case == "manager":
            np = 2
            self.runcmd("ap.mpirun -n {} ./t.commmap.manager".format(np))
            return ["out_{}".format(i) for i in range(np)]
        elif case == "manager_seq":
            np = 2
            self.runcmd("./t.commmap.manager".format(np))
            return ["out_0"]
        elif case == "rank_cubism":
            np = 4
            self.runcmd("ap.mpirun -n {} ./t.commmap.rank --extra 'set string backend cubismnc'".format(np))
            return ["out_{}".format(i) for i in range(np)]
        elif case == "rank_native":
            np = 4
            self.runcmd("ap.mpirun -n {} ./t.commmap.rank --extra 'set string backend native'".format(np))
            return ["out_{}".format(i) for i in range(np)]
        else:
            raise NotImplementedError()


Test().main()
