#!/bin/bash

set -eu

./clean

# config file
: ${c=openmp.conf}
# block size
: ${bs="8 8 1"}
# number of processors
: ${np=360}
# mesh
: ${m="160 144 1"}

nth=12

echo $np > np

ap.base
ap.part $m $bs $np $nth > mesh.conf

killall t.advection || true

OMP_NUM_THREADS=$nth ap.run ./t.advection "$c"
#OMP_NUM_THREADS=12 OMP_WAIT_POLICY=active mpirun  --bind-to core -mca mpi_yield_when_idle 1 -n 12 ./t.advection "$c"
#OMP_NUM_THREADS=$nth OMP_WAIT_POLICY=active mpirun --bind-to core --map.by core --rank-by core -n $np hostname | tee out

a=0
: ${r=refopenmp}
for f in $r/*.dat ; do
  echo $f
  if ! ap.diffnum "${f#$r/}" "$f" 1e-11; then
    a=1
  fi
done

exit $a
