#!/bin/bash

set -ue

make
./clean
#time ./t.advection uni.conf
#time ./t.advection str.conf
#time ./t.advection a.conf
time ./t.advection circle.conf
#time ./t.advection circlelast.conf
#time ./plot.py
