#!/bin/bash

set -eu

./clean

c=${1:-al16.conf}
np=${2:-2}
echo $np > np
ch.base
ch.run ./t.advection "$c"

a=0
for f in ref/*.dat ; do
  echo $f
  if ! ch.diff "${f#ref/}" "$f"; then
    a=1
  fi
done

exit $a
