#!/bin/bash

set -eu

: ${r=refshort}
ff="a_0001.dat
k_0001.dat
kh_0001.dat
kp_0001.dat
nx_0001.dat
ny_0001.dat
nz_0001.dat
u_0001.dat
u_0001.pdf
"

mkdir -p $r

./plot.py || true

for f in $ff ; do
  echo $f
  cp -v $f $r/$f
done

