#!/bin/bash

set -ue

make
./clean

c=${1:-circleplain.conf}

echo c=$c


o=o

rm -vf $o/*.pdf
mkdir -p $o

# bubble
#br="0.125"
bc="0.5212 0.4593 0. "

# rx/ry ratio
k=1.2
#k=1.

for br in 0.25 0.125 0.0625 0.045 0.037 ; do
  brx=`bc -l <<< "$br * $k"`
  bry=`bc -l <<< "$br / $k"`
  echo "brx=$brx, bry=$bry"

  echo "$bc $brx $bry" > b.dat

  ./t.advection $c  &> /dev/null
  g="gerris_k"
  p="r${br}_"
  (cd $g ; ./runplot) &> /dev/null
  cp $g/u0006.pdf $o/${p}u_ge.pdf
  cp $g/k0006.pdf $o/${p}k_ge.pdf
  ./plot.py &> /dev/null
  cp u_1.pdf $o/${p}u_ch.pdf
  cp k_1.pdf $o/${p}k_ch.pdf
  cp -v kcmp_1.pdf $o/${p}kcmp.pdf
done

(cd $o ; ../tile)


#mkdir o
#for f in *.pdf *.dat out ; do
#  cp -v $f o/$f
#done
