#!/usr/bin/env python

import os
sh = os.system

def sh(s, fatal=True):
    print(s)
    r = os.system(s)
    assert not fatal or r == 0

b = map(float, open("../b.dat").read().split())

dim = 3
np = 1

bx, by, bz, br = b

p = '''
#define DIM {dim}
#define REFINE (5)
'''.format(**locals())

open("par.h", 'w').write(p)


l = locals()
o = 'out'

if not os.path.isfile('main.s') or 1:
    sh("./run0make {dim} {np} |& tee -a {o}".format(**l))

sh("./run0 {dim} {np} |& tee -a {o}".format(**l))

