#!/bin/bash -l

dim=$1
np=$2
nxexp=`cat nxexp`

set -eu

. ba.setenv

if [ ! -f main.s ] ; then
  g="multigrid"
  if [ "$dim" == "3" ] ; then
    g="multigrid3D"
  fi
  make CFLAGS="-grid=$g" main.s
fi

chmod +x main.s

ba.run -n "$np" main.s
