#!/bin/bash -l

dim=$1
np=$2
nxexp=`cat nxexp`

set -eu

e=extra
if [ -f "$e" ] ; then
  extra=`cat "$e"`
else
  extra=
fi

if [ ! -f main.s ] ; then
  g="multigrid"
  if [ "$dim" == "3" ] ; then
    g="multigrid3D"
  fi
  ch.conf . -DEXTRA="-grid=$g $extra"
  make
fi

ba.env ba.run -n "$np" main.s
