#!/bin/bash

set -eu

make > /dev/null
make -C ../../ install > /dev/null

echo "
set double eb_box_angle 0.02
set vect vel 0 0 0
set vect force 1 0 0
set double cflvis 0.5

set vect eb_box_r 2 0.1 2

set string eb_init sphere
set vect eb_sphere_c 0.5 0.5 0.5
set vect eb_sphere_r 0.3 0.2 0.2
set double eb_sphere_angle 0.2

set int eb_init_inverse 0
" > add.conf

ap-run ./t.embed_proj
