grad(p):=[diff(p, 'r), diff(p, 't)/'r];
div(v):=block(local(v), 1/r * diff('r * v[1], 'r) + 1/'r*diff(v[2], 't));
lpl(p):=div(grad(p));
bi(p):=lpl(lpl(p));
vlpl(v):= block(local(v),
  [lpl(v[1]) - v[1]/'r^2 - 2/'r^2*diff(v[2], 't),
  lpl(v[2]) - v[2]/'r^2 + 2/'r^2*diff(v[1], 't)]);

psi: v * (a - sin(a) * cos(a))^(-1) * (a * sin(t) - t * cos(a - t) * sin(a)) * r;
expand(bi(psi));

block([C, D], local(co),
co(c):=ratcoef(expand(trigexpand(psi)), c),
C: co(r * t * sin(t)),
D: co(r * t * cos(t)),
p: - 2 * mu / r * (C * sin(t) + D * cos(t)),
p: factor(trigexpand(p)));

vr: r^(-1)*diff(psi, t);
vt: -diff(psi, r);

/* Stokes equation */
factor(trigexpand(mu * vlpl([vr, vt]) + grad(p)))

/* Boundary conditions */
vr, t = 0;
vt, t = 0;
vt, t = a;

ptt: -p  + 2 * mu * (1/r * diff(vt, t)  + vr/r);
ptt: trigsimp(factor(ptt));
ptt0: trigsimp(ptt), t = a, r = h/sin(a);
