lpl(e):=diff(e, r, 2) + 1/r*diff(e, r) + 1/r^2*diff(e, t, 2);
bi(e):=lpl(lpl(e));

p: r*(a*sin(t) + b*cos(t) + c*t*sin(t) + d*t*cos(t));
pr: diff(p, r);
pt: diff(p, t);
ptt: diff(p, t, 2);

a(e):=subst([a =  aA, b = bA, c = cA, d = dA, m = mA], e);
b(e):=subst([a =  aB, b = bB, c = cB, d = dB, m = mB], e);

mA: R;
mB: 1;
U: 1;
%b1: b(pr), t = 0;
%b2: b(pr), t = h;
%b3: a(pr), t = h;
%b4: a(pr), t = %pi;
%b5: a(pt)/r - b(pt)/r, t = h;
%b6: a(m*ptt)/r - b(m*ptt)/r, t = h;
%b7: U + 1/r*b(pt), t = 0;
%b8: -U + 1/r*a(pt), t = %pi;

%q: [%b1, %b2, %b3, %b4, %b5, %b6, %b7, %b8];
%v: flatten([a([a, b, c, d]), b([a, b, c, d])]);
%s: linsolve(%q, %v), backsubst = false;

aA + U + %pi * cA + dA, %s, infeval;
aB + dB + U, %s, infeval;
bB, %s;

vr: -b(pt)/r;

[cA, cB, dA, dB, vr], infeval, t = h, h = 30/180*%pi, R = 100, numer, %s;
[cA, cB, dA, dB, vr], infeval, t = h, h = 30/180*%pi, R = 4.5989, numer, %s;
[cA, cB, dA, dB, vr], infeval, t = h, h = 30/180*%pi, R = 1, numer, %s;
[cA, cB, dA, dB, vt], infeval, t = h, h = 30/180*%pi, R = 0.01, numer, %s;
[cA, cB, dA, dB, vt], infeval, t = h, h = 5/180*%pi, R = 1000, numer, %s;
[cA, cB, dA, dB, vt], infeval, t = h, h = 5/180*%pi, R = 34.136, numer, %s;
