#!/bin/bash

set -ue

# config file
c=${1:-a.conf}
echo c=$c

# output folder
o=o
rm -vf $o/*.pdf
mkdir -p $o

# bubble
#br="0.125"
bc="0.51 0.47 0. "

# rx/ry ratio
k=1.2
#k=1.

# log
l="out"
echo > $l

for br in 0.25 0.125 0.0625 0.045 0.037 ; do
#for br in 0.045 ; do
  brx=`bc -l <<< "$br * $k"`
  bry=`bc -l <<< "$br / $k"`
  echo "brx=$brx, bry=$bry"
  echo "$bc $brx $bry" > b.dat
  p="r${br}_"

  # runplot ch
  ch="ch"
  (cd $ch ; ./run) &>> $l

  # runplot ge
  ge="ge"
  (cd $ge ; ./run) &>> $l

  # plot cmp
  ./plot.py &>> $l
  exit
done

# tile all pdf
(cd $o ; ../tile)

