#!/bin/bash

set -ue

# config file
c=${1:-a.conf}
echo c=$c

# output folder
o=o
rm -vf $o/*.pdf
mkdir -p $o

# bubble
#br="0.125"
bc="0.51 0.47 0. "

# rx/ry ratio
#k=1.2
: ${k=1.}
echo k=$k

# log
l="out"
echo > $l

for br in 0.25 0.125 0.0625 0.045 0.037 ; do
#for br in 0.045 ; do
  brx=`bc -l <<< "$br * $k"`
  bry=`bc -l <<< "$br / $k"`
  echo "brx=$brx, bry=$bry"
  echo "$bc $brx $bry" > b.dat
  p="r${br}_"

  # runplot ch
  d="ch"
  (cd $d ; ./run) &>> $l


  # runplot ge
  d="ge"
  (cd $d ; ./run) &>> $l

  # plot cmp
  ./plot.py &>> $l

  d="ch"
  mv -f $d/vf_0.pdf $o/${p}vf_$d.pdf
  mv -f $d/k_0.pdf $o/${p}k_$d.pdf
  d="ge"
  mv -f $d/vf_0001.pdf $o/${p}vf_$d.pdf
  mv -f $d/k_0001.pdf $o/${p}k_$d.pdf
  cp -v cmp.pdf $o/${p}cmp.pdf
done

# tile all pdf
(cd $o ; ../tile)
mv $o ${o}_$k

