# This file is a template, and might need editing before it works on your project.
# use the official gcc image, based on debian
# can use verions as well, like gcc:5.2
# see https://hub.docker.com/_/gcc/
image: 
  name: gcc:7.4

build:
  stage: build
  script:
#    - apt update && apt -y install make cmake libhdf5-openmpi-dev python-numpy sudo
    - apt update && apt -y install sudo
    - useradd -M -d `basename ${CI_PROJECT_DIR}` -g users -N -m mpiuser
    - chown -R mpiuser:users `basename ${CI_PROJECT_DIR}`
    - | 
      sudo -i -H -u mpiuser sh -e -x << 'EOS'
      mkdir -p ~/bin
      export PATH=~/bin:$PATH
      ls -al .
      cd deploy
      ./all
      . ch.setenv
      (cd hypre ; ./_run)
      (cd eigen ; ./_run)
      cd ../src
      ./conf
      make -j
      make test
      EOS
  artifacts:
    paths:
    - src/build/Testing/Temporary/LastTest.log
    when: on_failure
    
    