# This file is a template, and might need editing before it works on your project.
# use the official gcc image, based on debian
# can use verions as well, like gcc:5.2
# see https://hub.docker.com/_/gcc/
image: 
  name: gcc:7.4

build:
  stage: build
  script:
    - apt update && apt -y install make cmake libhdf5-openmpi-dev python-numpy
    - mkdir -p ~/bin
    - export PATH=~/bin:$PATH
    - cd deploy
    - ./all
    - . ch.setenv
    - echo -e "#!/bin/bash  \nmake -f \`ch.makesim\` cleanall" > a
    - chmod +x a
    - ./a
    - (cd hypre ; ./_run)
    - (cd eigen ; ./_run)
    - cd ../src
    - ./conf
    - make -j
    - ls -al ~/bin
    - ls -al ../deploy/prefix/bin
    - echo $PATH
    - echo $SHELL
    - /bin/bash -c 'echo $SHELL'
    - ch.makesim
    - echo `ch.makesim`
    - make -f `ch.makesim` cleanrun || true
    - echo 'make -f `ch.makesim` cleanall' > a
    - chmod +x a
    - ./a
    - /bin/bash -c 'ch.makesim'
    - cd test/advection/
    - ./runshort
    - make test
  artifacts:
    paths:
    - src/build/Testing/Temporary/LastTest.log
    when: on_failure
    
    