# This file is a template, and might need editing before it works on your project.
# use the official gcc image, based on debian
# can use verions as well, like gcc:5.2
# see https://hub.docker.com/_/gcc/
image: gcc

build:
  stage: build
  # instead of calling g++ directly you can also use some build toolkit like make
  # install the necessary build tools when needed
  before_script: 
    - apt update && apt -y install make cmake mpi-default-dev 
    - mkdir -p ~/bin
    - export PATH=~/bin:$PATH
    - cd deploy
    - ./all
    - . ch.setenv
    - (cd hypre ; ./_run)
    - (cd eigen ; ./_run)
  script:
    - cd ${CI_PROJECT_DIR}
    - . ch.setenv
    - cd src
    - ./conf
    - make -j
    

cache:
  paths:
    - deploy/prefix

# run tests using the binary built before
test:
  stage: test
  script:
    - cd ${CI_PROJECT_DIR}
    - . ch.setenv
    - cd src
    - make test