image:
  name: gcc:7.4.0

build:
  stage: build
  script:
    - update-alternatives --install /usr/bin/gfortran gfortran /usr/local/bin/gfortran 999
    - apt update && apt -y install make cmake libhdf5-openmpi-dev python-numpy sudo rsync
    - useradd -M -d `dirname ${CI_PROJECT_DIR}` -g users -N mpiuser
    - chown -R mpiuser:users `dirname ${CI_PROJECT_DIR}`
    - |
      sudo -i -H -u mpiuser sh -e -x << EOS
      mkdir -p \$HOME/bin
      export PATH=\$HOME/bin:\$PATH
      cd ${CI_PROJECT_DIR}
      cd deploy
      ./all
      . ap-setenv
      (cd hypre ; ./_run)
      cd ../src
      ./conf
      make -j1
      make test
      EOS
  artifacts:
    paths:
    - src/build/Testing/Temporary/LastTest.log
    when: on_failure
