#!/usr/bin/env python3

import re

text = '''
# Aphrós [<img src="https://circleci.com/gh/cselab/aphros.svg?style=svg">](https://github.com/cselab/aphros/commits/master)

Finite volume solver for incompressible multiphase flows with surface tension.
Key features:

- implementation in C++14
- scalability to thousands of compute nodes
  with the Cubism library for distributed computing on structured grids
- coroutines to enable encapsulation in the block-wise processing framework
- fluid solver based on SIMPLE or Bell-Colella-Glaz methods
- conservative split PLIC advection solver
- novel particle method for curvature estimation improving the accuracy low resolutions
[[demo]](https://cselab.github.io/aphros/curv.html)
[[ref:partstr]]

### Clone

    git clone https://github.com/cselab/aphros.git

### Documentation

<https://cselab.github.io/aphros/doc>

generated by `doc/sphinx`

### Requirements

C++14, cmake, MPI, hdf5 (parallel), python3, python3-numpy.

### Build and install

Follow instructions from `deploy/README.md` to
prepare environment and install dependencies.

Configure, build, install and run tests:

    cd src
    make -j4
    make test

### Docker

Instead of building the code in your system, you can build and run a Docker
container

    docker build github.com/cselab/aphros --tag aprhos
    docker run -i aphros

## Videos

|    |    |
:---:|:---:
[<img src="/doc/images/coalescence.jpg" width=384 height=216>](https://www.cse-lab.ethz.ch/wp-content/uploads/2020/06/coalescence.mp4) | [<img src="/doc/images/taylor_green.jpg" width=250 height=250>](https://www.cse-lab.ethz.ch/wp-content/uploads/2020/06/taylor_green.mp4)
Coalescence of bubbles [[ref:partstr]] | Taylor-Green vortex with bubbles [[ref:pasc19]]
[<img src="/doc/images/vortex_bubble.jpg" width=200 height=400>](https://www.cse-lab.ethz.ch/wp-content/uploads/2020/06/vortex_bubble.mp4) | [<img src="/doc/images/plunging_jet.jpg" width=200 height=400>](https://www.cse-lab.ethz.ch/wp-content/uploads/2020/06/plunging_jet.mp4)
Bubble trapped by vortex ring [[ref:datadriven]] | Plunging jet [[ref:pasc19]]
[<img src="/doc/images/reactor.jpg" width=384 height=216>](https://www.cse-lab.ethz.ch/wp-content/uploads/2020/06/reactor.mp4) | [<img src="/doc/images/mesh_bubbles.jpg" width=384 height=216>](https://www.cse-lab.ethz.ch/wp-content/uploads/2020/06/mesh_bubbles.mp4)
Electrochemical reactor [[ref:ees]] | Bubbles through mesh
[<img src="/doc/images/rising_bubbles.jpg" width=384 height=216>](https://www.cse-lab.ethz.ch/wp-content/uploads/2020/06/rising_bubbles.mp4) | [<img src="/doc/images/foaming_waterfall.jpg" width=384 height=216>](https://www.cse-lab.ethz.ch/wp-content/uploads/2020/06/foaming_waterfall.mp4)
 Rising bubbles clustering on the surface [[ref:aps]] [[ref:cscs]] | Foaming waterfall

|     |
|:---:|
|[<img src="/doc/images/breaking_waves.jpg" width=795 height=447>](https://www.youtube.com/watch?v=iGdphpztCJQ)|
|APS Gallery of Fluid Motion 2019 award winner: Breaking waves: to foam or not to foam? [[ref:aps]]|

## Developers

Aphros is developed and maintained by researchers at ETH Zurich

* [Petr Karnakov](https://www.cse-lab.ethz.ch/member/petr-karnakov/)
* [Dr. Sergey Litvinov](https://www.cse-lab.ethz.ch/member/sergey-litvinov/)
* [Fabian Wermelinger](https://www.cse-lab.ethz.ch/member/fabian-wermelinger/)

under the supervision of

* [Prof. Petros Koumoutsakos](https://www.cse-lab.ethz.ch/member/petros-koumoutsakos/)

## Publications

[[item:ees]] S. M. H. Hashemi, P. Karnakov, P. Hadikhani, E. Chinello, S.
  Litvinov, C.  Moser, P. Koumoutsakos, and D. Psaltis, "A versatile and
  membrane-less electrochemical reactor for the electrolysis of water and
  brine", _Energy & environmental science_, 2019
  [10.1039/C9EE00219G](https://doi.org/10.1039/C9EE00219G)
[[item:pasc19]] P. Karnakov, F. Wermelinger, M. Chatzimanolakis, S. Litvinov,
  and P.  Koumoutsakos, "A high performance computing framework for multiphase,
  turbulent flows on structured grids" in _Proceedings of the platform for
  advanced scientific computing conference on – PASC ’19_, 2019
  [10.1145/3324989.3325727](https://doi.org/10.1145/3324989.3325727)
[[item:icmf]] P. Karnakov, S. Litvinov, P. Koumoutsakos
  "Coalescence and transport of bubbles and drops"
  _10th International Conference on Multiphase Flow (ICMF)_, 2019
[[item:partstr]] P. Karnakov, S. Litvinov, and P. Koumoutsakos, "A hybrid
  particle volume-of-fluid method for curvature estimation in multiphase
  flows”, _International journal of multiphase flow_, 2020
  [10.1016/j.ijmultiphaseflow.2020.103209](https://doi.org/10.1016/j.ijmultiphaseflow.2020.103209)
[[item:datadriven]] Z. Wan, P. Karnakov, P. Koumoutsakos, T. Sapsis, "Bubbles in
  Turbulent Flows: Data-driven, kinematic models with history terms”,
  _International journal of multiphase flow_, 2020
  [10.1016/j.ijmultiphaseflow.2020.103286](https://doi.org/10.1016/j.ijmultiphaseflow.2020.103286)
[[item:aps]] P. Karnakov, S. Litvinov, J. M. Favre, P. Koumoutsakos
  "V0018: Breaking waves: to foam or not to foam?"
  _Gallery of Fluid Motion Award_
  [10.1103/APS.DFD.2019.GFM.V0018](https://doi.org/10.1103/APS.DFD.2019.GFM.V0018)
[[item:cscs]] Annual report 2019 of the Swiss National Supercomputing Centre (cover page)
  [[webpage]](https://www.cscs.ch/publications/annual-reports/cscs-annual-report-2019)
'''


m_refs = re.finditer("\[\[ref:[^]]*\]\]", text)
m_items = re.finditer("\[\[item:[^]]*\]\]", text)

gen = text
for i, m_item in enumerate(m_items):
    item = m_item.group(0)
    name = re.match("\[\[item:([^]]*)\]\]", item).group(1)
    ref = "[[ref:{}]]".format(name)
    url = re.search("\((http[^)]*)\)", text[m_item.start(0):]).group(1)
    gen = gen.replace(item, "{:}.".format(i + 1))
    gen = gen.replace(ref, "[[{:}]]({})".format(i + 1, url))

with open("README.md", 'w') as f:
    f.write(gen)
