#!/bin/bash

set -eu

./clean

# config file
: ${c=std.conf}
# block size
: ${bs="32 32 1"}
# number of processors
: ${np=2}
# mesh
: ${m="64 64 1"}

echo $np > np

ch.base
ch.part $m $bs $np > mesh.conf

ch.run ./main "$c"
