#!/bin/bash -l

set -eu

echo running > job.status

export OMP_NUM_THREADS=1
n=2
time mpirun -n $n --oversubscribe xterm -e gdb -ex=run --args ../mfer localc$n.conf

echo "Done."
echo done > job.status

