#!/usr/bin/env python

import numpy as np
import sys

f = "part.log"

d = np.genfromtxt(f, names=True, dtype=(int, int, float, float))

h = dict()

rr = d['iter']

ns = d['string'].max() + 1

r = []

for s in range(ns):
    r.append(rr[d['string'] == s].max())

rm = np.median(r)
r0 = np.percentile(r, 10)
r1 = np.percentile(r, 90)

print(rm, r0, r1)
