#!/usr/bin/env python

import os
import textwrap

PREFIX = os.environ["PREFIX"]
EXTRA = ""
FLAGVAR = "APHROS_SETENV"
PREFIXVAR = "APHROS_PREFIX"

inc = "setenv_inc"
if os.path.isfile(inc):
    with open(inc) as f:
        EXTRA = textwrap.indent(f.read(), '  ')


o = """#!/bin/sh

# Source this file to append environment variables.

if [ "${[[FLAGVAR]]:-x}" != "1" ] ; then
  : ${LD_LIBRARY_PATH=}
  : ${PYTHONPATH=}
  : ${CMAKE_PREFIX_PATH=}

  export [[PREFIXVAR]]="[[PREFIX]]"
  export CHPREFIX="${[[PREFIXVAR]]}"
  export PATH="${[[PREFIXVAR]]}/bin:$PATH"
  export LD_LIBRARY_PATH="${[[PREFIXVAR]]}/lib:${LD_LIBRARY_PATH}"
  export PYTHONPATH="${[[PREFIXVAR]]}/bin:$PYTHONPATH"
  export EIGEN3_INCLUDE_DIR="${[[PREFIXVAR]]}/include"
  export CMAKE_PREFIX_PATH="${[[PREFIXVAR]]}/cmake:${CMAKE_PREFIX_PATH}"
  export MANPATH="$(MANPATH= manpath -g):${[[PREFIXVAR]]}/man"

  export OMP_NUM_THREADS=1
[[EXTRA]]
  export [[FLAGVAR]]=1
  echo "[[FLAGVAR]]=1" 1>&2
fi
"""

for name in [
        "PREFIX",
        "EXTRA",
        "FLAGVAR",
        "PREFIXVAR",
]:
    o = o.replace('[[' + name + ']]', locals()[name])

print(o)
