#!/usr/bin/env python3

import os

PREFIX = os.environ["PREFIX"]
PROFILE = os.environ["PROFILE"]
EXTRA = ""
FLAGVAR = "APHROS_SETENV"
PREFIXVAR = "APHROS_PREFIX"
PROFILEVAR = "APHROS_PROFILE"

inc = "setenv_inc"
if os.path.isfile(inc):
    with open(inc) as f:
        EXTRA = "  ".join(f.readlines())


o = """# Source this file to append environment variables.

if [ "${[[FLAGVAR]]:-x}" != "1" ] ; then
  : ${LD_LIBRARY_PATH=}
  : ${PYTHONPATH=}
  : ${CMAKE_PREFIX_PATH=}

  export [[PREFIXVAR]]="[[PREFIX]]"
  export [[PROFILEVAR]]="[[PROFILE]]"
  export PATH="${[[PREFIXVAR]]}/bin:$PATH"
  export LD_LIBRARY_PATH="${[[PREFIXVAR]]}/lib:${LD_LIBRARY_PATH}"
  export PYTHONPATH="${[[PREFIXVAR]]}/bin:$PYTHONPATH"
  export CMAKE_PREFIX_PATH="${[[PREFIXVAR]]}/cmake:${CMAKE_PREFIX_PATH}"
  if manpath -g 2>/dev/null 1>/dev/null; then
    export MANPATH="$(MANPATH= manpath -g):${[[PREFIXVAR]]}/man"
  fi
  export OMP_NUM_THREADS=1
  [[EXTRA]]
  export [[FLAGVAR]]=1
  cat >&2 <<-!
	[[FLAGVAR]]=$[[FLAGVAR]]
	[[PREFIXVAR]]=$[[PREFIXVAR]]
	[[PROFILEVAR]]=$[[PROFILEVAR]]
	!
fi
"""

for name in [
        "PREFIX",
        "EXTRA",
        "PROFILE",
        "FLAGVAR",
        "PREFIXVAR",
        "PROFILEVAR",
]:
    o = o.replace('[[' + name + ']]', locals()[name])

print(o)
