#!/bin/bash -l

#SBATCH --job-name=mfer
#SBATCH --time=60:00
#SBATCH --constraint=gpu
#SBATCH --ntasks=32

export OMP_NUM_THREADS=1

. ../setenv.daint

echo running > job.status

n=$SLURM_NTASKS
srun ../mfer daint$n.conf

echo "Done."
echo done > job.status

