#!/bin/bash

set -ue

job="daint-job"

cmd="sbatch $job"
echo $cmd
msg=`eval $cmd`

echo "$msg"
id=`echo "$msg" | sed -e "s/[^0-9]*\([0-9]*\)[^0-9]*/\1/"`
echo "Write $id to job.id"
echo $id > job.id

echo "pending" > job.status
