#!/bin/bash -l

#BSUB -J mfer
#BSUB -W 1:00
#BSUB -n 32

echo running > job.status

n=`mpirun echo | wc -l`
mpirun ../mfer daint$n.conf &> out

mv -vf job.id job.id.last

echo "Done."
echo done > job.status

