#!/bin/bash

set -eu

rm -f k*.{dat,iter}
for n in `seq 3 2 50` ; do
    o=k`printf %03d "$n"`.dat
    oi=k`printf %03d "$n"`.iter
    np=$n
    echo "0.5 0.5 0.5 0.125" > b.dat
    a=add.conf
    > $a
    echo "set int part_np $np" >> $a
    echo "set double part_tol 1e-5" >> $a
    ./run
    ./curv > $o
    ./plot > $oi
done


