#!/bin/bash

set -eu

rm -f k*.{dat,iter}
for n in 3 5 7 9 11 13 15 ; do
    o=k`printf %03d "$n"`.dat
    oi=k`printf %03d "$n"`.iter
    np=$n
    echo "0.5 0.5 0.5 0.125" > b.dat
    a=add.conf
    > $a
    echo "set int part_np $np" >> $a
    echo "set double part_tol 1e-5" >> $a
    ./run
    ./curv > $o
    ./plot > $oi
done


