#!/bin/bash -l

dim=$1
np=$2
nxexp=`cat nxexp`

set -eu

. ba.setenv

e=extra
if [ -f "$e" ] ; then
  extra=`cat "$e"`
else
  extra=
fi

if [ ! -f main.s ] ; then
  g="multigrid"
  if [ "$dim" == "3" ] ; then
    g="multigrid3D"
  fi
  make CFLAGS="-grid=$g $extra -DCURV_PARTSTR" main.s
fi

chmod +x main.s

rm -f *.csv

ba.run -n "$np" main.s
