#!/usr/bin/env python

import numpy as np
import glob
import re

nx = 32.
hx = 1. / nx

rr = [hx * 2. ** re for re in np.linspace(-1., 4., 20)]
bb = np.loadtxt('bb')

ff = sorted(glob.glob("kr*b*.dat"))

ee = []

for f in ff:
    m = re.findall("kr([0-9]*)b([0-9]*)", f)[0]
    ri = int(m[0])
    bi = int(m[1])
    r = rr[ri]
    b = bb[bi]
    # exact curv
    kex = 1. / r
    # particles
    k = np.loadtxt(f)
    # curvature error
    if not k.size:
        ekm = 1.
        ek1 = 1.
        ek2 = 1.
    else:
        ekm = abs(k - kex).max() / kex
        ek1 = abs(k - kex).mean() / kex
        ek2 = ((k - kex) ** 2).mean() ** 0.5 / kex
    cpr = nx * r

    fvf = "vfr{:}b{:}.dat".format(m[0], m[1]) # vf filename
    vf = float(open(fvf).read())

    e = [ri, bi, cpr, vf, ekm, ek1, ek2]
    ee.append(e)

fo = "kerr"
with open(fo, 'w') as f:
    f.write("ri bi cpr vf em e1 e2\n")
    for e in ee:
        f.write(' '.join(map(str, e)) + '\n')

