#!/usr/bin/env python

import numpy as np
import glob
import re
from getr import *


bb = np.loadtxt('bb')

ff = sorted(glob.glob("kr*b*.dat"))

if not len(ff):
    exit()

ee = []

dim = int(open("dim").read())

for f in ff:
    m = re.findall("kr([0-9]*)b([0-9]*)", f)[0]
    ri = int(m[0])
    bi = int(m[1])
    r, nx, cpr = GetR(ri)
    b = bb[bi]
    # volume
    fvf = "vfr{:}b{:}.dat".format(m[0], m[1]) # vf filename
    vf = float(open(fvf).read())
    # radius from volume 
    rvf = (vf / np.pi * nx) ** 0.5  if dim == 2 else (vf * 3. / (4. * np.pi)) ** (1. / 3.)
    # exact curv
    kex = 1. / rvf if rvf != 0. else 0.
    # particles
    k = np.loadtxt(f)
    # curvature error
    if not k.size:
        ekm = 1.
        ek1 = 1.
        ek2 = 1.
        eks = 1.
    else:
        ekm = abs(k - kex).max() / kex
        ek1 = abs(k - kex).mean() / kex
        ek2 = ((k - kex) ** 2).mean() ** 0.5 / kex
        eks = np.std(k) / kex

    e = [ri, bi, cpr, vf, ekm, ek1, ek2, nx, eks]
    ee.append(e)

fo = "kerr"
with open(fo, 'w') as f:
    f.write("ri bi cpr vf em e1 e2 nx es\n")
    for e in ee:
        f.write(' '.join(map(str, e)) + '\n')
