#!/usr/bin/env python

# Generates list of random positions
# in quarter of cell

import random

random.seed(0)

def R():
    return random.uniform(0., 1)

nb = 100 # size of output
for i in range(nb):
    x = R()
    y = R()
    z = R()
    print("{:} {:} {:}".format(x, y, z))
