#!/bin/bash

set -eu

dim=$1
overlap=$2

o=dim${dim}_overlap${overlap}
d=randc

echo "Output to $o"

rsync -La $d/ $o

cd $o

./_vary --dim ${dim} --overlap ${overlap} --nri 30 --nbi 1
./_gatherall
./a.gnu
