B = \
$(WRK)/explorer\
$(WRK)/main\
$(WRK)/test/advection/main\
$(WRK)/test/approx/linear\
$(WRK)/test/approx/main\
$(WRK)/test/benchmark_diffusion/main\
$(WRK)/test/benchmark/main\
$(WRK)/test/benchmark_mpi/main\
$(WRK)/test/benchmark_mpiraw/main\
$(WRK)/test/benchmark_normal/main\
$(WRK)/test/color/main\
$(WRK)/test/commhalo/main\
$(WRK)/test/comm/main\
$(WRK)/test/commmap/main\
$(WRK)/test/commmap/manager\
$(WRK)/test/commmap/rank\
$(WRK)/test/condface/main\
$(WRK)/test/debug/main\
$(WRK)/test/dump/dump_diff\
$(WRK)/test/dump/dump_gen\
$(WRK)/test/dump/dump_meta\
$(WRK)/test/dump/dump_util\
$(WRK)/test/embed_approx/main\
$(WRK)/test/embed_convdiff/main\
$(WRK)/test/embed_grad/main\
$(WRK)/test/embed_interpolate/main\
$(WRK)/test/embed/main\
$(WRK)/test/embed_potential/main\
$(WRK)/test/fluid/main\
$(WRK)/test/grad/main\
$(WRK)/test/hook/hook/hook\
$(WRK)/test/hypre/main\
$(WRK)/test/hypresub/main\
$(WRK)/test/init/main\
$(WRK)/test/inner/main\
$(WRK)/test/linear/main\
$(WRK)/test/mesh/main\
$(WRK)/test/openmp/main\
$(WRK)/test/parser/codeblocks\
$(WRK)/test/parser/main\
$(WRK)/test/particles/main\
$(WRK)/test/primlist/getmap\
$(WRK)/test/primlist/parse\
$(WRK)/test/range/main\
$(WRK)/test/recolor/main\
$(WRK)/test/reconst/levelset\
$(WRK)/test/reconst/main\
$(WRK)/test/reconst/plane\
$(WRK)/test/reflect/main\
$(WRK)/test/stat/main\
$(WRK)/test/subcomm/main\
$(WRK)/test/suspender/main\
$(WRK)/test/sysinfo/main\
$(WRK)/test/sysinfo/realpath\
$(WRK)/test/sysinfo/splitext\
$(WRK)/test/tracker/main\
$(WRK)/test/util/main\
$(WRK)/test/vars/main\
$(WRK)/test/visual/main\

