$(WRK)/aphros_c/git.o: $(WRK)/.dir
$(WRK)/aphros_c/main.o: $(WRK)/.dir
$(WRK)/aphros_c/parser.o: $(WRK)/.dir
$(WRK)/color/color.o: $(WRK)/.dir
$(WRK)/distr/comm_manager.o: $(WRK)/.dir
$(WRK)/distr/distrbasic.o: $(WRK)/.dir
$(WRK)/distr/distr.o: $(WRK)/.dir
$(WRK)/distr/distrsolver.o: $(WRK)/.dir
$(WRK)/distr/local.o: $(WRK)/.dir
$(WRK)/distr/native.o: $(WRK)/.dir
$(WRK)/distr/report.o: $(WRK)/.dir
$(WRK)/dump/dump.o: $(WRK)/.dir
$(WRK)/dump/dumper.o: $(WRK)/.dir
$(WRK)/dump/hdf.o: $(WRK)/.dir
$(WRK)/dump/raw.o: $(WRK)/.dir
$(WRK)/dump/xmf.o: $(WRK)/.dir
$(WRK)/func/init_contang.o: $(WRK)/.dir
$(WRK)/func/init.o: $(WRK)/.dir
$(WRK)/func/init_vel.o: $(WRK)/.dir
$(WRK)/func/primlist.o: $(WRK)/.dir
$(WRK)/geom/mesh.o: $(WRK)/.dir
$(WRK)/inside/bbox.o: $(WRK)/.dir
$(WRK)/inside/err.o: $(WRK)/.dir
$(WRK)/inside/main.o: $(WRK)/.dir
$(WRK)/inside/memory.o: $(WRK)/.dir
$(WRK)/inside/off.o: $(WRK)/.dir
$(WRK)/inside/ply.o: $(WRK)/.dir
$(WRK)/inside/predicate.o: $(WRK)/.dir
$(WRK)/inside/stl.o: $(WRK)/.dir
$(WRK)/kernel/hydro.o: $(WRK)/.dir
$(WRK)/linear/linear.o: $(WRK)/.dir
$(WRK)/march/main.o: $(WRK)/.dir
$(WRK)/overlap/overlap.o: $(WRK)/.dir
$(WRK)/parse/argparse.o: $(WRK)/.dir
$(WRK)/parse/codeblocks.o: $(WRK)/.dir
$(WRK)/parse/conf2py.o: $(WRK)/.dir
$(WRK)/parse/parser.o: $(WRK)/.dir
$(WRK)/parse/template.o: $(WRK)/.dir
$(WRK)/parse/vars.o: $(WRK)/.dir
$(WRK)/solver/approx_eb.o: $(WRK)/.dir
$(WRK)/solver/approx.o: $(WRK)/.dir
$(WRK)/solver/convdiffe.o: $(WRK)/.dir
$(WRK)/solver/convdiffi.o: $(WRK)/.dir
$(WRK)/solver/convdiffvg.o: $(WRK)/.dir
$(WRK)/solver/curv.o: $(WRK)/.dir
$(WRK)/solver/electro.o: $(WRK)/.dir
$(WRK)/solver/embed.o: $(WRK)/.dir
$(WRK)/solver/fluid_dummy.o: $(WRK)/.dir
$(WRK)/solver/normal.o: $(WRK)/.dir
$(WRK)/solver/particles.o: $(WRK)/.dir
$(WRK)/solver/partstrmeshm.o: $(WRK)/.dir
$(WRK)/solver/proj_eb.o: $(WRK)/.dir
$(WRK)/solver/proj.o: $(WRK)/.dir
$(WRK)/solver/simple.o: $(WRK)/.dir
$(WRK)/solver/solver.o: $(WRK)/.dir
$(WRK)/solver/tracer.o: $(WRK)/.dir
$(WRK)/solver/vofm.o: $(WRK)/.dir
$(WRK)/solver/vof.o: $(WRK)/.dir
$(WRK)/util/convdiff.o: $(WRK)/.dir
$(WRK)/util/distr.o: $(WRK)/.dir
$(WRK)/util/events.o: $(WRK)/.dir
$(WRK)/util/filesystem.o: $(WRK)/.dir
$(WRK)/util/fixed_allocator.o: $(WRK)/.dir
$(WRK)/util/fluid.o: $(WRK)/.dir
$(WRK)/util/format.o: $(WRK)/.dir
$(WRK)/util/gitgen.o: $(WRK)/.dir
$(WRK)/util/git.o: $(WRK)/.dir
$(WRK)/util/histogram.o: $(WRK)/.dir
$(WRK)/util/hydro_post.o: $(WRK)/.dir
$(WRK)/util/hydro.o: $(WRK)/.dir
$(WRK)/util/linear.o: $(WRK)/.dir
$(WRK)/util/logger.o: $(WRK)/.dir
$(WRK)/util/mpi.o: $(WRK)/.dir
$(WRK)/util/posthook_default.o: $(WRK)/.dir
$(WRK)/util/suspender.o: $(WRK)/.dir
$(WRK)/util/sysinfo.o: $(WRK)/.dir
$(WRK)/util/system.o: $(WRK)/.dir
$(WRK)/util/timer.o: $(WRK)/.dir
$(WRK)/util/visual.o: $(WRK)/.dir
$(WRK)/util/vof.o: $(WRK)/.dir
$(WRK)/young/main.o: $(WRK)/.dir
