$(WRK)/aphros_c/git.o: $(WRK)/.dir
$(WRK)/aphros_c/main.o: $(WRK)/.dir
$(WRK)/aphros_c/parser.o: $(WRK)/.dir
$(WRK)/color/color.o: $(WRK)/.dir
$(WRK)/distr/comm_manager.o: $(WRK)/.dir
$(WRK)/distr/distrbasic.o: $(WRK)/.dir
$(WRK)/distr/distr.o: $(WRK)/.dir
$(WRK)/distr/distrsolver.o: $(WRK)/.dir
$(WRK)/distr/local.o: $(WRK)/.dir
$(WRK)/distr/native.o: $(WRK)/.dir
$(WRK)/distr/report.o: $(WRK)/.dir
$(WRK)/dump/dump.o: $(WRK)/.dir
$(WRK)/dump/dumper.o: $(WRK)/.dir
$(WRK)/dump/hdf.o: $(WRK)/.dir
$(WRK)/dump/raw.o: $(WRK)/.dir
$(WRK)/dump/xmf.o: $(WRK)/.dir
$(WRK)/explorer.o: $(WRK)/.dir
$(WRK)/func/init_contang.o: $(WRK)/.dir
$(WRK)/func/init.o: $(WRK)/.dir
$(WRK)/func/init_vel.o: $(WRK)/.dir
$(WRK)/func/primlist.o: $(WRK)/.dir
$(WRK)/geom/mesh.o: $(WRK)/.dir
$(WRK)/inside/bbox.o: $(WRK)/.dir
$(WRK)/inside/err.o: $(WRK)/.dir
$(WRK)/inside/main.o: $(WRK)/.dir
$(WRK)/inside/memory.o: $(WRK)/.dir
$(WRK)/inside/off.o: $(WRK)/.dir
$(WRK)/inside/ply.o: $(WRK)/.dir
$(WRK)/inside/predicate.o: $(WRK)/.dir
$(WRK)/inside/stl.o: $(WRK)/.dir
$(WRK)/kernel/hydro.o: $(WRK)/.dir
$(WRK)/linear/linear.o: $(WRK)/.dir
$(WRK)/main.o: $(WRK)/.dir
$(WRK)/march/main.o: $(WRK)/.dir
$(WRK)/overlap/overlap.o: $(WRK)/.dir
$(WRK)/parse/argparse.o: $(WRK)/.dir
$(WRK)/parse/codeblocks.o: $(WRK)/.dir
$(WRK)/parse/conf2py.o: $(WRK)/.dir
$(WRK)/parse/parser.o: $(WRK)/.dir
$(WRK)/parse/template.o: $(WRK)/.dir
$(WRK)/parse/vars.o: $(WRK)/.dir
$(WRK)/solver/approx_eb.o: $(WRK)/.dir
$(WRK)/solver/approx.o: $(WRK)/.dir
$(WRK)/solver/convdiffe.o: $(WRK)/.dir
$(WRK)/solver/convdiffi.o: $(WRK)/.dir
$(WRK)/solver/convdiffvg.o: $(WRK)/.dir
$(WRK)/solver/curv.o: $(WRK)/.dir
$(WRK)/solver/electro.o: $(WRK)/.dir
$(WRK)/solver/embed.o: $(WRK)/.dir
$(WRK)/solver/fluid_dummy.o: $(WRK)/.dir
$(WRK)/solver/normal.o: $(WRK)/.dir
$(WRK)/solver/particles.o: $(WRK)/.dir
$(WRK)/solver/partstrmeshm.o: $(WRK)/.dir
$(WRK)/solver/proj_eb.o: $(WRK)/.dir
$(WRK)/solver/proj.o: $(WRK)/.dir
$(WRK)/solver/simple.o: $(WRK)/.dir
$(WRK)/solver/solver.o: $(WRK)/.dir
$(WRK)/solver/tracer.o: $(WRK)/.dir
$(WRK)/solver/vofm.o: $(WRK)/.dir
$(WRK)/solver/vof.o: $(WRK)/.dir
$(WRK)/test/advection/main.o: $(WRK)/.dir
$(WRK)/test/approx/linear.o: $(WRK)/.dir
$(WRK)/test/approx/main.o: $(WRK)/.dir
$(WRK)/test/benchmark_diffusion/main.o: $(WRK)/.dir
$(WRK)/test/benchmark/main.o: $(WRK)/.dir
$(WRK)/test/benchmark_mpi/main.o: $(WRK)/.dir
$(WRK)/test/benchmark_mpiraw/main.o: $(WRK)/.dir
$(WRK)/test/benchmark_normal/main.o: $(WRK)/.dir
$(WRK)/test/color/main.o: $(WRK)/.dir
$(WRK)/test/commhalo/main.o: $(WRK)/.dir
$(WRK)/test/comm/main.o: $(WRK)/.dir
$(WRK)/test/commmap/main.o: $(WRK)/.dir
$(WRK)/test/commmap/manager.o: $(WRK)/.dir
$(WRK)/test/commmap/rank.o: $(WRK)/.dir
$(WRK)/test/condface/main.o: $(WRK)/.dir
$(WRK)/test/debug/main.o: $(WRK)/.dir
$(WRK)/test/dump/dump_diff.o: $(WRK)/.dir
$(WRK)/test/dump/dump_gen.o: $(WRK)/.dir
$(WRK)/test/dump/dump_meta.o: $(WRK)/.dir
$(WRK)/test/dump/dump_util.o: $(WRK)/.dir
$(WRK)/test/embed_approx/main.o: $(WRK)/.dir
$(WRK)/test/embed_convdiff/main.o: $(WRK)/.dir
$(WRK)/test/embed_grad/main.o: $(WRK)/.dir
$(WRK)/test/embed_interpolate/main.o: $(WRK)/.dir
$(WRK)/test/embed/main.o: $(WRK)/.dir
$(WRK)/test/embed_potential/main.o: $(WRK)/.dir
$(WRK)/test/fluid/main.o: $(WRK)/.dir
$(WRK)/test/grad/main.o: $(WRK)/.dir
$(WRK)/test/hook/hook/hook.o: $(WRK)/.dir
$(WRK)/test/hypre/main.o: $(WRK)/.dir
$(WRK)/test/hypresub/main.o: $(WRK)/.dir
$(WRK)/test/init/main.o: $(WRK)/.dir
$(WRK)/test/inner/main.o: $(WRK)/.dir
$(WRK)/test/linear/main.o: $(WRK)/.dir
$(WRK)/test/mesh/main.o: $(WRK)/.dir
$(WRK)/test/openmp/main.o: $(WRK)/.dir
$(WRK)/test/parser/codeblocks.o: $(WRK)/.dir
$(WRK)/test/parser/main.o: $(WRK)/.dir
$(WRK)/test/primlist/getmap.o: $(WRK)/.dir
$(WRK)/test/primlist/parse.o: $(WRK)/.dir
$(WRK)/test/range/main.o: $(WRK)/.dir
$(WRK)/test/recolor/main.o: $(WRK)/.dir
$(WRK)/test/reconst/levelset.o: $(WRK)/.dir
$(WRK)/test/reconst/main.o: $(WRK)/.dir
$(WRK)/test/reconst/plane.o: $(WRK)/.dir
$(WRK)/test/reflect/main.o: $(WRK)/.dir
$(WRK)/test/stat/main.o: $(WRK)/.dir
$(WRK)/test/subcomm/main.o: $(WRK)/.dir
$(WRK)/test/suspender/main.o: $(WRK)/.dir
$(WRK)/test/sysinfo/main.o: $(WRK)/.dir
$(WRK)/test/sysinfo/realpath.o: $(WRK)/.dir
$(WRK)/test/sysinfo/splitext.o: $(WRK)/.dir
$(WRK)/test/tracker/main.o: $(WRK)/.dir
$(WRK)/test/util/main.o: $(WRK)/.dir
$(WRK)/test/vars/main.o: $(WRK)/.dir
$(WRK)/test/visual/main.o: $(WRK)/.dir
$(WRK)/util/convdiff.o: $(WRK)/.dir
$(WRK)/util/distr.o: $(WRK)/.dir
$(WRK)/util/events.o: $(WRK)/.dir
$(WRK)/util/filesystem.o: $(WRK)/.dir
$(WRK)/util/fixed_allocator.o: $(WRK)/.dir
$(WRK)/util/fluid.o: $(WRK)/.dir
$(WRK)/util/format.o: $(WRK)/.dir
$(WRK)/util/gitgen.o: $(WRK)/.dir
$(WRK)/util/git.o: $(WRK)/.dir
$(WRK)/util/histogram.o: $(WRK)/.dir
$(WRK)/util/hydro_post.o: $(WRK)/.dir
$(WRK)/util/hydro.o: $(WRK)/.dir
$(WRK)/util/linear.o: $(WRK)/.dir
$(WRK)/util/logger.o: $(WRK)/.dir
$(WRK)/util/mpi.o: $(WRK)/.dir
$(WRK)/util/posthook_default.o: $(WRK)/.dir
$(WRK)/util/suspender.o: $(WRK)/.dir
$(WRK)/util/sysinfo.o: $(WRK)/.dir
$(WRK)/util/system.o: $(WRK)/.dir
$(WRK)/util/timer.o: $(WRK)/.dir
$(WRK)/util/visual.o: $(WRK)/.dir
$(WRK)/util/vof.o: $(WRK)/.dir
$(WRK)/young/main.o: $(WRK)/.dir
