$(WRK)/aphros_c/git.o: $(SRC)/aphros_c/git.cpp; $(CXX_RULE) $(SRC)/aphros_c/git.cpp
$(WRK)/aphros_c/main.o: $(SRC)/aphros_c/main.cpp; $(CXX_RULE) $(SRC)/aphros_c/main.cpp
$(WRK)/aphros_c/parser.o: $(SRC)/aphros_c/parser.cpp; $(CXX_RULE) $(SRC)/aphros_c/parser.cpp
$(WRK)/color/color.o: $(SRC)/color/color.c; $(CC_RULE) $(SRC)/color/color.c
$(WRK)/distr/comm_manager.o: $(SRC)/distr/comm_manager.cpp; $(CXX_RULE) $(SRC)/distr/comm_manager.cpp
$(WRK)/distr/distrbasic.o: $(SRC)/distr/distrbasic.cpp; $(CXX_RULE) $(SRC)/distr/distrbasic.cpp
$(WRK)/distr/distr.o: $(SRC)/distr/distr.cpp; $(CXX_RULE) $(SRC)/distr/distr.cpp
$(WRK)/distr/distrsolver.o: $(SRC)/distr/distrsolver.cpp; $(CXX_RULE) $(SRC)/distr/distrsolver.cpp
$(WRK)/distr/local.o: $(SRC)/distr/local.cpp; $(CXX_RULE) $(SRC)/distr/local.cpp
$(WRK)/distr/native.o: $(SRC)/distr/native.cpp; $(CXX_RULE) $(SRC)/distr/native.cpp
$(WRK)/distr/report.o: $(SRC)/distr/report.cpp; $(CXX_RULE) $(SRC)/distr/report.cpp
$(WRK)/dump/dump.o: $(SRC)/dump/dump.cpp; $(CXX_RULE) $(SRC)/dump/dump.cpp
$(WRK)/dump/dumper.o: $(SRC)/dump/dumper.cpp; $(CXX_RULE) $(SRC)/dump/dumper.cpp
$(WRK)/dump/hdf.o: $(SRC)/dump/hdf.cpp; $(CXX_RULE) $(SRC)/dump/hdf.cpp
$(WRK)/dump/raw.o: $(SRC)/dump/raw.cpp; $(CXX_RULE) $(SRC)/dump/raw.cpp
$(WRK)/dump/xmf.o: $(SRC)/dump/xmf.cpp; $(CXX_RULE) $(SRC)/dump/xmf.cpp
$(WRK)/func/init_contang.o: $(SRC)/func/init_contang.cpp; $(CXX_RULE) $(SRC)/func/init_contang.cpp
$(WRK)/func/init.o: $(SRC)/func/init.cpp; $(CXX_RULE) $(SRC)/func/init.cpp
$(WRK)/func/init_vel.o: $(SRC)/func/init_vel.cpp; $(CXX_RULE) $(SRC)/func/init_vel.cpp
$(WRK)/func/primlist.o: $(SRC)/func/primlist.cpp; $(CXX_RULE) $(SRC)/func/primlist.cpp
$(WRK)/geom/mesh.o: $(SRC)/geom/mesh.cpp; $(CXX_RULE) $(SRC)/geom/mesh.cpp
$(WRK)/inside/bbox.o: $(SRC)/inside/bbox.c; $(CC_RULE) $(SRC)/inside/bbox.c
$(WRK)/inside/err.o: $(SRC)/inside/err.c; $(CC_RULE) $(SRC)/inside/err.c
$(WRK)/inside/main.o: $(SRC)/inside/main.c; $(CC_RULE) $(SRC)/inside/main.c
$(WRK)/inside/memory.o: $(SRC)/inside/memory.c; $(CC_RULE) $(SRC)/inside/memory.c
$(WRK)/inside/off.o: $(SRC)/inside/off.c; $(CC_RULE) $(SRC)/inside/off.c
$(WRK)/inside/ply.o: $(SRC)/inside/ply.c; $(CC_RULE) $(SRC)/inside/ply.c
$(WRK)/inside/predicate.o: $(SRC)/inside/predicate.c; $(CC_RULE) $(SRC)/inside/predicate.c
$(WRK)/inside/stl.o: $(SRC)/inside/stl.c; $(CC_RULE) $(SRC)/inside/stl.c
$(WRK)/kernel/hydro.o: $(SRC)/kernel/hydro.cpp; $(CXX_RULE) $(SRC)/kernel/hydro.cpp
$(WRK)/linear/linear.o: $(SRC)/linear/linear.cpp; $(CXX_RULE) $(SRC)/linear/linear.cpp
$(WRK)/march/main.o: $(SRC)/march/main.c; $(CC_RULE) $(SRC)/march/main.c
$(WRK)/parse/argparse.o: $(SRC)/parse/argparse.cpp; $(CXX_RULE) $(SRC)/parse/argparse.cpp
$(WRK)/parse/codeblocks.o: $(SRC)/parse/codeblocks.cpp; $(CXX_RULE) $(SRC)/parse/codeblocks.cpp
$(WRK)/parse/conf2py.o: $(SRC)/parse/conf2py.cpp; $(CXX_RULE) $(SRC)/parse/conf2py.cpp
$(WRK)/parse/parser.o: $(SRC)/parse/parser.cpp; $(CXX_RULE) $(SRC)/parse/parser.cpp
$(WRK)/parse/template.o: $(SRC)/parse/template.cpp; $(CXX_RULE) $(SRC)/parse/template.cpp
$(WRK)/parse/vars.o: $(SRC)/parse/vars.cpp; $(CXX_RULE) $(SRC)/parse/vars.cpp
$(WRK)/solver/approx_eb.o: $(SRC)/solver/approx_eb.cpp; $(CXX_RULE) $(SRC)/solver/approx_eb.cpp
$(WRK)/solver/approx.o: $(SRC)/solver/approx.cpp; $(CXX_RULE) $(SRC)/solver/approx.cpp
$(WRK)/solver/convdiffe.o: $(SRC)/solver/convdiffe.cpp; $(CXX_RULE) $(SRC)/solver/convdiffe.cpp
$(WRK)/solver/convdiffi.o: $(SRC)/solver/convdiffi.cpp; $(CXX_RULE) $(SRC)/solver/convdiffi.cpp
$(WRK)/solver/convdiffvg.o: $(SRC)/solver/convdiffvg.cpp; $(CXX_RULE) $(SRC)/solver/convdiffvg.cpp
$(WRK)/solver/curv.o: $(SRC)/solver/curv.cpp; $(CXX_RULE) $(SRC)/solver/curv.cpp
$(WRK)/solver/electro.o: $(SRC)/solver/electro.cpp; $(CXX_RULE) $(SRC)/solver/electro.cpp
$(WRK)/solver/embed.o: $(SRC)/solver/embed.cpp; $(CXX_RULE) $(SRC)/solver/embed.cpp
$(WRK)/solver/fluid_dummy.o: $(SRC)/solver/fluid_dummy.cpp; $(CXX_RULE) $(SRC)/solver/fluid_dummy.cpp
$(WRK)/solver/normal.o: $(SRC)/solver/normal.cpp; $(CXX_RULE) $(SRC)/solver/normal.cpp
$(WRK)/solver/particles.o: $(SRC)/solver/particles.cpp; $(CXX_RULE) $(SRC)/solver/particles.cpp
$(WRK)/solver/partstrmeshm.o: $(SRC)/solver/partstrmeshm.cpp; $(CXX_RULE) $(SRC)/solver/partstrmeshm.cpp
$(WRK)/solver/proj_eb.o: $(SRC)/solver/proj_eb.cpp; $(CXX_RULE) $(SRC)/solver/proj_eb.cpp
$(WRK)/solver/proj.o: $(SRC)/solver/proj.cpp; $(CXX_RULE) $(SRC)/solver/proj.cpp
$(WRK)/solver/simple.o: $(SRC)/solver/simple.cpp; $(CXX_RULE) $(SRC)/solver/simple.cpp
$(WRK)/solver/solver.o: $(SRC)/solver/solver.cpp; $(CXX_RULE) $(SRC)/solver/solver.cpp
$(WRK)/solver/tracer.o: $(SRC)/solver/tracer.cpp; $(CXX_RULE) $(SRC)/solver/tracer.cpp
$(WRK)/solver/vofm.o: $(SRC)/solver/vofm.cpp; $(CXX_RULE) $(SRC)/solver/vofm.cpp
$(WRK)/solver/vof.o: $(SRC)/solver/vof.cpp; $(CXX_RULE) $(SRC)/solver/vof.cpp
$(WRK)/util/convdiff.o: $(SRC)/util/convdiff.cpp; $(CXX_RULE) $(SRC)/util/convdiff.cpp
$(WRK)/util/distr.o: $(SRC)/util/distr.cpp; $(CXX_RULE) $(SRC)/util/distr.cpp
$(WRK)/util/events.o: $(SRC)/util/events.cpp; $(CXX_RULE) $(SRC)/util/events.cpp
$(WRK)/util/filesystem.o: $(SRC)/util/filesystem.cpp; $(CXX_RULE) $(SRC)/util/filesystem.cpp
$(WRK)/util/fixed_allocator.o: $(SRC)/util/fixed_allocator.cpp; $(CXX_RULE) $(SRC)/util/fixed_allocator.cpp
$(WRK)/util/fluid.o: $(SRC)/util/fluid.cpp; $(CXX_RULE) $(SRC)/util/fluid.cpp
$(WRK)/util/format.o: $(SRC)/util/format.cpp; $(CXX_RULE) $(SRC)/util/format.cpp
$(WRK)/util/gitgen.o: $(SRC)/util/gitgen.cpp; $(CXX_RULE) $(SRC)/util/gitgen.cpp
$(WRK)/util/git.o: $(SRC)/util/git.cpp; $(CXX_RULE) $(SRC)/util/git.cpp
$(WRK)/util/histogram.o: $(SRC)/util/histogram.cpp; $(CXX_RULE) $(SRC)/util/histogram.cpp
$(WRK)/util/hydro.o: $(SRC)/util/hydro.cpp; $(CXX_RULE) $(SRC)/util/hydro.cpp
$(WRK)/util/linear.o: $(SRC)/util/linear.cpp; $(CXX_RULE) $(SRC)/util/linear.cpp
$(WRK)/util/logger.o: $(SRC)/util/logger.cpp; $(CXX_RULE) $(SRC)/util/logger.cpp
$(WRK)/util/mpi.o: $(SRC)/util/mpi.cpp; $(CXX_RULE) $(SRC)/util/mpi.cpp
$(WRK)/util/posthook_default.o: $(SRC)/util/posthook_default.cpp; $(CXX_RULE) $(SRC)/util/posthook_default.cpp
$(WRK)/util/subcomm_dummy.o: $(SRC)/util/subcomm_dummy.cpp; $(CXX_RULE) $(SRC)/util/subcomm_dummy.cpp
$(WRK)/util/suspender.o: $(SRC)/util/suspender.cpp; $(CXX_RULE) $(SRC)/util/suspender.cpp
$(WRK)/util/sysinfo.o: $(SRC)/util/sysinfo.cpp; $(CXX_RULE) $(SRC)/util/sysinfo.cpp
$(WRK)/util/system.o: $(SRC)/util/system.c; $(CC_RULE) $(SRC)/util/system.c
$(WRK)/util/timer.o: $(SRC)/util/timer.cpp; $(CXX_RULE) $(SRC)/util/timer.cpp
$(WRK)/util/vof.o: $(SRC)/util/vof.cpp; $(CXX_RULE) $(SRC)/util/vof.cpp
$(WRK)/young/main.o: $(SRC)/young/main.cpp; $(CXX_RULE) $(SRC)/young/main.cpp
