#!/bin/sh

: ${GCC=gcc}

msg () { echo >&2 "$@" ; }
err () { msg "$me: $@"; exit 2 ; }

me=tool/uncomment

usg () cat <<!
$me [-p] -o file file
!

OutputFlag=0
PFlag=0
while test $# -ne 0
do case "$1" in
       -o) shift
           if test $# -eq 0; then err '-o needs an argument'; fi
           Output=$1; shift
           OutputFlag=1
           ;;
       -h ) usg
            exit 2
            ;;
       -p)  shift
            PFlag=1
            ;;
       -*) err "unknown option '$1'" ;;
       *) break
   esac
done

if test $OutputFlag -eq 0
then err "option '-o file' is not set"
fi

if test $# -ne 1
then err "wrong number of arguments: '$@'"
fi

if ! test -f "$1"
then err "not a file '$1'"
fi

if test $PFlag -eq 0
then Arg=
else Arg=-P
fi

"$GCC" -x c -fpreprocessed -dD -E $Arg "$1" > "$Output"
if test $? -ne 0
then err "$GCC failed"
fi
