#!/usr/bin/env python

import aphros
import numpy

R = 0.18
H = 0.7
inf = 10

vf = aphros.Geometry()
vf.Box([0, 1, 0], [inf, 1 - H, inf])

#vf.Sphere([0.5 - R, 0.5, 0], [R] * 3)
#vf.Sphere([0.5 + R, 0.5, 0], [R] * 3)
#vf.Sphere([0.5, 0.5 - R * 3 ** 0.5, 0], [R] * 3)

Rm = R * 0.75
vf.Sphere([0.5, 0.5, 0], [R] * 3)
vf.Sphere([0.5, 0.5 - R - Rm, 0], [Rm] * 3)

vf.GenerateFile("b.dat")
