#!/usr/bin/env python3

import sys

me = "2line"
def usg():
    sys.stderr.write("%s -o %s < data/cross \n" % (me, OutputList))
    sys.exit(2)

def off(p, line):
    print("OFF")
    print(len(p), len(line), 0)
    for e in p:
        print(e)
    for l in line:
        print(len(l) + 1, end = ' ')
        for e in l:
            print(e, end = ' ')
        print(l[0])

def gnuplot(p, line):
    for l in line:
        for e in l:
            print(p[e])
        print(p[l[0]])
        print("\n")

def many(p, line):
    xx = [ ]
    yy = [ ]
    for e in p:
        e = e.split()
        xx.append(float(e[0]))
        yy.append(float(e[2]))
    for i, l in enumerate(line):
        x = [xx[e] for e in l]
        y = [yy[e] for e in l]
        if y[0] > 0:
            x.reverse()
            y.reverse()
            y = [-e for e in y]
        m = x.index(max(x))
        with open("%02d.line" % i, 'w') as f:
            for u, v in zip(x, y):
                f.write("%-.16e %-.16e\n" % (u - x[m], v - y[m]))

def split(p, line):
    for i, l in enumerate(line):
        with open("%02d.line" % i, 'w') as f:
            for e in l:
                f.write(p[e])
                f.write("\n")

def one(p, line):
    l = line[1]
    for e in l:
        print(p[e])
    print(p[l[0]])
Output = {
           "gnuplot": gnuplot,
           "many": many,
           "off": off,
           "one": one,
           "split": split,
}
OutputList = "|".join(Output.keys())
output = None
while True:
    sys.argv.pop(0)
    if len(sys.argv) and len(sys.argv[0]) > 1 and sys.argv[0][0] == '-':
        if sys.argv[0][1] == 'h':
            usg()
        elif sys.argv[0][1] == 'o':
            sys.argv.pop(0)
            if not sys.argv:
                sys.stderr.write("%s: -o needs an argument\n" % me)
                sys.exit(2)
            if not sys.argv[0] in Output:
                sys.stderr.write("%s: '%s' not in %s\n" % (me, sys.argv[0], OutputList))
                sys.exit(2)
            output = Output[sys.argv[0]]
        else:
            sys.stderr.write("%s: unknown option '%s'\n" % (me, sys.argv[0]))
            sys.exit(2)
    else:
        break

if output == None:
    sys.stderr.write("%s: -o is not set\n" % me)
    sys.exit(2)

p = [ ]
adj = { }
for l in sys.stdin:
    l = l.split()
    c, l = l[0], l[1:]
    if c == 'p':
        p.append(" ".join(l))
    elif c == 'f':
        l = [int(e) for e in l]
        l = set(l)
        for i in l:
            for j in l:
                if i != j:
                    if not i in adj:
                        adj[i] = set()
                    adj[i].add(j)
nv = len(p)
seen = set()
line = [ ]
for i in range(nv):
    if not i in seen:
        l = [ ]
        j = i
        while True:
            seen.add(j)
            l.append(j)
            for k in adj[j]:
                if not k in seen:
                    break
            else:
                break
            j = k
        line.append(l)
output(p, line)
