#!/bin/sh

awk '
sub(/^p /, "") {
    nv++
    p[nv] = $0
}

sub(/^f /, "") {
    nf++
    f[nf] = $0
    n[nf] = NF
}

END {
    print "OFF"
    print nv, nf, 0
    for (i = 1; i in p; i++)
        print p[i]
    for (i = 1; i in n; i++)
        print n[i], f[i]
}
'
