#!/bin/sh

awk -v me=2off '
sub(/^p /, "") {
    nv++
    p[nv] = $0
}

sub(/^f /, "") {
    nf++
    f[nf] = $0
    n[nf] = NF
}

END {
    if (nv == 0) {
	printf "%s: no vertices\n", me | "cat >&2"
	exit(2)
    }
    print "OFF"
    print nv, nf, 0
    for (i = 1; i in p; i++)
        print p[i]
    for (i = 1; i in n; i++)
        print n[i], f[i]
}
'
