#!/usr/bin/env python3

import sys

me = "gen"
dx = -1.4990000000000947e-02
dy = +1.4477999999999547e-02

x0 = -5.5558352009921741e+00
y0 = -2.1999979999999999e+00
sx = 1.2

x = [ ]
y = [ ]
coef = [ ]

if len(sys.argv) < 3:
    sys.stderr.write("%s: needs two files\n" % me)
    sys.exit(2)
with open(sys.argv[1], 'r') as f:
    for l in f:
        l = l.split()
        x.append(float(l[0]))
        y.append(float(l[1]))
with open(sys.argv[2], 'r') as f:
    d = {'0' : 0, '1': 0.5, '2': 1.0}
    for l in f:
        l = l.rstrip()
        coef.append(d[l])
assert len(coef) == len(x)

First = True
for i in range(-1, 25):
    if First:
        First = False
    else:
        print("\n")
    for j in range(len(x)):
        print(x0 + x[j] + i*coef[j]*dx + i*sx, y0 + y[j] + i*coef[j]*dy)
