#!/usr/bin/env python3

import sys
import math
me = "inflate"

if len(sys.argv) < 2:
    sys.stderr.write("%s: needs a file\n" % me)
    sys.exit(2)

x = [ ]
y = [ ]
with open(sys.argv[1], 'r') as f:
    for l in f:
        l = l.split()
        x.append(float(l[0]))
        y.append(float(l[1]))

n = len(x)

def norm(x, y):
    u = -y
    v = x
    if u * y - v * x:
        u = -u
        v = -v
    d = math.sqrt(u*u + v*v)
    return u/d, v/d

eps = -0.05
u = [ ]
v = [ ]
for j in range(n):
    i = j - 1
    k = j + 1
    if i < 0:
        i += n
    if k >= n:
        k -= n
    x0 = x[j] - x[i]
    y0 = y[j] - y[i]

    x1 = x[k] - x[j]
    y1 = y[k] - y[j]    

    d0 = math.sqrt(x0*x0 + y0*y0)
    d1 = math.sqrt(x1*x1 + y1*y1)

    u0, v0 = norm(x0, y0)
    u1, v1 = norm(x1, y1)

    a = (u0 * d0 + u1 * d1)/(d0 + d1)
    b = (v0 * d0 + v1 * d1)/(d0 + d1)
    d = math.sqrt(a*a + b*b)
    a /= d
    b /= d
    u.append(x[j] + a * eps)
    v.append(y[j] + b * eps)
    
for i in range(n):
    print(u[i], v[i])
