#!/usr/bin/env python3

import sys
import math
import pyclipper
me = "offset"
def usg():
    sys.stderr.write("%s -o offset -e eps file.xy\n" % me)
    sys.exit(2)

def dist2(a, b):
    x = a[0] - b[0]
    y = a[1] - b[1]
    return x*x + y*y

def inflate(path, offset, eps):
    path = pyclipper.scale_to_clipper(path)
    pco = pyclipper.PyclipperOffset()
    pco.AddPath(path, pyclipper.JT_ROUND, pyclipper.ET_CLOSEDPOLYGON)
    path = pco.Execute(pyclipper.scale_to_clipper(offset))[0]
    path = pyclipper.scale_from_clipper(path)
    ans = [ ]
    i = 0
    n = len(path)
    while True:
        ans.append(path[i])
        if i == n - 1:
            break
        j = i + 1
        while j != n - 1 and dist2(path[i], path[j]) < eps*eps:
            j += 1
        i = j
    return ans

offset = None
eps = None
while True:
    sys.argv.pop(0)
    if len(sys.argv) and len(sys.argv[0]) > 1 and sys.argv[0][0] == '-':
        if sys.argv[0][1] == 'h':
            usg()
        elif sys.argv[0][1] == 'o':
            sys.argv.pop(0)
            if not sys.argv:
                sys.stderr.write("%s: -o needs an argument\n" % me)
                sys.exit(2)
            offset = float(sys.argv[0])
        elif sys.argv[0][1] == 'e':
            sys.argv.pop(0)
            if not sys.argv:
                sys.stderr.write("%s: -e needs an argument\n" % me)
                sys.exit(2)
            eps = float(sys.argv[0])
        else:
            sys.stderr.write("%s: unknown option '%s'\n" % (me, sys.argv[0]))
            sys.exit(2)
    else:
        break
if offset == None:
    sys.stderr.write("%s: -o is not set\n" % me)
    sys.exit(2)
if eps == None:
    sys.stderr.write("%s: -e is not set\n" % me)
    sys.exit(2)    
if not sys.argv:
    sys.stderr.write("%s: file.xy file is not set" % me)
    sys.exit(2)
path = [ ]
with open(sys.argv[0], 'r') as f:
    for l in f:
        l = l.split()
        x = float(l[0])
        y = float(l[1])
        path.append((x, y))
path = inflate(path, offset, eps)
for x, y in path:
    print("%-.16e %-.16e" % (x, y))
