#!/usr/bin/env python

def Exp():
    # SI units

    sig = 73e-3 # surface tension
    g = 9.8
    # water
    rho = 1000 # density
    mu = 1e-3  # dynamic viscosity
    nu = mu / rho # kinematic viscosity

    U = 0.25   # waterfall velocity
    W =  0.005  # waterfall thickness

    ###
    Re = U * W / nu
    Fr = (U ** 2 / (g * W)) ** 0.5
    We = rho * U ** 2 * W / sig

    for key in sorted(locals()):
        print("{:} \t=\t {:}".format(key, locals()[key]))
    print("\n")

    return locals()

def Sim(c):
    Re,We,Fr = (c['Re'], c['We'], c['Fr'])
    pi = 3.141592

    # domain 
    lx = 2.
    ly = 2.
    lz = 1.
    lmax = max([lx, ly, lz])

    U = 1. # velocity
    W = 0.1 # waterfall thickness

    # time
    tun = 1 / U  # unit
    tmax = tun * 500.
    dumpdt = tun * 0.05

    # oulet 
    outy0 = -1e-5
    outy1 = 1e-5

    # liquid
    rho0 = 1. # density
    # nu0 == mu0
    mu0 = U * W / Re  # viscosity

    sig = (rho0 * U ** 2 * W) / We
    g = U ** 2 / Fr ** 2 / W

    # gas, ratio to liquid
    mu = 0.01
    rho = 0.01

    def rnd(a): return int(a + 0.5)

    # mesh
    nn = 96
    nx = rnd(nn * lx)
    ny = rnd(nn * ly)
    nz = rnd(nn * lz)

    # block size
    bs = 16
    bsz = bs
    # cores
    np = 216
    # time limit (minutes)
    tl = 1440

    for key in sorted(locals()):
        print("{:} \t=\t {:}".format(key, locals()[key]))
    print("\n")

    return locals()

def Gen(c):
    lx = c['lx']
    ly = c['ly']
    lz = c['lz']
    W = c['W']
    # bubble 
    bx = lx * 0.5
    by = ly
    bz = lz * 0.5
    brx = 1e10
    bry = ly * 0.5
    brz = brx

    tmax = c['tmax']
    dumpdt = c['dumpdt']

    rho1 = c['rho0']
    mu1 = c['mu0']
    rho2 = rho1 * c['rho']
    mu2 = mu1 * c['mu']
    sig = c['sig']

    g = -c['g']

    inv = -c['U']

    inrc = W * 0.5
    isph_cx = lx * 0.5
    isph_cy = ly
    isph_cz = lz * 0.5

    outy0 = c['outy0']
    outy1 = c['outy1']

    with open("par.conf", 'w') as f:
        f.write('''\
# domain
set double extent 2

# time
set double tmax {tmax}
set double dump_field_dt {dumpdt}
set double dump_part_dt {dumpdt}
set double dump_traj_dt {dumpdt}

# physical 
set double rho1 {rho1}
set double rho2 {rho2}
set double mu1 {mu1}
set double mu2 {mu2}
set double sigma {sig}
set vect gravity 0 {g} 0

# bc boxes
set vect inlet_sph0_c {isph_cx} {isph_cy} {isph_cz}
set vect inlet_sph0_r {inrc} {inrc} 1e5
set vect inlet_sph0_vel 0 {inv} 0
set double inlet_sph0_vf 0

set string box1 outlet
set vect box1_a -1e10 {outy0} -1e10
set vect box1_b 1e10 {outy1} 1e10
set double box1_vf 0.

        '''.format(**locals()))


    with open("b.dat", 'w') as f:
        f.write("{bx} {by} {bz} {brx} {bry} {brz}\n".format(**locals()))

    with open("par.make", 'w') as f:
        f.write(
'''m = {nx} {ny} {nz}
bs = {bs} {bs} {bsz}
np = {np}
tl = {tl}
'''.format(**c))


c = Exp()
c = Sim(c)
Gen(c)
