#!/usr/bin/env python3

import aphros
import matplotlib.pyplot as plt
aphros.plot.ApplyParams(plt)
import numpy as np
import argparse
import os

def read_lines_vtk(path, mirror=True):
    '''
    Returns array of lines from `sm_*.vtk` generated with `spacedim=2`
    [line0_x, line0_y, line1_x, line1_y, ...]
    where line0_x and line1_y are lists of coordinates
    '''
    points, poly, fields = aphros.ReadVtkPoly(path)

    # [[[x0a, y0b], [x0a, y0b]], ...]
    lines = points[poly][:, :, :2]
    # [[[x0a, x0b], [y0a, y0b]], ...]
    lines = np.transpose(lines, (0, 2, 1))
    # [[x0a, x0b], [y0a, y0b], ...]
    lines = lines.reshape((-1, 2))
    if mirror:
        lines_mirror = lines.copy()
        lines_mirror[1::2, ] *= -1
        lines = np.vstack((lines, lines_mirror))
    return lines

def read_lines_moonmd(path):
    '''
    Returns array of lines from `c1g3l4s.txt` generated by MooNMD
    [line0_x, line0_y, line1_x, line1_y, ...]
    where line0_x and line1_y are lists of coordinates
    '''
    lines = np.genfromtxt(path).T
    yy, xx = lines
    yy -= 0.5
    lines = (xx, yy)
    return lines

def read_lines(path):
    ext = os.path.splitext(path)[1]
    if ext == ".vtk":
        return read_lines_vtk(path)
    if ext == ".txt":
        return read_lines_moonmd(path)
    raise RuntimeError("Unknown extention: " + ext)

def parse_args():
    parser = argparse.ArgumentParser()
    parser.add_argument('plots',
                        type=str,
                        nargs='*',
                        help="List of plots as 'PATH;LABEL;COLOR;STYLE'. "
                        "PATH points to sm_*.vtk or ref/*s.txt")
    parser.add_argument('--output',
                        type=str,
                        default="a.pdf",
                        help="Path to output image")
    parser.add_argument('--figsize',
                        type=float,
                        nargs=2,
                        default=[3, 3],
                        help="Figure size")
    return parser.parse_args()

if __name__ == "__main__":
    args = parse_args()
    fig = plt.figure(figsize=args.figsize)
    ax = plt.Axes(fig, [0, 0, 0.7, 1])
    fig.add_axes(ax)

    for plotarg in args.plots:
        plot = ['', '', '', '']
        for i, e in enumerate(plotarg.split(';')):
            plot[i] = e
        path, label, c, ls = plot
        lines = read_lines(path)
        d = dict()
        if c: d['c'] = c
        if ls: d['ls'] = ls
        l, = ax.plot([], [], label=label, **d)
        d['c'] = l.get_color()
        ax.plot(*lines, **d)

    #lines = read_lines("ref/c1g3l4s.txt")
    #ax.plot(*lines, c='k', ls='--', label='ref')

    ax.set_axis_off()
    ax.set_aspect(1)
    ax.legend(loc='upper left',
              fontsize=7,
              bbox_to_anchor=(1, 1),
              frameon=False)

    print(args.output)
    fig.savefig(args.output, dpi=300)
