#!/usr/bin/awk -f
BEGIN {
    pi = 3.141592653589793
}

{
    area[$1] += $2
    volume[$1] += $3
    n[$1] ++
}

END {
    for (k in n) {
        A = area[k]
        V = abs(volume[k])
        print sqrt(A/pi)/2, (3*V/(4*pi))^(1/3)
    }
}

function abs(x) { return x > 0 ? x : -x }
