#!/bin/sh
me="$0"
${AWK=awk} -v me="$me" '
BEGIN {
    FS = " *, *"
    if (ARGC < 2)
        err("not enough arguments")
    f = ARGV[1]
    r = getline < f
    if (r != 1)
        err("fail to read \"%s\"", f)
    for (i = 1; i <= NF; i++)
        Key[$i] = i
    while (getline < f == 1) {
        cl = get("cl")
        vf = get("vf")
        if (cl != 0 && vf < 0.1)
            print vf
    }
    close(f)
}


function msg(fmt, a, b, c, d, e)
{
    printf "%s: " fmt "\n", me, a, b, c, d, e | "cat >&2"
}

function err(fmt, a, b, c, d, e)
{
    msg(fmt, a, b, c, d, e)
    exit(2)
}

function get(key,   i) {
    i = Key[key]
    return $i
}
' "$@"
