#!/usr/bin/env python3

import os
import filecmp

import aphros


class Test(aphros.TestBase):
    def __init__(self):
        super().__init__(cases=["local", "cubismnc"])

    def run(self, case):
        if case == "local":
            self.runcmd("ap.mpirun -n 1 out 2>&1")
        elif case == "codeblocks":
            self.runcmd("./t.parser.codeblocks < codeblocks_in > out 2>&1")
        else:
            raise NotImplementedError()
        return ["out"]


Test().main()
