#!/usr/bin/env python

import glob
import os

c = {}
exec(open("../par.py").read(), None, c)

dim = c['dim']
d2 = (dim == 2)
d3 = (dim == 3)

# number of frames from ch
nfr = c['nfr']
if os.path.isfile("../ch/done"):
  g = "../ch/s_*.vtk"
  nfr = len(glob.glob(g))
  print("Found {:} frames as {:}".format(nfr, g))
  assert nfr >= 2, "Error: Need at least 2 frames $r, found %r" % (g, nfr)

c['nfr'] = nfr
c['dumpdt'] = c['tmax'] / c['nfr']
c['stdt'] = c['tmax'] / c['nfr'] / 10.

nx = c['nx']
nxexp = nx.bit_length() - 1
assert nx == 2 ** nxexp, "Mesh size nx=%r but must be power of 2" % nx
c['nxexp'] = nxexp

c['rho2'] = c['rho0'] * c['rho']
c['mu2'] = c['mu0'] * c['mu']

c['gx'] = c['g'][0]
c['gy'] = c['g'][1]
c['gz'] = c['g'][2]

o = '''Define VELX {vel[0]}
Define VELY {vel[1]}
Define VELZ {vel[2]}
Define TMAX {tmax}
Define DUMPDT {dumpdt}
Define STDT {stdt}
Define SIGMA {sig}
Define RHO1 {rho0}
Define RHO2 {rho2}
Define MU1 {mu0}
Define MU2 {mu2}
Define GESM {gesm}
Define REFINE {nxexp}
Define PGRAD {pgrad}
Define POISVEL {poisvel}
Define GX {gx}
Define GY {gy}
Define GZ {gz}

'''.format(**c)

# base config file
mb = "main.gfs"
print("Reading base config from {:}".format(mb))
bt = open(mb).read()

# dimension
bt = bt.replace('[D2]', '' if d2 else '#')
bt = bt.replace('[D3]', '' if d3 else '#')

# Poiseuille flow
bt = bt.replace('[POIS]', '' if c['pois'] else '#')
bt = bt.replace('[!POIS]', '' if not c['pois'] else '#')

drz = "" if d3 else ""
wl = '''{{:}} = Boundary {{{{
  [D2]BcAngle T (180)
  BcDirichlet U (0) 
  BcDirichlet V (0) 
  [D3]BcDirichlet W (0)
  }}}}
{{:}} = Boundary {{{{
  [D2]BcAngle T (180)
  BcDirichlet U (0) 
  BcDirichlet V (0) 
  [D3]BcDirichlet W (0)
  }}}}'''.format(drz=drz)

# wl dimension
wl = wl.replace('[D2]', '' if d2 else '#')
wl = wl.replace('[D3]', '' if d3 else '#')

b0 = {'X':'left', 'Y':'bottom', 'Z':'back'}
b1 = {'X':'right', 'Y':'top', 'Z':'front'}

numedge = 0

dd = ['X', 'Y', 'Z'] if d3 else ['X', 'Y']

# wall conditions
for d in dd:
    if c['wall{:}'.format(d.lower())]:
        bt = bt.replace('[BC{:}]'.format(d), wl.format(b0[d], b1[d]))
    else:
        numedge += 1
        bt = bt.replace('[EDGE{:}]'.format(d), "1 1 {:}".format(b1[d]))

bt = bt.replace('[NUMEDGE]'.format(d), str(numedge))

# cleanup
for d in ['X', 'Y', 'Z']:
    bt = bt.replace('[BC{:}]'.format(d), '')
    bt = bt.replace('[EDGE{:}]'.format(d), '')

o += bt

open("main.gen.gfs", 'w').write(o)
