#!/usr/bin/env python3

import aphros

geom = aphros.Geometry()
polygons = []
polygons.append([[0, 0], [0.3, 0], [0, 0.1]])
polygons.append([[0.3, 0.4], [0.6, 0.4], [0.6, 0.6], [0.3, 0.5]])
geom.Polygon(origin=[0.5, 0.15, 0],
             normal=[1, 0, 0],
             right=[0, 1, 0],
             normalrange=[-0.2, 0.2],
             scale=1.5,
             polygons=polygons)

bpath = "b_polygon.dat"
print(bpath)
s = geom.GenerateFile(bpath)

apath = "add.conf"
print(apath)
with open(apath, 'w') as f:
    f.write("set string list_path b_polygon.dat")
