#!/usr/bin/env python3

import aphros

geom = aphros.Geometry()
polygon0 = [[0, 0], [0.3, 0], [0, 0.1]]
polygon1 = [[0.3, 0.4], [0.6, 0.4], [0.6, 0.6], [0.3, 0.5]]
for p in [polygon0, polygon1]:
    geom.Polygon(origin=[0.5, 0.15, 0],
                 normal=[1, 0, 0],
                 right=[0, 1, 0],
                 normalrange=[-0.2, 0.2],
                 scale=1.5,
                 polygon=p)

bpath = "b_polygon.dat"
print(bpath)
s = geom.GenerateFile(bpath)

apath = "add.conf"
print(apath)
with open(apath, 'w') as f:
    f.write("set string list_path b_polygon.dat")
