#!/usr/bin/env python

import numpy as np
import glob
import re

ff = sorted(glob.glob('k???.dat'))
fref = ff[-1]

kref = np.loadtxt(fref)

ee = []

b = np.loadtxt("b.dat")
br = b[3]
# exact curv
kex = 1. / br

for f in ff:
    k = np.loadtxt(f)
    n = int(re.findall("k([0-9]*)", f)[0])
    # error reference
    er2 = np.sqrt((k - kref) ** 2).mean() / kex
    erm = np.max(np.abs(k - kref)) / kex
    # error exact
    ek2 = np.sqrt((k - kex) ** 2).mean() / kex
    ekm = np.max(np.abs(k - kex)) / kex
    # error exact average
    kexa = k.mean()
    ek2a = np.sqrt((k - kexa) ** 2).mean() / kexa
    ekma = np.max(np.abs(k - kexa)) / kexa
    e = [n, er2, ek2, erm, ekm, ek2a, ekma]
    ee.append(e)


fo = "kerr"
with open(fo, 'w') as f:
    f.write('n er2 ek2 erm ekm ek2a ekma\n')
    for e in ee:
        f.write(' '.join(map(str, e)) + '\n')

