#!/usr/bin/env python

import numpy as np
import glob
import re

ff = sorted(glob.glob('k???.dat'))
fref = ff[-1]

kref = np.loadtxt(fref)

ee = []

for f in ff:
    k = np.loadtxt(f)
    n = int(re.findall("k([0-9]*)", f)[0])
    dk = k - kref
    e = [n, dk.min(), dk.max(), abs(dk).mean()]
    ee.append(e)


fo = "kerr"
with open(fo, 'w') as f:
    for e in ee:
        f.write(' '.join(map(str, e)) + '\n')

