#!/usr/bin/env python

# Prints curvature sorted by cell index.

import numpy as np
import sys

f = "partit_0000.csv"

t = np.genfromtxt(f, names=True, delimiter=',', 
        dtype=(float, float, float, int, float))

c = t['c']
k = t['k']

uc, ui = np.unique(c, return_index=True)

k = k[ui]

np.savetxt(sys.stdout, k)
