SHELL := /bin/bash

CC ?= gcc
LD ?= gcc

# core
bs ?= 32
ap ?= float
weps ?= 1e-6
precdiv ?= 0
microfusion ?= 2
accurateweno ?= 0
omp ?= 1
align ?= 16
bgq ?= 0
qpx ?= 0
qpxemu ?= 0
sequoia ?= 0

# +node
hdf ?= 0
vtk ?= 0
numa ?= 0
cvt ?= 0

# +cluster
fftw ?= 0
#

#compression stage-1 (floating point)
wavz ?= 0
fpc ?= 0
fpzip ?= 0
shuffle ?= 0
zerobits ?= 0
wavz2 ?= 0

#compression stage-2 (encoding)
zlib ?= 0
lz4 ?= 0
lzf ?= 0
lzma ?= 0
zopfli ?=0
#fpc2 ?= 0	# this works but I do not work what we compress (mix below)
#fpzip2 ?= 0	# this does not seem to work when the stream is a mix of integers and floats
#

fpc3 ?= 0	# for wavz + fpc
fpzip3 ?= 0	# for wavz + fpz
shuffle3 ?= 0	# for wavz + shuffle3

ifeq "$(wavz)" "0" 
ifeq "$(fpc)" "0"
ifeq "$(fpzip)" "0"
#wavz = 1
endif
endif
endif


ifeq "$(zlib)" "0" 
ifeq "$(lz4)" "0" 
ifeq "$(lzf)" "0" 
ifeq "$(fpc2)" "0"
ifeq "$(fpzip2)" "0"
#zlib = 1
endif
endif
endif
endif
endif


CPPFLAGS+= $(extra) #-Wall

ifeq "$(sequoia)" "1"
	CPPFLAGS += -D_SEQUOIA_
endif

ifeq "$(ap)" "float"
        CPPFLAGS += -D_FLOAT_PRECISION_
endif

ifeq "$(accurateweno)" "1"
        CPPFLAGS += -D_ACCURATEWENO_
endif

CPPFLAGS += -D_MICROFUSION_=$(microfusion)

ifeq "$(config)" "release"
	ifeq "$(CC)" "icc"
		OPTFLAGS+= -DNDEBUG -O3 -xHOST  -ip -ansi-alias -fno-fnalias -inline-level=1
		ifeq "$(ap)" "float"
			CPPFLAGS += -fp-model precise 
		else
			CPPFLAGS += -fast
		endif
	else
		ifeq "$(bgq)" "1"
			OPTFLAGS += -O3 -qsmp=omp:speculative -qhot=level=1  -qarch=qp -qtune=qp # -qlibmpi -qnounwind -qalias=noaddrtaken:allptrs:ansi:global:restrict:typeptr -qnoeh
			#-qnoeh -qprefetch -qsimd=auto #-qnounroll #=assistthread
			#OPTFLAGS += -O4 -qsmp=speculative -qhot=level=2  -qarch=qp -qtune=qp -qnoeh # -qsimd=auto #-qprefetch  #-qnounroll #=assistthread
			#OPTFLAGS += -O3 -qsmp=speculative -qhot=level=1  -qarch=qp -qtune=qp -qprefetch #-qnounroll #=assistthread
			#OPTFLAGS += -O3 -qsmp=omp -qhot=level=1  -qarch=qp -qtune=qp -qprefetch #=assistthread
		else
			#OPTFLAGS += -O3 -DNDEBUG -xHOST -ip -ansi-alias -fno-fnalias -inline-level=1
			OPTFLAGS += -O3 -fno-expensive-optimizations -falign-functions=16 -DNDEBUG #one can leave out falign to the default of O2 level  which is machine-dependent
		endif

		OPTFLAGS += -DNDEBUG
	endif
else
	CPPFLAGS += -g 
endif

##CPPFLAGS += -Wno-deprecated 

ifeq "$(cvt)" "1"
	CPPFLAGS += -D_USE_CVT_
endif

ifeq "$(precdiv)" "1"
CPPFLAGS += -D_PREC_DIV_
endif 

ifeq "$(precdiv)" "-1"
	CPPFLAGS += -D_PREC_DIV_NONE_
	ifeq "$(CC)" "icc"
		#OPTFLAGS += -ipo
	endif
endif 

ifeq "$(ap)" "float"
	CPPFLAGS += -D_SP_COMP_
endif 

ifeq "$(qpx)" "1"
	CPPFLAGS += -D_QPX_
endif

ifeq "$(qpxemu)" "1"
	CPPFLAGS += -D_QPXEMU_ -msse -msse2 #-mxop
#-march=native # -mfma4 -march=native
# -msse -msse2 -msse4 -mfma -mfma4 -march=btver1 # -march=native -mtune=native  # -mfma -mfma4
endif

ifeq "$(omp)" "1"
	ifeq "$(CC)" "icc"
		CPPFLAGS += -openmp	
		OPTFLAGS += -openmp
	else
		ifeq "$(bgq)" "1"
			CPPFLAGS += -qsmp=omp:speculative
			OPTFLAGS += -qsmp=omp:speculative
		else
			CPPFLAGS += -fopenmp
			OPTFLAGS += -fopenmp
		endif
	endif	
endif

######

vtk-inc ?=/usr/local/include/vtk-5.2/ 
vtk-lib ?=/usr/local/lib/vtk-5.2/ 
numa-inc ?=/cluster/work/infk/diegor/numactl-2.0.8-rc4 
numa-lib ?=/cluster/work/infk/diegor/numactl-2.0.8-rc4
hdf-inc ?=.
hdf-lib ?=.

ifneq "$(findstring rosa,$(shell hostname))" ""
	ifeq "$(CC)" "cc"
		LIBS += -dynamic
	endif
endif

ifneq "$(findstring todi,$(shell hostname))" ""
	ifeq "$(CC)" "cc"
		LIBS += -dynamic
	endif
endif

ifeq "$(shell hostname)" "reynolds.inf.ethz.ch"
	vtk-inc =/usr/local/include/vtk-5.6/
	vtk-lib =/usr/local/lib/vtk-5.6/
endif

ifeq "$(shell hostname)" "silvio"
	vtk-inc = /usr/include/vtk-5.6/
	vtk-lib = /usr/lib/vtk-5.6/
	hdf-inc = /home/hbabak/hdf5-1.8.8_gcc_serial/include/
	hdf-lib = /home/hbabak/hdf5-1.8.8_gcc_serial/lib/
#        hdf-inc = /home/hbabak/hdf5-1.8.8_gcc/include/
#        hdf-lib = /home/hbabak/hdf5-1.8.8_gcc/lib/
	numa-inc = /home/hbabak/numactl-2.0.7/include/
	numa-lib = /home/hbabak/numactl-2.0.7/
endif

ifneq "$(findstring brutus,$(shell hostname))" ""
	vtk-inc = /cluster/work/infk/cconti/VTK5.8_gcc/include/vtk-5.8/
	vtk-lib = /cluster/work/infk/cconti/VTK5.8_gcc/lib/vtk-5.8/
	#ifneq "$(findstring mpi,$(CC))" ""
	hdf-inc = $HDF5_ROOT/include/
	hdf-lib = $HDF5_ROOT/lib/
	#else
	#	hdf-inc = /cluster/work/infk/hbabak/apps/hdf5-1.8.8_gcc_serial/include/
	#	hdf-lib = /cluster/work/infk/hbabak/apps/hdf5-1.8.8_gcc_serial/lib/
	#endif
	numa-inc = /cluster/work/infk/hbabak/numactl-2.0.7/include/
	numa-lib = /cluster/work/infk/hbabak/numactl-2.0.7/
endif

ifneq "$(findstring rosa,$(shell hostname))" ""
        vtk-inc = /users/petrosk/VTK/include/vtk-5.8/
        vtk-lib = /users/petrosk/VTK/lib/vtk-5.8/
	#ifeq "$(CC)" "icc"
	#	hdf-inc = /users/petrosk/hdf5-1.8.8_icc_serial/include/
	#	hdf-lib = /users/petrosk/hdf5-1.8.8_icc_serial/lib/
	#else
	#	hdf-inc = /users/petrosk/hdf5-1.8.8_gcc_serial/include/
	#	hdf-lib = /users/petrosk/hdf5-1.8.8_gcc_serial/lib/
	#endif

	ifeq "$(CC)" "icc"	
	     hdf-inc = /opt/cray/hdf5-parallel/1.8.8/intel/120/include/#/users/petrosk/hdf5-1.8.8/include/
     	     hdf-lib = /opt/cray/hdf5-parallel/1.8.8/intel/120/lib/#/users/petrosk/hdf5-1.8.8/lib/
	else
         #    hdf-inc = /users/petrosk/hdf5-1.8.8_gcc/include/
         #    hdf-lib = /users/petrosk/hdf5-1.8.8_gcc/lib/
	endif

	numa-inc = /users/petrosk/numactl-2.0.7/
	numa-lib = /users/petrosk/numactl-2.0.7/lib64/
endif


ifneq "$(findstring daint,$(shell hostname))" ""
        vtk-inc = /users/petrosk/VTK/include/vtk-5.8/
        vtk-lib = /users/petrosk/VTK/lib/vtk-5.8/
        #ifeq "$(CC)" "icc"                                                                                                                                                                                                                                                                                                                 
        #       hdf-inc = /users/petrosk/hdf5-1.8.8_icc_serial/include/                                                                                                                                                                                                                                                                     
        #       hdf-lib = /users/petrosk/hdf5-1.8.8_icc_serial/lib/                                                                                                                                                                                                                                                                         
        #else                                                                                                                                                                                                                                                                                                                               
        #       hdf-inc = /users/petrosk/hdf5-1.8.8_gcc_serial/include/                                                                                                                                                                                                                                                                     
        #       hdf-lib = /users/petrosk/hdf5-1.8.8_gcc_serial/lib/                                                                                                                                                                                                                                                                         
        #endif                                                                                                                                                                                                                                                                                                                              

        ifeq "$(CC)" "icc"
             hdf-inc = /opt/cray/hdf5-parallel/1.8.8/intel/120/include/#/users/petrosk/hdf5-1.8.8/include/                                                                                                                                                                                                                                  
             hdf-lib = /opt/cray/hdf5-parallel/1.8.8/intel/120/lib/#/users/petrosk/hdf5-1.8.8/lib/                                                                                                                                                                                                                                          
        else
            # hdf-inc = /users/petrosk/hdf5-1.8.8_gcc/include/
            # hdf-lib = /users/petrosk/hdf5-1.8.8_gcc/lib/
        endif

        numa-inc = /users/petrosk/numactl-2.0.7/
        numa-lib = /users/petrosk/numactl-2.0.7/lib64/
endif

ifneq "$(findstring todi,$(shell hostname))" ""
        vtk-inc = /users/petrosk/VTK/include/vtk-5.8/
        vtk-lib = /users/petrosk/VTK/lib/vtk-5.8/
	ifeq "$(CC)" "icc"
		hdf-inc = /users/petrosk/hdf5-1.8.8_icc_serial/include/
		hdf-lib = /users/petrosk/hdf5-1.8.8_icc_serial/lib/
	else
		hdf-inc = /users/petrosk/hdf5-1.8.8_gcc_serial/include/
		hdf-lib = /users/petrosk/hdf5-1.8.8_gcc_serial/lib/
	endif
	numa-inc = /users/petrosk/numactl-2.0.7/
	numa-lib = /users/petrosk/numactl-2.0.7/lib64/
endif

ifneq "$(findstring ibm,$(shell hostname))" ""
       hdf-inc = /gpfs/DDNgpfs1/bekas/BGQ/hdf5-1.8.0/hdf5/include/
       hdf-lib = /gpfs/DDNgpfs1/bekas/BGQ/hdf5-1.8.0/hdf5/lib/
endif

ifneq "$(findstring bulldozer,$(shell hostname))" ""
       hdf-inc = /home/chatzidp/usr/hdf5/include/
       hdf-lib = /home/chatzidp/usr/hdf5/lib/
endif

CPPFLAGS += -D_ALIGNBYTES_=$(align) -D_BLOCKSIZE_=$(bs) -D_BLOCKSIZEX_=$(bs) -D_BLOCKSIZEY_=$(bs) -D_BLOCKSIZEZ_=$(bs) -DWENOEPS=$(weps) 
CPPFLAGS += -I../../../Cubism/source/ -I../source -I../../Compressor/source/ -I/usr/local/include/

ifeq "$(hdf)" "1"
	CPPFLAGS += -I$(hdf-inc) -D_USE_HDF_
	LIBS += -L$(hdf-lib) -lhdf5
endif

CPPFLAGS +=  -I$(hdf-inc)

LIBS += -lstdc++ -lm -lz 
ifeq "$(findstring Darwin,$(shell uname))" ""
	LIBS += -lrt
endif

ifeq "$(bgq)" "1"
ifeq "$(hpm)" "1"
	CPPFLAGS += -D_USE_HPM_ 
	LIBS += /gpfs/DDNgpfs1/walkup/mpi_trace/bgq/lib/libmpihpm_smp.a \
			/bgsys/drivers/ppcfloor/bgpm/lib/libbgpm.a \
			-L/bgsys/drivers/ppcfloor/spi/lib -lSPI_upci_cnk -lSPI_l1p -lSPI #-lmassv
endif
endif

ifeq "$(bgq)" "1"
       CPPFLAGS += -I/gpfs/DDNgpfs1/bekas/BGQ/LIBS/zlib/include
       LIBS += -L/gpfs/DDNgpfs1/bekas/BGQ/LIBS/zlib/lib
endif


# Compression Options

ifeq "$(wavz)" "1"
       CPPFLAGS += -D_USE_WAVZ_
endif

ifeq "$(fpc)" "1"
       CPPFLAGS += -D_USE_FPC_  -I../../tools/fpc
       LIBS += -L../../tools/fpc -lfpc 
endif

ifeq "$(fpzip)" "1"
       CPPFLAGS += -D_USE_FPZIP_  -I../../tools/fpzip/inc
       LIBS += -L../../tools/fpzip/lib -lfpzip 
endif

ifeq "$(wavz2)" "1"
       CPPFLAGS += -D_USE_WAVZ2_  -I${HOME}/usr/DRain/include
       LIBS += -L${HOME}/usr/DRain/lib -lDRain
endif

ifeq "$(shuffle)" "1"
       CPPFLAGS += -D_USE_SHUFFLE_ 
endif

ifeq "$(zerobits)" "4"
       CPPFLAGS += -D_USE_ZEROBITS_ 
       CPPFLAGS += -D_ZEROBITS_=4 
endif
ifeq "$(zerobits)" "8"
       CPPFLAGS += -D_USE_ZEROBITS_ 
       CPPFLAGS += -D_ZEROBITS_=8 
endif
ifeq "$(zerobits)" "12"
       CPPFLAGS += -D_USE_ZEROBITS_ 
       CPPFLAGS += -D_ZEROBITS_=12
endif
ifeq "$(zerobits)" "16"
       CPPFLAGS += -D_USE_ZEROBITS_ 
       CPPFLAGS += -D_ZEROBITS_=16 
endif


# Encoding Options

ifeq "$(zlib)" "1"
       CPPFLAGS += -D_USE_ZLIB_
       LIBS +=  -lz
endif

ifeq "$(lz4)" "1"
       CPPFLAGS += -D_USE_LZ4_  -I../../tools/lz4
       LIBS += -L../../tools/lz4 -llz4
endif

ifeq "$(lzf)" "1"
       CPPFLAGS += -D_USE_LZF_  -I../../tools/lzf
       LIBS += -L../../tools/lzf -llzf 
endif

ifeq "$(lzma)" "1"
       CPPFLAGS += -D_USE_LZMA_  -I../../tools/xz-5.0.5/src/liblzma/api
       LIBS += -L../../tools/xz-5.0.5/src/liblzma/.libs -llzma 
endif

ifeq "$(zopfli)" "1"
       CPPFLAGS += -D_USE_ZOPFLI_  -I../../tools/zopfli
       LIBS += -L../../tools/zopfli -lzopfli 
endif

ifeq "$(fpc2)" "1"
       CPPFLAGS += -D_USE_FPC2_  -I../../tools/fpc
       LIBS += -L../../tools/fpc -lfpc 
endif

ifeq "$(fpzip2)" "1"
       CPPFLAGS += -D_USE_FPZIP2_  -I../../tools/fpzip/inc
       LIBS += -L../../tools/fpzip/lib -lfpzip 
endif


# Extensions to the Wavelet-based Compression (wavz)

ifeq "$(fpc3)" "1"
       CPPFLAGS += -D_USE_FPC3_  -I../../tools/fpc
       LIBS += -L../../tools/fpc -lfpc 
endif

ifeq "$(fpzip3)" "1"
       CPPFLAGS += -D_USE_FPZIP3_  -I../../tools/fpzip/inc
       LIBS += -L../../tools/fpzip/lib -lfpzip 
endif

ifeq "$(shuffle3)" "1"
       CPPFLAGS += -D_USE_SHUFFLE3_ 
endif



ifeq "$(vtk)" "1"
	CPPFLAGS += -I$(vtk-inc) -D_USE_VTK_

	LIBS += -L$(vtk-lib) \
		-lvtkVolumeRendering \
		-lvtkRendering \
		-lvtkIO \
		-lvtkGenericFiltering \
		-lvtkGraphics \
		-lvtkImaging \
		-lvtkFiltering \
		-lvtkCommon \
		-lvtkftgl \
		-lvtkDICOMParser \
		-lvtksys \
		-lvtkexoIIc \
		-lvtkNetCDF \
		-lvtkNetCDF_cxx \
		-lvtkmetaio \
		-lvtksqlite \
		-lvtkverdict \
		-lvtkexpat \
		-lvtktiff \
		-lvtkpng \
		-lvtkjpeg \
		-lvtkzlib \
		-lvtkHybrid \
		-lvtkfreetype

	ifneq "$(findstring brutus,$(shell hostname))" ""
		LIBS+= -lvtkParallel -lVPIC -lCosmo
	endif
endif

ifeq "$(numa)" "1"
	CPPFLAGS += -D_USE_NUMA_ -I$(numa-inc)
	LIBS += -L$(numa-lib) -lnuma
endif
