#!/bin/bash

set -ue

o=o

rm -rvf $o
mkdir -p $o

# bubble
#br="0.125"
bc="0.5 0.6 0. "
bcx=0.3
bcy=0.3
b=b.dat

for br in 0.25 0.125 0.0625 0.045 0.037 ; do
#for br in 0.045 ; do
#for br in 0.0625 ; do
  bcyy=`bc -l <<< "$bcy + 0.5*$br"`
  echo br=$br
  echo "$bcx $bcy 0. $br" > $b
  #echo "$bcx $bcyy 0. $br" >> $b

  # ch
  echo "ch"
  make #&> /dev/null

  # ge
  echo "ge"
  (cd gerris ; ./runconv) #&> /dev/null

  ./plot.py

  p=r${br}_
  mv -v cmp.pdf o/${p}cmp.pdf
  mv -v vf.pdf o/${p}vf.pdf
done

(cd $o ; ../tile)
