#!/usr/bin/env python

import numpy as np

f = "stat.dat"

a = np.genfromtxt(f, names=True)

ee = a["ekin"][3:]
tt = a["t"][3:]

cc = np.polyfit(tt, ee, 1)

# viscosity
nu = -cc[0]

Re = 1. / nu

print(Re)

