#!/usr/bin/env python

import numpy as np
import glob
import os
import re
import aphros
import sys

def PlotStream(ax, meta, vx, vy):
    psi = aphros.stream(vx, vy)
    ax.contour(meta['x1'], meta['y1'], psi, 36, colors='k',
                linestyles="solid", linewidths=0.5)


av = sys.argv
path = av[1] if len(av) > 1 else "omz_0000.dat"
dirname = os.path.dirname(path)
filename = os.path.basename(path)
suff = re.findall("[^_]*(.*)", filename)[0]
def GetFieldPath(field):
    return os.path.join(dirname, field + suff)
vx = aphros.ReadPlain(GetFieldPath('vx'))[0,:,:]
vy = aphros.ReadPlain(GetFieldPath('vy'))[0,:,:]
omz = aphros.ReadPlain(GetFieldPath('omz'))[0,:,:]

po = os.path.splitext(filename)[0] + ".pdf"
print(po)
fig, ax, meta = aphros.InitBasicFigure(omz, grid=False)
PlotStream(ax, meta, vx, vy)
vmax = np.std(omz)
aphros.PlotFieldCoolwarm(ax, omz, -vmax, vmax)
aphros.SaveBasicFigure(fig, po)
