#!/bin/bash

set -eu

ord () {
  echo grids $1 $2 $3
  field="vx_0000.dat"
  ea=$(./diff nx{$1,$2}/$field)
  eb=$(./diff nx{$2,$3}/$field)

  echo error $ea
  echo error $eb

  echo -e "$ea\n$eb" | python -c "
import sys
import numpy as np
fin = sys.stdin
va = np.array(fin.readline().split()).astype(float)
vb = np.array(fin.readline().split()).astype(float)
print('order {:}'.format(np.log2(va / vb)))
  "
  echo
}

ord 016 032 064
ord 032 064 128
ord 064 128 256
