# generated by ./bootstrap
IMG_PDF = \
src/../../../examples/103_embed_advection/case0/u_0000.pdf \
src/../../../examples/103_embed_advection/case0/u_0001.pdf \
src/../../../examples/103_embed_advection/case1/u_0001.pdf \
src/../../../examples/103_embed_advection/case2/u_0001.pdf \
src/../../../examples/104_embed_diffusion/case0_gradlim0/u_0000.pdf \
src/../../../examples/104_embed_diffusion/case0_gradlim0/u_0001.pdf \
src/../../../examples/104_embed_diffusion/case1_gradlim0/u_0001.pdf \
src/../../../examples/104_embed_diffusion/case2_gradlim0/u_0001.pdf \
src/../../../examples/201_taylor_couette/ref/convergence/error.pdf \
src/../../../examples/201_taylor_couette/ref/single/field.pdf \
src/../../../examples/203_hydrostatic/ref/multi/density_init.pdf \
src/../../../examples/203_hydrostatic/ref/multi/density.pdf \
src/../../../examples/203_hydrostatic/ref/multi/history.pdf \
src/../../../examples/203_hydrostatic/ref/multi/pressure.pdf \
src/../../../examples/203_hydrostatic/ref/multi/velocity.pdf \
src/../../../examples/203_hydrostatic/ref/single/pressure.pdf \
src/../../../examples/203_hydrostatic/ref/single/velocity.pdf \
src/log/log10_vtkmerge/vtkmerge.pdf \

