#!/bin/bash

set -eu
set -o pipefail

cr="#ff0000"
cb="#1F77B3"

convert "$1" bmp:- |
convert bmp:- -background black -gravity center -extent 125%  bmp:- |
mkbitmap -s 1 -f 7 -b 1 -3 -i | 
potrace -t 100 -C "$cb" | 
convert eps:- bmp:- |
convert bmp:- -background none -gravity center -extent 80%  bmp:- |
convert bmp:- -crop 800x650+100+300  bmp:- |
convert bmp:- "$2"

