#!/bin/bash

set -eu

pre=../vismirror/am_
for f in $pre*.png ; do
    echo $f
    o=ae_${f#$pre}
    if [ -f "$o" ] ; then
        echo "skip existing $o"
        continue
    fi
    echo $o
    ./edge $f $o
done
