#!/bin/bash

set -eu
set -o pipefail

convert "$1" bmp:- |
convert bmp:- -background black -gravity center -extent 125%  bmp:- |
mkbitmap -s 1 -f 2 -b 1 -3 -i | 
potrace -t 100 -C "#ff0000" | 
convert eps:- bmp:- |
convert bmp:- -background none -gravity center -extent 80%  bmp:- |
convert bmp:- -crop 800x650+100+300  bmp:- |
convert bmp:- "$2"

