#!/bin/bash

set -eu

eval $@

: ${dim=2}
: ${overlap=1}
: ${d=$CHPREFIX/sim/partstr/randc}
: ${r=9}

o=dim${dim}_overlap${overlap}

echo "Output to $o"
mkdir -p $o
rsync -La $d/ $o

(cd $o && echo "set int part_ns 2" >> ch/add.conf)

#pl="--plot"
#if [ "$dim" == 3 ] ; then pl="" ; fi
pl=""

(cd $o && ./_vary $pl --dim ${dim} --overlap ${overlap} --ri $r --bi 0 --solver ch)
