#!/bin/bash

set -eu

echo 256 > np
echo 1440 > tl

./gen -nx 512 -np 256 -mode osc -dim 3 -pos center  -We 0 -La 40000 -tmax 0.4 -br 0.15  -mu 0.01 -rho 0.01   -symmxy 1 -wallz 0   -bcod 0 0 0 -bcor 0 0 0   -b2xr 2 0 0 -b2rr 1   -nb 2 -nfr 40 


cat > ch/add.conf << EOF
set string dumpformat default
set string dumplist vf omz
set int part_ns 2
EOF


echo > r_ba

