#!/usr/bin/env python3

import scipy
import argparse
import os
import glob
import sys

import aphros

def printerr(msg):
    sys.stderr.write(str(msg) + "\n")

parser = argparse.ArgumentParser(
    description=
    "Prints the Hausdorff distance between sm_*.vtk files in two directories"
)
parser.add_argument('dir1', type=str)
parser.add_argument('dir2', type=str)
args = parser.parse_args()

files1 = sorted(glob.glob(os.path.join(args.dir1, "sm_*.vtk")))

for file1 in files1:
    file2 = os.path.join(args.dir2, os.path.basename(file1))
    printerr("{} {}".format(file1, file2))
    xa, _, _ = aphros.ReadVtkPoly(file1)
    xb, _, _ = aphros.ReadVtkPoly(file2)
    da = scipy.spatial.distance.directed_hausdorff(xa, xb)[0]
    db = scipy.spatial.distance.directed_hausdorff(xb, xa)[0]
    d = max(da, db)
    print(d)
