#!/bin/sh -eu

sides=${1:-4}
out="error_sides${sides}"

echo "nx error" > "$out"
for f in sides${sides}_* ; do
  nx=$(echo "$f" | sed -En 's/.*nx(\d*)/\1/p')
  nx=$(echo "$nx" | awk '{print $1 + 0}')
  error=$(./calc_rate --traj "$f/traj.dat" --sides $sides --slope_error)
  echo $nx $error
done | tee -a "$out"
