#!/bin/bash

set -eu

: ${dim=3}
: ${overlap=1}
: ${segcirc=0}
: ${np=9}
: ${ns=3}
: ${hp=4}
: ${nri=25}
: ${nbi=100}
: ${solver="ch ba bap"}


o=dim${dim}_overlap${overlap}_segcirc${segcirc}_np${np}_ns${ns}_hp${hp}
d=`readlink -f randc`

echo "Output to $o"

r=run_$o

ch.task $d $o > $r << EOF
echo "set double part_segcirc $segcirc
set int part_np $np
set int part_ns $ns
set double part_h $hp
" > ch/add.conf

echo "-DPS_Np=$np -DPS_Ns=$ns -DPS_Hp=$hp -DPS_circ=$segcirc" > bap/extra

cat > run << EOL
./_cleanall
./_vary --dim ${dim} --overlap ${overlap} --nri $nri --nbi $nbi \
    --solver "$solver"
./_gatherall
./_move
EOL
chmod +x run
EOF

chmod +x $r
