#!/bin/bash 

set -eu

. ../util

if [ -z "${P+x}" ] ; then      # if P not defined
  pf="`type -p ${PRE}prefix || true`"
  if [ -f "$pf" ] ; then     # if ch.prefix found in PATH
    . "$pf"
  else               # else default
    P='../prefix'
  fi
fi

# get full path
P="`realpath $P`"

echo "P='$P'"

mkdir -p "$P"

echo "P='$P'" > $B/${PRE}prefix
src gen.setenv > $B/${PRE}setenv
