#!/bin/bash

set -eu

if [ "$#" -lt "1" ] || [ "$1" == "-h" ] ; then
    cat << EOF
usage: `basename $0` [-h] ARGS
Reads the number of cores NP from file 'np' and executes
mpirun -n NP ARGS
If file 'np' does not exist, executes
mpirun ARGS
EOF
    exit 1
fi

if [ -f 'np' ] ; then
  if [ "$OMP_NUM_THREADS" != "1" ] ; then
    c="mpirun --oversubscribe --map-by node:PE=$OMP_NUM_THREADS -n $(cat np) $@"
  else
    c="mpirun --oversubscribe -n $(cat np) $@"
  fi
else
  c="mpirun $@"
fi

echo "$c"
eval "$c"
