#!/bin/bash

#set -e

mkdir pressure
mkdir pressure3
mkdir alpha
mkdir alpha3
mv *-p_slice* pressure
mv *-p* pressure3
mv *-a2_slice* alpha
mv *-a2* alpha3

for f in alpha{,3}/*-a2*.xmf
do
  newf="$f"
  newf="${newf/-a2_slice1./-alpha_slice.}"
  newf="${newf/-a2./.}"
  mv "$f" "$newf"
done

for f in pressure{,3}/*-p*.xmf
do
  newf="$f"
  newf="${newf/-p_slice1./-pressure_slice.}"
  newf="${newf/-p./.}"
  mv "$f" "$newf"
done

mkdir velocity
mkdir velocity3
mkdir density
mkdir density3
mv *-rho_slice* density
mv *-rho* density3
mv *-U_slice* velocity
mv *-U* velocity3

for f in velocity{,3}/*-U*.xmf
do
  newf="$f"
  newf="${newf/-U_slice1./-velocity_slice.}"
  newf="${newf/-U./.}"
  mv "$f" "$newf"
done

for f in density{,3}/*-p*.xmf
do
  newf="$f"
  newf="${newf/-rho_slice1./-density_slice.}"
  newf="${newf/-rho./.}"
  mv "$f" "$newf"
done

echo "Draw pressure"
(cd pressure; python -u ../draw.py)
#echo "Draw alpha"
#(cd alpha; ../draw.py)

