#!/bin/bash

#set -e

mkdir pressure
mkdir alpha
mv *-p_slice* pressure
mv *-a2_slice* alpha

for f in alpha/*-a2*.xmf
do
  newf="$f"
  newf="${newf/-a2_slice1./-alpha_slice.}"
  newf="${newf/-a2./.}"
  mv "$f" "$newf"
done

for f in pressure/*-p*.xmf
do
  newf="$f"
  newf="${newf/-p_slice1./-pressure_slice.}"
  newf="${newf/-p./.}"
  mv "$f" "$newf"
done


#echo "Draw pressure"
#(cd pressure; python -u ../draw.py)
echo "Draw alpha"
(cd alpha; ../draw.py)

