#!/bin/bash

set -eu

./clean
c="`./maingen`"
spl=".main.gfs"

npexp="`cat ../npexp`"
np=`bc <<< "2^($npexp)"`

echo > out

./split "$c" "$npexp" |& tee -a out
ge.run3d -n $np -m "$spl" |& tee -a out

echo "rename"
./rename
echo "convert"
./convert
