#!/bin/bash

# Splits domain for given config file.
# $1: config file (e.g. main.gfs)
# $2: exponent for number of processors np=2 ^ $2
# Output:
# .main.gfs: config file for split domain

set -eu

orig="$1"
npexp="$2"
spl=".main.gfs"
dim=3
# split s times in each direction
s=1
# partition to 2^p domains
p=$npexp
# number of split domains
ns=`bc <<< "2^($dim * $s)"`
# number of processors
np=`bc <<< "2^($p)"`

echo "split to $ns parts, partition for $np PEs" >&2

mkdir -p `eval echo "o/{0..$(expr $np - 1)}"`
mkdir -p o/-1

t=".smain.gfs"
if test $s -eq 0; then
  cp -vf $orig $t
else
  ge.run3d -s $s -m $orig > $t
fi

if test $p -eq 0; then
  cp -vf $t $spl
else
  ge.run3d -p $p -m $t > $spl
fi
rm -vf $t
