#!/bin/bash

set -ue


dim=3  
s=2      # split s times in each direction
p=6      # partition to 2^npexp subdomains

ns=$(echo "(2^($dim * $s))" | bc) 
np=$(echo "(2^($p))" | bc) 
echo $np > np

echo "split to $ns parts, partition for $np PEs"


