#!/bin/bash

set -eu

# count number of files by pattern p
cnt() {
  p="$@"
  arr=($p)
  echo ${#arr[@]}
}

for f in *{hist,vf_ch}.pdf ; do
  pdfcrop --margins '5 10 5 10' $f cr_$f
done

t=t.pdf
n=`cnt "cr_*hist.pdf"`
pdfnup cr_*{hist,vf_ch}.pdf --nup ${n}x4 --outfile $t

o=curv.pdf
pdfcrop --margins '5 5 5 5' $t $o

rm $t cr_*.pdf
