#!/bin/bash

set -eu

for f in *{cmp,vf_ch}.pdf ; do
  pdfcrop --margins '5 10 5 10' $f cr_$f
done

t=t.pdf
pdfnup cr_*cmp.pdf cr_*vf_ch.pdf --nup 5x2 --outfile $t

o=curv.pdf
pdfcrop --margins '5 5 5 5' $t $o

rm $t cr_*.pdf
