#!/bin/bash

set -ue

# output folder
o=o
rm -vf $o/*.pdf
mkdir -p $o

# bubble
: ${bc="0.51 0.47 0.56 "}

# rx/ry ratio
#k=1.2
: ${k=1.}
echo k=$k

# log
l="out"
echo > $l

# error
e="err"
echo > $e

for br in 0.037 0.045 0.0625 0.125 0.25 0.4 ; do
  brx=`bc -l <<< "$br * $k"`
  bry=`bc -l <<< "$br / $k"`
  echo "brx=$brx, bry=$bry"
  echo "$bc $brx $bry" > b.dat
  p="r${br}_"

  # run ch
  d="ch"
  (cd $d ; ./run) &>> $l

  # run ge
  d="ge"
  (cd $d ; ./run) &>> $l

  # plot cmp
  ./plot.py &>> $l

  # append error
  cat er >> $e

  d="ch"
  mv -f $d/vf_0.pdf $o/${p}vf_$d.pdf
  d="ge"
  mv -f $d/vf_0001.pdf $o/${p}vf_$d.pdf
  mv -v ttl.pdf $o/${p}ttl.pdf
  mv -v hist.pdf $o/${p}hist.pdf
  [ -f ang.pdf ] && mv -v ang.pdf $o/${p}ang.pdf
done

mv -v err $o/
mv -v out $o/

# tile all pdf
(cd $o ; ../tile)

# rename folder
d=${o}_$k
rm -rf $d
mv -T $o $d
