#!/bin/bash

set -ue

# config file
c=${1:-a.conf}
echo c=$c

# output folder
o=o
rm -vf $o/*.pdf
mkdir -p $o

# bubble
bc="0.51 0.47 0.56 "
#bc="0.5 0.5 0.5 "
#bc="0.2 0.35 0.5 "

# rx/ry ratio
#k=1.2
: ${k=1.}
echo k=$k

# log
l="out"
echo > $l

# error
e="err"
echo > $e

for br in 0.40 0.25 0.125 0.0625 0.045 0.037 ; do
  brx=`bc -l <<< "$br * $k"`
  bry=`bc -l <<< "$br / $k"`
  echo "brx=$brx, bry=$bry"
  echo "$bc $brx $bry" > b.dat
  p="r${br}_"

  # runplot ch
  d="ch"
  (cd $d ; ./run) &>> $l


  # runplot ge
  d="ge"
  (cd $d ; ./run) &>> $l

  # plot cmp
  ./plot.py &>> $l

  # append error
  cat er >> $e

  d="ch"
  mv -f $d/vf_0.pdf $o/${p}vf_$d.pdf
  #mv -f $d/k_0.pdf $o/${p}k_$d.pdf
  d="ge"
  mv -f $d/vf_0001.pdf $o/${p}vf_$d.pdf
  #mv -f $d/k_0001.pdf $o/${p}k_$d.pdf
  cp -v hist.pdf $o/${p}hist.pdf
  cp -v ttl.pdf $o/${p}ttl.pdf
  #cp -v ang.pdf $o/${p}ang.pdf
done

# tile all pdf
(cd $o ; ../tile)

#rm -rf ${o}_$k/*
#mv -f $o ${o}_$k
