#!/bin/sh

set -eu

me=$(basename "$0")

if [ "$#" -lt "1" ] || [ "$1" = "-h" ] ; then
  cat << EOF
usage: $me [-h] FILES
Adds copyright notice to FILES if 'copyright' not found in first 10 lines.
EOF
  exit 1
fi

tmp=${me}_$$.tmp

code=0
for file in "$@" ; do
  if ! [ -f "$file" ] ; then
    echo "$me: cannot access '$file': No such file or directory"
    code=2
    continue
  fi
  head=$(head -n 10 -- "$file" )
  if echo "$head" | grep -qi "copyright" ; then
    continue
  fi

  echo "adding copyright to '$file'" 1>&2
  cp "$file" "$tmp"
  ap.copyright "$file" > "$file"
  echo >> "$file"
  cat "$tmp" >> "$file"
done

rm -f "$tmp"

exit $code
