#!/usr/bin/env python3

import numpy as np
import sys
import os

if len(sys.argv) != 1:
  sys.stderr.write(
"""usage: {:} 
Compute derivative du/dt.
STDIN:
  u t: columns
STDOUT:
  du/dt: column

""".format(sys.argv[0]))
  exit(1)

# compute derivative, forward difference, extrapolate at last point
# u: function, 1d array
# t: intependent variable, 1d array
def GetDeriv(u, t):
  dt = np.roll(t, -1) - t
  dt[-1] = dt[-2]
  du = np.roll(u, -1) - u
  du[-1] = du[-2]
  return du / dt

ut = np.loadtxt(sys.stdin)

dudt = GetDeriv(ut[:,0], ut[:,1])

np.savetxt(sys.stdout, dudt)
