#!/usr/bin/env python3

import sys
import argparse
import numpy as np

parser = argparse.ArgumentParser(
    description="Extracts columns from statistics file 'stat.dat'.")
parser.add_argument('columns', nargs='*', help="columns")
parser.add_argument('--path', default="stat.dat", help="path to 'stat.dat'")
parser.add_argument('--header',
                    action="store_true",
                    help="print header with columns")
args = parser.parse_args()

u = np.genfromtxt(args.path, skip_header=1)
u = np.atleast_2d(u)

cc = args.columns

with open(args.path) as f:
    head = f.readline().split()

unknown = [c for c in cc if c not in head]
assert not unknown, "invalid columns {:}\nvalid columns are {:}".format(
    unknown, head)

if args.header:
    sys.stdout.write(' '.join(cc) + '\n')
    sys.stdout.flush()

ii = [head.index(c) for c in cc]

np.savetxt(sys.stdout.buffer, u[:, ii])
