#!/usr/bin/env python3

import sys
import argparse
import numpy as np

parser = argparse.ArgumentParser(
    description="Extracts columns from statistics file 'stat.dat'.")
parser.add_argument('columns', nargs='+', help="columns")
parser.add_argument('--path', default="stat.dat", help="path to 'stat.dat'")
parser.add_argument('--header',
                    action="store_true",
                    help="print header with columns")
args = parser.parse_args()

u = np.genfromtxt(args.path, names=True)

cc = args.columns

unknown = [c for c in cc if c not in u.dtype.names]
assert not unknown, "invalid columns {:}\nvalid columns are {:}".format(
    unknown, list(u.dtype.names))

if args.header:
    print(' '.join(cc))

np.savetxt(sys.stdout, u[args.columns])
