#!/usr/bin/env python3

import argparse
import sys

parser = argparse.ArgumentParser(
    description="Runs Python code and writes the defined local variables "
    "of permitted types (float, int, string, list) as configuration",
    formatter_class=argparse.ArgumentDefaultsHelpFormatter)
parser.add_argument(
    'input',
    type=str,
    nargs='?',
    default='-',
    help="Path to python script. If set to '-', read from stdin")
parser.add_argument(
    'output',
    type=str,
    nargs='?',
    default='-',
    help="Path to output configuration file. If set to '-', write to stdout")
args = parser.parse_args()

var = dict()

inp = sys.stdin if args.input == '-' else open(args.input, 'r')

textpy = inp.read()
exec(textpy, {}, var)

types = {float, int, list, str}
for k in var:
    if type(var[k]) is tuple:
        var[k] = list(var[k])

var = {k: v for k, v in var.items() if type(v) in types}

from aphros import Config
textconf = Config(var).Generate()

out = sys.stdout if args.output == '-' else open(args.output, 'w')
out.write(textconf + '\n')
