#!/usr/bin/env python3

import numpy as np
import sys
import os

if len(sys.argv) != 2 or sys.argv[1] == '-h':
  sys.stderr.write(
"""usage: {:} k
Multiply column by scalar k.
STDIN:
  u: column
STDOUT:
  k*u: column
""".format(sys.argv[0]))
  exit(1)

k = float(sys.argv[1])
u = np.loadtxt(sys.stdin)

np.savetxt(sys.stdout, k * u)
