#!/bin/bash

set -eu

tmax=`cat ../tmax`
dumpdt=`bc -l <<< "0.01 * $tmax"`
sig=`cat ../sig`
mu=`cat ../mu`
vel="`cat ../vel`"
npexp="`cat ../npexp`"
np=`bc -l <<< "2 ^ $npexp"`
c="par.conf"

if [ "$np" == "1" ] ; then
  loc=1
else
  loc=0
fi

echo "set double tmax $tmax
set double dump_field_dt $dumpdt
set double dump_part_dt $dumpdt
set double sigma $sig
set double mu1 $mu
set double mu2 $mu
set vect vel $vel
set int loc $loc
" > $c

