#!/bin/bash -l

#SBATCH --job-name=mfer
#SBATCH --time=60:00
#SBATCH --constraint=gpu

export OMP_NUM_THREADS=1

. ../setenv.daint

echo running > job.status

n=`cat np`
srun ../mfer cub$n.conf &> out

echo "Done."
echo done > job.status

