#!/bin/bash

set -eu

# config file
c=${1:-loc}
c=a${c}.conf
# block size
b=${2:-8}
# number of cores
n=${3:-2}

# mesh size
m="32 32 1"

# block size
bs="$b $b 1"

./clean
ch.base
ch.aconf

# write np
echo $n > np

# partition mesh
ch.part $m $bs `cat np` > mesh.conf

# run in foreground
ch.run ch.mfer "$c"

a=0
for f in ref/{vx,vy,vz,p,vf}*.dat ; do
  echo $f
  if ! ch.diffnum "${f#ref/}" "$f" "1e-12"; then
    a=1
  fi
done

for f in ref/*.csv ; do
  echo $f
  if ! ch.diffnum "${f#ref/}" "$f" "1e-10" sort rel; then
    a=1
  fi
done

exit $a
