#!/bin/bash

set -eu

#convert $1 -flatten -threshold 50% bmp:- |
#  mkbitmap -f 2 -b 2 -s 1 -t 0.3 | potrace -C "#ff0000" | convert eps:- $2

set -o pipefail

convert "$1" bmp:- |
convert bmp:- -scale 100%  bmp:- |
mkbitmap -s 1 -f 0.6 -t 0.5 -3 -i | 
potrace -C "#ff0000" | 
convert eps:- bmp:- |
convert bmp:- -background none -scale 100%  bmp:- |
convert bmp:- -crop 200x650+300+175  bmp:- |
convert bmp:- "$2"

