#!/usr/bin/env python3

import os
import filecmp

import aphros


class Test(aphros.TestBase):
    def __init__(self):
        super().__init__(cases=["getmap", "parse"])

    def run(self, case):
        self.runcmd("./run_{} | ./strippath > out".format(case))
        return ["out"]


Test().main()
