#!/bin/bash 

set -eu

. ch.prefix
. ../util

instfnd conf
instfnd confdeb

instfnd job
instfnd run 
instfnd submit
instfnd job0
instfnd submit0
instfnd kill 

mp="$BB/ch.base.makefile"
cp -vf ../../sim/base.makefile "$mp"
echo "echo '$mp'" | instin ${PRE}makesim

src gen.base | instin ${PRE}base

src gen.aconf | instin ${PRE}aconf
