#!/bin/bash 

set -eu

. ap-setenv
. ../util

instfnd conf
instfnd confdeb

instfnd mpirun
instfnd job
instfnd writearg
instfnd run 
instfnd run0
instfnd submit
instfnd job0
instfnd submit0
instfnd kill 
instfnd sysinfo

mp="$BB/ap-base.makefile"
cp -vf ../../sim/base.makefile "$mp"
echo "echo '$mp'" | instin ${PRE}makesim

src gen.base | instin ${PRE}base

src gen.aconf | instin ${PRE}aconf
