#!/bin/bash 

set -eu

. ap.setenv
. ../util

mp="$BB/ap.base.makefile"
cp -vf ../../sim/base.makefile "$mp"
echo "echo '$mp'" | instin ${PRE}makesim

src gen.base | instin ${PRE}base

src gen.aconf | instin ${PRE}aconf
