#!/bin/bash -l

# Run with arguments from arg on number of tasks from np

# run command with time and append to out
rt () {
  echo
  c="( time $@ ) |& tee -a out"
  echo $c
  eval "$c"
}

set -eu

e=ch.mfer
if [ -f arg ] ; then
  a="`cat arg`"
else
  a=
fi

np=`cat np`

js="job.status"

echo running > $js

rm -rf out

[[ -f pre ]] && rt "mpirun -n 1 ./pre"

rt "mpirun -n $np --report-pid pid $e $a"

[[ -f post ]] && rt "mpirun -n 1 ./post"

mv -vf job.id{,.last}

echo "done" > $js

cat $js

