#!/bin/bash -l

# Run with arguments from arg on number of tasks from np

set -eu

e=ch.mfer
a=
if [ -f arg ] ; then
  a="`cat arg`"
fi

np=`cat np`

js="job.status"

echo running > $js

c="time mpirun -n $np --report-pid pid $e $a |& tee out"
echo "$c"
eval "$c"

mv -vf job.id{,.last}

echo "done" > $js

cat $js

