#!/bin/bash

set -ue

make
./clean

c=${1:-circleplain.conf}

echo c=$c


o=o

rm -vf $o/*.pdf
mkdir -p $o

# bubble
#br="0.125"
bc="0.5212 0.4593 0. "

for br in 0.25 0.125 0.0625 0.045 0.037 ; do
  echo br=$br

  echo "$bc $br" > b.dat
  #echo "0.6 0.5 0. 0.1" > b.dat
  #echo "0.7 0.5 0. 0.1" >> b.dat
  #echo "0.65 0.55 0. 0.05" >> b.dat
  #echo "0.65 0.45 0. 0.05" >> b.dat

  ./t.advection $c  &> /dev/null
  g="gerris_k"
  p="r${br}_"
  (cd $g ; ./runplot) &> /dev/null
  cp $g/u0006.pdf $o/${p}u_ge.pdf
  cp $g/k0006.pdf $o/${p}k_ge.pdf
  ./plot.py &> /dev/null
  cp u_1.pdf $o/${p}u_ch.pdf
  cp k_1.pdf $o/${p}k_ch.pdf
  cp -v kcmp_1.pdf $o/${p}kcmp.pdf
done

(cd $o ; ../tile)


#mkdir o
#for f in *.pdf *.dat out ; do
#  cp -v $f o/$f
#done
