#!/usr/bin/env python

import os
import sys
import numpy as np

# Read uniform grid data
# p: path
# Format:
# <nx> <ny> <nz>
# <u[0,0,0]> <u[0,0,1]> ...
# Return:
# array of shape (nx, ny, nz)
# None if file not found
def ReadPlain(p):
  if not os.path.isfile(p):
    return None
  with open(p) as f:
    ll = f.readlines()
    # shape x,y,z
    s = np.array(ll[0].split(), dtype=int)
    # shape z,y,x
    ss = tuple(reversed(s))
    # data flat
    u = np.array(ll[1].split(), dtype=float)
    # data z,y,x
    u = u.reshape(ss)
    return u

av = sys.argv

pa = av[1]
pb = av[2]

ua = ReadPlain(pa)
ub = ReadPlain(pb)

d = abs(ua - ub)

l1 = d.mean()
l2 = (d ** 2).mean() ** 0.5
linf = d.max()

print("{:} {:} {:}".format(l1, l2, linf))
