#!/bin/sh

VERSION_CONTROL=none
export VERSION_CONTROL
me=tool/indent

if ! </dev/null indent 2>/dev/null
then
   echo >&2 "$me: indent command is not available"
   exit 2
fi

if ! </dev/null indent --pointer-align-right 2>/dev/null
then
   echo >&2 "$me: no --pointer-align-right option"
   exit 2
fi

exec indent \
     --k-and-r-style\
     --blank-lines-after-declarations\
     --procnames-start-lines\
     --no-tabs\
     --pointer-align-right\
     --tab-size 2\
     --indent-level 2\
     "$@"
