#!/bin/bash

set -eu

nx=$1
np=$2

echo "nx=$nx np=$np"

log=log

make cleanall &>>$log
make conf &>>$log

nice make runhook m="$nx $nx 1" np=$np &>>$log
t=$(grep -i "total = " out | sed -En 's/[^=]*=[^=]*=\s*(.*?)/\1/p')
echo "time $t"
{
  ./plot omz_0000.dat
  ap.plain2vtk omz_0000.dat
  ap.plain2vtk vx_0000.dat
  ap.plain2vtk vy_0000.dat
} &>$log
d=nx$nx
mkdir -p $d
cp {vx,vy,omz}_0000.* out $d
