#!/usr/bin/env python

import os
sh = os.system

c = {}
exec(open("../conf.py").read(), None, c)

np = c['np']
loc = True if np == 1 else False
dim = c['dim']
d3 = (dim == 3)

# minimal size in z
mz = 1 if loc else 2

nx = c['nx']
ny = nx
nz = nx if d3 else mz

# block size
bx = 8 if d3 else 16
by = bx
bz = bx if d3 else mz

sh("./clean")
sh("./pargen")
sh("make m='{nx} {ny} {nz}' bs='{bx} {by} {bz}' np={np} cleanrun"
        .format(**locals()))
