#!/bin/sh

if test $# = 0
then
    seq 1 1 250 | xargs -n1 ./main
    exit
fi

a=coal.dat
b=nocoal.dat
i="$1"

A=`awk -v i=$i '$1 == i' $a`
B=`awk -v i=$i '$1 == i' $b`

gnuplot -p <<END
set term pngcairo size 800,600 font "Arial,25" background rgb 'black'
set output '`printf 'a_%04d.png' $i`'
set macro

set border lw 3 lc rgb "white"
set xtics textcolor rgb "white"
set ytics textcolor rgb "white"
set xlabel "X" textcolor rgb "white"
set ylabel "Y" textcolor rgb "white"
set key textcolor rgb "white"

dumpdt = 0.004149625013793661
farea = 0.27*0.27*2

c(i) = column(i)

set xlabel "time, s"
set ylabel "area of bubbles, m^2"
set key off
u = 'u (c("i")*dumpdt):(c("s")*farea)'

cgreen="#5ebd3e"
cred="#e23838"

plot [:dumpdt*250] \
     "$a" @u w l lw 4 lc rgb cgreen, \
     "$b" @u w l lw 4 lc rgb cred, \
     "-" @u w p pt 7 ps 4 lt 4 lc rgb cgreen, \
     "-" @u w p pt 7 ps 4 lt 4 lc rgb cred
i s
$A
e
i s
$B
e
END
