#!/bin/sh

if test $# = 0
then
    seq 1 1 250 | xargs -n1 ./main
    exit
fi

a=coal.dat
b=nocoal.dat
i="$1"

A=`awk -v i=$i '$1 == i' $a`
B=`awk -v i=$i '$1 == i' $b`

gnuplot -p <<END
set term png transparent size 800,600 font "Arial,20"
set output '`printf '%04d.png' $i`'
set macro

set border lw 3 lc rgb "white"
set xtics textcolor rgb "white"
set ytics textcolor rgb "white"
set xlabel "X" textcolor rgb "white"
set ylabel "Y" textcolor rgb "white"
set key textcolor rgb "white"

freq = 0.01
farea = 0.1

c(i) = column(i)

set xlabel "time, s"
set ylabel "bubbles' area"
set key off
u = 'u (c("i")*freq):(c("s")*farea)'

plot [:freq*250] \
     "$a" @u w l lw 3, \
     "$b" @u w l lw 3, \
     "-" @u w p pt 7 ps 4 lt 3, \
     "-" @u w p pt 7 ps 4 lt 3
i s
$A
e
i s
$B
e
END
