#!/usr/bin/env python

import numpy as np
import glob
import re

ff = sorted(glob.glob('k???.dat'))
fref = ff[-1]

kref = np.loadtxt(fref)

ee = []

b = np.loadtxt("b.dat")
br = b[3]
# exact curv
kex = 1. / br

for f in ff:
    k = np.loadtxt(f)
    n = int(re.findall("k([0-9]*)", f)[0])
    # error reference
    er = np.sqrt((k - kref) ** 2).mean() / kex
    # error exact
    ek = np.sqrt((k - kex) ** 2).mean() / kex
    e = [n, er, ek]
    ee.append(e)


fo = "kerr"
with open(fo, 'w') as f:
    for e in ee:
        f.write(' '.join(map(str, e)) + '\n')

