#!/bin/bash

set -eu

for n in `seq 1 5` ; do
    n=`printf "%03d" "$n"`
    o=k$n.dat
    echo "0.507 0.503 0.5 0.025" > b.dat
    echo "set int part_ns $n" > add.conf
    ./run
    ./curv > $o
done


