#!/usr/bin/env python3

import aphros
import numpy as np

from argparse import ArgumentParser

parser = ArgumentParser()
parser.add_argument('--sides', type=int, default=4, help="number of sides")
args = parser.parse_args()

# radius of circle
R = 0.3

# radius of circles to construct Voronoi diagram
Rinf = 100

vf = aphros.Geometry()

sides = args.sides

# small shift so that interface do not coincide with cell boundaries
shift = 1e-6

phase = np.pi / sides

vf.Sphere([0.5, 0.5, 0], [R] * 3, intersect=True)

for i in range(sides):
    alpha = i * np.pi * 2 / sides + phase
    dx = np.cos(alpha) + shift
    dy = np.sin(alpha) + shift
    vf.Sphere([0.5 + dx, 0.5 + dy, 0], [Rinf] * 3)

vf.GenerateFile("b.dat")
