#!/bin/sh -eu

log=run.log

ev () {
  echo "$@" | tee -a "$log"
  eval "$@ 2>&1" >> "$log"
}

run () {
  sides=$1
  nx=$2
  np=$3
  shift 3
  dir=sides${sides}_nx$(printf %03d $nx)
  if [ -d "$dir" ] ; then
    echo "skip existing $dir"
    return
  fi
  ev "./clean"
  ev "echo $np > np"
  ev "./gen --sides $sides"
  ev "ap.run ./main --nx $nx""$@"
  ev "mkdir -p $dir && rsync -a {gen,{s,sm}_*.vtk,std.conf,out,traj.dat} $dir/"
}

for sides in 4 6 8 ; do
  run $sides 32 1
  run $sides 64 1
  run $sides 128 4
  run $sides 256 16
  run $sides 512 64
done
