#!/bin/bash

set -eu

ev () {
  echo "$@"
  eval "$@"
}

cmd () {
  a=$1 ; b=$2
  f=`basename $a`
  f=am_${f#*_}
  if [ -f $f ] ; then
    echo "skip existing $f"
  else
    dy=215
    dx=225
    h=400
    ev convert "'$b' \( '$a'[${h}x${h}] -background none \
     -geometry +$dx+$dy \
     -scale 107% \) \
     -compose over -composite -depth 8 '$f'"
  fi
}

rm am_*.png

fr=frames

./frsc sim exp 0.122 > $fr

d=""
while read f ; do
  cmd $f
done < $fr

