#!/bin/bash

set -eu

ev () {
  echo "$@"
  eval "$@"
}

cmd () {
  a=$1 ; b=$2
  f=`basename $a`
  f=am_${f#*_}
  if [ -f $f ] ; then
    echo "skip existing $f"
  else
    dx=225
    dy=109
    ev convert "'$b' \( '$a'[400x500] -background none \
     -geometry +$dx+$dy \
     -scale 107% \) \
     -compose over -composite -depth 8 '$f'"
  fi
}

fr=frames

./frsc sim exp 0.12 > $fr

d=""
while read f ; do
  cmd $f
done < $fr

