#!/usr/bin/env python

import os
sh = os.system

def sh(s, fatal=True):
    print(s)
    r = os.system(s)
    assert not fatal or r == 0

if os.path.isfile("done"):
    print("'done' found, exiting")
    exit(0)

c = {}
exec(open("../par.py").read(), None, c)

#if not c['ge']:
#  exit(0)

np = c['np']
loc = True if np == 1 else False
dim = c['dim']
npexp = np.bit_length() - 1
assert np == 2 ** npexp, "np=%r but must be power of 2" % np

o = "out"

l = locals()

sh("./clean")
sh("./pargen")

for i in range(np):
    os.makedirs("o/{:}".format(i))

sh("./run0 {dim} {np} |& tee -a {o}".format(**l))


sh("./merge &>> {o}".format(**l))

sh("./rename")

sh("./convert &>> {o}".format(**l))

sh("echo > done")
