#!/bin/bash

set -eu

. ch.setenv
. ../util

e () {
  echo "$@"
  eval "$@"
}

l="vofi overlap vof h5 march"
for d in $l ; do
  echo Entering $d
  e "(cd $d && ./conf && make install)"
done

(cd vtkcolor && make install PRE=$PRE)
