#!/bin/bash

set -eu

P=$APHROS_PREFIX
. ../util

e () {
  echo "$@"
  eval "$@"
}

# XXX order 'l' to satisfy dependencies
l="fpzip h5 march inside overlap vofi vof"
for d in $l ; do
  echo Entering $d
  e "(cd $d && ./conf && make install)"
done

l="chmath csv table vtk vtkcolor split"
for d in $l
do (
    e cd $d
    echo Entering `pwd`
    e make install PRE=$PRE CC=cc
) done
