#!/bin/bash

set -eu

. ch.setenv
. ../util

e () {
  echo "$@"
  eval "$@"
}

# XXX order 'l' to satisfy dependencies
l="chmath fpzip h5 march overlap vofi vof"
for d in $l ; do
  echo Entering $d
  e "(cd $d && ./conf && make install)"
done

l="csv table vtk vtkcolor split"
for d in $l
do (
    e cd $d
    echo Entering `pwd`
    e make install PRE=$PRE
) done
