#!/bin/bash

set -eu

: ${suf=xz}
: ${extra=}

t="iso.tmp"

b=${1:-./}

for f in $b/vf_????${suf}.dat ; do
  if [ -f $f ] ; then
    of=`basename $f`
    of=${of%.*}.iso
    if [ -f $of ] ; then
      echo "skip existing $of"
      continue
    fi 

    echo "$f > $of"
    ./iso.py < $f > $t
    mv $t $of
  fi
done
