#!/bin/bash

set -eu

: ${o=neck}
: ${x=0.5}
: ${y=0.5}
: ${extra=}

t=neck.tmp

a=`./neck.py --header --fitcirc`
echo "i $a" > $o

for f in vf_*.{h5,dat} ; do
  if [ -f $f ] ; then
    of=${f%.*}.neck
    if [ -f $of ] ; then
      echo "skip existing $of"
    else 
      echo "$f > $of"
      ./neck.py $f --x $x --y $y --fitcirc --plot $extra > $t
      mv $t $of
    fi
    # frame index from filename
    i=${f#*_}
    i=${i%.*}
    echo "$i `cat $of`" >> $o
  fi
done


