#!/bin/bash

set -eu

: ${o=neck}
: ${x=0.5}
: ${y=0.5}

./neck.py --header --fitcirc > $o

for f in vf_*.{h5,dat} ; do
  if [ -f $f ] ; then
    echo $f
    ./neck.py $f --x $x --y $y --fitcirc --plot >> $o
  fi
done


