#!/bin/bash

set -eu

: ${suf=}
: ${x=}
: ${y=0.5}
: ${z=}
: ${extra=}

t="slice.tmp"

if [ -z "$suf" ] ; then
  suf=""
  [ -z "$x" ] && suf=${suf}x
  [ -z "$y" ] && suf=${suf}y
  [ -z "$z" ] && suf=${suf}z
fi

for f in vf_*.{h5,dat} ; do
  if [ -f $f ] ; then
    of=${f%.*}${suf}.dat
    if [ -f $of ] ; then
      echo "skip existing $of"
      continue
    fi 

    echo "$f > $of"
    ./slice.py $f -x "$x" -y "$y" -z "$z" > $t
    mv $t $of
  fi
done


