#!/bin/bash

set -eu
set -o pipefail

src=$(dirname $(realpath $0))
dat=${1:-`pwd`}
dat=$(realpath "$dat")

(cd $dat && $src/t.py)

(cd $src && ./aclose.py $dat $dat/a0.png inter)
(cd $src && ./aclose.py $dat $dat/a1.png inter slice)
(cd $src && ./aclose.py $dat $dat/a2.png inter slice part)
