#!/bin/bash

set -eu
set -o pipefail

src=$(dirname $(realpath $0))
dat=${1:-`pwd`}
dat=$(realpath "$dat")

(cd $dat && $src/partcon.py partit_0000.csv o.vtk)

(cd $src && ./a.py $dat)

mv -v $src/a.png $dat/
