#!/usr/bin/env python3

import matplotlib.pyplot as plt
import numpy as np
import os

def Plot(fn):
    u = np.loadtxt(fn)
    plt.plot(u[:,0], u[:,1])
    plt.tight_layout()
    po = os.path.splitext(fn)[0] + ".pdf"
    plt.savefig(po, dpi=300)
    plt.close()

def Plot2(fn, fni):
    u = np.loadtxt(fn)
    ui = np.loadtxt(fni)
    plt.plot(u[:,0], u[:,1])
    plt.plot(ui[:,1], ui[:,0], ls='--')
    plt.tight_layout()
    po = os.path.splitext(fn)[0] + ".pdf"
    plt.savefig(po, dpi=300)
    plt.close()

Plot("vof_u.dat")
Plot2("vof_a.dat", "vof_u.dat")
