m = 32 64 32
np = 8

#m = 32 64 1
#bs = 16 16 1

#m = 64 128 1
#bs = 32 32 1
#np = 8

#m = 32 32 32
#m = 64 64 64

#m = 48 96 48
#np = 9

#bs = 16 16 16
tl = 1440

default:
	make cleanall
	nice make run

include $(shell ap.makesim)

conf: add.conf
