#!/usr/bin/env python

import numpy as np

f = "part.log"

d = np.genfromtxt(f, names=True, dtype=(int, int, float, float))


h = dict()

#for s in range(ns)[:10]:
#    h[s] = d['res'][np.where(d['string'] == s)]

r = d['res']


ns = d['string'].max() + 1
assert len(r) % ns == 0

r = r.reshape((ns, len(r) // ns))

i = range(r.shape[1])
rm = np.median(r, axis=0)
r0 = np.percentile(r, 10, axis=0)
r1 = np.percentile(r, 90, axis=0)
rmx = np.percentile(r, 90, axis=0)

np.savetxt('iter.dat', np.vstack((i, rm, r0, r1, rmx)).T, header="i rm r0 r1 rmx", comments='')
