load("interpol")$

%o: [g, h, -f*h];
al: 1.33;
%s: rk(%o, [f, g, h], [0, 0, al], [eta, 0, 3, 0.2]) $

%eta: map(first, %s) $
%f: map(second, %s) $
%g: map(third, %s) $
%h: map(fourth, %s) $

%u: 1/2*U*%g $
%v: 1/2*sqrt(mu*U/x)*(%eta*%g - %f) $
n: length(%eta);
obj: [];
for i thru n do
push(vector([x, 2*%eta[i]*sqrt(mu*x/U)], [%u[i], %v[i]]), obj);

s: 5.2*sqrt(mu*x/U) $
draw2d(terminal  = 'png,
  file_name = 'blayer,
  line_width = 4,
  head_length = 3, xrange = [0, 10], yrange = [0, 10], color = 'red, explicit(s, x, 0, 10), color = 'blue,
  head_angle = 1, ev(obj, x = 2), ev(obj, x = 4),  ev(obj, x = 6), ev(obj, x = 8)), U = 1, mu = 1/10 $

/*

Levich, V. G. (1962). Physicochemical Hydrodynamics
Prentice-Hall. Englewood Cliffs, NJ, 115.  eq (3.22-3.40)

*/
