load("interpol")$

%o: [g, h, -f*h];
al: 1.33;
%s: rk(%o, [f, g, h], [0, 0, al], [eta, 0, 3, 0.1]) $

%eta: map(first, %s) $
%f: map(second, %s) $
%g: map(third, %s) $
%h: map(fourth, %s) $

%data: map( lambda([e], [first(e), second(e)]), %s);
define(f(x), cspline(%data))$

v: 1/2*U*%g $
u: 1/2*sqrt(mu*U/x)*(%eta*%g - %f) $
draw2d(points(%eta, u), 'color = 'red, points(%eta, v)), U = 1, mu = 1, x = 1;

/*

Levich, V. G. (1962). Physicochemical Hydrodynamics
Prentice-Hall. Englewood Cliffs, NJ, 115.  eq (3.22-3.40)

*/
