#include <math.h>
#include <stdlib.h>
#include <stdio.h>
#include "adamar.h"

const char *me = "adamar";

int main(int argc, const char **argv) {
    struct Adamar q;
    double *vx;
    double *vy;
    double *vz;
    int *Inside;
    double *p;
    double x;
    double y;
    double z;

    q.a = 1;
    q.mu0 = 1;
    q.mu1 = 1;
    q.pi = 1;

    double lx;
    double ly;
    double hx;
    double hy;
    double dx;
    double dy;
    int nx;
    int ny;
    int n;
    int i;
    int j;
    int k;
    FILE *f;
    
    lx = ly = -10;
    hx = hy = 10;
    nx = ny = 300;
    n = (nx + 1) * (ny + 1);
    dx = (hx - lx)/nx;
    dy = (hy - ly)/ny;

    vx = malloc(n*sizeof(*vx));
    vy = malloc(n*sizeof(*vy));
    vz = malloc(n*sizeof(*vz));
    p = malloc(n*sizeof(*p));
    Inside = malloc(n*sizeof(*Inside));

    for (i = k = 0; i < nx + 1; i++)
	for (j = 0; j < ny + 1; j++, k++) {
	    x = lx + dx * i;
	    y = 0;
	    z = ly + dy * j;
	    adamar_fields(&q, x, y, z, &vx[k], &vz[k], &vy[k], &p[k]);
	    vy[k] -= q.U;
	    Inside[k] = q.Inside;
	}

    f = stdout;
    fprintf(f, "# vtk DataFile Version 2.0\n"
            "generated by %s\n"
            "ASCII\n"
            "DATASET STRUCTURED_POINTS\n"
            "DIMENSIONS %d %d %d\n"
            "ORIGIN %.16g %.16g %.16g\n"
            "SPACING %.16g %.16g %.16g\n",
            me, nx + 1, ny + 1, 1, lx, ly, 0.0, dx, dy, 0.0);
    fprintf(f, "POINT_DATA %d\n", n);
    fputs("VECTORS v double\n", f);
    for (i = 0; i < n; i++)
        fprintf(f, "%.16g %.16g %.16g\n", vx[i], vy[i], vz[i]);
    fputs("SCALARS Inside int\n", f);
    fputs("LOOKUP_TABLE DEFAULT\n", f);
    for (i = 0; i < n; i++)
        fprintf(f, "%d\n", Inside[i]);
    fputs("SCALARS p double\n", f);
    fputs("LOOKUP_TABLE DEFAULT\n", f);
    for (i = 0; i < n; i++)
        fprintf(f, "%.16g\n", p[i]);

    free(vx);
    free(vy);
    free(vz);
    free(p);
    free(Inside);
}
