#!/usr/bin/env python

import numpy as np
import sys
import os
import matplotlib as mpl
import matplotlib.pyplot as plt

# Read uniform grid data
# p: path
# Format:
# <nx> <ny> <nz>
# <u[0,0,0]> <u[0,0,1]> ...
# Return:
# array of shape (nx, ny, nz)
# None if file not found
def ReadPlain(fn):
  if not os.path.isfile(fn):
    return None
  with open(fn) as f:
    ll = f.readlines()
    # shape x,y,z
    s = np.array(ll[0].split(), dtype=int)
    # shape z,y,x
    ss = tuple(reversed(s))
    # data flat
    u = np.array(ll[1].split(), dtype=float)
    # data z,y,x
    u = u.reshape(ss)
    return u

pathdat = sys.argv[1]
u = ReadPlain(pathdat)
u = u[0,:,:]

fig = plt.figure(figsize=(1,1))
ax = plt.Axes(fig, [0., 0., 1., 1.])
ax.set_axis_off()
fig.add_axes(ax)
ax.imshow(np.flipud(u), vmin=-1, vmax=1, interpolation='nearest',
        cmap=plt.get_cmap("coolwarm"))

pathfig = os.path.splitext(pathdat)[0] + ".pdf"
print(pathfig)
plt.savefig(pathfig)

