#!/bin/bash -l

ch.conf . -DEXTRA="-grid=multigrid3D"
make
ba.env ba.run main.s


a=0
r=ref
for f in $r/* ; do
  echo $f
  if ! ch.diffnum "${f#$r/}" "$f" "1e-16" sort rel; then
    a=1
  fi
done

exit $a
