SHELL := /bin/bash

CC ?= gcc
LD ?= gcc

# core
bs ?= 16
ap ?= float
weps ?= 1e-6
peps ?= 1e-5
alphaeps ?= 0.0
precdiv ?= 0
preclevel ?= 0
microfusion ?= 2
accurateweno ?= 0
omp ?= 1
align ?= 16
bgq ?= 0
qpx ?= 0
qpxemu ?= 0
sequoia ?= 0
noK ?= 0
nonuniform ?= 0

# +node
hdf ?= 0
vtk ?= 0
numa ?= 0
cvt ?= 0

# +cluster
fftw ?= 0
#

# compression methods
use_wavz ?= 1
use_fpzip ?= 0

#other
zlib ?= 1
lz4 ?= 0
fpzip ?= 1
#

GIT_COMMIT := -D_GIT_HASH_=\"$(shell git rev-parse --verify HEAD)\"
CPPFLAGS += $(GIT_COMMIT)

CPPFLAGS+= $(extra)

ifeq "$(sequoia)" "1"
	CPPFLAGS += -D_SEQUOIA_
endif

ifeq "$(noK)" "1"
	CPPFLAGS += -D_NOK_
endif

ifeq "$(nonuniform)" "1"
	CPPFLAGS += -D_NONUNIFORM_BLOCK_
endif

ifeq "$(ap)" "float"
        CPPFLAGS += -D_FLOAT_PRECISION_
endif

ifeq "$(accurateweno)" "1"
        CPPFLAGS += -D_ACCURATEWENO_
endif

CPPFLAGS += -D_MICROFUSION_=$(microfusion)
CPPFLAGS += -D_PREC_LEVEL_=$(preclevel)

#CPPFLAGS += -qlist -qsource -qreport

ifeq "$(config)" "release"
	ifeq "$(CC)" "icc"
		OPTFLAGS+= -DNDEBUG -O3 -xHOST  -ip -ansi-alias -fno-fnalias -inline-level=1
		ifeq "$(ap)" "float"
			CPPFLAGS += -fp-model precise
		else
			CPPFLAGS += -fast
		endif
	else
		ifeq "$(bgq)" "1"
			OPTFLAGS += -O3 -qsmp=speculative -qhot=level=1  -qarch=qp -qtune=qp -qprefetch=aggressive
#assistthread
		else
			OPTFLAGS += -O3 -fno-expensive-optimizations -falign-functions=16 -DNDEBUG #one can leave out falign to the default of O2 level  which is machine-dependent
		endif

		OPTFLAGS += -DNDEBUG
	endif
else
	CPPFLAGS += -g
endif

##CPPFLAGS += -Wno-deprecated

ifeq "$(cvt)" "1"
	CPPFLAGS += -D_USE_CVT_
endif

ifeq "$(precdiv)" "1"
CPPFLAGS += -D_PREC_DIV_
endif

ifeq "$(precdiv)" "-1"
	CPPFLAGS += -D_PREC_DIV_NONE_
	ifeq "$(CC)" "icc"
		#OPTFLAGS += -ipo
	endif
endif

ifeq "$(ap)" "float"
	CPPFLAGS += -D_SP_COMP_
endif

ifeq "$(qpx)" "1"
	CPPFLAGS += -D_QPX_
endif

ifeq "$(bgq)" "1"
	CPPFLAGS += -D_BGQ_
endif

ifeq "$(qpxemu)" "1"
	CPPFLAGS += -D_QPXEMU_ -msse -msse2
endif

ifeq "$(daint)" "1"
	CPPFLAGS += -D_DAINT_
endif

ifeq "$(omp)" "1"
	ifeq "$(CC)" "icc"
		CPPFLAGS += -openmp
		OPTFLAGS += -openmp
	else
		ifeq "$(bgq)" "1"
			CPPFLAGS += -qsmp=speculative
			OPTFLAGS += -qsmp=speculative
		else
			CPPFLAGS += -fopenmp
			OPTFLAGS += -fopenmp
		endif
	endif
endif

######

vtk-inc ?=/usr/local/include/vtk-5.2/
vtk-lib ?=/usr/local/lib/vtk-5.2/
numa-inc ?=/cluster/work/infk/diegor/numactl-2.0.8-rc4
numa-lib ?=/cluster/work/infk/diegor/numactl-2.0.8-rc4
hdf-inc ?=.
hdf-lib ?=.

ifneq "$(findstring rosa,$(shell hostname))" ""
	ifeq "$(CC)" "cc"
		LIBS += -dynamic
	endif
endif

ifneq "$(findstring todi,$(shell hostname))" ""
	ifeq "$(CC)" "cc"
		LIBS += -dynamic
	endif
endif

ifeq "$(shell hostname)" "reynolds.inf.ethz.ch"
	vtk-inc =/usr/local/include/vtk-5.6/
	vtk-lib =/usr/local/lib/vtk-5.6/
endif

ifeq "$(shell hostname)" "silvio"
	vtk-inc = /usr/include/vtk-5.6/
	vtk-lib = /usr/lib/vtk-5.6/
	hdf-inc = /home/hbabak/hdf5-1.8.8_gcc_serial/include/
	hdf-lib = /home/hbabak/hdf5-1.8.8_gcc_serial/lib/
#        hdf-inc = /home/hbabak/hdf5-1.8.8_gcc/include/
#        hdf-lib = /home/hbabak/hdf5-1.8.8_gcc/lib/
	numa-inc = /home/hbabak/numactl-2.0.7/include/
	numa-lib = /home/hbabak/numactl-2.0.7/
endif

ifneq "$(findstring brutus,$(shell hostname))" ""
	vtk-inc = /cluster/work/infk/cconti/VTK5.8_gcc/include/vtk-5.8/
	vtk-lib = /cluster/work/infk/cconti/VTK5.8_gcc/lib/vtk-5.8/
	#ifneq "$(findstring mpi,$(CC))" ""
	hdf-inc = $(HDF5_ROOT)/include/
	hdf-lib = $(HDF5_ROOT)/lib/
	#else
	#	hdf-inc = /cluster/work/infk/hbabak/apps/hdf5-1.8.8_gcc_serial/include/
	#	hdf-lib = /cluster/work/infk/hbabak/apps/hdf5-1.8.8_gcc_serial/lib/
	#endif
	numa-inc = /cluster/work/infk/hbabak/numactl-2.0.7/include/
	numa-lib = /cluster/work/infk/hbabak/numactl-2.0.7/
endif

ifneq "$(findstring rosa,$(shell hostname))" ""
        vtk-inc = /users/petrosk/VTK/include/vtk-5.8/
        vtk-lib = /users/petrosk/VTK/lib/vtk-5.8/
	#ifeq "$(CC)" "icc"
	#	hdf-inc = /users/petrosk/hdf5-1.8.8_icc_serial/include/
	#	hdf-lib = /users/petrosk/hdf5-1.8.8_icc_serial/lib/
	#else
	#	hdf-inc = /users/petrosk/hdf5-1.8.8_gcc_serial/include/
	#	hdf-lib = /users/petrosk/hdf5-1.8.8_gcc_serial/lib/
	#endif

	ifeq "$(CC)" "icc"
	     hdf-inc = /opt/cray/hdf5-parallel/1.8.8/intel/120/include/#/users/petrosk/hdf5-1.8.8/include/
     	     hdf-lib = /opt/cray/hdf5-parallel/1.8.8/intel/120/lib/#/users/petrosk/hdf5-1.8.8/lib/
	else
             hdf-inc = /users/petrosk/hdf5-1.8.8_gcc/include/
             hdf-lib = /users/petrosk/hdf5-1.8.8_gcc/lib/
	endif

	numa-inc = /users/petrosk/numactl-2.0.7/
	numa-lib = /users/petrosk/numactl-2.0.7/lib64/
endif

ifneq "$(findstring daint,$(shell hostname))" ""
        vtk-inc = /users/petrosk/VTK/include/vtk-5.8/
        vtk-lib = /users/petrosk/VTK/lib/vtk-5.8/
        #ifeq "$(CC)" "icc"
        #       hdf-inc = /users/petrosk/hdf5-1.8.8_icc_serial/include/
        #       hdf-lib = /users/petrosk/hdf5-1.8.8_icc_serial/lib/
        #else
        #       hdf-inc = /users/petrosk/hdf5-1.8.8_gcc_serial/include/
        #       hdf-lib = /users/petrosk/hdf5-1.8.8_gcc_serial/lib/
        #endif

        ifeq "$(CC)" "icc"
             hdf-inc = /opt/cray/hdf5-parallel/1.8.8/intel/120/include/#/users/petrosk/hdf5-1.8.8/include/
             hdf-lib = /opt/cray/hdf5-parallel/1.8.8/intel/120/lib/#/users/petrosk/hdf5-1.8.8/lib/
        else
             hdf-inc = /users/petrosk/hdf5-1.8.8_gcc/include/
             hdf-lib = /users/petrosk/hdf5-1.8.8_gcc/lib/
        endif

        numa-inc = /users/petrosk/numactl-2.0.7/
        numa-lib = /users/petrosk/numactl-2.0.7/lib64/
endif

ifneq "$(findstring todi,$(shell hostname))" ""
        vtk-inc = /users/petrosk/VTK/include/vtk-5.8/
        vtk-lib = /users/petrosk/VTK/lib/vtk-5.8/
	ifeq "$(CC)" "icc"
		hdf-inc = /users/petrosk/hdf5-1.8.8_icc_serial/include/
		hdf-lib = /users/petrosk/hdf5-1.8.8_icc_serial/lib/
	else
		hdf-inc = /users/petrosk/hdf5-1.8.8_gcc_serial/include/
		hdf-lib = /users/petrosk/hdf5-1.8.8_gcc_serial/lib/
	endif
	numa-inc = /users/petrosk/numactl-2.0.7/
	numa-lib = /users/petrosk/numactl-2.0.7/lib64/
endif

ifneq "$(findstring ibm,$(shell hostname))" ""
       hdf-inc = ${HDF5_INCLUDE}
       hdf-lib = ${HDF5_LIB}
endif

ifneq "$(findstring juq,$(shell hostname))" ""
       CPPFLAGS += -I/bgsys/local/zlib/include/
       LIBS += -L/bgsys/local/zlib/lib/
       hdf-inc = ${HDF5_INCLUDE}
       hdf-lib = ${HDF5_LIB}
endif

ifneq "$(findstring fen,$(shell hostname))" ""
       CPPFLAGS += -I${HOME}/usr/zlib/include
       LIBS += -L${HOME}/usr/zlib/lib/
       hdf-inc = ${HDF5_INC}
       hdf-lib = ${HDF5_LIB}
endif

ifneq "$(findstring mira,$(shell hostname))" ""
       CPPFLAGS += -I${HOME}/usr/zlib/include/
       LIBS += -L${HOME}/usr/zlib/lib/
       hdf-inc = /soft/libraries/hdf5/current/cnk-xl/current/include
       hdf-lib = /soft/libraries/hdf5/current/cnk-xl/current/lib
endif

ifneq "$(findstring cetus,$(shell hostname))" ""
       CPPFLAGS += -I${HOME}/usr/zlib/include/
       LIBS += -L${HOME}/usr/zlib/lib/
       hdf-inc = /soft/libraries/hdf5/current/cnk-xl/current/include
       hdf-lib = /soft/libraries/hdf5/current/cnk-xl/current/lib
endif

ifneq "$(findstring richardson.cluster,$(shell hostname))" ""
       # hdf-inc = ${HOME}/local/hdf5-1.8.18/build-serial/include
       # hdf-lib = ${HOME}/local/hdf5-1.8.18/build-serial/lib
       hdf-inc = ${HOME}/local/hdf5-1.8.18/build-parallel/include
       hdf-lib = ${HOME}/local/hdf5-1.8.18/build-parallel/lib
endif

ifneq "$(findstring tukey,$(shell hostname))" ""
	hdf-inc = ${HDF5_HOME}/include
	hdf-lib = ${HDF5_HOME}/lib
endif

ifneq "$(findstring panda,$(shell hostname))" ""
	# hdf-inc = /opt/hdf5_mpich/include
	# hdf-lib = /opt/hdf5_mpich/lib
	hdf-inc = /opt/hdf5_openmpi/include
	hdf-lib = /opt/hdf5_openmpi/lib
endif
ifneq "$(findstring falcon,$(shell hostname))" ""
	# hdf-inc = /opt/hdf5_mpich/include
	# hdf-lib = /opt/hdf5_mpich/lib
	hdf-inc = /opt/hdf5_openmpi/include
	hdf-lib = /opt/hdf5_openmpi/lib
endif

CPPFLAGS += -D_ALIGNBYTES_=$(align) -D_BLOCKSIZE_=$(bs) -D_BLOCKSIZEX_=$(bs) -D_BLOCKSIZEY_=$(bs) -D_BLOCKSIZEZ_=$(bs) -DWENOEPS=$(weps) -DPRESEPS=$(peps) -DALPHAEPS=$(alphaeps)
CPPFLAGS += -I../../../Cubism/source/ -I../source -I../../MPCFcore/source/ -I/usr/local/include/

ifeq "$(hdf)" "1"
	CPPFLAGS += -I$(hdf-inc) -D_USE_HDF_
	LIBS += -L$(hdf-lib) -lhdf5

	ifneq "$(findstring juq,$(shell hostname))" ""
	      LIBS += -L/bgsys/local/szip/lib/ -lsz
	endif

        ifneq "$(findstring fen,$(shell hostname))" ""
              #LIBS += -L$SZIP_LIB -lsz -L$ZLIB_LIB -lz
              LIBS += -L/cineca/prod/libraries/szip/2.1/bgq-xl--1.0/lib -lsz -L/cineca/prod/libraries/zlib/1.2.7/bgq-gnu--4.4.6/lib -lz
              CPPFLAGS += -D_ON_FERMI_
        endif
endif

#CPPFLAGS +=  -I$(hdf-inc)

# LIBS += -lstdc++ -lm -lz
# ifeq "$(findstring Darwin,$(shell uname))" ""
# 	LIBS += -lrt
# endif

ifeq "$(bgq)" "1"
ifeq "$(hpm)" "1"
	CPPFLAGS += -D_USE_HPM_
	LIBS += ${HOME}/usr/mpitrace/bgq/lib/libmpihpm_smp.a \
			/bgsys/drivers/ppcfloor/bgpm/lib/libbgpm.a \
			-L/bgsys/drivers/ppcfloor/spi/lib -lSPI_upci_cnk
endif
endif


LIBS += -lstdc++ -lm -lz
ifeq "$(findstring Darwin,$(shell uname))" ""
	LIBS += -lrt
endif

ifeq "$(vtk)" "1"
	CPPFLAGS += -I$(vtk-inc) -D_USE_VTK_

	LIBS += -L$(vtk-lib) \
		-lvtkVolumeRendering \
		-lvtkRendering \
		-lvtkIO \
		-lvtkGenericFiltering \
		-lvtkGraphics \
		-lvtkImaging \
		-lvtkFiltering \
		-lvtkCommon \
		-lvtkftgl \
		-lvtkDICOMParser \
		-lvtksys \
		-lvtkexoIIc \
		-lvtkNetCDF \
		-lvtkNetCDF_cxx \
		-lvtkmetaio \
		-lvtksqlite \
		-lvtkverdict \
		-lvtkexpat \
		-lvtktiff \
		-lvtkpng \
		-lvtkjpeg \
		-lvtkzlib \
		-lvtkHybrid \
		-lvtkfreetype

	ifneq "$(findstring brutus,$(shell hostname))" ""
		LIBS+= -lvtkParallel -lVPIC -lCosmo
	endif
endif

ifeq "$(numa)" "1"
	CPPFLAGS += -D_USE_NUMA_ -I$(numa-inc)
	LIBS += -L$(numa-lib) -lnuma
endif

