#!/bin/bash

set -eu

ord () {
  echo grids $1 $2 $3
  ea=`./diff2 omz_$1.dat omz_$2.dat`
  eb=`./diff2 omz_$2.dat omz_$3.dat`

  echo error $ea
  echo error $eb

  echo -e "$ea\n$eb" | python -c "
import sys
import numpy as np
fin = sys.stdin
va = np.array(fin.readline().split()).astype(float)
vb = np.array(fin.readline().split()).astype(float)
print('order {:}'.format(np.log2(va / vb)))
  "
  echo
}

ord 0 1 2
ord 1 2 3
ord 2 3 4
