#!/bin/bash

set -eu

# reference
r=ref

# run 
make -f sim.makefile cleanrun
awk 'NR%17==1{print}' < partit_0000.csv  > partit.csv

a=0
for f in $r/* ; do
  echo $f
  eps=1e-11
  if ! ap.diffnum "${f#$r/}" "$f" $eps; then a=1; fi
done

exit $a
