#!/bin/bash

set -eu

./plot.py

d=plot/traj
rm -rf $d

dc=$d/dat/ch
mkdir -p $dc
cp ch/stat.dat $dc/
dg=$d/dat/ge
mkdir -p $dg
cp ge/o/sc/* $dg/

mkdir -p $d/pdf
mv -f traj*.pdf $d/pdf

mkdir -p $d/dat
mv -f traj*.dat $d/dat

