#!/usr/bin/env python

import os
import itertools as it
import numpy
import sys
from glob import glob

import ch

sh = ch.sh

a = ch.GetStdPar('out', 'We', 'La', 'tmax', 'dim', 'dumpdefault', 
        'nfr', 'np', 'nx', 'chsm')
a['La'][0] = 1200.
a['We'][0] = 0.01
a['tmax'][0] = 1.
a['cpr0'] = [-1, "cpr range left"]
a['cpr1'] = [5, "cpr range right"]
a['cprs'] = [0.25, "cpr range step"]
a['dim'][0] = 2
a['np'][0] = 1
a['nfr'][0] = 5
a['nx'][0] = 64
c = ch.GetArgs(a)
assert c.out is not None
o = os.path.realpath(c.out)
sh("mkdir -p '{:}'".format(o))

r0,r1,rs = (c.cpr0, c.cpr1, c.cprs)

args = os.path.abspath(os.path.realpath(sys.argv[0])) 
args += ' ' + ' '.join(sys.argv[1:])

for dim,cpr in it.product([c.dim], 1. * 2 ** numpy.arange(r0,r1,rs)):
    nxm = ch.GetBs(dim)
    La = c.La
    We = c.We
    tmax = c.tmax
    #nx = max(nxm, ch.Upper2(2 * cpr * (1. + tmax)))
    nx = c.nx
    dumpdefault = c.dumpdefault
    np = c.np
    nfr = c.nfr
    chsm = c.chsm

    sf = "dim{:}_cpr{:06.02f}_we{:06.03f}_la{:06.01f}".format(dim, cpr, We, La)
    ot = os.path.join(o, "run_{:}".format(sf))
    od = os.path.join(o, "dat_{:}".format(sf))

    cf = '''

# {args}

rm -f ch/done ge/done ba/done

./gen -nx {nx} -cpr {cpr} -We {We} -La {La} -np {np} -nfr {nfr}  \
-dim {dim} -tmax {tmax} -mode vel -chsm {chsm}

echo "set int statvel 1" > ch/add.conf
'''.format(**locals())

    sh("ch.task {:} {:} > {:} <<< '{:}'".format(__file__, od, ot, cf))
    sh("chmod +x {:}".format(ot))
