#!/usr/bin/env python

import os
import itertools as it
import numpy as np
from glob import glob

import ch

sh = ch.sh

a = ch.GetStdPar('out', 'We', 'La', 'tmax')
a['La'][0] = 1200.
a['We'][0] = 0.1
a['tmax'][0] = 2.
c = ch.GetArgs(a)
assert c.out is not None
o = os.path.realpath(c.out)
sh("mkdir -p '{:}'".format(o))

ddim = [2,3]
for dim,cpr in it.product(ddim, 2 ** np.arange(0,3,1)):
    nxm = ch.GetBs(dim)
    La = c.La
    We = c.We
    tmax = c.tmax
    nx = max(nxm, ch.Upper2(2 * cpr * (1. + tmax)))

    sf = "dim{:}_cpr{:06.02f}".format(dim, cpr)
    ot = os.path.join(o, "run_{:}".format(sf))
    od = os.path.join(o, "dat_{:}".format(sf))

    cf = '''
rm -f ch/done ge/done
./gen -nx {nx} -cpr {cpr} -We {We} -La {La}  \
-dim {dim} -tmax {tmax} -mode vel'''.format(**locals())

    sh("ch.task {:} > {:} <<< '{:}'".format(od, ot, cf))
    sh("chmod +x {:}".format(ot))
