#!/bin/bash

set -eu

r=0.1

./gen -nx 16 -np 1 -mode mu -dim 2 -pos center\
  -We 0 -La 1000 -bryk 1.2 -tmax 0.1 -br 0.2\
  -mu $r -rho $r -pois 1 -wally 1 -meshvel 0\
  -bcod 0 0 0 \
  -Ga 10

./r_ch > /dev/null
./r_ge > /dev/null
#./r_plot
./r_vis
#./run
