#!/usr/bin/env python

import aphros

par = {}
exec(open("par.py").read(), None, par)

extent = par["extent"]
Re = par["Re"]

inf = extent * 10
eps = 1e-2

lx = extent
ly = extent * 0.5

center = [lx * 0.3, ly * 0.5, 0]
radii = [0.5, 0.5, 0.5]
gap = 0
gap2 = 0.05
gapy = 0

# geometry
geom = aphros.Geometry()
geom.Sphere(center, radii)
geom.Box([0, 0, 0], [gap, inf, inf])
geom.Box([lx, 0, 0], [gap2, inf, inf])
geom.Box([0, 0, 0], [inf, gapy, inf])
geom.Box([0, ly, 0], [inf, gapy, inf])

with open("body.dat", 'w') as f:
    f.write(geom.Generate())


# boundary conditions
bc = aphros.Bc()

g = aphros.Geometry()
g.Box([0, 0, 0], [inf, inf, inf])
bc.SlipWall(g)

g = aphros.Geometry()
g.Box([gap, 0, 0], [eps, inf, inf])
bc.Inlet(g, velocity = [1, 0, 0])

g = aphros.Geometry()
g.Box([lx - gap2, 0, 0], [eps, inf, inf])
bc.Outlet(g)

g = aphros.Geometry()
g.Box(center, radii)
bc.Wall(g, velocity = [0, 0, 0])

with open("bc.dat", 'w') as f:
    f.write(bc.Generate())


# configuration
var = aphros.Var()
var['extent'] = float(extent)
var['mu1'] = 1. / Re

for k in par:
    var[k] = par[k]

with open("par.conf", 'w') as f:
    f.write(var.Generate())
