#!/usr/bin/env python

import aphros
import par

extent = par.extent
Re = par.Re

inf = extent * 10
eps = 1e-3

lx = extent
ly = extent * 0.2

center = [lx * 0.3, ly * 0.5, 0]
radii = [1, 1, 1]
gap = 1

# geometry
geom = aphros.Geometry()
geom.Sphere(center, radii)
geom.Box([0, 0, 0], [gap, inf, inf], invert=1, intersect=1)
geom.Box([lx, 0, 0], [gap, inf, inf], invert=1, intersect=1)

with open("body.dat", 'w') as f:
    f.write(geom.Generate())


# boundary conditions
bc = aphros.Bc()

g = aphros.Geometry()
g.Box([0, 0, 0], [inf, inf, inf])
bc.SlipWall(g)

g = aphros.Geometry()
g.Box([gap, 0, 0], [eps, inf, inf])
bc.Inlet(g, velocity = [1, 0, 0])

g = aphros.Geometry()
g.Box([lx - gap, 0, 0], [eps, inf, inf])
bc.Outlet(g)

g = aphros.Geometry()
g.Box(center, radii)
bc.Wall(g, velocity = [0, 0, 0])

with open("bc.dat", 'w') as f:
    f.write(bc.Generate())


# configuration
var = aphros.Var()
var['extent'] = float(extent)
var['mu1'] = 1. / Re

with open("par.conf", 'w') as f:
    f.write(var.Generate())
