#!/bin/sh

set -eu

e () {
  echo "$@" 1>&2
  eval "$@"
}

getval () {
  prefix=$1
  r=$(grep "$prefix" out)
  echo ${r#$prefix}
}


bdat="body.dat"
cx=`cat $bdat | awk '{print $1}'`
cy=`cat $bdat | awk '{print $2}'`
r=`cat $bdat | awk '{print $4}'`
hdf=$1
extent=$(getval 'set double extent')
e "./separation0 $cx $cy $r "$hdf" $extent"
