#!/bin/bash

cat > par.py << EOF
Re = 1000.
extent = 10.
dim = 3

np = 4096 * 2
nx = 512
bs = 16

sigma = 0.1

Rbub = 0.05
Nbubfactor = 3

dump_field_dt = 0.1
tmax = 100.

shape = "humanoid_ellip"

rho = 0.1

EOF

make cleanrun
