#!/bin/bash

set -eu

cat > par.py << EOF
Re = 1000.
extent = 10.
dim = 3
#np = 128
#nx = 128
np = 216
nx = 192

shape = "humanoid_ellip"

bs = 16

EOF

killall ap.mfer &> /dev/null || true

make cleanrun
