#!/usr/bin/env python3

import aphros


class Test(aphros.TestBase):
    def __init__(self):
        super().__init__(cases=["main", "codeblocks"])

    def run(self, case):
        if case == "main":
            self.runcmd("./t.parser > out 2>&1")
        elif case == "codeblocks":
            self.runcmd("./t.parser.codeblocks < codeblocks_in > out 2>&1")
        else:
            raise NotImplementedError()
        return ["out"]


Test().main()
