#!/bin/bash

set -eu

r=0.001
nx=256
np=1024

Ca=0.008
Reh=500
Fr=5.37
tmax=2.5

nfr=200

echo $np > np
echo 1440 > tl


./gen -nx $nx -np $np -mode pois -dim 3 -pos center\
   -Ca $Ca -Reh $Reh -tmax $tmax \
   -chsm 3 \
   -mu $r -rho $r -pois 1 -wally 1 -wallz 1 -symm 1 \
   -nfr $nfr -g0 0 0 1 -Fr $Fr

r0=0.0987
r1=0.079
r2=0.04
cat > b.dat << EOF
0.2 $r0 $r0 $r0
0.37 $r1 $r1 $r1 
EOF

cat > ch/add.conf << EOF
set string dumpformat default
set double dump_field_t0 1e10
set double prelax 0.8
set double vrelax 0.8
set double dump_traj_dt 0.0125
set int enable_color 1
set int max_iter 10
set string init_sig linearlow
set vect sig_x 0. 0.1 0.
set vect sig_grad 0. 8.33333e-05 0.
EOF
