#!/bin/bash -l

echo running > job.status

. ../../src/setenv.daint

./clean

export OMP_NUM_THREADS=1
export OVERSUBSCRIBE=1 
#time srun -n 1536  ../mfer 
time srun -n 128  ../mfer 
#time srun -n 1  ../mfer 

echo "Done."
echo done > job.status

