#!/bin/bash

set -eu

#convert $1 -flatten -threshold 50% bmp:- |
#  mkbitmap -f 2 -b 2 -s 1 -t 0.3 | potrace -C "#ff0000" | convert eps:- $2

set -o pipefail

convert "$1" bmp:- |
convert bmp:- -alpha extract -threshold 10% bmp:- |
convert bmp:- -background black -gravity center -extent 125%  bmp:- |
mkbitmap -s 1 -f 2 -b 1 -3 -i | 
potrace -t 100 -C "#ff0000" | 
convert eps:- bmp:- |
#convert pgm:- bmp:- |
convert bmp:- -background none -gravity center -extent 80%  bmp:- |
convert bmp:- "$2"
