#!/usr/bin/env python

from sympy import *

from sympy.printing import ccode
import textwrap


x = Symbol('x')
y = Symbol('y')
z = Symbol('z')
t = Symbol('t')
V = Symbol('V')  # z-velocity of vortex translation
Z = V * t
a = Symbol('a')

Zt = diff(Z, t)
r = sqrt(x*x + y*y)
zz = z - Z

# inside
vri = 3*Zt*r*zz / (2*a*a)
vzi = Zt * (5*a*a - 3*zz*zz - 6*r*r) / (2*a*a)

R = sqrt(r**2 + zz**2)

# outside
vro = 3 * a**3 * Zt * r * zz / (2*R**5)
vzo = a**3 * Zt * (3 * zz**2 - R**2) / (2*R**5)

vri = vri.subs(t, 0)
vzi = vzi.subs(t, 0)
vro = vro.subs(t, 0)
vzo = vzo.subs(t, 0)

if 1:
    # set a=1 V=2/3 and subtract V for Zhong's paper
    vzi -= V
    vzo -= V
    vri = vri.subs(a, 1)
    vzi = vzi.subs(a, 1)
    vro = vro.subs(a, 1)
    vzo = vzo.subs(a, 1)
    vri = vri.subs(V, "2/3")
    vzi = vzi.subs(V, "2/3")
    vro = vro.subs(V, "2/3")
    vzo = vzo.subs(V, "2/3")

ll = []
ll.append(ccode(vri/r, assign_to='vrr'))
ll.append(ccode(vzi, assign_to='vz'))
ll.append(ccode(vro/r, assign_to='vrr'))
ll.append(ccode(vzo, assign_to='vz'))

o = "\n".join(ll)

print(o)
