#!/bin/sh

# $ cd src
# $ ../make/bootstrap
#
# ../make/obj.mk also creates ../make/dir.wrk.mk and ../make/dir.rule.mk

../make/obj > ../make/obj.mk &&
    ../make/hdr > ../make/hdr.mk &&
    ../make/dir > ../make/dir.mk &&
    ../make/list | ../make/dep  > ../make/dep.mk &&
    ../make/nmake Makefile_legacy > Makefile_nmake
