#!/bin/sh

me=make/bootstrap
if test $# -ge 0 -a "$1" = -h
then
    cat >&1 <<'!'
usage:
$ cd src
$ ../make/bootstrap
generates *.mk files in make/
a program ../make/obj defines object files for a library
!
    exit 2
fi

if ! test -f parse/parser.h
then
    printf >&2 '%s: error: should be used from aphros/src\n' $me
    exit 1
fi

l=/tmp/bootstrap.list.$$
o=/tmp/bootstrap.obj.$$
h=/tmp/bootstrap.hdr.$$
d=/tmp/bootstrap.dep.$$
r=/tmp/bootstrap.rule.$$

trap 'rm -f $d $h $l $o; exit 2' 1 2 3 14 15
{
    find . \
     -type f \
     -name '*.c' -or \
     -name '*.cpp' -or \
     -name '*.h' -or \
     -name '*.hpp' -or \
     -name '*.inc' -or \
     -name '*.ipp' | sed 's,^\.\/,,g' | \
	grep -v '^build[a-z_0-9]*\/';
    echo explorer.inc;
    echo linear/conjugate_cl.inc;
    echo opencl/kernels.inc;
    echo util/gitgen.cpp;
} > $l
../make/obj $l | sort | uniq > $o
grep '\.h$' $l | grep -v '^test\/' | fgrep -v aphros_c.h | sort | uniq > $h
../make/var H $h > ../make/hdr.mk
../make/list $l | ../make/dep > $d

# unix
awk '{printf "$(WRK)/%s.o: $(SRC)/%s\n", $1, $2}' $d > ../make/unix/dep.mk
grep '\/' $h | sed 's,\/.*,,g' | uniq | ../make/var D > ../make/unix/dir.mk
grep '\/' $o | sed 's,\/.*,,g' | uniq | awk '{printf "$(WRK)/%s\n", $1}' | \
    ../make/var P > ../make/unix/dir.rule.mk
awk '{printf "$(WRK)/%s.o: $(WRK)/.dir\n", $1}' $o > ../make/unix/dir.dep.mk
awk '{printf "$(WRK)/%s.o\n", $1}' $o | ../make/var O > ../make/unix/obj.mk
awk '{printf "$(WRK)/%s.o: $(SRC)/%s; %s $(SRC)/%s\n", $1, $2, $3, $2}' $o > ../make/unix/rule.mk

# windows
awk '{printf "%s.obj: %s\n", $1, $2}' $d | \
    sed 's,/,\\,g' > ../make/windows/dep.mk
awk '{printf "%s.obj\n", $1}' $o | sed 's,/,\\,g' | \
    ../make/var O > ../make/windows/obj.mk
awk '{printf "%s.obj: %s; %s %s\n", $1, $2, $3, $2}' $o | \
    sed 's,/,\\,g' > ../make/windows/rule.mk

status=$?
rm $d $h $l $o
exit $status
