$(WRK)/aphros_c/git.o: $(SRC)/aphros_c.h
$(WRK)/aphros_c/git.o: $(SRC)/util/git.h
$(WRK)/aphros_c/main.o: $(SRC)/aphros_c.h
$(WRK)/aphros_c/main.o: $(SRC)/debug/isnan.h
$(WRK)/aphros_c/main.o: $(SRC)/debug/linear.h
$(WRK)/aphros_c/main.o: $(SRC)/distr/distr.h
$(WRK)/aphros_c/main.o: $(SRC)/distr/distrsolver.h
$(WRK)/aphros_c/main.o: $(SRC)/distr/reduce.h
$(WRK)/aphros_c/main.o: $(SRC)/dump/dumper.h
$(WRK)/aphros_c/main.o: $(SRC)/dump/dump.h
$(WRK)/aphros_c/main.o: $(SRC)/dump/hdf.h
$(WRK)/aphros_c/main.o: $(SRC)/func/init_contang.h
$(WRK)/aphros_c/main.o: $(SRC)/func/init.h
$(WRK)/aphros_c/main.o: $(SRC)/geom/blockface.h
$(WRK)/aphros_c/main.o: $(SRC)/geom/block.h
$(WRK)/aphros_c/main.o: $(SRC)/geom/dir.h
$(WRK)/aphros_c/main.o: $(SRC)/geom/field.h
$(WRK)/aphros_c/main.o: $(SRC)/geom/filter.h
$(WRK)/aphros_c/main.o: $(SRC)/geom/idx.h
$(WRK)/aphros_c/main.o: $(SRC)/geom/loop.h
$(WRK)/aphros_c/main.o: $(SRC)/geom/map.h
$(WRK)/aphros_c/main.o: $(SRC)/geom/mesh.h
$(WRK)/aphros_c/main.o: $(SRC)/geom/notation.h
$(WRK)/aphros_c/main.o: $(SRC)/geom/range.h
$(WRK)/aphros_c/main.o: $(SRC)/geom/rangein.h
$(WRK)/aphros_c/main.o: $(SRC)/geom/rangemulti.h
$(WRK)/aphros_c/main.o: $(SRC)/geom/transform.h
$(WRK)/aphros_c/main.o: $(SRC)/geom/vect.h
$(WRK)/aphros_c/main.o: $(SRC)/kernel/hydro.h
$(WRK)/aphros_c/main.o: $(SRC)/kernel/kernelmesh.h
$(WRK)/aphros_c/main.o: $(SRC)/kernel/kernelmeshpar.h
$(WRK)/aphros_c/main.o: $(SRC)/linear/linear.h
$(WRK)/aphros_c/main.o: $(SRC)/parse/curv.h
$(WRK)/aphros_c/main.o: $(SRC)/parse/parser.h
$(WRK)/aphros_c/main.o: $(SRC)/parse/proj.h
$(WRK)/aphros_c/main.o: $(SRC)/parse/simple.h
$(WRK)/aphros_c/main.o: $(SRC)/parse/solver.h
$(WRK)/aphros_c/main.o: $(SRC)/parse/util.h
$(WRK)/aphros_c/main.o: $(SRC)/parse/vars.h
$(WRK)/aphros_c/main.o: $(SRC)/parse/vof.h
$(WRK)/aphros_c/main.o: $(SRC)/solver/advection.h
$(WRK)/aphros_c/main.o: $(SRC)/solver/approx2.h
$(WRK)/aphros_c/main.o: $(SRC)/solver/approx_eb.h
$(WRK)/aphros_c/main.o: $(SRC)/solver/approx.h
$(WRK)/aphros_c/main.o: $(SRC)/solver/cond.h
$(WRK)/aphros_c/main.o: $(SRC)/solver/convdiff.h
$(WRK)/aphros_c/main.o: $(SRC)/solver/convdiffvg.h
$(WRK)/aphros_c/main.o: $(SRC)/solver/convdiffv.h
$(WRK)/aphros_c/main.o: $(SRC)/solver/curv.h
$(WRK)/aphros_c/main.o: $(SRC)/solver/electro.h
$(WRK)/aphros_c/main.o: $(SRC)/solver/embed.h
$(WRK)/aphros_c/main.o: $(SRC)/solver/fluid_dummy.h
$(WRK)/aphros_c/main.o: $(SRC)/solver/fluid.h
$(WRK)/aphros_c/main.o: $(SRC)/solver/multi.h
$(WRK)/aphros_c/main.o: $(SRC)/solver/normal.h
$(WRK)/aphros_c/main.o: $(SRC)/solver/particles.h
$(WRK)/aphros_c/main.o: $(SRC)/solver/partstr.h
$(WRK)/aphros_c/main.o: $(SRC)/solver/partstrmeshm.h
$(WRK)/aphros_c/main.o: $(SRC)/solver/proj.h
$(WRK)/aphros_c/main.o: $(SRC)/solver/reconst.h
$(WRK)/aphros_c/main.o: $(SRC)/solver/simple.h
$(WRK)/aphros_c/main.o: $(SRC)/solver/solver.h
$(WRK)/aphros_c/main.o: $(SRC)/solver/tracer.h
$(WRK)/aphros_c/main.o: $(SRC)/solver/vof.h
$(WRK)/aphros_c/main.o: $(SRC)/solver/vofm.h
$(WRK)/aphros_c/main.o: $(SRC)/util/convdiff.h
$(WRK)/aphros_c/main.o: $(SRC)/util/distr.h
$(WRK)/aphros_c/main.o: $(SRC)/util/events.h
$(WRK)/aphros_c/main.o: $(SRC)/util/filesystem.h
$(WRK)/aphros_c/main.o: $(SRC)/util/format.h
$(WRK)/aphros_c/main.o: $(SRC)/util/hydro.h
$(WRK)/aphros_c/main.o: $(SRC)/util/linear.h
$(WRK)/aphros_c/main.o: $(SRC)/util/logger.h
$(WRK)/aphros_c/main.o: $(SRC)/util/macros.h
$(WRK)/aphros_c/main.o: $(SRC)/util/metrics.h
$(WRK)/aphros_c/main.o: $(SRC)/util/module.h
$(WRK)/aphros_c/main.o: $(SRC)/util/mpi.h
$(WRK)/aphros_c/main.o: $(SRC)/util/posthook.h
$(WRK)/aphros_c/main.o: $(SRC)/util/stat.h
$(WRK)/aphros_c/main.o: $(SRC)/util/suspender.h
$(WRK)/aphros_c/main.o: $(SRC)/util/sysinfo.h
$(WRK)/aphros_c/main.o: $(SRC)/util/timer.h
$(WRK)/aphros_c/parser.o: $(SRC)/aphros_c.h
$(WRK)/aphros_c/parser.o: $(SRC)/parse/parser.h
$(WRK)/aphros_c/parser.o: $(SRC)/parse/vars.h
$(WRK)/aphros_c/parser.o: $(SRC)/util/logger.h
$(WRK)/aphros_c/parser.o: $(SRC)/util/macros.h
$(WRK)/color/color.o: $(SRC)/color/color.h
$(WRK)/distr/comm_manager.o: $(SRC)/distr/comm_manager.h
$(WRK)/distr/comm_manager.o: $(SRC)/distr/comm_manager.ipp
$(WRK)/distr/comm_manager.o: $(SRC)/distr/comm_manager_seq.ipp
$(WRK)/distr/comm_manager.o: $(SRC)/distr/distr.h
$(WRK)/distr/comm_manager.o: $(SRC)/distr/distrsolver.h
$(WRK)/distr/comm_manager.o: $(SRC)/distr/reduce.h
$(WRK)/distr/comm_manager.o: $(SRC)/dump/dumper.h
$(WRK)/distr/comm_manager.o: $(SRC)/dump/dump.h
$(WRK)/distr/comm_manager.o: $(SRC)/geom/blockface.h
$(WRK)/distr/comm_manager.o: $(SRC)/geom/block.h
$(WRK)/distr/comm_manager.o: $(SRC)/geom/dir.h
$(WRK)/distr/comm_manager.o: $(SRC)/geom/field.h
$(WRK)/distr/comm_manager.o: $(SRC)/geom/idx.h
$(WRK)/distr/comm_manager.o: $(SRC)/geom/loop.h
$(WRK)/distr/comm_manager.o: $(SRC)/geom/map.h
$(WRK)/distr/comm_manager.o: $(SRC)/geom/mesh.h
$(WRK)/distr/comm_manager.o: $(SRC)/geom/notation.h
$(WRK)/distr/comm_manager.o: $(SRC)/geom/range.h
$(WRK)/distr/comm_manager.o: $(SRC)/geom/rangein.h
$(WRK)/distr/comm_manager.o: $(SRC)/geom/rangemulti.h
$(WRK)/distr/comm_manager.o: $(SRC)/geom/transform.h
$(WRK)/distr/comm_manager.o: $(SRC)/geom/vect.h
$(WRK)/distr/comm_manager.o: $(SRC)/kernel/kernelmesh.h
$(WRK)/distr/comm_manager.o: $(SRC)/kernel/kernelmeshpar.h
$(WRK)/distr/comm_manager.o: $(SRC)/parse/parser.h
$(WRK)/distr/comm_manager.o: $(SRC)/parse/vars.h
$(WRK)/distr/comm_manager.o: $(SRC)/util/distr.h
$(WRK)/distr/comm_manager.o: $(SRC)/util/format.h
$(WRK)/distr/comm_manager.o: $(SRC)/util/logger.h
$(WRK)/distr/comm_manager.o: $(SRC)/util/macros.h
$(WRK)/distr/comm_manager.o: $(SRC)/util/metrics.h
$(WRK)/distr/comm_manager.o: $(SRC)/util/module.h
$(WRK)/distr/comm_manager.o: $(SRC)/util/mpi.h
$(WRK)/distr/comm_manager.o: $(SRC)/util/suspender.h
$(WRK)/distr/comm_manager.o: $(SRC)/util/sysinfo.h
$(WRK)/distr/comm_manager.o: $(SRC)/util/timer.h
$(WRK)/distr/cubismnc.o: $(SRC)/CubismNoCopy/BlockInfo.h
$(WRK)/distr/cubismnc.o: $(SRC)/CubismNoCopy/BlockLab.h
$(WRK)/distr/cubismnc.o: $(SRC)/CubismNoCopy/BlockLabMPI.h
$(WRK)/distr/cubismnc.o: $(SRC)/CubismNoCopy/DependencyCubeMPI.h
$(WRK)/distr/cubismnc.o: $(SRC)/CubismNoCopy/Grid.h
$(WRK)/distr/cubismnc.o: $(SRC)/CubismNoCopy/GridMPI.h
$(WRK)/distr/cubismnc.o: $(SRC)/CubismNoCopy/HDF5Dumper_MPI.h
$(WRK)/distr/cubismnc.o: $(SRC)/CubismNoCopy/PUPkernelsMPI.h
$(WRK)/distr/cubismnc.o: $(SRC)/CubismNoCopy/QPXEMU.h
$(WRK)/distr/cubismnc.o: $(SRC)/CubismNoCopy/StencilInfo.h
$(WRK)/distr/cubismnc.o: $(SRC)/CubismNoCopy/SynchronizerMPI.h
$(WRK)/distr/cubismnc.o: $(SRC)/distr/cubismnc.ipp
$(WRK)/distr/cubismnc.o: $(SRC)/distr/distr.h
$(WRK)/distr/cubismnc.o: $(SRC)/distr/reduce.h
$(WRK)/distr/cubismnc.o: $(SRC)/dump/dumper.h
$(WRK)/distr/cubismnc.o: $(SRC)/dump/dump.h
$(WRK)/distr/cubismnc.o: $(SRC)/geom/blockface.h
$(WRK)/distr/cubismnc.o: $(SRC)/geom/block.h
$(WRK)/distr/cubismnc.o: $(SRC)/geom/dir.h
$(WRK)/distr/cubismnc.o: $(SRC)/geom/field.h
$(WRK)/distr/cubismnc.o: $(SRC)/geom/idx.h
$(WRK)/distr/cubismnc.o: $(SRC)/geom/loop.h
$(WRK)/distr/cubismnc.o: $(SRC)/geom/map.h
$(WRK)/distr/cubismnc.o: $(SRC)/geom/mesh.h
$(WRK)/distr/cubismnc.o: $(SRC)/geom/notation.h
$(WRK)/distr/cubismnc.o: $(SRC)/geom/range.h
$(WRK)/distr/cubismnc.o: $(SRC)/geom/rangein.h
$(WRK)/distr/cubismnc.o: $(SRC)/geom/rangemulti.h
$(WRK)/distr/cubismnc.o: $(SRC)/geom/transform.h
$(WRK)/distr/cubismnc.o: $(SRC)/geom/vect.h
$(WRK)/distr/cubismnc.o: $(SRC)/kernel/kernelmesh.h
$(WRK)/distr/cubismnc.o: $(SRC)/parse/vars.h
$(WRK)/distr/cubismnc.o: $(SRC)/util/compressor.h
$(WRK)/distr/cubismnc.o: $(SRC)/util/format.h
$(WRK)/distr/cubismnc.o: $(SRC)/util/histogram.h
$(WRK)/distr/cubismnc.o: $(SRC)/util/logger.h
$(WRK)/distr/cubismnc.o: $(SRC)/util/macros.h
$(WRK)/distr/cubismnc.o: $(SRC)/util/metrics.h
$(WRK)/distr/cubismnc.o: $(SRC)/util/module.h
$(WRK)/distr/cubismnc.o: $(SRC)/util/mpi.h
$(WRK)/distr/cubismnc.o: $(SRC)/util/suspender.h
$(WRK)/distr/cubismnc.o: $(SRC)/util/sysinfo.h
$(WRK)/distr/cubismnc.o: $(SRC)/util/timer.h
$(WRK)/distr/distrbasic.o: $(SRC)/distr/distr.h
$(WRK)/distr/distrbasic.o: $(SRC)/distr/distrsolver.h
$(WRK)/distr/distrbasic.o: $(SRC)/distr/reduce.h
$(WRK)/distr/distrbasic.o: $(SRC)/dump/dumper.h
$(WRK)/distr/distrbasic.o: $(SRC)/dump/dump.h
$(WRK)/distr/distrbasic.o: $(SRC)/geom/blockface.h
$(WRK)/distr/distrbasic.o: $(SRC)/geom/block.h
$(WRK)/distr/distrbasic.o: $(SRC)/geom/dir.h
$(WRK)/distr/distrbasic.o: $(SRC)/geom/field.h
$(WRK)/distr/distrbasic.o: $(SRC)/geom/idx.h
$(WRK)/distr/distrbasic.o: $(SRC)/geom/loop.h
$(WRK)/distr/distrbasic.o: $(SRC)/geom/map.h
$(WRK)/distr/distrbasic.o: $(SRC)/geom/mesh.h
$(WRK)/distr/distrbasic.o: $(SRC)/geom/notation.h
$(WRK)/distr/distrbasic.o: $(SRC)/geom/range.h
$(WRK)/distr/distrbasic.o: $(SRC)/geom/rangein.h
$(WRK)/distr/distrbasic.o: $(SRC)/geom/rangemulti.h
$(WRK)/distr/distrbasic.o: $(SRC)/geom/transform.h
$(WRK)/distr/distrbasic.o: $(SRC)/geom/vect.h
$(WRK)/distr/distrbasic.o: $(SRC)/kernel/kernelmesh.h
$(WRK)/distr/distrbasic.o: $(SRC)/kernel/kernelmeshpar.h
$(WRK)/distr/distrbasic.o: $(SRC)/parse/parser.h
$(WRK)/distr/distrbasic.o: $(SRC)/parse/vars.h
$(WRK)/distr/distrbasic.o: $(SRC)/util/distr.h
$(WRK)/distr/distrbasic.o: $(SRC)/util/format.h
$(WRK)/distr/distrbasic.o: $(SRC)/util/git.h
$(WRK)/distr/distrbasic.o: $(SRC)/util/logger.h
$(WRK)/distr/distrbasic.o: $(SRC)/util/macros.h
$(WRK)/distr/distrbasic.o: $(SRC)/util/metrics.h
$(WRK)/distr/distrbasic.o: $(SRC)/util/module.h
$(WRK)/distr/distrbasic.o: $(SRC)/util/mpi.h
$(WRK)/distr/distrbasic.o: $(SRC)/util/subcomm.h
$(WRK)/distr/distrbasic.o: $(SRC)/util/suspender.h
$(WRK)/distr/distrbasic.o: $(SRC)/util/sysinfo.h
$(WRK)/distr/distrbasic.o: $(SRC)/util/timer.h
$(WRK)/distr/distr.o: $(SRC)/distr/distr.h
$(WRK)/distr/distr.o: $(SRC)/distr/distr.ipp
$(WRK)/distr/distr.o: $(SRC)/distr/reduce.h
$(WRK)/distr/distr.o: $(SRC)/distr/report.h
$(WRK)/distr/distr.o: $(SRC)/dump/dumper.h
$(WRK)/distr/distr.o: $(SRC)/dump/dump.h
$(WRK)/distr/distr.o: $(SRC)/dump/raw.h
$(WRK)/distr/distr.o: $(SRC)/dump/xmf.h
$(WRK)/distr/distr.o: $(SRC)/geom/blockface.h
$(WRK)/distr/distr.o: $(SRC)/geom/block.h
$(WRK)/distr/distr.o: $(SRC)/geom/dir.h
$(WRK)/distr/distr.o: $(SRC)/geom/field.h
$(WRK)/distr/distr.o: $(SRC)/geom/idx.h
$(WRK)/distr/distr.o: $(SRC)/geom/loop.h
$(WRK)/distr/distr.o: $(SRC)/geom/map.h
$(WRK)/distr/distr.o: $(SRC)/geom/mesh.h
$(WRK)/distr/distr.o: $(SRC)/geom/notation.h
$(WRK)/distr/distr.o: $(SRC)/geom/range.h
$(WRK)/distr/distr.o: $(SRC)/geom/rangein.h
$(WRK)/distr/distr.o: $(SRC)/geom/rangemulti.h
$(WRK)/distr/distr.o: $(SRC)/geom/transform.h
$(WRK)/distr/distr.o: $(SRC)/geom/vect.h
$(WRK)/distr/distr.o: $(SRC)/kernel/kernelmesh.h
$(WRK)/distr/distr.o: $(SRC)/parse/vars.h
$(WRK)/distr/distrsolver.o: $(SRC)/distr/distr.h
$(WRK)/distr/distrsolver.o: $(SRC)/distr/distrsolver.h
$(WRK)/distr/distrsolver.o: $(SRC)/distr/reduce.h
$(WRK)/distr/distrsolver.o: $(SRC)/dump/dumper.h
$(WRK)/distr/distrsolver.o: $(SRC)/dump/dump.h
$(WRK)/distr/distrsolver.o: $(SRC)/geom/blockface.h
$(WRK)/distr/distrsolver.o: $(SRC)/geom/block.h
$(WRK)/distr/distrsolver.o: $(SRC)/geom/dir.h
$(WRK)/distr/distrsolver.o: $(SRC)/geom/field.h
$(WRK)/distr/distrsolver.o: $(SRC)/geom/idx.h
$(WRK)/distr/distrsolver.o: $(SRC)/geom/loop.h
$(WRK)/distr/distrsolver.o: $(SRC)/geom/map.h
$(WRK)/distr/distrsolver.o: $(SRC)/geom/mesh.h
$(WRK)/distr/distrsolver.o: $(SRC)/geom/notation.h
$(WRK)/distr/distrsolver.o: $(SRC)/geom/range.h
$(WRK)/distr/distrsolver.o: $(SRC)/geom/rangein.h
$(WRK)/distr/distrsolver.o: $(SRC)/geom/rangemulti.h
$(WRK)/distr/distrsolver.o: $(SRC)/geom/transform.h
$(WRK)/distr/distrsolver.o: $(SRC)/geom/vect.h
$(WRK)/distr/distrsolver.o: $(SRC)/kernel/kernelmesh.h
$(WRK)/distr/distrsolver.o: $(SRC)/kernel/kernelmeshpar.h
$(WRK)/distr/distrsolver.o: $(SRC)/parse/argparse.h
$(WRK)/distr/distrsolver.o: $(SRC)/parse/parser.h
$(WRK)/distr/distrsolver.o: $(SRC)/parse/vars.h
$(WRK)/distr/distrsolver.o: $(SRC)/util/distr.h
$(WRK)/distr/distrsolver.o: $(SRC)/util/format.h
$(WRK)/distr/distrsolver.o: $(SRC)/util/git.h
$(WRK)/distr/distrsolver.o: $(SRC)/util/logger.h
$(WRK)/distr/distrsolver.o: $(SRC)/util/macros.h
$(WRK)/distr/distrsolver.o: $(SRC)/util/metrics.h
$(WRK)/distr/distrsolver.o: $(SRC)/util/module.h
$(WRK)/distr/distrsolver.o: $(SRC)/util/mpi.h
$(WRK)/distr/distrsolver.o: $(SRC)/util/subcomm.h
$(WRK)/distr/distrsolver.o: $(SRC)/util/suspender.h
$(WRK)/distr/distrsolver.o: $(SRC)/util/sysinfo.h
$(WRK)/distr/distrsolver.o: $(SRC)/util/timer.h
$(WRK)/distr/distr.o: $(SRC)/util/filesystem.h
$(WRK)/distr/distr.o: $(SRC)/util/format.h
$(WRK)/distr/distr.o: $(SRC)/util/logger.h
$(WRK)/distr/distr.o: $(SRC)/util/macros.h
$(WRK)/distr/distr.o: $(SRC)/util/metrics.h
$(WRK)/distr/distr.o: $(SRC)/util/module.h
$(WRK)/distr/distr.o: $(SRC)/util/mpi.h
$(WRK)/distr/distr.o: $(SRC)/util/suspender.h
$(WRK)/distr/distr.o: $(SRC)/util/sysinfo.h
$(WRK)/distr/distr.o: $(SRC)/util/timer.h
$(WRK)/distr/local.o: $(SRC)/distr/distr.h
$(WRK)/distr/local.o: $(SRC)/distr/local.ipp
$(WRK)/distr/local.o: $(SRC)/distr/reduce.h
$(WRK)/distr/local.o: $(SRC)/dump/dumper.h
$(WRK)/distr/local.o: $(SRC)/dump/dump.h
$(WRK)/distr/local.o: $(SRC)/dump/output.h
$(WRK)/distr/local.o: $(SRC)/dump/output_paraview.h
$(WRK)/distr/local.o: $(SRC)/geom/blockface.h
$(WRK)/distr/local.o: $(SRC)/geom/block.h
$(WRK)/distr/local.o: $(SRC)/geom/dir.h
$(WRK)/distr/local.o: $(SRC)/geom/field.h
$(WRK)/distr/local.o: $(SRC)/geom/idx.h
$(WRK)/distr/local.o: $(SRC)/geom/loop.h
$(WRK)/distr/local.o: $(SRC)/geom/map.h
$(WRK)/distr/local.o: $(SRC)/geom/mesh.h
$(WRK)/distr/local.o: $(SRC)/geom/notation.h
$(WRK)/distr/local.o: $(SRC)/geom/range.h
$(WRK)/distr/local.o: $(SRC)/geom/rangein.h
$(WRK)/distr/local.o: $(SRC)/geom/rangemulti.h
$(WRK)/distr/local.o: $(SRC)/geom/transform.h
$(WRK)/distr/local.o: $(SRC)/geom/vect.h
$(WRK)/distr/local.o: $(SRC)/kernel/kernelmesh.h
$(WRK)/distr/local.o: $(SRC)/parse/vars.h
$(WRK)/distr/local.o: $(SRC)/util/logger.h
$(WRK)/distr/local.o: $(SRC)/util/macros.h
$(WRK)/distr/local.o: $(SRC)/util/metrics.h
$(WRK)/distr/local.o: $(SRC)/util/module.h
$(WRK)/distr/local.o: $(SRC)/util/mpi.h
$(WRK)/distr/local.o: $(SRC)/util/suspender.h
$(WRK)/distr/local.o: $(SRC)/util/sysinfo.h
$(WRK)/distr/local.o: $(SRC)/util/timer.h
$(WRK)/distr/native.o: $(SRC)/distr/comm_manager.h
$(WRK)/distr/native.o: $(SRC)/distr/distr.h
$(WRK)/distr/native.o: $(SRC)/distr/distrsolver.h
$(WRK)/distr/native.o: $(SRC)/distr/native.ipp
$(WRK)/distr/native.o: $(SRC)/distr/reduce.h
$(WRK)/distr/native.o: $(SRC)/dump/dumper.h
$(WRK)/distr/native.o: $(SRC)/dump/dump.h
$(WRK)/distr/native.o: $(SRC)/geom/blockface.h
$(WRK)/distr/native.o: $(SRC)/geom/block.h
$(WRK)/distr/native.o: $(SRC)/geom/dir.h
$(WRK)/distr/native.o: $(SRC)/geom/field.h
$(WRK)/distr/native.o: $(SRC)/geom/idx.h
$(WRK)/distr/native.o: $(SRC)/geom/loop.h
$(WRK)/distr/native.o: $(SRC)/geom/map.h
$(WRK)/distr/native.o: $(SRC)/geom/mesh.h
$(WRK)/distr/native.o: $(SRC)/geom/notation.h
$(WRK)/distr/native.o: $(SRC)/geom/range.h
$(WRK)/distr/native.o: $(SRC)/geom/rangein.h
$(WRK)/distr/native.o: $(SRC)/geom/rangemulti.h
$(WRK)/distr/native.o: $(SRC)/geom/transform.h
$(WRK)/distr/native.o: $(SRC)/geom/vect.h
$(WRK)/distr/native.o: $(SRC)/kernel/kernelmesh.h
$(WRK)/distr/native.o: $(SRC)/kernel/kernelmeshpar.h
$(WRK)/distr/native.o: $(SRC)/parse/parser.h
$(WRK)/distr/native.o: $(SRC)/parse/vars.h
$(WRK)/distr/native.o: $(SRC)/util/distr.h
$(WRK)/distr/native.o: $(SRC)/util/format.h
$(WRK)/distr/native.o: $(SRC)/util/logger.h
$(WRK)/distr/native.o: $(SRC)/util/macros.h
$(WRK)/distr/native.o: $(SRC)/util/metrics.h
$(WRK)/distr/native.o: $(SRC)/util/module.h
$(WRK)/distr/native.o: $(SRC)/util/mpi.h
$(WRK)/distr/native.o: $(SRC)/util/suspender.h
$(WRK)/distr/native.o: $(SRC)/util/sysinfo.h
$(WRK)/distr/native.o: $(SRC)/util/timer.h
$(WRK)/distr/report.o: $(SRC)/distr/report.h
$(WRK)/distr/report.o: $(SRC)/util/format.h
$(WRK)/dump/dump.o: $(SRC)/distr/reduce.h
$(WRK)/dump/dumper.o: $(SRC)/dump/dumper.h
$(WRK)/dump/dumper.o: $(SRC)/parse/vars.h
$(WRK)/dump/dump.o: $(SRC)/geom/blockface.h
$(WRK)/dump/dump.o: $(SRC)/geom/block.h
$(WRK)/dump/dump.o: $(SRC)/geom/dir.h
$(WRK)/dump/dump.o: $(SRC)/geom/field.h
$(WRK)/dump/dump.o: $(SRC)/geom/idx.h
$(WRK)/dump/dump.o: $(SRC)/geom/loop.h
$(WRK)/dump/dump.o: $(SRC)/geom/map.h
$(WRK)/dump/dump.o: $(SRC)/geom/mesh.h
$(WRK)/dump/dump.o: $(SRC)/geom/notation.h
$(WRK)/dump/dump.o: $(SRC)/geom/range.h
$(WRK)/dump/dump.o: $(SRC)/geom/rangein.h
$(WRK)/dump/dump.o: $(SRC)/geom/rangemulti.h
$(WRK)/dump/dump.o: $(SRC)/geom/transform.h
$(WRK)/dump/dump.o: $(SRC)/geom/vect.h
$(WRK)/dump/dump.o: $(SRC)/util/logger.h
$(WRK)/dump/dump.o: $(SRC)/util/macros.h
$(WRK)/dump/dump.o: $(SRC)/util/mpi.h
$(WRK)/dump/dump.o: $(SRC)/util/suspender.h
$(WRK)/dump/hdf.o: $(SRC)/distr/reduce.h
$(WRK)/dump/hdf.o: $(SRC)/dump/hdf.h
$(WRK)/dump/hdf.o: $(SRC)/dump/hdf.ipp
$(WRK)/dump/hdf.o: $(SRC)/dump/hdf_nompi.ipp
$(WRK)/dump/hdf.o: $(SRC)/geom/blockface.h
$(WRK)/dump/hdf.o: $(SRC)/geom/block.h
$(WRK)/dump/hdf.o: $(SRC)/geom/dir.h
$(WRK)/dump/hdf.o: $(SRC)/geom/field.h
$(WRK)/dump/hdf.o: $(SRC)/geom/idx.h
$(WRK)/dump/hdf.o: $(SRC)/geom/loop.h
$(WRK)/dump/hdf.o: $(SRC)/geom/map.h
$(WRK)/dump/hdf.o: $(SRC)/geom/mesh.h
$(WRK)/dump/hdf.o: $(SRC)/geom/notation.h
$(WRK)/dump/hdf.o: $(SRC)/geom/range.h
$(WRK)/dump/hdf.o: $(SRC)/geom/rangein.h
$(WRK)/dump/hdf.o: $(SRC)/geom/rangemulti.h
$(WRK)/dump/hdf.o: $(SRC)/geom/transform.h
$(WRK)/dump/hdf.o: $(SRC)/geom/vect.h
$(WRK)/dump/hdf.o: $(SRC)/util/logger.h
$(WRK)/dump/hdf.o: $(SRC)/util/macros.h
$(WRK)/dump/hdf.o: $(SRC)/util/mpi.h
$(WRK)/dump/hdf.o: $(SRC)/util/suspender.h
$(WRK)/dump/raw.o: $(SRC)/distr/reduce.h
$(WRK)/dump/raw.o: $(SRC)/dump/raw.h
$(WRK)/dump/raw.o: $(SRC)/dump/raw.ipp
$(WRK)/dump/raw.o: $(SRC)/dump/xmf.h
$(WRK)/dump/raw.o: $(SRC)/geom/blockface.h
$(WRK)/dump/raw.o: $(SRC)/geom/block.h
$(WRK)/dump/raw.o: $(SRC)/geom/dir.h
$(WRK)/dump/raw.o: $(SRC)/geom/field.h
$(WRK)/dump/raw.o: $(SRC)/geom/idx.h
$(WRK)/dump/raw.o: $(SRC)/geom/loop.h
$(WRK)/dump/raw.o: $(SRC)/geom/map.h
$(WRK)/dump/raw.o: $(SRC)/geom/mesh.h
$(WRK)/dump/raw.o: $(SRC)/geom/notation.h
$(WRK)/dump/raw.o: $(SRC)/geom/range.h
$(WRK)/dump/raw.o: $(SRC)/geom/rangein.h
$(WRK)/dump/raw.o: $(SRC)/geom/rangemulti.h
$(WRK)/dump/raw.o: $(SRC)/geom/transform.h
$(WRK)/dump/raw.o: $(SRC)/geom/vect.h
$(WRK)/dump/raw.o: $(SRC)/util/distr.h
$(WRK)/dump/raw.o: $(SRC)/util/format.h
$(WRK)/dump/raw.o: $(SRC)/util/logger.h
$(WRK)/dump/raw.o: $(SRC)/util/macros.h
$(WRK)/dump/raw.o: $(SRC)/util/mpi.h
$(WRK)/dump/raw.o: $(SRC)/util/suspender.h
$(WRK)/dump/xmf.o: $(SRC)/distr/reduce.h
$(WRK)/dump/xmf.o: $(SRC)/dump/xmf.h
$(WRK)/dump/xmf.o: $(SRC)/dump/xmf.ipp
$(WRK)/dump/xmf.o: $(SRC)/geom/blockface.h
$(WRK)/dump/xmf.o: $(SRC)/geom/block.h
$(WRK)/dump/xmf.o: $(SRC)/geom/dir.h
$(WRK)/dump/xmf.o: $(SRC)/geom/field.h
$(WRK)/dump/xmf.o: $(SRC)/geom/idx.h
$(WRK)/dump/xmf.o: $(SRC)/geom/loop.h
$(WRK)/dump/xmf.o: $(SRC)/geom/map.h
$(WRK)/dump/xmf.o: $(SRC)/geom/mesh.h
$(WRK)/dump/xmf.o: $(SRC)/geom/notation.h
$(WRK)/dump/xmf.o: $(SRC)/geom/range.h
$(WRK)/dump/xmf.o: $(SRC)/geom/rangein.h
$(WRK)/dump/xmf.o: $(SRC)/geom/rangemulti.h
$(WRK)/dump/xmf.o: $(SRC)/geom/transform.h
$(WRK)/dump/xmf.o: $(SRC)/geom/vect.h
$(WRK)/dump/xmf.o: $(SRC)/parse/template.h
$(WRK)/dump/xmf.o: $(SRC)/util/logger.h
$(WRK)/dump/xmf.o: $(SRC)/util/macros.h
$(WRK)/dump/xmf.o: $(SRC)/util/mpi.h
$(WRK)/dump/xmf.o: $(SRC)/util/suspender.h
$(WRK)/func/init_contang.o: $(SRC)/distr/reduce.h
$(WRK)/func/init_contang.o: $(SRC)/func/init_contang.h
$(WRK)/func/init_contang.o: $(SRC)/geom/blockface.h
$(WRK)/func/init_contang.o: $(SRC)/geom/block.h
$(WRK)/func/init_contang.o: $(SRC)/geom/dir.h
$(WRK)/func/init_contang.o: $(SRC)/geom/field.h
$(WRK)/func/init_contang.o: $(SRC)/geom/idx.h
$(WRK)/func/init_contang.o: $(SRC)/geom/loop.h
$(WRK)/func/init_contang.o: $(SRC)/geom/map.h
$(WRK)/func/init_contang.o: $(SRC)/geom/mesh.h
$(WRK)/func/init_contang.o: $(SRC)/geom/notation.h
$(WRK)/func/init_contang.o: $(SRC)/geom/range.h
$(WRK)/func/init_contang.o: $(SRC)/geom/rangein.h
$(WRK)/func/init_contang.o: $(SRC)/geom/rangemulti.h
$(WRK)/func/init_contang.o: $(SRC)/geom/transform.h
$(WRK)/func/init_contang.o: $(SRC)/geom/vect.h
$(WRK)/func/init_contang.o: $(SRC)/parse/config.h
$(WRK)/func/init_contang.o: $(SRC)/parse/vars.h
$(WRK)/func/init_contang.o: $(SRC)/util/logger.h
$(WRK)/func/init_contang.o: $(SRC)/util/macros.h
$(WRK)/func/init_contang.o: $(SRC)/util/module.h
$(WRK)/func/init_contang.o: $(SRC)/util/mpi.h
$(WRK)/func/init_contang.o: $(SRC)/util/suspender.h
$(WRK)/func/init.o: $(SRC)/debug/isnan.h
$(WRK)/func/init.o: $(SRC)/distr/reduce.h
$(WRK)/func/init.o: $(SRC)/dump/hdf.h
$(WRK)/func/init.o: $(SRC)/func/init_cl.h
$(WRK)/func/init.o: $(SRC)/func/init.h
$(WRK)/func/init.o: $(SRC)/func/init_sig.h
$(WRK)/func/init.o: $(SRC)/func/init_u.h
$(WRK)/func/init.o: $(SRC)/func/primlist.h
$(WRK)/func/init.o: $(SRC)/geom/blockface.h
$(WRK)/func/init.o: $(SRC)/geom/block.h
$(WRK)/func/init.o: $(SRC)/geom/dir.h
$(WRK)/func/init.o: $(SRC)/geom/field.h
$(WRK)/func/init.o: $(SRC)/geom/filter.h
$(WRK)/func/init.o: $(SRC)/geom/idx.h
$(WRK)/func/init.o: $(SRC)/geom/loop.h
$(WRK)/func/init.o: $(SRC)/geom/map.h
$(WRK)/func/init.o: $(SRC)/geom/mesh.h
$(WRK)/func/init.o: $(SRC)/geom/notation.h
$(WRK)/func/init.o: $(SRC)/geom/range.h
$(WRK)/func/init.o: $(SRC)/geom/rangein.h
$(WRK)/func/init.o: $(SRC)/geom/rangemulti.h
$(WRK)/func/init.o: $(SRC)/geom/transform.h
$(WRK)/func/init.o: $(SRC)/geom/vect.h
$(WRK)/func/init.o: $(SRC)/overlap/overlap.h
$(WRK)/func/init.o: $(SRC)/parse/vars.h
$(WRK)/func/init.o: $(SRC)/solver/embed.h
$(WRK)/func/init.o: $(SRC)/solver/reconst.h
$(WRK)/func/init.o: $(SRC)/util/format.h
$(WRK)/func/init.o: $(SRC)/util/logger.h
$(WRK)/func/init.o: $(SRC)/util/macros.h
$(WRK)/func/init.o: $(SRC)/util/mpi.h
$(WRK)/func/init.o: $(SRC)/util/suspender.h
$(WRK)/func/init_vel.o: $(SRC)/distr/reduce.h
$(WRK)/func/init_vel.o: $(SRC)/func/init_vel.h
$(WRK)/func/init_vel.o: $(SRC)/geom/blockface.h
$(WRK)/func/init_vel.o: $(SRC)/geom/block.h
$(WRK)/func/init_vel.o: $(SRC)/geom/dir.h
$(WRK)/func/init_vel.o: $(SRC)/geom/field.h
$(WRK)/func/init_vel.o: $(SRC)/geom/idx.h
$(WRK)/func/init_vel.o: $(SRC)/geom/loop.h
$(WRK)/func/init_vel.o: $(SRC)/geom/map.h
$(WRK)/func/init_vel.o: $(SRC)/geom/mesh.h
$(WRK)/func/init_vel.o: $(SRC)/geom/notation.h
$(WRK)/func/init_vel.o: $(SRC)/geom/range.h
$(WRK)/func/init_vel.o: $(SRC)/geom/rangein.h
$(WRK)/func/init_vel.o: $(SRC)/geom/rangemulti.h
$(WRK)/func/init_vel.o: $(SRC)/geom/transform.h
$(WRK)/func/init_vel.o: $(SRC)/geom/vect.h
$(WRK)/func/init_vel.o: $(SRC)/parse/vars.h
$(WRK)/func/init_vel.o: $(SRC)/util/logger.h
$(WRK)/func/init_vel.o: $(SRC)/util/macros.h
$(WRK)/func/init_vel.o: $(SRC)/util/module.h
$(WRK)/func/init_vel.o: $(SRC)/util/mpi.h
$(WRK)/func/init_vel.o: $(SRC)/util/suspender.h
$(WRK)/func/primlist.o: $(SRC)/func/primlist.h
$(WRK)/func/primlist.o: $(SRC)/func/primlist.ipp
$(WRK)/func/primlist.o: $(SRC)/geom/vect.h
$(WRK)/func/primlist.o: $(SRC)/util/format.h
$(WRK)/func/primlist.o: $(SRC)/util/logger.h
$(WRK)/func/primlist.o: $(SRC)/util/macros.h
$(WRK)/geom/mesh.o: $(SRC)/distr/reduce.h
$(WRK)/geom/mesh.o: $(SRC)/geom/blockface.h
$(WRK)/geom/mesh.o: $(SRC)/geom/block.h
$(WRK)/geom/mesh.o: $(SRC)/geom/dir.h
$(WRK)/geom/mesh.o: $(SRC)/geom/field.h
$(WRK)/geom/mesh.o: $(SRC)/geom/idx.h
$(WRK)/geom/mesh.o: $(SRC)/geom/loop.h
$(WRK)/geom/mesh.o: $(SRC)/geom/map.h
$(WRK)/geom/mesh.o: $(SRC)/geom/mesh.h
$(WRK)/geom/mesh.o: $(SRC)/geom/mesh.ipp
$(WRK)/geom/mesh.o: $(SRC)/geom/notation.h
$(WRK)/geom/mesh.o: $(SRC)/geom/range.h
$(WRK)/geom/mesh.o: $(SRC)/geom/rangein.h
$(WRK)/geom/mesh.o: $(SRC)/geom/rangemulti.h
$(WRK)/geom/mesh.o: $(SRC)/geom/transform.h
$(WRK)/geom/mesh.o: $(SRC)/geom/vect.h
$(WRK)/geom/mesh.o: $(SRC)/util/logger.h
$(WRK)/geom/mesh.o: $(SRC)/util/macros.h
$(WRK)/geom/mesh.o: $(SRC)/util/mpi.h
$(WRK)/geom/mesh.o: $(SRC)/util/suspender.h
$(WRK)/inside/bbox.o: $(SRC)/inside/bbox.h
$(WRK)/inside/bbox.o: $(SRC)/inside/err.h
$(WRK)/inside/bbox.o: $(SRC)/inside/memory.h
$(WRK)/inside/err.o: $(SRC)/inside/err.h
$(WRK)/inside/main.o: $(SRC)/inside/bbox.h
$(WRK)/inside/main.o: $(SRC)/inside/err.h
$(WRK)/inside/main.o: $(SRC)/inside/inside.h
$(WRK)/inside/main.o: $(SRC)/inside/memory.h
$(WRK)/inside/main.o: $(SRC)/inside/predicate.h
$(WRK)/inside/memory.o: $(SRC)/inside/memory.h
$(WRK)/inside/off.o: $(SRC)/inside/err.h
$(WRK)/inside/off.o: $(SRC)/inside/memory.h
$(WRK)/inside/ply.o: $(SRC)/inside/err.h
$(WRK)/inside/ply.o: $(SRC)/inside/memory.h
$(WRK)/inside/predicate.o: $(SRC)/inside/err.h
$(WRK)/inside/predicate.o: $(SRC)/inside/predicate.h
$(WRK)/inside/predicate.o: $(SRC)/inside/predicate.inc
$(WRK)/inside/stl.o: $(SRC)/inside/err.h
$(WRK)/inside/stl.o: $(SRC)/inside/memory.h
$(WRK)/kernel/hydro.o: $(SRC)/debug/isnan.h
$(WRK)/kernel/hydro.o: $(SRC)/debug/linear.h
$(WRK)/kernel/hydro.o: $(SRC)/distr/reduce.h
$(WRK)/kernel/hydro.o: $(SRC)/dump/dumper.h
$(WRK)/kernel/hydro.o: $(SRC)/dump/hdf.h
$(WRK)/kernel/hydro.o: $(SRC)/func/init_contang.h
$(WRK)/kernel/hydro.o: $(SRC)/func/init.h
$(WRK)/kernel/hydro.o: $(SRC)/geom/blockface.h
$(WRK)/kernel/hydro.o: $(SRC)/geom/block.h
$(WRK)/kernel/hydro.o: $(SRC)/geom/dir.h
$(WRK)/kernel/hydro.o: $(SRC)/geom/field.h
$(WRK)/kernel/hydro.o: $(SRC)/geom/filter.h
$(WRK)/kernel/hydro.o: $(SRC)/geom/idx.h
$(WRK)/kernel/hydro.o: $(SRC)/geom/loop.h
$(WRK)/kernel/hydro.o: $(SRC)/geom/map.h
$(WRK)/kernel/hydro.o: $(SRC)/geom/mesh.h
$(WRK)/kernel/hydro.o: $(SRC)/geom/notation.h
$(WRK)/kernel/hydro.o: $(SRC)/geom/range.h
$(WRK)/kernel/hydro.o: $(SRC)/geom/rangein.h
$(WRK)/kernel/hydro.o: $(SRC)/geom/rangemulti.h
$(WRK)/kernel/hydro.o: $(SRC)/geom/transform.h
$(WRK)/kernel/hydro.o: $(SRC)/geom/vect.h
$(WRK)/kernel/hydro.o: $(SRC)/hydro.h
$(WRK)/kernel/hydro.o: $(SRC)/kernel/hydro.ipp
$(WRK)/kernel/hydro.o: $(SRC)/kernel/kernelmesh.h
$(WRK)/kernel/hydro.o: $(SRC)/kernel/kernelmeshpar.h
$(WRK)/kernel/hydro.o: $(SRC)/linear/linear.h
$(WRK)/kernel/hydro.o: $(SRC)/parse/curv.h
$(WRK)/kernel/hydro.o: $(SRC)/parse/parser.h
$(WRK)/kernel/hydro.o: $(SRC)/parse/proj.h
$(WRK)/kernel/hydro.o: $(SRC)/parse/simple.h
$(WRK)/kernel/hydro.o: $(SRC)/parse/solver.h
$(WRK)/kernel/hydro.o: $(SRC)/parse/util.h
$(WRK)/kernel/hydro.o: $(SRC)/parse/vars.h
$(WRK)/kernel/hydro.o: $(SRC)/parse/vof.h
$(WRK)/kernel/hydro.o: $(SRC)/solver/advection.h
$(WRK)/kernel/hydro.o: $(SRC)/solver/approx2.h
$(WRK)/kernel/hydro.o: $(SRC)/solver/approx_eb.h
$(WRK)/kernel/hydro.o: $(SRC)/solver/approx.h
$(WRK)/kernel/hydro.o: $(SRC)/solver/cond.h
$(WRK)/kernel/hydro.o: $(SRC)/solver/convdiff.h
$(WRK)/kernel/hydro.o: $(SRC)/solver/convdiffvg.h
$(WRK)/kernel/hydro.o: $(SRC)/solver/convdiffv.h
$(WRK)/kernel/hydro.o: $(SRC)/solver/curv.h
$(WRK)/kernel/hydro.o: $(SRC)/solver/electro.h
$(WRK)/kernel/hydro.o: $(SRC)/solver/embed.h
$(WRK)/kernel/hydro.o: $(SRC)/solver/fluid_dummy.h
$(WRK)/kernel/hydro.o: $(SRC)/solver/fluid.h
$(WRK)/kernel/hydro.o: $(SRC)/solver/multi.h
$(WRK)/kernel/hydro.o: $(SRC)/solver/normal.h
$(WRK)/kernel/hydro.o: $(SRC)/solver/particles.h
$(WRK)/kernel/hydro.o: $(SRC)/solver/partstr.h
$(WRK)/kernel/hydro.o: $(SRC)/solver/partstrmeshm.h
$(WRK)/kernel/hydro.o: $(SRC)/solver/proj.h
$(WRK)/kernel/hydro.o: $(SRC)/solver/reconst.h
$(WRK)/kernel/hydro.o: $(SRC)/solver/simple.h
$(WRK)/kernel/hydro.o: $(SRC)/solver/solver.h
$(WRK)/kernel/hydro.o: $(SRC)/solver/tracer.h
$(WRK)/kernel/hydro.o: $(SRC)/solver/vof.h
$(WRK)/kernel/hydro.o: $(SRC)/solver/vofm.h
$(WRK)/kernel/hydro.o: $(SRC)/util/convdiff.h
$(WRK)/kernel/hydro.o: $(SRC)/util/events.h
$(WRK)/kernel/hydro.o: $(SRC)/util/filesystem.h
$(WRK)/kernel/hydro.o: $(SRC)/util/format.h
$(WRK)/kernel/hydro.o: $(SRC)/util/hydro.h
$(WRK)/kernel/hydro.o: $(SRC)/util/linear.h
$(WRK)/kernel/hydro.o: $(SRC)/util/logger.h
$(WRK)/kernel/hydro.o: $(SRC)/util/macros.h
$(WRK)/kernel/hydro.o: $(SRC)/util/metrics.h
$(WRK)/kernel/hydro.o: $(SRC)/util/module.h
$(WRK)/kernel/hydro.o: $(SRC)/util/mpi.h
$(WRK)/kernel/hydro.o: $(SRC)/util/posthook.h
$(WRK)/kernel/hydro.o: $(SRC)/util/stat.h
$(WRK)/kernel/hydro.o: $(SRC)/util/suspender.h
$(WRK)/kernel/hydro.o: $(SRC)/util/sysinfo.h
$(WRK)/kernel/hydro.o: $(SRC)/util/timer.h
$(WRK)/linear/hypre.o: $(SRC)/linear/hypre.h
$(WRK)/linear/hypresub.o: $(SRC)/linear/hypre.h
$(WRK)/linear/hypresub.o: $(SRC)/linear/hypresub.h
$(WRK)/linear/hypresub.o: $(SRC)/util/histogram.h
$(WRK)/linear/hypresub.o: $(SRC)/util/logger.h
$(WRK)/linear/hypresub.o: $(SRC)/util/macros.h
$(WRK)/linear/hypresub.o: $(SRC)/util/mpi.h
$(WRK)/linear/hypresub.o: $(SRC)/util/subcomm.h
$(WRK)/linear/hypresub.o: $(SRC)/util/timer.h
$(WRK)/linear/hypre.o: $(SRC)/util/logger.h
$(WRK)/linear/hypre.o: $(SRC)/util/macros.h
$(WRK)/linear/linear_amgx.o: $(SRC)/debug/linear.h
$(WRK)/linear/linear_amgx.o: $(SRC)/distr/commmap.h
$(WRK)/linear/linear_amgx.o: $(SRC)/distr/distr.h
$(WRK)/linear/linear_amgx.o: $(SRC)/distr/distrsolver.h
$(WRK)/linear/linear_amgx.o: $(SRC)/distr/reduce.h
$(WRK)/linear/linear_amgx.o: $(SRC)/dump/dumper.h
$(WRK)/linear/linear_amgx.o: $(SRC)/dump/dump.h
$(WRK)/linear/linear_amgx.o: $(SRC)/geom/blockface.h
$(WRK)/linear/linear_amgx.o: $(SRC)/geom/block.h
$(WRK)/linear/linear_amgx.o: $(SRC)/geom/dir.h
$(WRK)/linear/linear_amgx.o: $(SRC)/geom/field.h
$(WRK)/linear/linear_amgx.o: $(SRC)/geom/idx.h
$(WRK)/linear/linear_amgx.o: $(SRC)/geom/loop.h
$(WRK)/linear/linear_amgx.o: $(SRC)/geom/map.h
$(WRK)/linear/linear_amgx.o: $(SRC)/geom/mesh.h
$(WRK)/linear/linear_amgx.o: $(SRC)/geom/notation.h
$(WRK)/linear/linear_amgx.o: $(SRC)/geom/range.h
$(WRK)/linear/linear_amgx.o: $(SRC)/geom/rangein.h
$(WRK)/linear/linear_amgx.o: $(SRC)/geom/rangemulti.h
$(WRK)/linear/linear_amgx.o: $(SRC)/geom/transform.h
$(WRK)/linear/linear_amgx.o: $(SRC)/geom/vect.h
$(WRK)/linear/linear_amgx.o: $(SRC)/kernel/kernelmesh.h
$(WRK)/linear/linear_amgx.o: $(SRC)/kernel/kernelmeshpar.h
$(WRK)/linear/linear_amgx.o: $(SRC)/linear/amgx.h
$(WRK)/linear/linear_amgx.o: $(SRC)/linear/linear_amgx.h
$(WRK)/linear/linear_amgx.o: $(SRC)/linear/linear.h
$(WRK)/linear/linear_amgx.o: $(SRC)/parse/parser.h
$(WRK)/linear/linear_amgx.o: $(SRC)/parse/vars.h
$(WRK)/linear/linear_amgx.o: $(SRC)/util/distr.h
$(WRK)/linear/linear_amgx.o: $(SRC)/util/format.h
$(WRK)/linear/linear_amgx.o: $(SRC)/util/logger.h
$(WRK)/linear/linear_amgx.o: $(SRC)/util/macros.h
$(WRK)/linear/linear_amgx.o: $(SRC)/util/metrics.h
$(WRK)/linear/linear_amgx.o: $(SRC)/util/module.h
$(WRK)/linear/linear_amgx.o: $(SRC)/util/mpi.h
$(WRK)/linear/linear_amgx.o: $(SRC)/util/suspender.h
$(WRK)/linear/linear_amgx.o: $(SRC)/util/sysinfo.h
$(WRK)/linear/linear_amgx.o: $(SRC)/util/timer.h
$(WRK)/linear/linear.o: $(SRC)/debug/linear.h
$(WRK)/linear/linear.o: $(SRC)/distr/reduce.h
$(WRK)/linear/linear.o: $(SRC)/geom/blockface.h
$(WRK)/linear/linear.o: $(SRC)/geom/block.h
$(WRK)/linear/linear.o: $(SRC)/geom/dir.h
$(WRK)/linear/linear.o: $(SRC)/geom/field.h
$(WRK)/linear/linear.o: $(SRC)/geom/idx.h
$(WRK)/linear/linear.o: $(SRC)/geom/loop.h
$(WRK)/linear/linear.o: $(SRC)/geom/map.h
$(WRK)/linear/linear.o: $(SRC)/geom/mesh.h
$(WRK)/linear/linear.o: $(SRC)/geom/notation.h
$(WRK)/linear/linear.o: $(SRC)/geom/range.h
$(WRK)/linear/linear.o: $(SRC)/geom/rangein.h
$(WRK)/linear/linear.o: $(SRC)/geom/rangemulti.h
$(WRK)/linear/linear.o: $(SRC)/geom/transform.h
$(WRK)/linear/linear.o: $(SRC)/geom/vect.h
$(WRK)/linear/linear_hypre.o: $(SRC)/debug/linear.h
$(WRK)/linear/linear_hypre.o: $(SRC)/distr/reduce.h
$(WRK)/linear/linear_hypre.o: $(SRC)/geom/blockface.h
$(WRK)/linear/linear_hypre.o: $(SRC)/geom/block.h
$(WRK)/linear/linear_hypre.o: $(SRC)/geom/dir.h
$(WRK)/linear/linear_hypre.o: $(SRC)/geom/field.h
$(WRK)/linear/linear_hypre.o: $(SRC)/geom/idx.h
$(WRK)/linear/linear_hypre.o: $(SRC)/geom/loop.h
$(WRK)/linear/linear_hypre.o: $(SRC)/geom/map.h
$(WRK)/linear/linear_hypre.o: $(SRC)/geom/mesh.h
$(WRK)/linear/linear_hypre.o: $(SRC)/geom/notation.h
$(WRK)/linear/linear_hypre.o: $(SRC)/geom/range.h
$(WRK)/linear/linear_hypre.o: $(SRC)/geom/rangein.h
$(WRK)/linear/linear_hypre.o: $(SRC)/geom/rangemulti.h
$(WRK)/linear/linear_hypre.o: $(SRC)/geom/transform.h
$(WRK)/linear/linear_hypre.o: $(SRC)/geom/vect.h
$(WRK)/linear/linear_hypre.o: $(SRC)/linear/hypre.h
$(WRK)/linear/linear_hypre.o: $(SRC)/linear/linear.h
$(WRK)/linear/linear_hypre.o: $(SRC)/linear/linear_hypre.h
$(WRK)/linear/linear_hypre.o: $(SRC)/parse/vars.h
$(WRK)/linear/linear_hypre.o: $(SRC)/util/logger.h
$(WRK)/linear/linear_hypre.o: $(SRC)/util/macros.h
$(WRK)/linear/linear_hypre.o: $(SRC)/util/module.h
$(WRK)/linear/linear_hypre.o: $(SRC)/util/mpi.h
$(WRK)/linear/linear_hypre.o: $(SRC)/util/suspender.h
$(WRK)/linear/linear.o: $(SRC)/linear/linear.h
$(WRK)/linear/linear.o: $(SRC)/linear/linear.ipp
$(WRK)/linear/linear.o: $(SRC)/parse/vars.h
$(WRK)/linear/linear.o: $(SRC)/util/logger.h
$(WRK)/linear/linear.o: $(SRC)/util/macros.h
$(WRK)/linear/linear.o: $(SRC)/util/module.h
$(WRK)/linear/linear.o: $(SRC)/util/mpi.h
$(WRK)/linear/linear.o: $(SRC)/util/suspender.h
$(WRK)/main.o: $(SRC)/aphros_c.h
$(WRK)/march/main.o: $(SRC)/march/march.h
$(WRK)/march/main.o: $(SRC)/march/table.h
$(WRK)/overlap/overlap.o: $(SRC)/geom/vect.h
$(WRK)/overlap/overlap.o: $(SRC)/overlap/overlap.h
$(WRK)/overlap/overlap.o: $(SRC)/overlap/overlap.hpp
$(WRK)/parse/argparse.o: $(SRC)/parse/argparse.h
$(WRK)/parse/argparse.o: $(SRC)/parse/vars.h
$(WRK)/parse/argparse.o: $(SRC)/util/format.h
$(WRK)/parse/argparse.o: $(SRC)/util/logger.h
$(WRK)/parse/argparse.o: $(SRC)/util/macros.h
$(WRK)/parse/codeblocks.o: $(SRC)/util/logger.h
$(WRK)/parse/codeblocks.o: $(SRC)/util/macros.h
$(WRK)/parse/conf2py.o: $(SRC)/parse/argparse.h
$(WRK)/parse/conf2py.o: $(SRC)/parse/parser.h
$(WRK)/parse/conf2py.o: $(SRC)/parse/vars.h
$(WRK)/parse/conf2py.o: $(SRC)/util/format.h
$(WRK)/parse/conf2py.o: $(SRC)/util/logger.h
$(WRK)/parse/conf2py.o: $(SRC)/util/macros.h
$(WRK)/parse/parser.o: $(SRC)/parse/parser.h
$(WRK)/parse/parser.o: $(SRC)/parse/vars.h
$(WRK)/parse/parser.o: $(SRC)/util/filesystem.h
$(WRK)/parse/parser.o: $(SRC)/util/format.h
$(WRK)/parse/parser.o: $(SRC)/util/logger.h
$(WRK)/parse/parser.o: $(SRC)/util/macros.h
$(WRK)/parse/template.o: $(SRC)/parse/template.h
$(WRK)/parse/template.o: $(SRC)/util/logger.h
$(WRK)/parse/template.o: $(SRC)/util/macros.h
$(WRK)/parse/vars.o: $(SRC)/parse/vars.h
$(WRK)/parse/vars.o: $(SRC)/util/logger.h
$(WRK)/parse/vars.o: $(SRC)/util/macros.h
$(WRK)/solver/approx.o: $(SRC)/debug/linear.h
$(WRK)/solver/approx.o: $(SRC)/distr/reduce.h
$(WRK)/solver/approx_eb.o: $(SRC)/debug/linear.h
$(WRK)/solver/approx_eb.o: $(SRC)/distr/reduce.h
$(WRK)/solver/approx_eb.o: $(SRC)/func/primlist.h
$(WRK)/solver/approx_eb.o: $(SRC)/geom/blockface.h
$(WRK)/solver/approx_eb.o: $(SRC)/geom/block.h
$(WRK)/solver/approx_eb.o: $(SRC)/geom/dir.h
$(WRK)/solver/approx_eb.o: $(SRC)/geom/field.h
$(WRK)/solver/approx_eb.o: $(SRC)/geom/filter.h
$(WRK)/solver/approx_eb.o: $(SRC)/geom/idx.h
$(WRK)/solver/approx_eb.o: $(SRC)/geom/loop.h
$(WRK)/solver/approx_eb.o: $(SRC)/geom/map.h
$(WRK)/solver/approx_eb.o: $(SRC)/geom/mesh.h
$(WRK)/solver/approx_eb.o: $(SRC)/geom/notation.h
$(WRK)/solver/approx_eb.o: $(SRC)/geom/range.h
$(WRK)/solver/approx_eb.o: $(SRC)/geom/rangein.h
$(WRK)/solver/approx_eb.o: $(SRC)/geom/rangemulti.h
$(WRK)/solver/approx_eb.o: $(SRC)/geom/transform.h
$(WRK)/solver/approx_eb.o: $(SRC)/geom/vect.h
$(WRK)/solver/approx_eb.o: $(SRC)/inside/inside.h
$(WRK)/solver/approx_eb.o: $(SRC)/linear/linear.h
$(WRK)/solver/approx_eb.o: $(SRC)/parse/vars.h
$(WRK)/solver/approx_eb.o: $(SRC)/solver/approx_eb.h
$(WRK)/solver/approx_eb.o: $(SRC)/solver/approx_eb.ipp
$(WRK)/solver/approx_eb.o: $(SRC)/solver/approx.h
$(WRK)/solver/approx_eb.o: $(SRC)/solver/cond.h
$(WRK)/solver/approx_eb.o: $(SRC)/solver/embed.h
$(WRK)/solver/approx_eb.o: $(SRC)/solver/reconst.h
$(WRK)/solver/approx_eb.o: $(SRC)/solver/solver.h
$(WRK)/solver/approx_eb.o: $(SRC)/util/format.h
$(WRK)/solver/approx_eb.o: $(SRC)/util/logger.h
$(WRK)/solver/approx_eb.o: $(SRC)/util/macros.h
$(WRK)/solver/approx_eb.o: $(SRC)/util/module.h
$(WRK)/solver/approx_eb.o: $(SRC)/util/mpi.h
$(WRK)/solver/approx_eb.o: $(SRC)/util/suspender.h
$(WRK)/solver/approx.o: $(SRC)/geom/blockface.h
$(WRK)/solver/approx.o: $(SRC)/geom/block.h
$(WRK)/solver/approx.o: $(SRC)/geom/dir.h
$(WRK)/solver/approx.o: $(SRC)/geom/field.h
$(WRK)/solver/approx.o: $(SRC)/geom/filter.h
$(WRK)/solver/approx.o: $(SRC)/geom/idx.h
$(WRK)/solver/approx.o: $(SRC)/geom/loop.h
$(WRK)/solver/approx.o: $(SRC)/geom/map.h
$(WRK)/solver/approx.o: $(SRC)/geom/mesh.h
$(WRK)/solver/approx.o: $(SRC)/geom/notation.h
$(WRK)/solver/approx.o: $(SRC)/geom/range.h
$(WRK)/solver/approx.o: $(SRC)/geom/rangein.h
$(WRK)/solver/approx.o: $(SRC)/geom/rangemulti.h
$(WRK)/solver/approx.o: $(SRC)/geom/transform.h
$(WRK)/solver/approx.o: $(SRC)/geom/vect.h
$(WRK)/solver/approx.o: $(SRC)/linear/linear.h
$(WRK)/solver/approx.o: $(SRC)/parse/vars.h
$(WRK)/solver/approx.o: $(SRC)/solver/approx.h
$(WRK)/solver/approx.o: $(SRC)/solver/approx.ipp
$(WRK)/solver/approx.o: $(SRC)/solver/cond.h
$(WRK)/solver/approx.o: $(SRC)/solver/embed.h
$(WRK)/solver/approx.o: $(SRC)/solver/reconst.h
$(WRK)/solver/approx.o: $(SRC)/solver/solver.h
$(WRK)/solver/approx.o: $(SRC)/util/logger.h
$(WRK)/solver/approx.o: $(SRC)/util/macros.h
$(WRK)/solver/approx.o: $(SRC)/util/module.h
$(WRK)/solver/approx.o: $(SRC)/util/mpi.h
$(WRK)/solver/approx.o: $(SRC)/util/suspender.h
$(WRK)/solver/convdiffe.o: $(SRC)/debug/isnan.h
$(WRK)/solver/convdiffe.o: $(SRC)/debug/linear.h
$(WRK)/solver/convdiffe.o: $(SRC)/distr/reduce.h
$(WRK)/solver/convdiffe.o: $(SRC)/geom/blockface.h
$(WRK)/solver/convdiffe.o: $(SRC)/geom/block.h
$(WRK)/solver/convdiffe.o: $(SRC)/geom/dir.h
$(WRK)/solver/convdiffe.o: $(SRC)/geom/field.h
$(WRK)/solver/convdiffe.o: $(SRC)/geom/filter.h
$(WRK)/solver/convdiffe.o: $(SRC)/geom/idx.h
$(WRK)/solver/convdiffe.o: $(SRC)/geom/loop.h
$(WRK)/solver/convdiffe.o: $(SRC)/geom/map.h
$(WRK)/solver/convdiffe.o: $(SRC)/geom/mesh.h
$(WRK)/solver/convdiffe.o: $(SRC)/geom/notation.h
$(WRK)/solver/convdiffe.o: $(SRC)/geom/range.h
$(WRK)/solver/convdiffe.o: $(SRC)/geom/rangein.h
$(WRK)/solver/convdiffe.o: $(SRC)/geom/rangemulti.h
$(WRK)/solver/convdiffe.o: $(SRC)/geom/transform.h
$(WRK)/solver/convdiffe.o: $(SRC)/geom/vect.h
$(WRK)/solver/convdiffe.o: $(SRC)/linear/linear.h
$(WRK)/solver/convdiffe.o: $(SRC)/parse/vars.h
$(WRK)/solver/convdiffe.o: $(SRC)/solver/approx_eb.h
$(WRK)/solver/convdiffe.o: $(SRC)/solver/approx.h
$(WRK)/solver/convdiffe.o: $(SRC)/solver/cond.h
$(WRK)/solver/convdiffe.o: $(SRC)/solver/convdiffe.h
$(WRK)/solver/convdiffe.o: $(SRC)/solver/convdiffe.ipp
$(WRK)/solver/convdiffe.o: $(SRC)/solver/convdiff.h
$(WRK)/solver/convdiffe.o: $(SRC)/solver/embed.h
$(WRK)/solver/convdiffe.o: $(SRC)/solver/reconst.h
$(WRK)/solver/convdiffe.o: $(SRC)/solver/solver.h
$(WRK)/solver/convdiffe.o: $(SRC)/util/format.h
$(WRK)/solver/convdiffe.o: $(SRC)/util/logger.h
$(WRK)/solver/convdiffe.o: $(SRC)/util/macros.h
$(WRK)/solver/convdiffe.o: $(SRC)/util/module.h
$(WRK)/solver/convdiffe.o: $(SRC)/util/mpi.h
$(WRK)/solver/convdiffe.o: $(SRC)/util/suspender.h
$(WRK)/solver/convdiffi.o: $(SRC)/debug/isnan.h
$(WRK)/solver/convdiffi.o: $(SRC)/debug/linear.h
$(WRK)/solver/convdiffi.o: $(SRC)/distr/reduce.h
$(WRK)/solver/convdiffi.o: $(SRC)/geom/blockface.h
$(WRK)/solver/convdiffi.o: $(SRC)/geom/block.h
$(WRK)/solver/convdiffi.o: $(SRC)/geom/dir.h
$(WRK)/solver/convdiffi.o: $(SRC)/geom/field.h
$(WRK)/solver/convdiffi.o: $(SRC)/geom/filter.h
$(WRK)/solver/convdiffi.o: $(SRC)/geom/idx.h
$(WRK)/solver/convdiffi.o: $(SRC)/geom/loop.h
$(WRK)/solver/convdiffi.o: $(SRC)/geom/map.h
$(WRK)/solver/convdiffi.o: $(SRC)/geom/mesh.h
$(WRK)/solver/convdiffi.o: $(SRC)/geom/notation.h
$(WRK)/solver/convdiffi.o: $(SRC)/geom/range.h
$(WRK)/solver/convdiffi.o: $(SRC)/geom/rangein.h
$(WRK)/solver/convdiffi.o: $(SRC)/geom/rangemulti.h
$(WRK)/solver/convdiffi.o: $(SRC)/geom/transform.h
$(WRK)/solver/convdiffi.o: $(SRC)/geom/vect.h
$(WRK)/solver/convdiffi.o: $(SRC)/linear/linear.h
$(WRK)/solver/convdiffi.o: $(SRC)/parse/vars.h
$(WRK)/solver/convdiffi.o: $(SRC)/solver/approx_eb.h
$(WRK)/solver/convdiffi.o: $(SRC)/solver/approx.h
$(WRK)/solver/convdiffi.o: $(SRC)/solver/cond.h
$(WRK)/solver/convdiffi.o: $(SRC)/solver/convdiff.h
$(WRK)/solver/convdiffi.o: $(SRC)/solver/convdiffi.h
$(WRK)/solver/convdiffi.o: $(SRC)/solver/convdiffi.ipp
$(WRK)/solver/convdiffi.o: $(SRC)/solver/convdiffvg.h
$(WRK)/solver/convdiffi.o: $(SRC)/solver/convdiffv.h
$(WRK)/solver/convdiffi.o: $(SRC)/solver/embed.h
$(WRK)/solver/convdiffi.o: $(SRC)/solver/reconst.h
$(WRK)/solver/convdiffi.o: $(SRC)/solver/solver.h
$(WRK)/solver/convdiffi.o: $(SRC)/util/convdiff.h
$(WRK)/solver/convdiffi.o: $(SRC)/util/format.h
$(WRK)/solver/convdiffi.o: $(SRC)/util/logger.h
$(WRK)/solver/convdiffi.o: $(SRC)/util/macros.h
$(WRK)/solver/convdiffi.o: $(SRC)/util/module.h
$(WRK)/solver/convdiffi.o: $(SRC)/util/mpi.h
$(WRK)/solver/convdiffi.o: $(SRC)/util/suspender.h
$(WRK)/solver/convdiffvg.o: $(SRC)/debug/linear.h
$(WRK)/solver/convdiffvg.o: $(SRC)/distr/reduce.h
$(WRK)/solver/convdiffvg.o: $(SRC)/geom/blockface.h
$(WRK)/solver/convdiffvg.o: $(SRC)/geom/block.h
$(WRK)/solver/convdiffvg.o: $(SRC)/geom/dir.h
$(WRK)/solver/convdiffvg.o: $(SRC)/geom/field.h
$(WRK)/solver/convdiffvg.o: $(SRC)/geom/filter.h
$(WRK)/solver/convdiffvg.o: $(SRC)/geom/idx.h
$(WRK)/solver/convdiffvg.o: $(SRC)/geom/loop.h
$(WRK)/solver/convdiffvg.o: $(SRC)/geom/map.h
$(WRK)/solver/convdiffvg.o: $(SRC)/geom/mesh.h
$(WRK)/solver/convdiffvg.o: $(SRC)/geom/notation.h
$(WRK)/solver/convdiffvg.o: $(SRC)/geom/range.h
$(WRK)/solver/convdiffvg.o: $(SRC)/geom/rangein.h
$(WRK)/solver/convdiffvg.o: $(SRC)/geom/rangemulti.h
$(WRK)/solver/convdiffvg.o: $(SRC)/geom/transform.h
$(WRK)/solver/convdiffvg.o: $(SRC)/geom/vect.h
$(WRK)/solver/convdiffvg.o: $(SRC)/linear/linear.h
$(WRK)/solver/convdiffvg.o: $(SRC)/parse/vars.h
$(WRK)/solver/convdiffvg.o: $(SRC)/solver/cond.h
$(WRK)/solver/convdiffvg.o: $(SRC)/solver/convdiffe.h
$(WRK)/solver/convdiffvg.o: $(SRC)/solver/convdiff.h
$(WRK)/solver/convdiffvg.o: $(SRC)/solver/convdiffi.h
$(WRK)/solver/convdiffvg.o: $(SRC)/solver/convdiffvg.h
$(WRK)/solver/convdiffvg.o: $(SRC)/solver/convdiffvg.ipp
$(WRK)/solver/convdiffvg.o: $(SRC)/solver/convdiffv.h
$(WRK)/solver/convdiffvg.o: $(SRC)/solver/embed.h
$(WRK)/solver/convdiffvg.o: $(SRC)/solver/reconst.h
$(WRK)/solver/convdiffvg.o: $(SRC)/solver/solver.h
$(WRK)/solver/convdiffvg.o: $(SRC)/util/convdiff.h
$(WRK)/solver/convdiffvg.o: $(SRC)/util/logger.h
$(WRK)/solver/convdiffvg.o: $(SRC)/util/macros.h
$(WRK)/solver/convdiffvg.o: $(SRC)/util/metrics.h
$(WRK)/solver/convdiffvg.o: $(SRC)/util/module.h
$(WRK)/solver/convdiffvg.o: $(SRC)/util/mpi.h
$(WRK)/solver/convdiffvg.o: $(SRC)/util/suspender.h
$(WRK)/solver/convdiffvg.o: $(SRC)/util/timer.h
$(WRK)/solver/curv.o: $(SRC)/debug/isnan.h
$(WRK)/solver/curv.o: $(SRC)/distr/reduce.h
$(WRK)/solver/curv.o: $(SRC)/dump/dumper.h
$(WRK)/solver/curv.o: $(SRC)/geom/blockface.h
$(WRK)/solver/curv.o: $(SRC)/geom/block.h
$(WRK)/solver/curv.o: $(SRC)/geom/dir.h
$(WRK)/solver/curv.o: $(SRC)/geom/field.h
$(WRK)/solver/curv.o: $(SRC)/geom/filter.h
$(WRK)/solver/curv.o: $(SRC)/geom/idx.h
$(WRK)/solver/curv.o: $(SRC)/geom/loop.h
$(WRK)/solver/curv.o: $(SRC)/geom/map.h
$(WRK)/solver/curv.o: $(SRC)/geom/mesh.h
$(WRK)/solver/curv.o: $(SRC)/geom/notation.h
$(WRK)/solver/curv.o: $(SRC)/geom/range.h
$(WRK)/solver/curv.o: $(SRC)/geom/rangein.h
$(WRK)/solver/curv.o: $(SRC)/geom/rangemulti.h
$(WRK)/solver/curv.o: $(SRC)/geom/transform.h
$(WRK)/solver/curv.o: $(SRC)/geom/vect.h
$(WRK)/solver/curv.o: $(SRC)/parse/vars.h
$(WRK)/solver/curv.o: $(SRC)/solver/advection.h
$(WRK)/solver/curv.o: $(SRC)/solver/approx.h
$(WRK)/solver/curv.o: $(SRC)/solver/cond.h
$(WRK)/solver/curv.o: $(SRC)/solver/curv.h
$(WRK)/solver/curv.o: $(SRC)/solver/curv.ipp
$(WRK)/solver/curv.o: $(SRC)/solver/embed.h
$(WRK)/solver/curv.o: $(SRC)/solver/multi.h
$(WRK)/solver/curv.o: $(SRC)/solver/normal.h
$(WRK)/solver/curv.o: $(SRC)/solver/partstr.h
$(WRK)/solver/curv.o: $(SRC)/solver/partstrmeshm.h
$(WRK)/solver/curv.o: $(SRC)/solver/reconst.h
$(WRK)/solver/curv.o: $(SRC)/solver/solver.h
$(WRK)/solver/curv.o: $(SRC)/solver/trackerm.h
$(WRK)/solver/curv.o: $(SRC)/solver/vof.h
$(WRK)/solver/curv.o: $(SRC)/solver/vofm.h
$(WRK)/solver/curv.o: $(SRC)/util/format.h
$(WRK)/solver/curv.o: $(SRC)/util/logger.h
$(WRK)/solver/curv.o: $(SRC)/util/macros.h
$(WRK)/solver/curv.o: $(SRC)/util/mpi.h
$(WRK)/solver/curv.o: $(SRC)/util/suspender.h
$(WRK)/solver/curv.o: $(SRC)/util/vof.h
$(WRK)/solver/electro.o: $(SRC)/debug/linear.h
$(WRK)/solver/electro.o: $(SRC)/distr/reduce.h
$(WRK)/solver/electro.o: $(SRC)/geom/blockface.h
$(WRK)/solver/electro.o: $(SRC)/geom/block.h
$(WRK)/solver/electro.o: $(SRC)/geom/dir.h
$(WRK)/solver/electro.o: $(SRC)/geom/field.h
$(WRK)/solver/electro.o: $(SRC)/geom/filter.h
$(WRK)/solver/electro.o: $(SRC)/geom/idx.h
$(WRK)/solver/electro.o: $(SRC)/geom/loop.h
$(WRK)/solver/electro.o: $(SRC)/geom/map.h
$(WRK)/solver/electro.o: $(SRC)/geom/mesh.h
$(WRK)/solver/electro.o: $(SRC)/geom/notation.h
$(WRK)/solver/electro.o: $(SRC)/geom/range.h
$(WRK)/solver/electro.o: $(SRC)/geom/rangein.h
$(WRK)/solver/electro.o: $(SRC)/geom/rangemulti.h
$(WRK)/solver/electro.o: $(SRC)/geom/transform.h
$(WRK)/solver/electro.o: $(SRC)/geom/vect.h
$(WRK)/solver/electro.o: $(SRC)/linear/linear.h
$(WRK)/solver/electro.o: $(SRC)/parse/vars.h
$(WRK)/solver/electro.o: $(SRC)/solver/advection.h
$(WRK)/solver/electro.o: $(SRC)/solver/approx_eb.h
$(WRK)/solver/electro.o: $(SRC)/solver/approx.h
$(WRK)/solver/electro.o: $(SRC)/solver/cond.h
$(WRK)/solver/electro.o: $(SRC)/solver/electro.h
$(WRK)/solver/electro.o: $(SRC)/solver/electro.ipp
$(WRK)/solver/electro.o: $(SRC)/solver/embed.h
$(WRK)/solver/electro.o: $(SRC)/solver/multi.h
$(WRK)/solver/electro.o: $(SRC)/solver/pois.h
$(WRK)/solver/electro.o: $(SRC)/solver/reconst.h
$(WRK)/solver/electro.o: $(SRC)/solver/solver.h
$(WRK)/solver/electro.o: $(SRC)/util/logger.h
$(WRK)/solver/electro.o: $(SRC)/util/macros.h
$(WRK)/solver/electro.o: $(SRC)/util/module.h
$(WRK)/solver/electro.o: $(SRC)/util/mpi.h
$(WRK)/solver/electro.o: $(SRC)/util/suspender.h
$(WRK)/solver/electro.o: $(SRC)/util/vof.h
$(WRK)/solver/embed.o: $(SRC)/debug/isnan.h
$(WRK)/solver/embed.o: $(SRC)/distr/reduce.h
$(WRK)/solver/embed.o: $(SRC)/dump/dumper.h
$(WRK)/solver/embed.o: $(SRC)/dump/hdf.h
$(WRK)/solver/embed.o: $(SRC)/dump/vtk.h
$(WRK)/solver/embed.o: $(SRC)/func/init_u.h
$(WRK)/solver/embed.o: $(SRC)/func/primlist.h
$(WRK)/solver/embed.o: $(SRC)/geom/blockface.h
$(WRK)/solver/embed.o: $(SRC)/geom/block.h
$(WRK)/solver/embed.o: $(SRC)/geom/dir.h
$(WRK)/solver/embed.o: $(SRC)/geom/field.h
$(WRK)/solver/embed.o: $(SRC)/geom/filter.h
$(WRK)/solver/embed.o: $(SRC)/geom/idx.h
$(WRK)/solver/embed.o: $(SRC)/geom/loop.h
$(WRK)/solver/embed.o: $(SRC)/geom/map.h
$(WRK)/solver/embed.o: $(SRC)/geom/mesh.h
$(WRK)/solver/embed.o: $(SRC)/geom/notation.h
$(WRK)/solver/embed.o: $(SRC)/geom/range.h
$(WRK)/solver/embed.o: $(SRC)/geom/rangein.h
$(WRK)/solver/embed.o: $(SRC)/geom/rangemulti.h
$(WRK)/solver/embed.o: $(SRC)/geom/transform.h
$(WRK)/solver/embed.o: $(SRC)/geom/vect.h
$(WRK)/solver/embed.o: $(SRC)/parse/vars.h
$(WRK)/solver/embed.o: $(SRC)/solver/embed.h
$(WRK)/solver/embed.o: $(SRC)/solver/embed.ipp
$(WRK)/solver/embed.o: $(SRC)/solver/reconst.h
$(WRK)/solver/embed.o: $(SRC)/util/format.h
$(WRK)/solver/embed.o: $(SRC)/util/logger.h
$(WRK)/solver/embed.o: $(SRC)/util/macros.h
$(WRK)/solver/embed.o: $(SRC)/util/mpi.h
$(WRK)/solver/embed.o: $(SRC)/util/suspender.h
$(WRK)/solver/fluid_dummy.o: $(SRC)/debug/isnan.h
$(WRK)/solver/fluid_dummy.o: $(SRC)/debug/linear.h
$(WRK)/solver/fluid_dummy.o: $(SRC)/distr/reduce.h
$(WRK)/solver/fluid_dummy.o: $(SRC)/geom/blockface.h
$(WRK)/solver/fluid_dummy.o: $(SRC)/geom/block.h
$(WRK)/solver/fluid_dummy.o: $(SRC)/geom/dir.h
$(WRK)/solver/fluid_dummy.o: $(SRC)/geom/field.h
$(WRK)/solver/fluid_dummy.o: $(SRC)/geom/filter.h
$(WRK)/solver/fluid_dummy.o: $(SRC)/geom/idx.h
$(WRK)/solver/fluid_dummy.o: $(SRC)/geom/loop.h
$(WRK)/solver/fluid_dummy.o: $(SRC)/geom/map.h
$(WRK)/solver/fluid_dummy.o: $(SRC)/geom/mesh.h
$(WRK)/solver/fluid_dummy.o: $(SRC)/geom/notation.h
$(WRK)/solver/fluid_dummy.o: $(SRC)/geom/range.h
$(WRK)/solver/fluid_dummy.o: $(SRC)/geom/rangein.h
$(WRK)/solver/fluid_dummy.o: $(SRC)/geom/rangemulti.h
$(WRK)/solver/fluid_dummy.o: $(SRC)/geom/transform.h
$(WRK)/solver/fluid_dummy.o: $(SRC)/geom/vect.h
$(WRK)/solver/fluid_dummy.o: $(SRC)/linear/linear.h
$(WRK)/solver/fluid_dummy.o: $(SRC)/parse/vars.h
$(WRK)/solver/fluid_dummy.o: $(SRC)/solver/approx_eb.h
$(WRK)/solver/fluid_dummy.o: $(SRC)/solver/approx.h
$(WRK)/solver/fluid_dummy.o: $(SRC)/solver/cond.h
$(WRK)/solver/fluid_dummy.o: $(SRC)/solver/embed.h
$(WRK)/solver/fluid_dummy.o: $(SRC)/solver/fluid_dummy.h
$(WRK)/solver/fluid_dummy.o: $(SRC)/solver/fluid_dummy.ipp
$(WRK)/solver/fluid_dummy.o: $(SRC)/solver/fluid.h
$(WRK)/solver/fluid_dummy.o: $(SRC)/solver/reconst.h
$(WRK)/solver/fluid_dummy.o: $(SRC)/solver/solver.h
$(WRK)/solver/fluid_dummy.o: $(SRC)/util/format.h
$(WRK)/solver/fluid_dummy.o: $(SRC)/util/logger.h
$(WRK)/solver/fluid_dummy.o: $(SRC)/util/macros.h
$(WRK)/solver/fluid_dummy.o: $(SRC)/util/module.h
$(WRK)/solver/fluid_dummy.o: $(SRC)/util/mpi.h
$(WRK)/solver/fluid_dummy.o: $(SRC)/util/posthook.h
$(WRK)/solver/fluid_dummy.o: $(SRC)/util/suspender.h
$(WRK)/solver/normal.o: $(SRC)/debug/isnan.h
$(WRK)/solver/normal.o: $(SRC)/distr/reduce.h
$(WRK)/solver/normal.o: $(SRC)/geom/blockface.h
$(WRK)/solver/normal.o: $(SRC)/geom/block.h
$(WRK)/solver/normal.o: $(SRC)/geom/dir.h
$(WRK)/solver/normal.o: $(SRC)/geom/field.h
$(WRK)/solver/normal.o: $(SRC)/geom/filter.h
$(WRK)/solver/normal.o: $(SRC)/geom/idx.h
$(WRK)/solver/normal.o: $(SRC)/geom/loop.h
$(WRK)/solver/normal.o: $(SRC)/geom/map.h
$(WRK)/solver/normal.o: $(SRC)/geom/mesh.h
$(WRK)/solver/normal.o: $(SRC)/geom/notation.h
$(WRK)/solver/normal.o: $(SRC)/geom/range.h
$(WRK)/solver/normal.o: $(SRC)/geom/rangein.h
$(WRK)/solver/normal.o: $(SRC)/geom/rangemulti.h
$(WRK)/solver/normal.o: $(SRC)/geom/transform.h
$(WRK)/solver/normal.o: $(SRC)/geom/vect.h
$(WRK)/solver/normal.o: $(SRC)/parse/vars.h
$(WRK)/solver/normal.o: $(SRC)/solver/approx_eb.h
$(WRK)/solver/normal.o: $(SRC)/solver/approx.h
$(WRK)/solver/normal.o: $(SRC)/solver/cond.h
$(WRK)/solver/normal.o: $(SRC)/solver/embed.h
$(WRK)/solver/normal.o: $(SRC)/solver/normal.h
$(WRK)/solver/normal.o: $(SRC)/solver/normal.ipp
$(WRK)/solver/normal.o: $(SRC)/solver/reconst.h
$(WRK)/solver/normal.o: $(SRC)/solver/solver.h
$(WRK)/solver/normal.o: $(SRC)/util/avx.h
$(WRK)/solver/normal.o: $(SRC)/util/format.h
$(WRK)/solver/normal.o: $(SRC)/util/height.h
$(WRK)/solver/normal.o: $(SRC)/util/logger.h
$(WRK)/solver/normal.o: $(SRC)/util/macros.h
$(WRK)/solver/normal.o: $(SRC)/util/mpi.h
$(WRK)/solver/normal.o: $(SRC)/util/suspender.h
$(WRK)/solver/particles.o: $(SRC)/distr/reduce.h
$(WRK)/solver/particles.o: $(SRC)/geom/blockface.h
$(WRK)/solver/particles.o: $(SRC)/geom/block.h
$(WRK)/solver/particles.o: $(SRC)/geom/dir.h
$(WRK)/solver/particles.o: $(SRC)/geom/field.h
$(WRK)/solver/particles.o: $(SRC)/geom/filter.h
$(WRK)/solver/particles.o: $(SRC)/geom/idx.h
$(WRK)/solver/particles.o: $(SRC)/geom/loop.h
$(WRK)/solver/particles.o: $(SRC)/geom/map.h
$(WRK)/solver/particles.o: $(SRC)/geom/mesh.h
$(WRK)/solver/particles.o: $(SRC)/geom/notation.h
$(WRK)/solver/particles.o: $(SRC)/geom/range.h
$(WRK)/solver/particles.o: $(SRC)/geom/rangein.h
$(WRK)/solver/particles.o: $(SRC)/geom/rangemulti.h
$(WRK)/solver/particles.o: $(SRC)/geom/transform.h
$(WRK)/solver/particles.o: $(SRC)/geom/vect.h
$(WRK)/solver/particles.o: $(SRC)/parse/vars.h
$(WRK)/solver/particles.o: $(SRC)/solver/advection.h
$(WRK)/solver/particles.o: $(SRC)/solver/approx_eb.h
$(WRK)/solver/particles.o: $(SRC)/solver/approx.h
$(WRK)/solver/particles.o: $(SRC)/solver/cond.h
$(WRK)/solver/particles.o: $(SRC)/solver/embed.h
$(WRK)/solver/particles.o: $(SRC)/solver/multi.h
$(WRK)/solver/particles.o: $(SRC)/solver/particles.h
$(WRK)/solver/particles.o: $(SRC)/solver/particles.ipp
$(WRK)/solver/particles.o: $(SRC)/solver/reconst.h
$(WRK)/solver/particles.o: $(SRC)/solver/solver.h
$(WRK)/solver/particles.o: $(SRC)/util/logger.h
$(WRK)/solver/particles.o: $(SRC)/util/macros.h
$(WRK)/solver/particles.o: $(SRC)/util/mpi.h
$(WRK)/solver/particles.o: $(SRC)/util/suspender.h
$(WRK)/solver/particles.o: $(SRC)/util/vof.h
$(WRK)/solver/partstrmeshm.o: $(SRC)/debug/isnan.h
$(WRK)/solver/partstrmeshm.o: $(SRC)/distr/reduce.h
$(WRK)/solver/partstrmeshm.o: $(SRC)/dump/dumper.h
$(WRK)/solver/partstrmeshm.o: $(SRC)/dump/vtk.h
$(WRK)/solver/partstrmeshm.o: $(SRC)/geom/blockface.h
$(WRK)/solver/partstrmeshm.o: $(SRC)/geom/block.h
$(WRK)/solver/partstrmeshm.o: $(SRC)/geom/dir.h
$(WRK)/solver/partstrmeshm.o: $(SRC)/geom/field.h
$(WRK)/solver/partstrmeshm.o: $(SRC)/geom/filter.h
$(WRK)/solver/partstrmeshm.o: $(SRC)/geom/idx.h
$(WRK)/solver/partstrmeshm.o: $(SRC)/geom/loop.h
$(WRK)/solver/partstrmeshm.o: $(SRC)/geom/map.h
$(WRK)/solver/partstrmeshm.o: $(SRC)/geom/mesh.h
$(WRK)/solver/partstrmeshm.o: $(SRC)/geom/notation.h
$(WRK)/solver/partstrmeshm.o: $(SRC)/geom/range.h
$(WRK)/solver/partstrmeshm.o: $(SRC)/geom/rangein.h
$(WRK)/solver/partstrmeshm.o: $(SRC)/geom/rangemulti.h
$(WRK)/solver/partstrmeshm.o: $(SRC)/geom/transform.h
$(WRK)/solver/partstrmeshm.o: $(SRC)/geom/vect.h
$(WRK)/solver/partstrmeshm.o: $(SRC)/parse/vars.h
$(WRK)/solver/partstrmeshm.o: $(SRC)/solver/advection.h
$(WRK)/solver/partstrmeshm.o: $(SRC)/solver/cond.h
$(WRK)/solver/partstrmeshm.o: $(SRC)/solver/embed.h
$(WRK)/solver/partstrmeshm.o: $(SRC)/solver/multi.h
$(WRK)/solver/partstrmeshm.o: $(SRC)/solver/partstr.h
$(WRK)/solver/partstrmeshm.o: $(SRC)/solver/partstrmeshm.h
$(WRK)/solver/partstrmeshm.o: $(SRC)/solver/partstrmeshm.ipp
$(WRK)/solver/partstrmeshm.o: $(SRC)/solver/reconst.h
$(WRK)/solver/partstrmeshm.o: $(SRC)/solver/solver.h
$(WRK)/solver/partstrmeshm.o: $(SRC)/solver/vof.h
$(WRK)/solver/partstrmeshm.o: $(SRC)/util/format.h
$(WRK)/solver/partstrmeshm.o: $(SRC)/util/logger.h
$(WRK)/solver/partstrmeshm.o: $(SRC)/util/macros.h
$(WRK)/solver/partstrmeshm.o: $(SRC)/util/mpi.h
$(WRK)/solver/partstrmeshm.o: $(SRC)/util/suspender.h
$(WRK)/solver/proj.o: $(SRC)/debug/isnan.h
$(WRK)/solver/proj.o: $(SRC)/debug/linear.h
$(WRK)/solver/proj.o: $(SRC)/distr/reduce.h
$(WRK)/solver/proj_eb.o: $(SRC)/debug/isnan.h
$(WRK)/solver/proj_eb.o: $(SRC)/debug/linear.h
$(WRK)/solver/proj_eb.o: $(SRC)/distr/reduce.h
$(WRK)/solver/proj_eb.o: $(SRC)/geom/blockface.h
$(WRK)/solver/proj_eb.o: $(SRC)/geom/block.h
$(WRK)/solver/proj_eb.o: $(SRC)/geom/dir.h
$(WRK)/solver/proj_eb.o: $(SRC)/geom/field.h
$(WRK)/solver/proj_eb.o: $(SRC)/geom/filter.h
$(WRK)/solver/proj_eb.o: $(SRC)/geom/idx.h
$(WRK)/solver/proj_eb.o: $(SRC)/geom/loop.h
$(WRK)/solver/proj_eb.o: $(SRC)/geom/map.h
$(WRK)/solver/proj_eb.o: $(SRC)/geom/mesh.h
$(WRK)/solver/proj_eb.o: $(SRC)/geom/notation.h
$(WRK)/solver/proj_eb.o: $(SRC)/geom/range.h
$(WRK)/solver/proj_eb.o: $(SRC)/geom/rangein.h
$(WRK)/solver/proj_eb.o: $(SRC)/geom/rangemulti.h
$(WRK)/solver/proj_eb.o: $(SRC)/geom/transform.h
$(WRK)/solver/proj_eb.o: $(SRC)/geom/vect.h
$(WRK)/solver/proj_eb.o: $(SRC)/linear/linear.h
$(WRK)/solver/proj_eb.o: $(SRC)/parse/vars.h
$(WRK)/solver/proj_eb.o: $(SRC)/solver/approx_eb.h
$(WRK)/solver/proj_eb.o: $(SRC)/solver/approx.h
$(WRK)/solver/proj_eb.o: $(SRC)/solver/cond.h
$(WRK)/solver/proj_eb.o: $(SRC)/solver/convdiff.h
$(WRK)/solver/proj_eb.o: $(SRC)/solver/convdiffvg.h
$(WRK)/solver/proj_eb.o: $(SRC)/solver/convdiffv.h
$(WRK)/solver/proj_eb.o: $(SRC)/solver/embed.h
$(WRK)/solver/proj_eb.o: $(SRC)/solver/fluid.h
$(WRK)/solver/proj_eb.o: $(SRC)/solver/proj.h
$(WRK)/solver/proj_eb.o: $(SRC)/solver/proj.ipp
$(WRK)/solver/proj_eb.o: $(SRC)/solver/reconst.h
$(WRK)/solver/proj_eb.o: $(SRC)/solver/solver.h
$(WRK)/solver/proj_eb.o: $(SRC)/util/convdiff.h
$(WRK)/solver/proj_eb.o: $(SRC)/util/fluid.h
$(WRK)/solver/proj_eb.o: $(SRC)/util/format.h
$(WRK)/solver/proj_eb.o: $(SRC)/util/logger.h
$(WRK)/solver/proj_eb.o: $(SRC)/util/macros.h
$(WRK)/solver/proj_eb.o: $(SRC)/util/metrics.h
$(WRK)/solver/proj_eb.o: $(SRC)/util/module.h
$(WRK)/solver/proj_eb.o: $(SRC)/util/mpi.h
$(WRK)/solver/proj_eb.o: $(SRC)/util/suspender.h
$(WRK)/solver/proj_eb.o: $(SRC)/util/timer.h
$(WRK)/solver/proj.o: $(SRC)/geom/blockface.h
$(WRK)/solver/proj.o: $(SRC)/geom/block.h
$(WRK)/solver/proj.o: $(SRC)/geom/dir.h
$(WRK)/solver/proj.o: $(SRC)/geom/field.h
$(WRK)/solver/proj.o: $(SRC)/geom/filter.h
$(WRK)/solver/proj.o: $(SRC)/geom/idx.h
$(WRK)/solver/proj.o: $(SRC)/geom/loop.h
$(WRK)/solver/proj.o: $(SRC)/geom/map.h
$(WRK)/solver/proj.o: $(SRC)/geom/mesh.h
$(WRK)/solver/proj.o: $(SRC)/geom/notation.h
$(WRK)/solver/proj.o: $(SRC)/geom/range.h
$(WRK)/solver/proj.o: $(SRC)/geom/rangein.h
$(WRK)/solver/proj.o: $(SRC)/geom/rangemulti.h
$(WRK)/solver/proj.o: $(SRC)/geom/transform.h
$(WRK)/solver/proj.o: $(SRC)/geom/vect.h
$(WRK)/solver/proj.o: $(SRC)/linear/linear.h
$(WRK)/solver/proj.o: $(SRC)/parse/vars.h
$(WRK)/solver/proj.o: $(SRC)/solver/approx_eb.h
$(WRK)/solver/proj.o: $(SRC)/solver/approx.h
$(WRK)/solver/proj.o: $(SRC)/solver/cond.h
$(WRK)/solver/proj.o: $(SRC)/solver/convdiff.h
$(WRK)/solver/proj.o: $(SRC)/solver/convdiffvg.h
$(WRK)/solver/proj.o: $(SRC)/solver/convdiffv.h
$(WRK)/solver/proj.o: $(SRC)/solver/embed.h
$(WRK)/solver/proj.o: $(SRC)/solver/fluid.h
$(WRK)/solver/proj.o: $(SRC)/solver/proj.h
$(WRK)/solver/proj.o: $(SRC)/solver/proj.ipp
$(WRK)/solver/proj.o: $(SRC)/solver/reconst.h
$(WRK)/solver/proj.o: $(SRC)/solver/solver.h
$(WRK)/solver/proj.o: $(SRC)/util/convdiff.h
$(WRK)/solver/proj.o: $(SRC)/util/fluid.h
$(WRK)/solver/proj.o: $(SRC)/util/format.h
$(WRK)/solver/proj.o: $(SRC)/util/logger.h
$(WRK)/solver/proj.o: $(SRC)/util/macros.h
$(WRK)/solver/proj.o: $(SRC)/util/metrics.h
$(WRK)/solver/proj.o: $(SRC)/util/module.h
$(WRK)/solver/proj.o: $(SRC)/util/mpi.h
$(WRK)/solver/proj.o: $(SRC)/util/suspender.h
$(WRK)/solver/proj.o: $(SRC)/util/timer.h
$(WRK)/solver/simple.o: $(SRC)/debug/isnan.h
$(WRK)/solver/simple.o: $(SRC)/debug/linear.h
$(WRK)/solver/simple.o: $(SRC)/distr/reduce.h
$(WRK)/solver/simple.o: $(SRC)/geom/blockface.h
$(WRK)/solver/simple.o: $(SRC)/geom/block.h
$(WRK)/solver/simple.o: $(SRC)/geom/dir.h
$(WRK)/solver/simple.o: $(SRC)/geom/field.h
$(WRK)/solver/simple.o: $(SRC)/geom/filter.h
$(WRK)/solver/simple.o: $(SRC)/geom/idx.h
$(WRK)/solver/simple.o: $(SRC)/geom/loop.h
$(WRK)/solver/simple.o: $(SRC)/geom/map.h
$(WRK)/solver/simple.o: $(SRC)/geom/mesh.h
$(WRK)/solver/simple.o: $(SRC)/geom/notation.h
$(WRK)/solver/simple.o: $(SRC)/geom/range.h
$(WRK)/solver/simple.o: $(SRC)/geom/rangein.h
$(WRK)/solver/simple.o: $(SRC)/geom/rangemulti.h
$(WRK)/solver/simple.o: $(SRC)/geom/transform.h
$(WRK)/solver/simple.o: $(SRC)/geom/vect.h
$(WRK)/solver/simple.o: $(SRC)/linear/linear.h
$(WRK)/solver/simple.o: $(SRC)/parse/vars.h
$(WRK)/solver/simple.o: $(SRC)/solver/approx_eb.h
$(WRK)/solver/simple.o: $(SRC)/solver/approx.h
$(WRK)/solver/simple.o: $(SRC)/solver/cond.h
$(WRK)/solver/simple.o: $(SRC)/solver/convdiff.h
$(WRK)/solver/simple.o: $(SRC)/solver/convdiffvg.h
$(WRK)/solver/simple.o: $(SRC)/solver/convdiffv.h
$(WRK)/solver/simple.o: $(SRC)/solver/embed.h
$(WRK)/solver/simple.o: $(SRC)/solver/fluid.h
$(WRK)/solver/simple.o: $(SRC)/solver/reconst.h
$(WRK)/solver/simple.o: $(SRC)/solver/simple.h
$(WRK)/solver/simple.o: $(SRC)/solver/simple.ipp
$(WRK)/solver/simple.o: $(SRC)/solver/solver.h
$(WRK)/solver/simple.o: $(SRC)/util/convdiff.h
$(WRK)/solver/simple.o: $(SRC)/util/fluid.h
$(WRK)/solver/simple.o: $(SRC)/util/format.h
$(WRK)/solver/simple.o: $(SRC)/util/logger.h
$(WRK)/solver/simple.o: $(SRC)/util/macros.h
$(WRK)/solver/simple.o: $(SRC)/util/metrics.h
$(WRK)/solver/simple.o: $(SRC)/util/module.h
$(WRK)/solver/simple.o: $(SRC)/util/mpi.h
$(WRK)/solver/simple.o: $(SRC)/util/suspender.h
$(WRK)/solver/simple.o: $(SRC)/util/timer.h
$(WRK)/solver/solver.o: $(SRC)/solver/solver.h
$(WRK)/solver/solver.o: $(SRC)/util/logger.h
$(WRK)/solver/solver.o: $(SRC)/util/macros.h
$(WRK)/solver/tracer.o: $(SRC)/distr/reduce.h
$(WRK)/solver/tracer.o: $(SRC)/geom/blockface.h
$(WRK)/solver/tracer.o: $(SRC)/geom/block.h
$(WRK)/solver/tracer.o: $(SRC)/geom/dir.h
$(WRK)/solver/tracer.o: $(SRC)/geom/field.h
$(WRK)/solver/tracer.o: $(SRC)/geom/filter.h
$(WRK)/solver/tracer.o: $(SRC)/geom/idx.h
$(WRK)/solver/tracer.o: $(SRC)/geom/loop.h
$(WRK)/solver/tracer.o: $(SRC)/geom/map.h
$(WRK)/solver/tracer.o: $(SRC)/geom/mesh.h
$(WRK)/solver/tracer.o: $(SRC)/geom/notation.h
$(WRK)/solver/tracer.o: $(SRC)/geom/range.h
$(WRK)/solver/tracer.o: $(SRC)/geom/rangein.h
$(WRK)/solver/tracer.o: $(SRC)/geom/rangemulti.h
$(WRK)/solver/tracer.o: $(SRC)/geom/transform.h
$(WRK)/solver/tracer.o: $(SRC)/geom/vect.h
$(WRK)/solver/tracer.o: $(SRC)/parse/vars.h
$(WRK)/solver/tracer.o: $(SRC)/solver/advection.h
$(WRK)/solver/tracer.o: $(SRC)/solver/approx_eb.h
$(WRK)/solver/tracer.o: $(SRC)/solver/approx.h
$(WRK)/solver/tracer.o: $(SRC)/solver/cond.h
$(WRK)/solver/tracer.o: $(SRC)/solver/embed.h
$(WRK)/solver/tracer.o: $(SRC)/solver/multi.h
$(WRK)/solver/tracer.o: $(SRC)/solver/reconst.h
$(WRK)/solver/tracer.o: $(SRC)/solver/solver.h
$(WRK)/solver/tracer.o: $(SRC)/solver/tracer.h
$(WRK)/solver/tracer.o: $(SRC)/solver/tracer.ipp
$(WRK)/solver/tracer.o: $(SRC)/util/logger.h
$(WRK)/solver/tracer.o: $(SRC)/util/macros.h
$(WRK)/solver/tracer.o: $(SRC)/util/mpi.h
$(WRK)/solver/tracer.o: $(SRC)/util/suspender.h
$(WRK)/solver/tracer.o: $(SRC)/util/vof.h
$(WRK)/solver/vof.o: $(SRC)/debug/isnan.h
$(WRK)/solver/vof.o: $(SRC)/debug/linear.h
$(WRK)/solver/vof.o: $(SRC)/distr/reduce.h
$(WRK)/solver/vof.o: $(SRC)/geom/blockface.h
$(WRK)/solver/vof.o: $(SRC)/geom/block.h
$(WRK)/solver/vof.o: $(SRC)/geom/dir.h
$(WRK)/solver/vof.o: $(SRC)/geom/field.h
$(WRK)/solver/vof.o: $(SRC)/geom/filter.h
$(WRK)/solver/vof.o: $(SRC)/geom/idx.h
$(WRK)/solver/vof.o: $(SRC)/geom/loop.h
$(WRK)/solver/vof.o: $(SRC)/geom/map.h
$(WRK)/solver/vof.o: $(SRC)/geom/mesh.h
$(WRK)/solver/vof.o: $(SRC)/geom/notation.h
$(WRK)/solver/vof.o: $(SRC)/geom/range.h
$(WRK)/solver/vof.o: $(SRC)/geom/rangein.h
$(WRK)/solver/vof.o: $(SRC)/geom/rangemulti.h
$(WRK)/solver/vof.o: $(SRC)/geom/transform.h
$(WRK)/solver/vof.o: $(SRC)/geom/vect.h
$(WRK)/solver/vof.o: $(SRC)/linear/linear.h
$(WRK)/solver/vofm.o: $(SRC)/debug/isnan.h
$(WRK)/solver/vofm.o: $(SRC)/debug/linear.h
$(WRK)/solver/vofm.o: $(SRC)/distr/reduce.h
$(WRK)/solver/vofm.o: $(SRC)/dump/hdf.h
$(WRK)/solver/vofm.o: $(SRC)/geom/blockface.h
$(WRK)/solver/vofm.o: $(SRC)/geom/block.h
$(WRK)/solver/vofm.o: $(SRC)/geom/dir.h
$(WRK)/solver/vofm.o: $(SRC)/geom/field.h
$(WRK)/solver/vofm.o: $(SRC)/geom/filter.h
$(WRK)/solver/vofm.o: $(SRC)/geom/idx.h
$(WRK)/solver/vofm.o: $(SRC)/geom/loop.h
$(WRK)/solver/vofm.o: $(SRC)/geom/map.h
$(WRK)/solver/vofm.o: $(SRC)/geom/mesh.h
$(WRK)/solver/vofm.o: $(SRC)/geom/notation.h
$(WRK)/solver/vofm.o: $(SRC)/geom/range.h
$(WRK)/solver/vofm.o: $(SRC)/geom/rangein.h
$(WRK)/solver/vofm.o: $(SRC)/geom/rangemulti.h
$(WRK)/solver/vofm.o: $(SRC)/geom/transform.h
$(WRK)/solver/vofm.o: $(SRC)/geom/vect.h
$(WRK)/solver/vofm.o: $(SRC)/linear/linear.h
$(WRK)/solver/vofm.o: $(SRC)/parse/vars.h
$(WRK)/solver/vofm.o: $(SRC)/solver/advection.h
$(WRK)/solver/vofm.o: $(SRC)/solver/approx_eb.h
$(WRK)/solver/vofm.o: $(SRC)/solver/approx.h
$(WRK)/solver/vofm.o: $(SRC)/solver/cond.h
$(WRK)/solver/vofm.o: $(SRC)/solver/convdiff.h
$(WRK)/solver/vofm.o: $(SRC)/solver/convdiffvg.h
$(WRK)/solver/vofm.o: $(SRC)/solver/convdiffv.h
$(WRK)/solver/vofm.o: $(SRC)/solver/embed.h
$(WRK)/solver/vofm.o: $(SRC)/solver/multi.h
$(WRK)/solver/vofm.o: $(SRC)/solver/normal.h
$(WRK)/solver/vofm.o: $(SRC)/solver/reconst.h
$(WRK)/solver/vofm.o: $(SRC)/solver/solver.h
$(WRK)/solver/vofm.o: $(SRC)/solver/trackerm.h
$(WRK)/solver/vofm.o: $(SRC)/solver/vof.h
$(WRK)/solver/vofm.o: $(SRC)/solver/vofm.h
$(WRK)/solver/vofm.o: $(SRC)/solver/vofm.ipp
$(WRK)/solver/vofm.o: $(SRC)/util/convdiff.h
$(WRK)/solver/vofm.o: $(SRC)/util/filesystem.h
$(WRK)/solver/vofm.o: $(SRC)/util/format.h
$(WRK)/solver/vofm.o: $(SRC)/util/logger.h
$(WRK)/solver/vofm.o: $(SRC)/util/macros.h
$(WRK)/solver/vofm.o: $(SRC)/util/module.h
$(WRK)/solver/vofm.o: $(SRC)/util/mpi.h
$(WRK)/solver/vofm.o: $(SRC)/util/suspender.h
$(WRK)/solver/vofm.o: $(SRC)/util/vof.h
$(WRK)/solver/vof.o: $(SRC)/parse/vars.h
$(WRK)/solver/vof.o: $(SRC)/solver/advection.h
$(WRK)/solver/vof.o: $(SRC)/solver/approx_eb.h
$(WRK)/solver/vof.o: $(SRC)/solver/approx.h
$(WRK)/solver/vof.o: $(SRC)/solver/cond.h
$(WRK)/solver/vof.o: $(SRC)/solver/convdiff.h
$(WRK)/solver/vof.o: $(SRC)/solver/convdiffvg.h
$(WRK)/solver/vof.o: $(SRC)/solver/convdiffv.h
$(WRK)/solver/vof.o: $(SRC)/solver/embed.h
$(WRK)/solver/vof.o: $(SRC)/solver/multi.h
$(WRK)/solver/vof.o: $(SRC)/solver/normal.h
$(WRK)/solver/vof.o: $(SRC)/solver/reconst.h
$(WRK)/solver/vof.o: $(SRC)/solver/solver.h
$(WRK)/solver/vof.o: $(SRC)/solver/trackerm.h
$(WRK)/solver/vof.o: $(SRC)/solver/vof.h
$(WRK)/solver/vof.o: $(SRC)/solver/vof.ipp
$(WRK)/solver/vof.o: $(SRC)/util/convdiff.h
$(WRK)/solver/vof.o: $(SRC)/util/format.h
$(WRK)/solver/vof.o: $(SRC)/util/logger.h
$(WRK)/solver/vof.o: $(SRC)/util/macros.h
$(WRK)/solver/vof.o: $(SRC)/util/module.h
$(WRK)/solver/vof.o: $(SRC)/util/mpi.h
$(WRK)/solver/vof.o: $(SRC)/util/suspender.h
$(WRK)/solver/vof.o: $(SRC)/util/vof.h
$(WRK)/util/convdiff.o: $(SRC)/debug/linear.h
$(WRK)/util/convdiff.o: $(SRC)/distr/reduce.h
$(WRK)/util/convdiff.o: $(SRC)/geom/blockface.h
$(WRK)/util/convdiff.o: $(SRC)/geom/block.h
$(WRK)/util/convdiff.o: $(SRC)/geom/dir.h
$(WRK)/util/convdiff.o: $(SRC)/geom/field.h
$(WRK)/util/convdiff.o: $(SRC)/geom/filter.h
$(WRK)/util/convdiff.o: $(SRC)/geom/idx.h
$(WRK)/util/convdiff.o: $(SRC)/geom/loop.h
$(WRK)/util/convdiff.o: $(SRC)/geom/map.h
$(WRK)/util/convdiff.o: $(SRC)/geom/mesh.h
$(WRK)/util/convdiff.o: $(SRC)/geom/notation.h
$(WRK)/util/convdiff.o: $(SRC)/geom/range.h
$(WRK)/util/convdiff.o: $(SRC)/geom/rangein.h
$(WRK)/util/convdiff.o: $(SRC)/geom/rangemulti.h
$(WRK)/util/convdiff.o: $(SRC)/geom/transform.h
$(WRK)/util/convdiff.o: $(SRC)/geom/vect.h
$(WRK)/util/convdiff.o: $(SRC)/linear/linear.h
$(WRK)/util/convdiff.o: $(SRC)/parse/vars.h
$(WRK)/util/convdiff.o: $(SRC)/solver/cond.h
$(WRK)/util/convdiff.o: $(SRC)/solver/convdiffe.h
$(WRK)/util/convdiff.o: $(SRC)/solver/convdiff.h
$(WRK)/util/convdiff.o: $(SRC)/solver/convdiffi.h
$(WRK)/util/convdiff.o: $(SRC)/solver/convdiffvg.h
$(WRK)/util/convdiff.o: $(SRC)/solver/convdiffv.h
$(WRK)/util/convdiff.o: $(SRC)/solver/embed.h
$(WRK)/util/convdiff.o: $(SRC)/solver/reconst.h
$(WRK)/util/convdiff.o: $(SRC)/solver/solver.h
$(WRK)/util/convdiff.o: $(SRC)/util/convdiff.h
$(WRK)/util/convdiff.o: $(SRC)/util/logger.h
$(WRK)/util/convdiff.o: $(SRC)/util/macros.h
$(WRK)/util/convdiff.o: $(SRC)/util/module.h
$(WRK)/util/convdiff.o: $(SRC)/util/mpi.h
$(WRK)/util/convdiff.o: $(SRC)/util/suspender.h
$(WRK)/util/distr.o: $(SRC)/geom/dir.h
$(WRK)/util/distr.o: $(SRC)/geom/idx.h
$(WRK)/util/distr.o: $(SRC)/geom/range.h
$(WRK)/util/distr.o: $(SRC)/geom/vect.h
$(WRK)/util/distr.o: $(SRC)/util/distr.h
$(WRK)/util/distr.o: $(SRC)/util/distr.ipp
$(WRK)/util/distr.o: $(SRC)/util/format.h
$(WRK)/util/distr.o: $(SRC)/util/logger.h
$(WRK)/util/distr.o: $(SRC)/util/macros.h
$(WRK)/util/events.o: $(SRC)/parse/parser.h
$(WRK)/util/events.o: $(SRC)/parse/vars.h
$(WRK)/util/events.o: $(SRC)/util/events.h
$(WRK)/util/events.o: $(SRC)/util/logger.h
$(WRK)/util/events.o: $(SRC)/util/macros.h
$(WRK)/util/filesystem.o: $(SRC)/util/filesystem.h
$(WRK)/util/filesystem.o: $(SRC)/util/logger.h
$(WRK)/util/filesystem.o: $(SRC)/util/macros.h
$(WRK)/util/filesystem.o: $(SRC)/util/system.h
$(WRK)/util/fixed_allocator.o: $(SRC)/util/fixed_allocator.h
$(WRK)/util/format.o: $(SRC)/util/format.h
$(WRK)/util/format.o: $(SRC)/util/logger.h
$(WRK)/util/format.o: $(SRC)/util/macros.h
$(WRK)/util/git.o: $(SRC)/util/git.h
$(WRK)/util/histogram.o: $(SRC)/util/histogram.h
$(WRK)/util/histogram.o: $(SRC)/util/logger.h
$(WRK)/util/histogram.o: $(SRC)/util/macros.h
$(WRK)/util/histogram.o: $(SRC)/util/mpi.h
$(WRK)/util/histogram.o: $(SRC)/util/timer.h
$(WRK)/util/hydro.o: $(SRC)/debug/isnan.h
$(WRK)/util/hydro.o: $(SRC)/debug/linear.h
$(WRK)/util/hydro.o: $(SRC)/distr/reduce.h
$(WRK)/util/hydro.o: $(SRC)/dump/dumper.h
$(WRK)/util/hydro.o: $(SRC)/dump/hdf.h
$(WRK)/util/hydro.o: $(SRC)/dump/vtk.h
$(WRK)/util/hydro.o: $(SRC)/func/init_bc.h
$(WRK)/util/hydro.o: $(SRC)/func/init_u.h
$(WRK)/util/hydro.o: $(SRC)/func/init_vel.h
$(WRK)/util/hydro.o: $(SRC)/func/primlist.h
$(WRK)/util/hydro.o: $(SRC)/geom/blockface.h
$(WRK)/util/hydro.o: $(SRC)/geom/block.h
$(WRK)/util/hydro.o: $(SRC)/geom/dir.h
$(WRK)/util/hydro.o: $(SRC)/geom/field.h
$(WRK)/util/hydro.o: $(SRC)/geom/filter.h
$(WRK)/util/hydro.o: $(SRC)/geom/idx.h
$(WRK)/util/hydro.o: $(SRC)/geom/loop.h
$(WRK)/util/hydro.o: $(SRC)/geom/map.h
$(WRK)/util/hydro.o: $(SRC)/geom/mesh.h
$(WRK)/util/hydro.o: $(SRC)/geom/notation.h
$(WRK)/util/hydro.o: $(SRC)/geom/range.h
$(WRK)/util/hydro.o: $(SRC)/geom/rangein.h
$(WRK)/util/hydro.o: $(SRC)/geom/rangemulti.h
$(WRK)/util/hydro.o: $(SRC)/geom/transform.h
$(WRK)/util/hydro.o: $(SRC)/geom/vect.h
$(WRK)/util/hydro.o: $(SRC)/hydro.h
$(WRK)/util/hydro.o: $(SRC)/linear/linear.h
$(WRK)/util/hydro.o: $(SRC)/parse/codeblocks.h
$(WRK)/util/hydro.o: $(SRC)/parse/util.h
$(WRK)/util/hydro.o: $(SRC)/parse/vars.h
$(WRK)/util/hydro.o: $(SRC)/solver/advection.h
$(WRK)/util/hydro.o: $(SRC)/solver/approx_eb.h
$(WRK)/util/hydro.o: $(SRC)/solver/approx.h
$(WRK)/util/hydro.o: $(SRC)/solver/cond.h
$(WRK)/util/hydro.o: $(SRC)/solver/convdiff.h
$(WRK)/util/hydro.o: $(SRC)/solver/convdiffvg.h
$(WRK)/util/hydro.o: $(SRC)/solver/convdiffv.h
$(WRK)/util/hydro.o: $(SRC)/solver/embed.h
$(WRK)/util/hydro.o: $(SRC)/solver/fluid.h
$(WRK)/util/hydro.o: $(SRC)/solver/multi.h
$(WRK)/util/hydro.o: $(SRC)/solver/pois.h
$(WRK)/util/hydro.o: $(SRC)/solver/reconst.h
$(WRK)/util/hydro.o: $(SRC)/solver/solver.h
$(WRK)/util/hydro.o: $(SRC)/solver/sphavg.h
$(WRK)/util/hydro.o: $(SRC)/solver/vof.h
$(WRK)/util/hydro.o: $(SRC)/solver/vofm.h
$(WRK)/util/hydro.o: $(SRC)/util/convdiff.h
$(WRK)/util/hydro.o: $(SRC)/util/format.h
$(WRK)/util/hydro.o: $(SRC)/util/hydro.ipp
$(WRK)/util/hydro.o: $(SRC)/util/logger.h
$(WRK)/util/hydro.o: $(SRC)/util/macros.h
$(WRK)/util/hydro.o: $(SRC)/util/module.h
$(WRK)/util/hydro.o: $(SRC)/util/mpi.h
$(WRK)/util/hydro.o: $(SRC)/util/suspender.h
$(WRK)/util/linear.o: $(SRC)/debug/linear.h
$(WRK)/util/linear.o: $(SRC)/distr/reduce.h
$(WRK)/util/linear.o: $(SRC)/geom/blockface.h
$(WRK)/util/linear.o: $(SRC)/geom/block.h
$(WRK)/util/linear.o: $(SRC)/geom/dir.h
$(WRK)/util/linear.o: $(SRC)/geom/field.h
$(WRK)/util/linear.o: $(SRC)/geom/idx.h
$(WRK)/util/linear.o: $(SRC)/geom/loop.h
$(WRK)/util/linear.o: $(SRC)/geom/map.h
$(WRK)/util/linear.o: $(SRC)/geom/mesh.h
$(WRK)/util/linear.o: $(SRC)/geom/notation.h
$(WRK)/util/linear.o: $(SRC)/geom/range.h
$(WRK)/util/linear.o: $(SRC)/geom/rangein.h
$(WRK)/util/linear.o: $(SRC)/geom/rangemulti.h
$(WRK)/util/linear.o: $(SRC)/geom/transform.h
$(WRK)/util/linear.o: $(SRC)/geom/vect.h
$(WRK)/util/linear.o: $(SRC)/linear/linear.h
$(WRK)/util/linear.o: $(SRC)/parse/vars.h
$(WRK)/util/linear.o: $(SRC)/util/linear.h
$(WRK)/util/linear.o: $(SRC)/util/linear.ipp
$(WRK)/util/linear.o: $(SRC)/util/logger.h
$(WRK)/util/linear.o: $(SRC)/util/macros.h
$(WRK)/util/linear.o: $(SRC)/util/module.h
$(WRK)/util/linear.o: $(SRC)/util/mpi.h
$(WRK)/util/linear.o: $(SRC)/util/suspender.h
$(WRK)/util/logger.o: $(SRC)/util/logger.h
$(WRK)/util/logger.o: $(SRC)/util/macros.h
$(WRK)/util/mpi.o: $(SRC)/util/logger.h
$(WRK)/util/mpi.o: $(SRC)/util/macros.h
$(WRK)/util/mpi.o: $(SRC)/util/mpi.h
$(WRK)/util/posthook_default.o: $(SRC)/distr/reduce.h
$(WRK)/util/posthook_default.o: $(SRC)/geom/blockface.h
$(WRK)/util/posthook_default.o: $(SRC)/geom/block.h
$(WRK)/util/posthook_default.o: $(SRC)/geom/dir.h
$(WRK)/util/posthook_default.o: $(SRC)/geom/field.h
$(WRK)/util/posthook_default.o: $(SRC)/geom/filter.h
$(WRK)/util/posthook_default.o: $(SRC)/geom/idx.h
$(WRK)/util/posthook_default.o: $(SRC)/geom/loop.h
$(WRK)/util/posthook_default.o: $(SRC)/geom/map.h
$(WRK)/util/posthook_default.o: $(SRC)/geom/mesh.h
$(WRK)/util/posthook_default.o: $(SRC)/geom/notation.h
$(WRK)/util/posthook_default.o: $(SRC)/geom/range.h
$(WRK)/util/posthook_default.o: $(SRC)/geom/rangein.h
$(WRK)/util/posthook_default.o: $(SRC)/geom/rangemulti.h
$(WRK)/util/posthook_default.o: $(SRC)/geom/transform.h
$(WRK)/util/posthook_default.o: $(SRC)/geom/vect.h
$(WRK)/util/posthook_default.o: $(SRC)/parse/vars.h
$(WRK)/util/posthook_default.o: $(SRC)/solver/embed.h
$(WRK)/util/posthook_default.o: $(SRC)/solver/reconst.h
$(WRK)/util/posthook_default.o: $(SRC)/util/logger.h
$(WRK)/util/posthook_default.o: $(SRC)/util/macros.h
$(WRK)/util/posthook_default.o: $(SRC)/util/mpi.h
$(WRK)/util/posthook_default.o: $(SRC)/util/posthook.h
$(WRK)/util/posthook_default.o: $(SRC)/util/suspender.h
$(WRK)/util/subcomm_dummy.o: $(SRC)/util/logger.h
$(WRK)/util/subcomm_dummy.o: $(SRC)/util/macros.h
$(WRK)/util/subcomm_dummy.o: $(SRC)/util/mpi.h
$(WRK)/util/subcomm_dummy.o: $(SRC)/util/subcomm.h
$(WRK)/util/subcomm.o: $(SRC)/util/logger.h
$(WRK)/util/subcomm.o: $(SRC)/util/macros.h
$(WRK)/util/subcomm.o: $(SRC)/util/mpi.h
$(WRK)/util/subcomm.o: $(SRC)/util/subcomm.h
$(WRK)/util/subcomm.o: $(SRC)/util/sysinfo.h
$(WRK)/util/suspender.o: $(SRC)/util/logger.h
$(WRK)/util/suspender.o: $(SRC)/util/macros.h
$(WRK)/util/suspender.o: $(SRC)/util/suspender.h
$(WRK)/util/sysinfo.o: $(SRC)/util/logger.h
$(WRK)/util/sysinfo.o: $(SRC)/util/macros.h
$(WRK)/util/sysinfo.o: $(SRC)/util/mpi.h
$(WRK)/util/sysinfo.o: $(SRC)/util/sysinfo.h
$(WRK)/util/sysinfo.o: $(SRC)/util/system.h
$(WRK)/util/system.o: $(SRC)/util/system.h
$(WRK)/util/system.o: $(SRC)/util/system_unix.inc
$(WRK)/util/system.o: $(SRC)/util/system_windows.inc
$(WRK)/util/timer.o: $(SRC)/util/timer.h
$(WRK)/util/vof.o: $(SRC)/debug/isnan.h
$(WRK)/util/vof.o: $(SRC)/distr/reduce.h
$(WRK)/util/vof.o: $(SRC)/dump/vtk.h
$(WRK)/util/vof.o: $(SRC)/geom/blockface.h
$(WRK)/util/vof.o: $(SRC)/geom/block.h
$(WRK)/util/vof.o: $(SRC)/geom/dir.h
$(WRK)/util/vof.o: $(SRC)/geom/field.h
$(WRK)/util/vof.o: $(SRC)/geom/filter.h
$(WRK)/util/vof.o: $(SRC)/geom/idx.h
$(WRK)/util/vof.o: $(SRC)/geom/loop.h
$(WRK)/util/vof.o: $(SRC)/geom/map.h
$(WRK)/util/vof.o: $(SRC)/geom/mesh.h
$(WRK)/util/vof.o: $(SRC)/geom/notation.h
$(WRK)/util/vof.o: $(SRC)/geom/range.h
$(WRK)/util/vof.o: $(SRC)/geom/rangein.h
$(WRK)/util/vof.o: $(SRC)/geom/rangemulti.h
$(WRK)/util/vof.o: $(SRC)/geom/transform.h
$(WRK)/util/vof.o: $(SRC)/geom/vect.h
$(WRK)/util/vof.o: $(SRC)/march/march.h
$(WRK)/util/vof.o: $(SRC)/solver/advection.h
$(WRK)/util/vof.o: $(SRC)/solver/approx.h
$(WRK)/util/vof.o: $(SRC)/solver/cond.h
$(WRK)/util/vof.o: $(SRC)/solver/embed.h
$(WRK)/util/vof.o: $(SRC)/solver/multi.h
$(WRK)/util/vof.o: $(SRC)/solver/reconst.h
$(WRK)/util/vof.o: $(SRC)/solver/solver.h
$(WRK)/util/vof.o: $(SRC)/solver/trackerm.h
$(WRK)/util/vof.o: $(SRC)/util/format.h
$(WRK)/util/vof.o: $(SRC)/util/logger.h
$(WRK)/util/vof.o: $(SRC)/util/macros.h
$(WRK)/util/vof.o: $(SRC)/util/mpi.h
$(WRK)/util/vof.o: $(SRC)/util/suspender.h
$(WRK)/util/vof.o: $(SRC)/util/vof.h
$(WRK)/util/vof.o: $(SRC)/util/vof.ipp
$(WRK)/young/main.o: $(SRC)/young/young.h
