#!/bin/sh

find . -name '*.cpp' -or -name '*.c' | awk '
BEGIN {
    print "D = \\"
    skip["main.cpp"]
    skip["linear/hypre.cpp"]
    skip["linear/linear_amgx.cpp"]
}
{ sub(/^\.\//, "") }
($0 in skip) || /^test\// { next }
{
    sub(/\/.*/, "")
    print $0 "\\" | "sort | uniq"
}

END {
    close("sort | uniq")
    printf "\n"
}

'
