#!/bin/sh

find . -name '*.h' | awk '
BEGIN {
    print "D = \\"
}
{ sub(/^\.\//, "") }
/^test\// { next }
{
    if (sub(/\/.*/, ""))
        print $0 "\\" | "sort | uniq"
}

END {
    close("sort | uniq")
    printf "\n"
}

'
