#!/bin/sh

find . -name '*.h' | awk '
BEGIN {
    print "H = \\"
    skip["aphros_c.h"]
}
{ sub(/^\.\//, "") }
($0 in skip) || /^test\// { next }
{
    print $0 "\\" | "sort"
}

END {
    close("sort")
    printf "\n"
}

'
