#!/bin/sh

(find . -name '*.cpp' -or -name '*.c'; echo util/gitgen.cpp) | awk '
BEGIN {
    print "O = \\"
    skip["distr/comm_manager.cpp"]
    skip["distr/cubismnc.cpp"]
    skip["distr/native.cpp"]
    skip["gen/wave_lamb.c"]
    skip["linear/hypre.cpp"]
    skip["linear/hypresub.cpp"]
    skip["linear/linear_amgx.cpp"]
    skip["linear/linear_hypre.cpp"]
    skip["main.cpp"]
    skip["overlap/overlap.cpp"]
    skip["util/subcomm.cpp"]
}
{ sub(/^\.\//, "") }
($0 in skip) || /^test\// { next }
{
    file = $0
    if (sub(/\.cpp$/, ".o"))
        rule = "$(CXX_RULE)"
    else if (sub(/\.c$/, ".o"))
        rule = "$(CC_RULE)"
    printf "%s: $S/%s; mkdir -p %s && %s\n", $0, file, dirname($0), rule | "sort > ../make/rule.mk"
    print $0 "\\" | "sort | uniq"
}

END {
    print "util/gitgen.o" "\\" | "sort | uniq"
    close("sort")
    printf "\n"
}

function dirname(s)
{
    if (!sub(/\/.*/, "", s))
        return "."
    else
        return s
}

'
