#!/usr/bin/awk -f

BEGIN {
    skip["distr/cubismnc.cpp"]
    skip["gen/wave_lamb.c"]
    skip["linear/hypre.cpp"]
    skip["linear/hypresub.cpp"]
    skip["linear/linear_amgx.cpp"]
    skip["linear/linear_hypre.cpp"]
    skip["main.c"]
    skip["overlap/overlap.cpp"]
    skip["util/subcomm.cpp"]
}

!($0 in skip) {
    file = $0
    if (sub(/\.cpp$/, ""))
	print $0, file, "$(CXX_RULE)"
    else if (sub(/\.c$/, ""))
	print $0, file, "$(CC_RULE)"
}

