O = \
overlap/overlap.o\
overlap/overlap0.o\
distr/distr.o\
distr/cubismnc.o\
distr/comm_manager.o\
distr/distrsolver.o\
distr/report.o\
distr/local.o\
distr/native.o\
distr/distrbasic.o\
parse/vars.o\
parse/conf2py.o\
parse/parser.o\
parse/argparse.o\
linear/hypresub.o\
linear/linear.o\
linear/linear_hypre.o\
linear/hypre.o\
util/distr.o\
util/fluid.o\
util/sysinfo.o\
util/fixed_allocator.o\
util/filesystem.o\
util/format.o\
util/posthook_default.o\
util/suspender.o\
util/subcomm_dummy.o\
util/git.o\
util/histogram.o\
util/timer.o\
util/vof.o\
util/linear.o\
util/hydro.o\
util/events.o\
util/convdiff.o\
util/subcomm.o\
dump/dump.o\
dump/dumper.o\
dump/hdf.o\
solver/vofm.o\
solver/convdiffi.o\
solver/embed.o\
solver/proj.o\
solver/simple.o\
solver/proj_eb.o\
solver/particles.o\
solver/fluid_dummy.o\
solver/convdiffvg.o\
solver/tracer.o\
solver/electro.o\
solver/vof.o\
solver/partstrmeshm.o\
solver/approx.o\
solver/convdiffe.o\
solver/normal.o\
solver/approx_eb.o\
solver/solver.o\
solver/curv.o\
young/main.o\
color/color.o\
gen/wave_lamb.o\
geom/mesh.o\
func/init_vel.o\
func/init_contang.o\
func/init.o\
func/primlist.o\

