#!/usr/bin/env python

import glob

c = {}
exec(open("../conf.py").read(), None, c)

dim = c['dim']
d3 = (dim == 3)

# number of frames from ch
g = "../ch/vf_*.dat"
nfr = len(glob.glob(g))
assert nfr >= 2, "Error: Need at least 2 frames $r, found %r" % (g, nfr)

c['nfr'] = nfr
c['dumpdt'] = c['tmax'] / c['nfr']

nx = c['nx']
nxexp = nx.bit_length() - 1
assert nx == 2 ** nxexp, "Mesh size nx=%r but must be power of 2" % nx
c['nxexp'] = nxexp

o = '''Define VELX {vel[0]}
Define VELY {vel[1]}
Define VELZ {vel[2]}
Define TMAX {tmax}
Define DUMPDT {dumpdt}
Define SIGMA {sig}
Define MU {mu}
Define REFINE {nxexp}

'''.format(**c)

# base config file
mb = "main{:}.gfs".format(dim)
print("Reading base config from {:}".format(mb))
o += open(mb).read()

open("main.gen.gfs", 'w').write(o)
