#!/bin/bash

# Splits domain for given config file.
# $1: config file (e.g. main.gfs)
# $2: exponent for number of processors np=2 ^ $2
# $3: dimension, 2 or 3
# Output:
# .main.gfs: config file for split domain

set -eu

orig="$1"
npexp="$2"
spl=".main.gfs"
dim=$3

p=$npexp
# number of processors
np=`bc <<< "2^($p)"`

# split s times in each direction
s=1
while true ;  do
  # number of split domains
  ns=`bc <<< "2^($dim * $s)"`
  if [ "$ns" -ge "$np" ] ; then
    break
  fi
  s=$(($s + 1))
done

echo "split to $ns parts, partition for $np PEs" >&2

mkdir -p `eval echo "o/{0..$(expr $np - 1)}"`
mkdir -p o/-1

ex="ge.run${dim}d"

t=".smain.gfs"
if test $s -eq 0; then
  cp -vf $orig $t
else
  c="$ex -s $s -m $orig > $t"
  echo "$c"
  eval "$c"
fi

if test $p -eq 0; then
  cp -vf $t $spl
else
  c="$ex -p $p -m $t > $spl"
  echo "$c"
  eval "$c"
fi
rm -vf $t
