#!/bin/bash

set -ue

# output folder
o=o
rm -vf $o/*.pdf
mkdir -p $o

# bubble
: ${bc="0.31 0.29 0.26 "}
: ${vel="0.4 0.3 0.2 "}
: ${tmax="1."}
: ${lexp="2 3 4 5 6"}

# log
l="out"
echo > $l

echo "vel=$vel"
echo "tmax=$tmax"
echo "lexp=$lexp"

for exp in $lexp ; do
  br=`bc -l <<< "0.4 * sqrt(2 ^ (-$exp))"`
  echo "br=$br"
  echo "$bc $br $br $br" > b.dat
  p="r${br}_"

  echo "$vel" > vel
  echo "$tmax" > tmax

  # run ch
  d="ch"
  echo $d
  (cd $d ; ./run) &>> $l

  # run ge
  d="ge"
  echo $d
  (cd $d ; ./run) &>> $l

  # plot cmp
  ./plot.py &>> $l

  d="ch"
  mv -f $d/vf_0000.pdf $o/${p}vf_$d.pdf
  d="ge"
  mv -f $d/vf_0000.pdf $o/${p}vf_$d.pdf
  for f in `ls {traj,trajp,trajx,trajy,trajz,trajvxm,trajvym,trajvzm,trajvx2,trajvy2,trajvz2}.pdf` ; do
    mv -v $f $o/${p}${f}
  done
done

# tile all pdf
(cd $o ; ../tile)

mv -v out $o/

# rename folder
IFS=' ' read velx vely velz <<< "$vel"
dout=${o}_vel${velx}_t${tmax}
echo $dout
rm -rf $dout
mv -T $o $dout
