#!/bin/bash

set -ue

# output folder
o=o
rm -vf $o/*.pdf
mkdir -p $o

# bubble
: ${bc="0.31 0.29 0.26 "}
: ${vel="0.4 0.3 0.2 "}

# log
l="out"
echo > $l

for exp in `seq 2 6` ; do
#for exp in 4 ; do
  br=`bc -l <<< "0.4 * sqrt(2 ^ (-$exp))"`
  echo "br=$br"
  echo "$bc $br $br $br" > b.dat
  p="r${br}_"

  echo "$vel" > vel

  # run ch
  d="ch"
  echo $d
  (cd $d ; ./run) &>> $l

  # run ge
  d="ge"
  echo $d
  (cd $d ; ./run) &>> $l

  # plot cmp
  ./plot.py &>> $l

  d="ch"
  mv -f $d/vf_0000.pdf $o/${p}vf_$d.pdf
  d="ge"
  mv -f $d/vf_0000.pdf $o/${p}vf_$d.pdf
  for f in `ls {traj,trajp,trajx,trajy,trajz,trajvxm,trajvym,trajvzm,trajvx2,trajvy2,trajvz2}.pdf` ; do
    mv -v $f $o/${p}${f}
  done
done

# tile all pdf
(cd $o ; ../tile)

mv -v out $o/
