B = \
explorer.exe\
main.exe\
test/advection/main.exe\
test/approx/linear.exe\
test/approx/main.exe\
test/benchmark_diffusion/main.exe\
test/benchmark/main.exe\
test/benchmark_mpi/main.exe\
test/benchmark_mpiraw/main.exe\
test/benchmark_normal/main.exe\
test/color/main.exe\
test/commhalo/main.exe\
test/comm/main.exe\
test/commmap/main.exe\
test/commmap/manager.exe\
test/commmap/rank.exe\
test/condface/main.exe\
test/debug/main.exe\
test/dump/dump_diff.exe\
test/dump/dump_gen.exe\
test/dump/dump_meta.exe\
test/dump/dump_util.exe\
test/embed_approx/main.exe\
test/embed_convdiff/main.exe\
test/embed_grad/main.exe\
test/embed_interpolate/main.exe\
test/embed/main.exe\
test/embed_potential/main.exe\
test/fluid/main.exe\
test/grad/main.exe\
test/hook/hook/hook.exe\
test/hypre/main.exe\
test/hypresub/main.exe\
test/init/main.exe\
test/inner/main.exe\
test/linear/main.exe\
test/mesh/main.exe\
test/openmp/main.exe\
test/parser/codeblocks.exe\
test/parser/main.exe\
test/primlist/getmap.exe\
test/primlist/parse.exe\
test/range/main.exe\
test/recolor/main.exe\
test/reconst/levelset.exe\
test/reconst/main.exe\
test/reconst/plane.exe\
test/reflect/main.exe\
test/stat/main.exe\
test/subcomm/main.exe\
test/suspender/main.exe\
test/sysinfo/main.exe\
test/sysinfo/realpath.exe\
test/sysinfo/splitext.exe\
test/tracker/main.exe\
test/util/main.exe\
test/vars/main.exe\
test/visual/main.exe\

