$(WRK)\aphros_c\git.obj: $(SRC)\aphros_c.h
$(WRK)\aphros_c\git.obj: $(SRC)\util\git.h
$(WRK)\aphros_c\main.obj: $(SRC)\aphros_c.h
$(WRK)\aphros_c\main.obj: $(SRC)\debug\isnan.h
$(WRK)\aphros_c\main.obj: $(SRC)\debug\linear.h
$(WRK)\aphros_c\main.obj: $(SRC)\distr\distr.h
$(WRK)\aphros_c\main.obj: $(SRC)\distr\distrsolver.h
$(WRK)\aphros_c\main.obj: $(SRC)\distr\reduce.h
$(WRK)\aphros_c\main.obj: $(SRC)\dump\dumper.h
$(WRK)\aphros_c\main.obj: $(SRC)\dump\dump.h
$(WRK)\aphros_c\main.obj: $(SRC)\dump\hdf.h
$(WRK)\aphros_c\main.obj: $(SRC)\func\init_contang.h
$(WRK)\aphros_c\main.obj: $(SRC)\func\init.h
$(WRK)\aphros_c\main.obj: $(SRC)\geom\blockface.h
$(WRK)\aphros_c\main.obj: $(SRC)\geom\block.h
$(WRK)\aphros_c\main.obj: $(SRC)\geom\dir.h
$(WRK)\aphros_c\main.obj: $(SRC)\geom\field.h
$(WRK)\aphros_c\main.obj: $(SRC)\geom\filter.h
$(WRK)\aphros_c\main.obj: $(SRC)\geom\idx.h
$(WRK)\aphros_c\main.obj: $(SRC)\geom\loop.h
$(WRK)\aphros_c\main.obj: $(SRC)\geom\map.h
$(WRK)\aphros_c\main.obj: $(SRC)\geom\mesh.h
$(WRK)\aphros_c\main.obj: $(SRC)\geom\notation.h
$(WRK)\aphros_c\main.obj: $(SRC)\geom\range.h
$(WRK)\aphros_c\main.obj: $(SRC)\geom\rangein.h
$(WRK)\aphros_c\main.obj: $(SRC)\geom\rangemulti.h
$(WRK)\aphros_c\main.obj: $(SRC)\geom\transform.h
$(WRK)\aphros_c\main.obj: $(SRC)\geom\vect.h
$(WRK)\aphros_c\main.obj: $(SRC)\kernel\hydro.h
$(WRK)\aphros_c\main.obj: $(SRC)\kernel\kernelmesh.h
$(WRK)\aphros_c\main.obj: $(SRC)\kernel\kernelmeshpar.h
$(WRK)\aphros_c\main.obj: $(SRC)\linear\linear.h
$(WRK)\aphros_c\main.obj: $(SRC)\parse\curv.h
$(WRK)\aphros_c\main.obj: $(SRC)\parse\parser.h
$(WRK)\aphros_c\main.obj: $(SRC)\parse\proj.h
$(WRK)\aphros_c\main.obj: $(SRC)\parse\simple.h
$(WRK)\aphros_c\main.obj: $(SRC)\parse\solver.h
$(WRK)\aphros_c\main.obj: $(SRC)\parse\util.h
$(WRK)\aphros_c\main.obj: $(SRC)\parse\vars.h
$(WRK)\aphros_c\main.obj: $(SRC)\parse\vof.h
$(WRK)\aphros_c\main.obj: $(SRC)\solver\advection.h
$(WRK)\aphros_c\main.obj: $(SRC)\solver\approx2.h
$(WRK)\aphros_c\main.obj: $(SRC)\solver\approx_eb.h
$(WRK)\aphros_c\main.obj: $(SRC)\solver\approx.h
$(WRK)\aphros_c\main.obj: $(SRC)\solver\cond.h
$(WRK)\aphros_c\main.obj: $(SRC)\solver\convdiff.h
$(WRK)\aphros_c\main.obj: $(SRC)\solver\convdiffvg.h
$(WRK)\aphros_c\main.obj: $(SRC)\solver\convdiffv.h
$(WRK)\aphros_c\main.obj: $(SRC)\solver\curv.h
$(WRK)\aphros_c\main.obj: $(SRC)\solver\electro.h
$(WRK)\aphros_c\main.obj: $(SRC)\solver\embed.h
$(WRK)\aphros_c\main.obj: $(SRC)\solver\fluid_dummy.h
$(WRK)\aphros_c\main.obj: $(SRC)\solver\fluid.h
$(WRK)\aphros_c\main.obj: $(SRC)\solver\multi.h
$(WRK)\aphros_c\main.obj: $(SRC)\solver\normal.h
$(WRK)\aphros_c\main.obj: $(SRC)\solver\particles.h
$(WRK)\aphros_c\main.obj: $(SRC)\solver\partstr.h
$(WRK)\aphros_c\main.obj: $(SRC)\solver\partstrmeshm.h
$(WRK)\aphros_c\main.obj: $(SRC)\solver\proj.h
$(WRK)\aphros_c\main.obj: $(SRC)\solver\reconst.h
$(WRK)\aphros_c\main.obj: $(SRC)\solver\simple.h
$(WRK)\aphros_c\main.obj: $(SRC)\solver\solver.h
$(WRK)\aphros_c\main.obj: $(SRC)\solver\tracer.h
$(WRK)\aphros_c\main.obj: $(SRC)\solver\vof.h
$(WRK)\aphros_c\main.obj: $(SRC)\solver\vofm.h
$(WRK)\aphros_c\main.obj: $(SRC)\util\convdiff.h
$(WRK)\aphros_c\main.obj: $(SRC)\util\distr.h
$(WRK)\aphros_c\main.obj: $(SRC)\util\events.h
$(WRK)\aphros_c\main.obj: $(SRC)\util\filesystem.h
$(WRK)\aphros_c\main.obj: $(SRC)\util\format.h
$(WRK)\aphros_c\main.obj: $(SRC)\util\hydro.h
$(WRK)\aphros_c\main.obj: $(SRC)\util\linear.h
$(WRK)\aphros_c\main.obj: $(SRC)\util\logger.h
$(WRK)\aphros_c\main.obj: $(SRC)\util\macros.h
$(WRK)\aphros_c\main.obj: $(SRC)\util\metrics.h
$(WRK)\aphros_c\main.obj: $(SRC)\util\module.h
$(WRK)\aphros_c\main.obj: $(SRC)\util\mpi.h
$(WRK)\aphros_c\main.obj: $(SRC)\util\posthook.h
$(WRK)\aphros_c\main.obj: $(SRC)\util\stat.h
$(WRK)\aphros_c\main.obj: $(SRC)\util\suspender.h
$(WRK)\aphros_c\main.obj: $(SRC)\util\sysinfo.h
$(WRK)\aphros_c\main.obj: $(SRC)\util\timer.h
$(WRK)\aphros_c\parser.obj: $(SRC)\aphros_c.h
$(WRK)\aphros_c\parser.obj: $(SRC)\parse\parser.h
$(WRK)\aphros_c\parser.obj: $(SRC)\parse\vars.h
$(WRK)\aphros_c\parser.obj: $(SRC)\util\logger.h
$(WRK)\aphros_c\parser.obj: $(SRC)\util\macros.h
$(WRK)\color\color.obj: $(SRC)\color\color.h
$(WRK)\distr\comm_manager.obj: $(SRC)\distr\comm_manager.h
$(WRK)\distr\comm_manager.obj: $(SRC)\distr\comm_manager.ipp
$(WRK)\distr\comm_manager.obj: $(SRC)\distr\comm_manager_seq.ipp
$(WRK)\distr\comm_manager.obj: $(SRC)\distr\distr.h
$(WRK)\distr\comm_manager.obj: $(SRC)\distr\distrsolver.h
$(WRK)\distr\comm_manager.obj: $(SRC)\distr\reduce.h
$(WRK)\distr\comm_manager.obj: $(SRC)\dump\dumper.h
$(WRK)\distr\comm_manager.obj: $(SRC)\dump\dump.h
$(WRK)\distr\comm_manager.obj: $(SRC)\geom\blockface.h
$(WRK)\distr\comm_manager.obj: $(SRC)\geom\block.h
$(WRK)\distr\comm_manager.obj: $(SRC)\geom\dir.h
$(WRK)\distr\comm_manager.obj: $(SRC)\geom\field.h
$(WRK)\distr\comm_manager.obj: $(SRC)\geom\idx.h
$(WRK)\distr\comm_manager.obj: $(SRC)\geom\loop.h
$(WRK)\distr\comm_manager.obj: $(SRC)\geom\map.h
$(WRK)\distr\comm_manager.obj: $(SRC)\geom\mesh.h
$(WRK)\distr\comm_manager.obj: $(SRC)\geom\notation.h
$(WRK)\distr\comm_manager.obj: $(SRC)\geom\range.h
$(WRK)\distr\comm_manager.obj: $(SRC)\geom\rangein.h
$(WRK)\distr\comm_manager.obj: $(SRC)\geom\rangemulti.h
$(WRK)\distr\comm_manager.obj: $(SRC)\geom\transform.h
$(WRK)\distr\comm_manager.obj: $(SRC)\geom\vect.h
$(WRK)\distr\comm_manager.obj: $(SRC)\kernel\kernelmesh.h
$(WRK)\distr\comm_manager.obj: $(SRC)\kernel\kernelmeshpar.h
$(WRK)\distr\comm_manager.obj: $(SRC)\parse\parser.h
$(WRK)\distr\comm_manager.obj: $(SRC)\parse\vars.h
$(WRK)\distr\comm_manager.obj: $(SRC)\util\distr.h
$(WRK)\distr\comm_manager.obj: $(SRC)\util\format.h
$(WRK)\distr\comm_manager.obj: $(SRC)\util\logger.h
$(WRK)\distr\comm_manager.obj: $(SRC)\util\macros.h
$(WRK)\distr\comm_manager.obj: $(SRC)\util\metrics.h
$(WRK)\distr\comm_manager.obj: $(SRC)\util\module.h
$(WRK)\distr\comm_manager.obj: $(SRC)\util\mpi.h
$(WRK)\distr\comm_manager.obj: $(SRC)\util\suspender.h
$(WRK)\distr\comm_manager.obj: $(SRC)\util\sysinfo.h
$(WRK)\distr\comm_manager.obj: $(SRC)\util\timer.h
$(WRK)\distr\cubismnc.obj: $(SRC)\CubismNoCopy\BlockInfo.h
$(WRK)\distr\cubismnc.obj: $(SRC)\CubismNoCopy\BlockLab.h
$(WRK)\distr\cubismnc.obj: $(SRC)\CubismNoCopy\BlockLabMPI.h
$(WRK)\distr\cubismnc.obj: $(SRC)\CubismNoCopy\DependencyCubeMPI.h
$(WRK)\distr\cubismnc.obj: $(SRC)\CubismNoCopy\Grid.h
$(WRK)\distr\cubismnc.obj: $(SRC)\CubismNoCopy\GridMPI.h
$(WRK)\distr\cubismnc.obj: $(SRC)\CubismNoCopy\HDF5Dumper_MPI.h
$(WRK)\distr\cubismnc.obj: $(SRC)\CubismNoCopy\PUPkernelsMPI.h
$(WRK)\distr\cubismnc.obj: $(SRC)\CubismNoCopy\QPXEMU.h
$(WRK)\distr\cubismnc.obj: $(SRC)\CubismNoCopy\StencilInfo.h
$(WRK)\distr\cubismnc.obj: $(SRC)\CubismNoCopy\SynchronizerMPI.h
$(WRK)\distr\cubismnc.obj: $(SRC)\distr\cubismnc.ipp
$(WRK)\distr\cubismnc.obj: $(SRC)\distr\distr.h
$(WRK)\distr\cubismnc.obj: $(SRC)\distr\reduce.h
$(WRK)\distr\cubismnc.obj: $(SRC)\dump\dumper.h
$(WRK)\distr\cubismnc.obj: $(SRC)\dump\dump.h
$(WRK)\distr\cubismnc.obj: $(SRC)\geom\blockface.h
$(WRK)\distr\cubismnc.obj: $(SRC)\geom\block.h
$(WRK)\distr\cubismnc.obj: $(SRC)\geom\dir.h
$(WRK)\distr\cubismnc.obj: $(SRC)\geom\field.h
$(WRK)\distr\cubismnc.obj: $(SRC)\geom\idx.h
$(WRK)\distr\cubismnc.obj: $(SRC)\geom\loop.h
$(WRK)\distr\cubismnc.obj: $(SRC)\geom\map.h
$(WRK)\distr\cubismnc.obj: $(SRC)\geom\mesh.h
$(WRK)\distr\cubismnc.obj: $(SRC)\geom\notation.h
$(WRK)\distr\cubismnc.obj: $(SRC)\geom\range.h
$(WRK)\distr\cubismnc.obj: $(SRC)\geom\rangein.h
$(WRK)\distr\cubismnc.obj: $(SRC)\geom\rangemulti.h
$(WRK)\distr\cubismnc.obj: $(SRC)\geom\transform.h
$(WRK)\distr\cubismnc.obj: $(SRC)\geom\vect.h
$(WRK)\distr\cubismnc.obj: $(SRC)\kernel\kernelmesh.h
$(WRK)\distr\cubismnc.obj: $(SRC)\parse\vars.h
$(WRK)\distr\cubismnc.obj: $(SRC)\util\compressor.h
$(WRK)\distr\cubismnc.obj: $(SRC)\util\format.h
$(WRK)\distr\cubismnc.obj: $(SRC)\util\histogram.h
$(WRK)\distr\cubismnc.obj: $(SRC)\util\logger.h
$(WRK)\distr\cubismnc.obj: $(SRC)\util\macros.h
$(WRK)\distr\cubismnc.obj: $(SRC)\util\metrics.h
$(WRK)\distr\cubismnc.obj: $(SRC)\util\module.h
$(WRK)\distr\cubismnc.obj: $(SRC)\util\mpi.h
$(WRK)\distr\cubismnc.obj: $(SRC)\util\suspender.h
$(WRK)\distr\cubismnc.obj: $(SRC)\util\sysinfo.h
$(WRK)\distr\cubismnc.obj: $(SRC)\util\timer.h
$(WRK)\distr\distrbasic.obj: $(SRC)\distr\distr.h
$(WRK)\distr\distrbasic.obj: $(SRC)\distr\distrsolver.h
$(WRK)\distr\distrbasic.obj: $(SRC)\distr\reduce.h
$(WRK)\distr\distrbasic.obj: $(SRC)\dump\dumper.h
$(WRK)\distr\distrbasic.obj: $(SRC)\dump\dump.h
$(WRK)\distr\distrbasic.obj: $(SRC)\geom\blockface.h
$(WRK)\distr\distrbasic.obj: $(SRC)\geom\block.h
$(WRK)\distr\distrbasic.obj: $(SRC)\geom\dir.h
$(WRK)\distr\distrbasic.obj: $(SRC)\geom\field.h
$(WRK)\distr\distrbasic.obj: $(SRC)\geom\idx.h
$(WRK)\distr\distrbasic.obj: $(SRC)\geom\loop.h
$(WRK)\distr\distrbasic.obj: $(SRC)\geom\map.h
$(WRK)\distr\distrbasic.obj: $(SRC)\geom\mesh.h
$(WRK)\distr\distrbasic.obj: $(SRC)\geom\notation.h
$(WRK)\distr\distrbasic.obj: $(SRC)\geom\range.h
$(WRK)\distr\distrbasic.obj: $(SRC)\geom\rangein.h
$(WRK)\distr\distrbasic.obj: $(SRC)\geom\rangemulti.h
$(WRK)\distr\distrbasic.obj: $(SRC)\geom\transform.h
$(WRK)\distr\distrbasic.obj: $(SRC)\geom\vect.h
$(WRK)\distr\distrbasic.obj: $(SRC)\kernel\kernelmesh.h
$(WRK)\distr\distrbasic.obj: $(SRC)\kernel\kernelmeshpar.h
$(WRK)\distr\distrbasic.obj: $(SRC)\parse\parser.h
$(WRK)\distr\distrbasic.obj: $(SRC)\parse\vars.h
$(WRK)\distr\distrbasic.obj: $(SRC)\util\distr.h
$(WRK)\distr\distrbasic.obj: $(SRC)\util\format.h
$(WRK)\distr\distrbasic.obj: $(SRC)\util\git.h
$(WRK)\distr\distrbasic.obj: $(SRC)\util\logger.h
$(WRK)\distr\distrbasic.obj: $(SRC)\util\macros.h
$(WRK)\distr\distrbasic.obj: $(SRC)\util\metrics.h
$(WRK)\distr\distrbasic.obj: $(SRC)\util\module.h
$(WRK)\distr\distrbasic.obj: $(SRC)\util\mpi.h
$(WRK)\distr\distrbasic.obj: $(SRC)\util\subcomm.h
$(WRK)\distr\distrbasic.obj: $(SRC)\util\suspender.h
$(WRK)\distr\distrbasic.obj: $(SRC)\util\sysinfo.h
$(WRK)\distr\distrbasic.obj: $(SRC)\util\timer.h
$(WRK)\distr\distr.obj: $(SRC)\distr\distr.h
$(WRK)\distr\distr.obj: $(SRC)\distr\distr.ipp
$(WRK)\distr\distr.obj: $(SRC)\distr\reduce.h
$(WRK)\distr\distr.obj: $(SRC)\distr\report.h
$(WRK)\distr\distr.obj: $(SRC)\dump\dumper.h
$(WRK)\distr\distr.obj: $(SRC)\dump\dump.h
$(WRK)\distr\distr.obj: $(SRC)\dump\raw.h
$(WRK)\distr\distr.obj: $(SRC)\dump\xmf.h
$(WRK)\distr\distr.obj: $(SRC)\geom\blockface.h
$(WRK)\distr\distr.obj: $(SRC)\geom\block.h
$(WRK)\distr\distr.obj: $(SRC)\geom\dir.h
$(WRK)\distr\distr.obj: $(SRC)\geom\field.h
$(WRK)\distr\distr.obj: $(SRC)\geom\idx.h
$(WRK)\distr\distr.obj: $(SRC)\geom\loop.h
$(WRK)\distr\distr.obj: $(SRC)\geom\map.h
$(WRK)\distr\distr.obj: $(SRC)\geom\mesh.h
$(WRK)\distr\distr.obj: $(SRC)\geom\notation.h
$(WRK)\distr\distr.obj: $(SRC)\geom\range.h
$(WRK)\distr\distr.obj: $(SRC)\geom\rangein.h
$(WRK)\distr\distr.obj: $(SRC)\geom\rangemulti.h
$(WRK)\distr\distr.obj: $(SRC)\geom\transform.h
$(WRK)\distr\distr.obj: $(SRC)\geom\vect.h
$(WRK)\distr\distr.obj: $(SRC)\kernel\kernelmesh.h
$(WRK)\distr\distr.obj: $(SRC)\parse\vars.h
$(WRK)\distr\distrsolver.obj: $(SRC)\distr\distr.h
$(WRK)\distr\distrsolver.obj: $(SRC)\distr\distrsolver.h
$(WRK)\distr\distrsolver.obj: $(SRC)\distr\reduce.h
$(WRK)\distr\distrsolver.obj: $(SRC)\dump\dumper.h
$(WRK)\distr\distrsolver.obj: $(SRC)\dump\dump.h
$(WRK)\distr\distrsolver.obj: $(SRC)\geom\blockface.h
$(WRK)\distr\distrsolver.obj: $(SRC)\geom\block.h
$(WRK)\distr\distrsolver.obj: $(SRC)\geom\dir.h
$(WRK)\distr\distrsolver.obj: $(SRC)\geom\field.h
$(WRK)\distr\distrsolver.obj: $(SRC)\geom\idx.h
$(WRK)\distr\distrsolver.obj: $(SRC)\geom\loop.h
$(WRK)\distr\distrsolver.obj: $(SRC)\geom\map.h
$(WRK)\distr\distrsolver.obj: $(SRC)\geom\mesh.h
$(WRK)\distr\distrsolver.obj: $(SRC)\geom\notation.h
$(WRK)\distr\distrsolver.obj: $(SRC)\geom\range.h
$(WRK)\distr\distrsolver.obj: $(SRC)\geom\rangein.h
$(WRK)\distr\distrsolver.obj: $(SRC)\geom\rangemulti.h
$(WRK)\distr\distrsolver.obj: $(SRC)\geom\transform.h
$(WRK)\distr\distrsolver.obj: $(SRC)\geom\vect.h
$(WRK)\distr\distrsolver.obj: $(SRC)\kernel\kernelmesh.h
$(WRK)\distr\distrsolver.obj: $(SRC)\kernel\kernelmeshpar.h
$(WRK)\distr\distrsolver.obj: $(SRC)\parse\argparse.h
$(WRK)\distr\distrsolver.obj: $(SRC)\parse\parser.h
$(WRK)\distr\distrsolver.obj: $(SRC)\parse\vars.h
$(WRK)\distr\distrsolver.obj: $(SRC)\util\distr.h
$(WRK)\distr\distrsolver.obj: $(SRC)\util\format.h
$(WRK)\distr\distrsolver.obj: $(SRC)\util\git.h
$(WRK)\distr\distrsolver.obj: $(SRC)\util\logger.h
$(WRK)\distr\distrsolver.obj: $(SRC)\util\macros.h
$(WRK)\distr\distrsolver.obj: $(SRC)\util\metrics.h
$(WRK)\distr\distrsolver.obj: $(SRC)\util\module.h
$(WRK)\distr\distrsolver.obj: $(SRC)\util\mpi.h
$(WRK)\distr\distrsolver.obj: $(SRC)\util\subcomm.h
$(WRK)\distr\distrsolver.obj: $(SRC)\util\suspender.h
$(WRK)\distr\distrsolver.obj: $(SRC)\util\sysinfo.h
$(WRK)\distr\distrsolver.obj: $(SRC)\util\timer.h
$(WRK)\distr\distr.obj: $(SRC)\util\filesystem.h
$(WRK)\distr\distr.obj: $(SRC)\util\format.h
$(WRK)\distr\distr.obj: $(SRC)\util\logger.h
$(WRK)\distr\distr.obj: $(SRC)\util\macros.h
$(WRK)\distr\distr.obj: $(SRC)\util\metrics.h
$(WRK)\distr\distr.obj: $(SRC)\util\module.h
$(WRK)\distr\distr.obj: $(SRC)\util\mpi.h
$(WRK)\distr\distr.obj: $(SRC)\util\suspender.h
$(WRK)\distr\distr.obj: $(SRC)\util\sysinfo.h
$(WRK)\distr\distr.obj: $(SRC)\util\timer.h
$(WRK)\distr\local.obj: $(SRC)\distr\distr.h
$(WRK)\distr\local.obj: $(SRC)\distr\local.ipp
$(WRK)\distr\local.obj: $(SRC)\distr\reduce.h
$(WRK)\distr\local.obj: $(SRC)\dump\dumper.h
$(WRK)\distr\local.obj: $(SRC)\dump\dump.h
$(WRK)\distr\local.obj: $(SRC)\dump\output.h
$(WRK)\distr\local.obj: $(SRC)\dump\output_paraview.h
$(WRK)\distr\local.obj: $(SRC)\geom\blockface.h
$(WRK)\distr\local.obj: $(SRC)\geom\block.h
$(WRK)\distr\local.obj: $(SRC)\geom\dir.h
$(WRK)\distr\local.obj: $(SRC)\geom\field.h
$(WRK)\distr\local.obj: $(SRC)\geom\idx.h
$(WRK)\distr\local.obj: $(SRC)\geom\loop.h
$(WRK)\distr\local.obj: $(SRC)\geom\map.h
$(WRK)\distr\local.obj: $(SRC)\geom\mesh.h
$(WRK)\distr\local.obj: $(SRC)\geom\notation.h
$(WRK)\distr\local.obj: $(SRC)\geom\range.h
$(WRK)\distr\local.obj: $(SRC)\geom\rangein.h
$(WRK)\distr\local.obj: $(SRC)\geom\rangemulti.h
$(WRK)\distr\local.obj: $(SRC)\geom\transform.h
$(WRK)\distr\local.obj: $(SRC)\geom\vect.h
$(WRK)\distr\local.obj: $(SRC)\kernel\kernelmesh.h
$(WRK)\distr\local.obj: $(SRC)\parse\vars.h
$(WRK)\distr\local.obj: $(SRC)\util\logger.h
$(WRK)\distr\local.obj: $(SRC)\util\macros.h
$(WRK)\distr\local.obj: $(SRC)\util\metrics.h
$(WRK)\distr\local.obj: $(SRC)\util\module.h
$(WRK)\distr\local.obj: $(SRC)\util\mpi.h
$(WRK)\distr\local.obj: $(SRC)\util\suspender.h
$(WRK)\distr\local.obj: $(SRC)\util\sysinfo.h
$(WRK)\distr\local.obj: $(SRC)\util\timer.h
$(WRK)\distr\native.obj: $(SRC)\distr\comm_manager.h
$(WRK)\distr\native.obj: $(SRC)\distr\distr.h
$(WRK)\distr\native.obj: $(SRC)\distr\distrsolver.h
$(WRK)\distr\native.obj: $(SRC)\distr\native.ipp
$(WRK)\distr\native.obj: $(SRC)\distr\reduce.h
$(WRK)\distr\native.obj: $(SRC)\dump\dumper.h
$(WRK)\distr\native.obj: $(SRC)\dump\dump.h
$(WRK)\distr\native.obj: $(SRC)\geom\blockface.h
$(WRK)\distr\native.obj: $(SRC)\geom\block.h
$(WRK)\distr\native.obj: $(SRC)\geom\dir.h
$(WRK)\distr\native.obj: $(SRC)\geom\field.h
$(WRK)\distr\native.obj: $(SRC)\geom\idx.h
$(WRK)\distr\native.obj: $(SRC)\geom\loop.h
$(WRK)\distr\native.obj: $(SRC)\geom\map.h
$(WRK)\distr\native.obj: $(SRC)\geom\mesh.h
$(WRK)\distr\native.obj: $(SRC)\geom\notation.h
$(WRK)\distr\native.obj: $(SRC)\geom\range.h
$(WRK)\distr\native.obj: $(SRC)\geom\rangein.h
$(WRK)\distr\native.obj: $(SRC)\geom\rangemulti.h
$(WRK)\distr\native.obj: $(SRC)\geom\transform.h
$(WRK)\distr\native.obj: $(SRC)\geom\vect.h
$(WRK)\distr\native.obj: $(SRC)\kernel\kernelmesh.h
$(WRK)\distr\native.obj: $(SRC)\kernel\kernelmeshpar.h
$(WRK)\distr\native.obj: $(SRC)\parse\parser.h
$(WRK)\distr\native.obj: $(SRC)\parse\vars.h
$(WRK)\distr\native.obj: $(SRC)\util\distr.h
$(WRK)\distr\native.obj: $(SRC)\util\format.h
$(WRK)\distr\native.obj: $(SRC)\util\logger.h
$(WRK)\distr\native.obj: $(SRC)\util\macros.h
$(WRK)\distr\native.obj: $(SRC)\util\metrics.h
$(WRK)\distr\native.obj: $(SRC)\util\module.h
$(WRK)\distr\native.obj: $(SRC)\util\mpi.h
$(WRK)\distr\native.obj: $(SRC)\util\suspender.h
$(WRK)\distr\native.obj: $(SRC)\util\sysinfo.h
$(WRK)\distr\native.obj: $(SRC)\util\timer.h
$(WRK)\distr\report.obj: $(SRC)\distr\report.h
$(WRK)\distr\report.obj: $(SRC)\util\format.h
$(WRK)\dump\dump.obj: $(SRC)\distr\reduce.h
$(WRK)\dump\dumper.obj: $(SRC)\dump\dumper.h
$(WRK)\dump\dumper.obj: $(SRC)\parse\vars.h
$(WRK)\dump\dump.obj: $(SRC)\geom\blockface.h
$(WRK)\dump\dump.obj: $(SRC)\geom\block.h
$(WRK)\dump\dump.obj: $(SRC)\geom\dir.h
$(WRK)\dump\dump.obj: $(SRC)\geom\field.h
$(WRK)\dump\dump.obj: $(SRC)\geom\idx.h
$(WRK)\dump\dump.obj: $(SRC)\geom\loop.h
$(WRK)\dump\dump.obj: $(SRC)\geom\map.h
$(WRK)\dump\dump.obj: $(SRC)\geom\mesh.h
$(WRK)\dump\dump.obj: $(SRC)\geom\notation.h
$(WRK)\dump\dump.obj: $(SRC)\geom\range.h
$(WRK)\dump\dump.obj: $(SRC)\geom\rangein.h
$(WRK)\dump\dump.obj: $(SRC)\geom\rangemulti.h
$(WRK)\dump\dump.obj: $(SRC)\geom\transform.h
$(WRK)\dump\dump.obj: $(SRC)\geom\vect.h
$(WRK)\dump\dump.obj: $(SRC)\util\logger.h
$(WRK)\dump\dump.obj: $(SRC)\util\macros.h
$(WRK)\dump\dump.obj: $(SRC)\util\mpi.h
$(WRK)\dump\dump.obj: $(SRC)\util\suspender.h
$(WRK)\dump\hdf.obj: $(SRC)\distr\reduce.h
$(WRK)\dump\hdf.obj: $(SRC)\dump\hdf.h
$(WRK)\dump\hdf.obj: $(SRC)\dump\hdf.ipp
$(WRK)\dump\hdf.obj: $(SRC)\dump\hdf_nompi.ipp
$(WRK)\dump\hdf.obj: $(SRC)\geom\blockface.h
$(WRK)\dump\hdf.obj: $(SRC)\geom\block.h
$(WRK)\dump\hdf.obj: $(SRC)\geom\dir.h
$(WRK)\dump\hdf.obj: $(SRC)\geom\field.h
$(WRK)\dump\hdf.obj: $(SRC)\geom\idx.h
$(WRK)\dump\hdf.obj: $(SRC)\geom\loop.h
$(WRK)\dump\hdf.obj: $(SRC)\geom\map.h
$(WRK)\dump\hdf.obj: $(SRC)\geom\mesh.h
$(WRK)\dump\hdf.obj: $(SRC)\geom\notation.h
$(WRK)\dump\hdf.obj: $(SRC)\geom\range.h
$(WRK)\dump\hdf.obj: $(SRC)\geom\rangein.h
$(WRK)\dump\hdf.obj: $(SRC)\geom\rangemulti.h
$(WRK)\dump\hdf.obj: $(SRC)\geom\transform.h
$(WRK)\dump\hdf.obj: $(SRC)\geom\vect.h
$(WRK)\dump\hdf.obj: $(SRC)\util\logger.h
$(WRK)\dump\hdf.obj: $(SRC)\util\macros.h
$(WRK)\dump\hdf.obj: $(SRC)\util\mpi.h
$(WRK)\dump\hdf.obj: $(SRC)\util\suspender.h
$(WRK)\dump\raw.obj: $(SRC)\distr\reduce.h
$(WRK)\dump\raw.obj: $(SRC)\dump\raw.h
$(WRK)\dump\raw.obj: $(SRC)\dump\raw.ipp
$(WRK)\dump\raw.obj: $(SRC)\dump\xmf.h
$(WRK)\dump\raw.obj: $(SRC)\geom\blockface.h
$(WRK)\dump\raw.obj: $(SRC)\geom\block.h
$(WRK)\dump\raw.obj: $(SRC)\geom\dir.h
$(WRK)\dump\raw.obj: $(SRC)\geom\field.h
$(WRK)\dump\raw.obj: $(SRC)\geom\idx.h
$(WRK)\dump\raw.obj: $(SRC)\geom\loop.h
$(WRK)\dump\raw.obj: $(SRC)\geom\map.h
$(WRK)\dump\raw.obj: $(SRC)\geom\mesh.h
$(WRK)\dump\raw.obj: $(SRC)\geom\notation.h
$(WRK)\dump\raw.obj: $(SRC)\geom\range.h
$(WRK)\dump\raw.obj: $(SRC)\geom\rangein.h
$(WRK)\dump\raw.obj: $(SRC)\geom\rangemulti.h
$(WRK)\dump\raw.obj: $(SRC)\geom\transform.h
$(WRK)\dump\raw.obj: $(SRC)\geom\vect.h
$(WRK)\dump\raw.obj: $(SRC)\util\distr.h
$(WRK)\dump\raw.obj: $(SRC)\util\format.h
$(WRK)\dump\raw.obj: $(SRC)\util\logger.h
$(WRK)\dump\raw.obj: $(SRC)\util\macros.h
$(WRK)\dump\raw.obj: $(SRC)\util\mpi.h
$(WRK)\dump\raw.obj: $(SRC)\util\suspender.h
$(WRK)\dump\xmf.obj: $(SRC)\distr\reduce.h
$(WRK)\dump\xmf.obj: $(SRC)\dump\xmf.h
$(WRK)\dump\xmf.obj: $(SRC)\dump\xmf.ipp
$(WRK)\dump\xmf.obj: $(SRC)\geom\blockface.h
$(WRK)\dump\xmf.obj: $(SRC)\geom\block.h
$(WRK)\dump\xmf.obj: $(SRC)\geom\dir.h
$(WRK)\dump\xmf.obj: $(SRC)\geom\field.h
$(WRK)\dump\xmf.obj: $(SRC)\geom\idx.h
$(WRK)\dump\xmf.obj: $(SRC)\geom\loop.h
$(WRK)\dump\xmf.obj: $(SRC)\geom\map.h
$(WRK)\dump\xmf.obj: $(SRC)\geom\mesh.h
$(WRK)\dump\xmf.obj: $(SRC)\geom\notation.h
$(WRK)\dump\xmf.obj: $(SRC)\geom\range.h
$(WRK)\dump\xmf.obj: $(SRC)\geom\rangein.h
$(WRK)\dump\xmf.obj: $(SRC)\geom\rangemulti.h
$(WRK)\dump\xmf.obj: $(SRC)\geom\transform.h
$(WRK)\dump\xmf.obj: $(SRC)\geom\vect.h
$(WRK)\dump\xmf.obj: $(SRC)\parse\template.h
$(WRK)\dump\xmf.obj: $(SRC)\util\logger.h
$(WRK)\dump\xmf.obj: $(SRC)\util\macros.h
$(WRK)\dump\xmf.obj: $(SRC)\util\mpi.h
$(WRK)\dump\xmf.obj: $(SRC)\util\suspender.h
$(WRK)\func\init_contang.obj: $(SRC)\distr\reduce.h
$(WRK)\func\init_contang.obj: $(SRC)\func\init_contang.h
$(WRK)\func\init_contang.obj: $(SRC)\geom\blockface.h
$(WRK)\func\init_contang.obj: $(SRC)\geom\block.h
$(WRK)\func\init_contang.obj: $(SRC)\geom\dir.h
$(WRK)\func\init_contang.obj: $(SRC)\geom\field.h
$(WRK)\func\init_contang.obj: $(SRC)\geom\idx.h
$(WRK)\func\init_contang.obj: $(SRC)\geom\loop.h
$(WRK)\func\init_contang.obj: $(SRC)\geom\map.h
$(WRK)\func\init_contang.obj: $(SRC)\geom\mesh.h
$(WRK)\func\init_contang.obj: $(SRC)\geom\notation.h
$(WRK)\func\init_contang.obj: $(SRC)\geom\range.h
$(WRK)\func\init_contang.obj: $(SRC)\geom\rangein.h
$(WRK)\func\init_contang.obj: $(SRC)\geom\rangemulti.h
$(WRK)\func\init_contang.obj: $(SRC)\geom\transform.h
$(WRK)\func\init_contang.obj: $(SRC)\geom\vect.h
$(WRK)\func\init_contang.obj: $(SRC)\parse\config.h
$(WRK)\func\init_contang.obj: $(SRC)\parse\vars.h
$(WRK)\func\init_contang.obj: $(SRC)\util\logger.h
$(WRK)\func\init_contang.obj: $(SRC)\util\macros.h
$(WRK)\func\init_contang.obj: $(SRC)\util\module.h
$(WRK)\func\init_contang.obj: $(SRC)\util\mpi.h
$(WRK)\func\init_contang.obj: $(SRC)\util\suspender.h
$(WRK)\func\init.obj: $(SRC)\debug\isnan.h
$(WRK)\func\init.obj: $(SRC)\distr\reduce.h
$(WRK)\func\init.obj: $(SRC)\dump\hdf.h
$(WRK)\func\init.obj: $(SRC)\func\init_cl.h
$(WRK)\func\init.obj: $(SRC)\func\init.h
$(WRK)\func\init.obj: $(SRC)\func\init_sig.h
$(WRK)\func\init.obj: $(SRC)\func\init_u.h
$(WRK)\func\init.obj: $(SRC)\func\primlist.h
$(WRK)\func\init.obj: $(SRC)\geom\blockface.h
$(WRK)\func\init.obj: $(SRC)\geom\block.h
$(WRK)\func\init.obj: $(SRC)\geom\dir.h
$(WRK)\func\init.obj: $(SRC)\geom\field.h
$(WRK)\func\init.obj: $(SRC)\geom\filter.h
$(WRK)\func\init.obj: $(SRC)\geom\idx.h
$(WRK)\func\init.obj: $(SRC)\geom\loop.h
$(WRK)\func\init.obj: $(SRC)\geom\map.h
$(WRK)\func\init.obj: $(SRC)\geom\mesh.h
$(WRK)\func\init.obj: $(SRC)\geom\notation.h
$(WRK)\func\init.obj: $(SRC)\geom\range.h
$(WRK)\func\init.obj: $(SRC)\geom\rangein.h
$(WRK)\func\init.obj: $(SRC)\geom\rangemulti.h
$(WRK)\func\init.obj: $(SRC)\geom\transform.h
$(WRK)\func\init.obj: $(SRC)\geom\vect.h
$(WRK)\func\init.obj: $(SRC)\overlap\overlap.h
$(WRK)\func\init.obj: $(SRC)\parse\vars.h
$(WRK)\func\init.obj: $(SRC)\solver\embed.h
$(WRK)\func\init.obj: $(SRC)\solver\reconst.h
$(WRK)\func\init.obj: $(SRC)\util\format.h
$(WRK)\func\init.obj: $(SRC)\util\logger.h
$(WRK)\func\init.obj: $(SRC)\util\macros.h
$(WRK)\func\init.obj: $(SRC)\util\mpi.h
$(WRK)\func\init.obj: $(SRC)\util\suspender.h
$(WRK)\func\init_vel.obj: $(SRC)\distr\reduce.h
$(WRK)\func\init_vel.obj: $(SRC)\func\init_vel.h
$(WRK)\func\init_vel.obj: $(SRC)\geom\blockface.h
$(WRK)\func\init_vel.obj: $(SRC)\geom\block.h
$(WRK)\func\init_vel.obj: $(SRC)\geom\dir.h
$(WRK)\func\init_vel.obj: $(SRC)\geom\field.h
$(WRK)\func\init_vel.obj: $(SRC)\geom\idx.h
$(WRK)\func\init_vel.obj: $(SRC)\geom\loop.h
$(WRK)\func\init_vel.obj: $(SRC)\geom\map.h
$(WRK)\func\init_vel.obj: $(SRC)\geom\mesh.h
$(WRK)\func\init_vel.obj: $(SRC)\geom\notation.h
$(WRK)\func\init_vel.obj: $(SRC)\geom\range.h
$(WRK)\func\init_vel.obj: $(SRC)\geom\rangein.h
$(WRK)\func\init_vel.obj: $(SRC)\geom\rangemulti.h
$(WRK)\func\init_vel.obj: $(SRC)\geom\transform.h
$(WRK)\func\init_vel.obj: $(SRC)\geom\vect.h
$(WRK)\func\init_vel.obj: $(SRC)\parse\vars.h
$(WRK)\func\init_vel.obj: $(SRC)\util\logger.h
$(WRK)\func\init_vel.obj: $(SRC)\util\macros.h
$(WRK)\func\init_vel.obj: $(SRC)\util\module.h
$(WRK)\func\init_vel.obj: $(SRC)\util\mpi.h
$(WRK)\func\init_vel.obj: $(SRC)\util\suspender.h
$(WRK)\func\primlist.obj: $(SRC)\func\primlist.h
$(WRK)\func\primlist.obj: $(SRC)\func\primlist.ipp
$(WRK)\func\primlist.obj: $(SRC)\geom\vect.h
$(WRK)\func\primlist.obj: $(SRC)\util\format.h
$(WRK)\func\primlist.obj: $(SRC)\util\logger.h
$(WRK)\func\primlist.obj: $(SRC)\util\macros.h
$(WRK)\geom\mesh.obj: $(SRC)\distr\reduce.h
$(WRK)\geom\mesh.obj: $(SRC)\geom\blockface.h
$(WRK)\geom\mesh.obj: $(SRC)\geom\block.h
$(WRK)\geom\mesh.obj: $(SRC)\geom\dir.h
$(WRK)\geom\mesh.obj: $(SRC)\geom\field.h
$(WRK)\geom\mesh.obj: $(SRC)\geom\idx.h
$(WRK)\geom\mesh.obj: $(SRC)\geom\loop.h
$(WRK)\geom\mesh.obj: $(SRC)\geom\map.h
$(WRK)\geom\mesh.obj: $(SRC)\geom\mesh.h
$(WRK)\geom\mesh.obj: $(SRC)\geom\mesh.ipp
$(WRK)\geom\mesh.obj: $(SRC)\geom\notation.h
$(WRK)\geom\mesh.obj: $(SRC)\geom\range.h
$(WRK)\geom\mesh.obj: $(SRC)\geom\rangein.h
$(WRK)\geom\mesh.obj: $(SRC)\geom\rangemulti.h
$(WRK)\geom\mesh.obj: $(SRC)\geom\transform.h
$(WRK)\geom\mesh.obj: $(SRC)\geom\vect.h
$(WRK)\geom\mesh.obj: $(SRC)\util\logger.h
$(WRK)\geom\mesh.obj: $(SRC)\util\macros.h
$(WRK)\geom\mesh.obj: $(SRC)\util\mpi.h
$(WRK)\geom\mesh.obj: $(SRC)\util\suspender.h
$(WRK)\inside\bbox.obj: $(SRC)\inside\bbox.h
$(WRK)\inside\bbox.obj: $(SRC)\inside\err.h
$(WRK)\inside\bbox.obj: $(SRC)\inside\memory.h
$(WRK)\inside\err.obj: $(SRC)\inside\err.h
$(WRK)\inside\main.obj: $(SRC)\inside\bbox.h
$(WRK)\inside\main.obj: $(SRC)\inside\err.h
$(WRK)\inside\main.obj: $(SRC)\inside\inside.h
$(WRK)\inside\main.obj: $(SRC)\inside\memory.h
$(WRK)\inside\main.obj: $(SRC)\inside\predicate.h
$(WRK)\inside\memory.obj: $(SRC)\inside\memory.h
$(WRK)\inside\off.obj: $(SRC)\inside\err.h
$(WRK)\inside\off.obj: $(SRC)\inside\memory.h
$(WRK)\inside\ply.obj: $(SRC)\inside\err.h
$(WRK)\inside\ply.obj: $(SRC)\inside\memory.h
$(WRK)\inside\predicate.obj: $(SRC)\inside\err.h
$(WRK)\inside\predicate.obj: $(SRC)\inside\predicate.h
$(WRK)\inside\predicate.obj: $(SRC)\inside\predicate.inc
$(WRK)\inside\stl.obj: $(SRC)\inside\err.h
$(WRK)\inside\stl.obj: $(SRC)\inside\memory.h
$(WRK)\kernel\hydro.obj: $(SRC)\debug\isnan.h
$(WRK)\kernel\hydro.obj: $(SRC)\debug\linear.h
$(WRK)\kernel\hydro.obj: $(SRC)\distr\reduce.h
$(WRK)\kernel\hydro.obj: $(SRC)\dump\dumper.h
$(WRK)\kernel\hydro.obj: $(SRC)\dump\hdf.h
$(WRK)\kernel\hydro.obj: $(SRC)\func\init_contang.h
$(WRK)\kernel\hydro.obj: $(SRC)\func\init.h
$(WRK)\kernel\hydro.obj: $(SRC)\geom\blockface.h
$(WRK)\kernel\hydro.obj: $(SRC)\geom\block.h
$(WRK)\kernel\hydro.obj: $(SRC)\geom\dir.h
$(WRK)\kernel\hydro.obj: $(SRC)\geom\field.h
$(WRK)\kernel\hydro.obj: $(SRC)\geom\filter.h
$(WRK)\kernel\hydro.obj: $(SRC)\geom\idx.h
$(WRK)\kernel\hydro.obj: $(SRC)\geom\loop.h
$(WRK)\kernel\hydro.obj: $(SRC)\geom\map.h
$(WRK)\kernel\hydro.obj: $(SRC)\geom\mesh.h
$(WRK)\kernel\hydro.obj: $(SRC)\geom\notation.h
$(WRK)\kernel\hydro.obj: $(SRC)\geom\range.h
$(WRK)\kernel\hydro.obj: $(SRC)\geom\rangein.h
$(WRK)\kernel\hydro.obj: $(SRC)\geom\rangemulti.h
$(WRK)\kernel\hydro.obj: $(SRC)\geom\transform.h
$(WRK)\kernel\hydro.obj: $(SRC)\geom\vect.h
$(WRK)\kernel\hydro.obj: $(SRC)\hydro.h
$(WRK)\kernel\hydro.obj: $(SRC)\kernel\hydro.ipp
$(WRK)\kernel\hydro.obj: $(SRC)\kernel\kernelmesh.h
$(WRK)\kernel\hydro.obj: $(SRC)\kernel\kernelmeshpar.h
$(WRK)\kernel\hydro.obj: $(SRC)\linear\linear.h
$(WRK)\kernel\hydro.obj: $(SRC)\parse\curv.h
$(WRK)\kernel\hydro.obj: $(SRC)\parse\parser.h
$(WRK)\kernel\hydro.obj: $(SRC)\parse\proj.h
$(WRK)\kernel\hydro.obj: $(SRC)\parse\simple.h
$(WRK)\kernel\hydro.obj: $(SRC)\parse\solver.h
$(WRK)\kernel\hydro.obj: $(SRC)\parse\util.h
$(WRK)\kernel\hydro.obj: $(SRC)\parse\vars.h
$(WRK)\kernel\hydro.obj: $(SRC)\parse\vof.h
$(WRK)\kernel\hydro.obj: $(SRC)\solver\advection.h
$(WRK)\kernel\hydro.obj: $(SRC)\solver\approx2.h
$(WRK)\kernel\hydro.obj: $(SRC)\solver\approx_eb.h
$(WRK)\kernel\hydro.obj: $(SRC)\solver\approx.h
$(WRK)\kernel\hydro.obj: $(SRC)\solver\cond.h
$(WRK)\kernel\hydro.obj: $(SRC)\solver\convdiff.h
$(WRK)\kernel\hydro.obj: $(SRC)\solver\convdiffvg.h
$(WRK)\kernel\hydro.obj: $(SRC)\solver\convdiffv.h
$(WRK)\kernel\hydro.obj: $(SRC)\solver\curv.h
$(WRK)\kernel\hydro.obj: $(SRC)\solver\electro.h
$(WRK)\kernel\hydro.obj: $(SRC)\solver\embed.h
$(WRK)\kernel\hydro.obj: $(SRC)\solver\fluid_dummy.h
$(WRK)\kernel\hydro.obj: $(SRC)\solver\fluid.h
$(WRK)\kernel\hydro.obj: $(SRC)\solver\multi.h
$(WRK)\kernel\hydro.obj: $(SRC)\solver\normal.h
$(WRK)\kernel\hydro.obj: $(SRC)\solver\particles.h
$(WRK)\kernel\hydro.obj: $(SRC)\solver\partstr.h
$(WRK)\kernel\hydro.obj: $(SRC)\solver\partstrmeshm.h
$(WRK)\kernel\hydro.obj: $(SRC)\solver\proj.h
$(WRK)\kernel\hydro.obj: $(SRC)\solver\reconst.h
$(WRK)\kernel\hydro.obj: $(SRC)\solver\simple.h
$(WRK)\kernel\hydro.obj: $(SRC)\solver\solver.h
$(WRK)\kernel\hydro.obj: $(SRC)\solver\tracer.h
$(WRK)\kernel\hydro.obj: $(SRC)\solver\vof.h
$(WRK)\kernel\hydro.obj: $(SRC)\solver\vofm.h
$(WRK)\kernel\hydro.obj: $(SRC)\util\convdiff.h
$(WRK)\kernel\hydro.obj: $(SRC)\util\events.h
$(WRK)\kernel\hydro.obj: $(SRC)\util\filesystem.h
$(WRK)\kernel\hydro.obj: $(SRC)\util\format.h
$(WRK)\kernel\hydro.obj: $(SRC)\util\hydro.h
$(WRK)\kernel\hydro.obj: $(SRC)\util\linear.h
$(WRK)\kernel\hydro.obj: $(SRC)\util\logger.h
$(WRK)\kernel\hydro.obj: $(SRC)\util\macros.h
$(WRK)\kernel\hydro.obj: $(SRC)\util\metrics.h
$(WRK)\kernel\hydro.obj: $(SRC)\util\module.h
$(WRK)\kernel\hydro.obj: $(SRC)\util\mpi.h
$(WRK)\kernel\hydro.obj: $(SRC)\util\posthook.h
$(WRK)\kernel\hydro.obj: $(SRC)\util\stat.h
$(WRK)\kernel\hydro.obj: $(SRC)\util\suspender.h
$(WRK)\kernel\hydro.obj: $(SRC)\util\sysinfo.h
$(WRK)\kernel\hydro.obj: $(SRC)\util\timer.h
$(WRK)\linear\hypre.obj: $(SRC)\linear\hypre.h
$(WRK)\linear\hypresub.obj: $(SRC)\linear\hypre.h
$(WRK)\linear\hypresub.obj: $(SRC)\linear\hypresub.h
$(WRK)\linear\hypresub.obj: $(SRC)\util\histogram.h
$(WRK)\linear\hypresub.obj: $(SRC)\util\logger.h
$(WRK)\linear\hypresub.obj: $(SRC)\util\macros.h
$(WRK)\linear\hypresub.obj: $(SRC)\util\mpi.h
$(WRK)\linear\hypresub.obj: $(SRC)\util\subcomm.h
$(WRK)\linear\hypresub.obj: $(SRC)\util\timer.h
$(WRK)\linear\hypre.obj: $(SRC)\util\logger.h
$(WRK)\linear\hypre.obj: $(SRC)\util\macros.h
$(WRK)\linear\linear_amgx.obj: $(SRC)\debug\linear.h
$(WRK)\linear\linear_amgx.obj: $(SRC)\distr\commmap.h
$(WRK)\linear\linear_amgx.obj: $(SRC)\distr\distr.h
$(WRK)\linear\linear_amgx.obj: $(SRC)\distr\distrsolver.h
$(WRK)\linear\linear_amgx.obj: $(SRC)\distr\reduce.h
$(WRK)\linear\linear_amgx.obj: $(SRC)\dump\dumper.h
$(WRK)\linear\linear_amgx.obj: $(SRC)\dump\dump.h
$(WRK)\linear\linear_amgx.obj: $(SRC)\geom\blockface.h
$(WRK)\linear\linear_amgx.obj: $(SRC)\geom\block.h
$(WRK)\linear\linear_amgx.obj: $(SRC)\geom\dir.h
$(WRK)\linear\linear_amgx.obj: $(SRC)\geom\field.h
$(WRK)\linear\linear_amgx.obj: $(SRC)\geom\idx.h
$(WRK)\linear\linear_amgx.obj: $(SRC)\geom\loop.h
$(WRK)\linear\linear_amgx.obj: $(SRC)\geom\map.h
$(WRK)\linear\linear_amgx.obj: $(SRC)\geom\mesh.h
$(WRK)\linear\linear_amgx.obj: $(SRC)\geom\notation.h
$(WRK)\linear\linear_amgx.obj: $(SRC)\geom\range.h
$(WRK)\linear\linear_amgx.obj: $(SRC)\geom\rangein.h
$(WRK)\linear\linear_amgx.obj: $(SRC)\geom\rangemulti.h
$(WRK)\linear\linear_amgx.obj: $(SRC)\geom\transform.h
$(WRK)\linear\linear_amgx.obj: $(SRC)\geom\vect.h
$(WRK)\linear\linear_amgx.obj: $(SRC)\kernel\kernelmesh.h
$(WRK)\linear\linear_amgx.obj: $(SRC)\kernel\kernelmeshpar.h
$(WRK)\linear\linear_amgx.obj: $(SRC)\linear\amgx.h
$(WRK)\linear\linear_amgx.obj: $(SRC)\linear\linear_amgx.h
$(WRK)\linear\linear_amgx.obj: $(SRC)\linear\linear.h
$(WRK)\linear\linear_amgx.obj: $(SRC)\parse\parser.h
$(WRK)\linear\linear_amgx.obj: $(SRC)\parse\vars.h
$(WRK)\linear\linear_amgx.obj: $(SRC)\util\distr.h
$(WRK)\linear\linear_amgx.obj: $(SRC)\util\format.h
$(WRK)\linear\linear_amgx.obj: $(SRC)\util\logger.h
$(WRK)\linear\linear_amgx.obj: $(SRC)\util\macros.h
$(WRK)\linear\linear_amgx.obj: $(SRC)\util\metrics.h
$(WRK)\linear\linear_amgx.obj: $(SRC)\util\module.h
$(WRK)\linear\linear_amgx.obj: $(SRC)\util\mpi.h
$(WRK)\linear\linear_amgx.obj: $(SRC)\util\suspender.h
$(WRK)\linear\linear_amgx.obj: $(SRC)\util\sysinfo.h
$(WRK)\linear\linear_amgx.obj: $(SRC)\util\timer.h
$(WRK)\linear\linear.obj: $(SRC)\debug\linear.h
$(WRK)\linear\linear.obj: $(SRC)\distr\reduce.h
$(WRK)\linear\linear.obj: $(SRC)\geom\blockface.h
$(WRK)\linear\linear.obj: $(SRC)\geom\block.h
$(WRK)\linear\linear.obj: $(SRC)\geom\dir.h
$(WRK)\linear\linear.obj: $(SRC)\geom\field.h
$(WRK)\linear\linear.obj: $(SRC)\geom\idx.h
$(WRK)\linear\linear.obj: $(SRC)\geom\loop.h
$(WRK)\linear\linear.obj: $(SRC)\geom\map.h
$(WRK)\linear\linear.obj: $(SRC)\geom\mesh.h
$(WRK)\linear\linear.obj: $(SRC)\geom\notation.h
$(WRK)\linear\linear.obj: $(SRC)\geom\range.h
$(WRK)\linear\linear.obj: $(SRC)\geom\rangein.h
$(WRK)\linear\linear.obj: $(SRC)\geom\rangemulti.h
$(WRK)\linear\linear.obj: $(SRC)\geom\transform.h
$(WRK)\linear\linear.obj: $(SRC)\geom\vect.h
$(WRK)\linear\linear_hypre.obj: $(SRC)\debug\linear.h
$(WRK)\linear\linear_hypre.obj: $(SRC)\distr\reduce.h
$(WRK)\linear\linear_hypre.obj: $(SRC)\geom\blockface.h
$(WRK)\linear\linear_hypre.obj: $(SRC)\geom\block.h
$(WRK)\linear\linear_hypre.obj: $(SRC)\geom\dir.h
$(WRK)\linear\linear_hypre.obj: $(SRC)\geom\field.h
$(WRK)\linear\linear_hypre.obj: $(SRC)\geom\idx.h
$(WRK)\linear\linear_hypre.obj: $(SRC)\geom\loop.h
$(WRK)\linear\linear_hypre.obj: $(SRC)\geom\map.h
$(WRK)\linear\linear_hypre.obj: $(SRC)\geom\mesh.h
$(WRK)\linear\linear_hypre.obj: $(SRC)\geom\notation.h
$(WRK)\linear\linear_hypre.obj: $(SRC)\geom\range.h
$(WRK)\linear\linear_hypre.obj: $(SRC)\geom\rangein.h
$(WRK)\linear\linear_hypre.obj: $(SRC)\geom\rangemulti.h
$(WRK)\linear\linear_hypre.obj: $(SRC)\geom\transform.h
$(WRK)\linear\linear_hypre.obj: $(SRC)\geom\vect.h
$(WRK)\linear\linear_hypre.obj: $(SRC)\linear\hypre.h
$(WRK)\linear\linear_hypre.obj: $(SRC)\linear\linear.h
$(WRK)\linear\linear_hypre.obj: $(SRC)\linear\linear_hypre.h
$(WRK)\linear\linear_hypre.obj: $(SRC)\parse\vars.h
$(WRK)\linear\linear_hypre.obj: $(SRC)\util\logger.h
$(WRK)\linear\linear_hypre.obj: $(SRC)\util\macros.h
$(WRK)\linear\linear_hypre.obj: $(SRC)\util\module.h
$(WRK)\linear\linear_hypre.obj: $(SRC)\util\mpi.h
$(WRK)\linear\linear_hypre.obj: $(SRC)\util\suspender.h
$(WRK)\linear\linear.obj: $(SRC)\linear\linear.h
$(WRK)\linear\linear.obj: $(SRC)\linear\linear.ipp
$(WRK)\linear\linear.obj: $(SRC)\parse\vars.h
$(WRK)\linear\linear.obj: $(SRC)\util\logger.h
$(WRK)\linear\linear.obj: $(SRC)\util\macros.h
$(WRK)\linear\linear.obj: $(SRC)\util\module.h
$(WRK)\linear\linear.obj: $(SRC)\util\mpi.h
$(WRK)\linear\linear.obj: $(SRC)\util\suspender.h
$(WRK)\main.obj: $(SRC)\aphros_c.h
$(WRK)\march\main.obj: $(SRC)\march\march.h
$(WRK)\march\main.obj: $(SRC)\march\table.h
$(WRK)\overlap\overlap.obj: $(SRC)\geom\vect.h
$(WRK)\overlap\overlap.obj: $(SRC)\overlap\overlap.h
$(WRK)\overlap\overlap.obj: $(SRC)\overlap\overlap.hpp
$(WRK)\parse\argparse.obj: $(SRC)\parse\argparse.h
$(WRK)\parse\argparse.obj: $(SRC)\parse\vars.h
$(WRK)\parse\argparse.obj: $(SRC)\util\format.h
$(WRK)\parse\argparse.obj: $(SRC)\util\logger.h
$(WRK)\parse\argparse.obj: $(SRC)\util\macros.h
$(WRK)\parse\codeblocks.obj: $(SRC)\util\logger.h
$(WRK)\parse\codeblocks.obj: $(SRC)\util\macros.h
$(WRK)\parse\conf2py.obj: $(SRC)\parse\argparse.h
$(WRK)\parse\conf2py.obj: $(SRC)\parse\parser.h
$(WRK)\parse\conf2py.obj: $(SRC)\parse\vars.h
$(WRK)\parse\conf2py.obj: $(SRC)\util\format.h
$(WRK)\parse\conf2py.obj: $(SRC)\util\logger.h
$(WRK)\parse\conf2py.obj: $(SRC)\util\macros.h
$(WRK)\parse\parser.obj: $(SRC)\parse\parser.h
$(WRK)\parse\parser.obj: $(SRC)\parse\vars.h
$(WRK)\parse\parser.obj: $(SRC)\util\filesystem.h
$(WRK)\parse\parser.obj: $(SRC)\util\format.h
$(WRK)\parse\parser.obj: $(SRC)\util\logger.h
$(WRK)\parse\parser.obj: $(SRC)\util\macros.h
$(WRK)\parse\template.obj: $(SRC)\parse\template.h
$(WRK)\parse\template.obj: $(SRC)\util\logger.h
$(WRK)\parse\template.obj: $(SRC)\util\macros.h
$(WRK)\parse\vars.obj: $(SRC)\parse\vars.h
$(WRK)\parse\vars.obj: $(SRC)\util\logger.h
$(WRK)\parse\vars.obj: $(SRC)\util\macros.h
$(WRK)\solver\approx.obj: $(SRC)\debug\linear.h
$(WRK)\solver\approx.obj: $(SRC)\distr\reduce.h
$(WRK)\solver\approx_eb.obj: $(SRC)\debug\linear.h
$(WRK)\solver\approx_eb.obj: $(SRC)\distr\reduce.h
$(WRK)\solver\approx_eb.obj: $(SRC)\func\primlist.h
$(WRK)\solver\approx_eb.obj: $(SRC)\geom\blockface.h
$(WRK)\solver\approx_eb.obj: $(SRC)\geom\block.h
$(WRK)\solver\approx_eb.obj: $(SRC)\geom\dir.h
$(WRK)\solver\approx_eb.obj: $(SRC)\geom\field.h
$(WRK)\solver\approx_eb.obj: $(SRC)\geom\filter.h
$(WRK)\solver\approx_eb.obj: $(SRC)\geom\idx.h
$(WRK)\solver\approx_eb.obj: $(SRC)\geom\loop.h
$(WRK)\solver\approx_eb.obj: $(SRC)\geom\map.h
$(WRK)\solver\approx_eb.obj: $(SRC)\geom\mesh.h
$(WRK)\solver\approx_eb.obj: $(SRC)\geom\notation.h
$(WRK)\solver\approx_eb.obj: $(SRC)\geom\range.h
$(WRK)\solver\approx_eb.obj: $(SRC)\geom\rangein.h
$(WRK)\solver\approx_eb.obj: $(SRC)\geom\rangemulti.h
$(WRK)\solver\approx_eb.obj: $(SRC)\geom\transform.h
$(WRK)\solver\approx_eb.obj: $(SRC)\geom\vect.h
$(WRK)\solver\approx_eb.obj: $(SRC)\inside\inside.h
$(WRK)\solver\approx_eb.obj: $(SRC)\linear\linear.h
$(WRK)\solver\approx_eb.obj: $(SRC)\parse\vars.h
$(WRK)\solver\approx_eb.obj: $(SRC)\solver\approx_eb.h
$(WRK)\solver\approx_eb.obj: $(SRC)\solver\approx_eb.ipp
$(WRK)\solver\approx_eb.obj: $(SRC)\solver\approx.h
$(WRK)\solver\approx_eb.obj: $(SRC)\solver\cond.h
$(WRK)\solver\approx_eb.obj: $(SRC)\solver\embed.h
$(WRK)\solver\approx_eb.obj: $(SRC)\solver\reconst.h
$(WRK)\solver\approx_eb.obj: $(SRC)\solver\solver.h
$(WRK)\solver\approx_eb.obj: $(SRC)\util\format.h
$(WRK)\solver\approx_eb.obj: $(SRC)\util\logger.h
$(WRK)\solver\approx_eb.obj: $(SRC)\util\macros.h
$(WRK)\solver\approx_eb.obj: $(SRC)\util\module.h
$(WRK)\solver\approx_eb.obj: $(SRC)\util\mpi.h
$(WRK)\solver\approx_eb.obj: $(SRC)\util\suspender.h
$(WRK)\solver\approx.obj: $(SRC)\geom\blockface.h
$(WRK)\solver\approx.obj: $(SRC)\geom\block.h
$(WRK)\solver\approx.obj: $(SRC)\geom\dir.h
$(WRK)\solver\approx.obj: $(SRC)\geom\field.h
$(WRK)\solver\approx.obj: $(SRC)\geom\filter.h
$(WRK)\solver\approx.obj: $(SRC)\geom\idx.h
$(WRK)\solver\approx.obj: $(SRC)\geom\loop.h
$(WRK)\solver\approx.obj: $(SRC)\geom\map.h
$(WRK)\solver\approx.obj: $(SRC)\geom\mesh.h
$(WRK)\solver\approx.obj: $(SRC)\geom\notation.h
$(WRK)\solver\approx.obj: $(SRC)\geom\range.h
$(WRK)\solver\approx.obj: $(SRC)\geom\rangein.h
$(WRK)\solver\approx.obj: $(SRC)\geom\rangemulti.h
$(WRK)\solver\approx.obj: $(SRC)\geom\transform.h
$(WRK)\solver\approx.obj: $(SRC)\geom\vect.h
$(WRK)\solver\approx.obj: $(SRC)\linear\linear.h
$(WRK)\solver\approx.obj: $(SRC)\parse\vars.h
$(WRK)\solver\approx.obj: $(SRC)\solver\approx.h
$(WRK)\solver\approx.obj: $(SRC)\solver\approx.ipp
$(WRK)\solver\approx.obj: $(SRC)\solver\cond.h
$(WRK)\solver\approx.obj: $(SRC)\solver\embed.h
$(WRK)\solver\approx.obj: $(SRC)\solver\reconst.h
$(WRK)\solver\approx.obj: $(SRC)\solver\solver.h
$(WRK)\solver\approx.obj: $(SRC)\util\logger.h
$(WRK)\solver\approx.obj: $(SRC)\util\macros.h
$(WRK)\solver\approx.obj: $(SRC)\util\module.h
$(WRK)\solver\approx.obj: $(SRC)\util\mpi.h
$(WRK)\solver\approx.obj: $(SRC)\util\suspender.h
$(WRK)\solver\convdiffe.obj: $(SRC)\debug\isnan.h
$(WRK)\solver\convdiffe.obj: $(SRC)\debug\linear.h
$(WRK)\solver\convdiffe.obj: $(SRC)\distr\reduce.h
$(WRK)\solver\convdiffe.obj: $(SRC)\geom\blockface.h
$(WRK)\solver\convdiffe.obj: $(SRC)\geom\block.h
$(WRK)\solver\convdiffe.obj: $(SRC)\geom\dir.h
$(WRK)\solver\convdiffe.obj: $(SRC)\geom\field.h
$(WRK)\solver\convdiffe.obj: $(SRC)\geom\filter.h
$(WRK)\solver\convdiffe.obj: $(SRC)\geom\idx.h
$(WRK)\solver\convdiffe.obj: $(SRC)\geom\loop.h
$(WRK)\solver\convdiffe.obj: $(SRC)\geom\map.h
$(WRK)\solver\convdiffe.obj: $(SRC)\geom\mesh.h
$(WRK)\solver\convdiffe.obj: $(SRC)\geom\notation.h
$(WRK)\solver\convdiffe.obj: $(SRC)\geom\range.h
$(WRK)\solver\convdiffe.obj: $(SRC)\geom\rangein.h
$(WRK)\solver\convdiffe.obj: $(SRC)\geom\rangemulti.h
$(WRK)\solver\convdiffe.obj: $(SRC)\geom\transform.h
$(WRK)\solver\convdiffe.obj: $(SRC)\geom\vect.h
$(WRK)\solver\convdiffe.obj: $(SRC)\linear\linear.h
$(WRK)\solver\convdiffe.obj: $(SRC)\parse\vars.h
$(WRK)\solver\convdiffe.obj: $(SRC)\solver\approx_eb.h
$(WRK)\solver\convdiffe.obj: $(SRC)\solver\approx.h
$(WRK)\solver\convdiffe.obj: $(SRC)\solver\cond.h
$(WRK)\solver\convdiffe.obj: $(SRC)\solver\convdiffe.h
$(WRK)\solver\convdiffe.obj: $(SRC)\solver\convdiffe.ipp
$(WRK)\solver\convdiffe.obj: $(SRC)\solver\convdiff.h
$(WRK)\solver\convdiffe.obj: $(SRC)\solver\embed.h
$(WRK)\solver\convdiffe.obj: $(SRC)\solver\reconst.h
$(WRK)\solver\convdiffe.obj: $(SRC)\solver\solver.h
$(WRK)\solver\convdiffe.obj: $(SRC)\util\format.h
$(WRK)\solver\convdiffe.obj: $(SRC)\util\logger.h
$(WRK)\solver\convdiffe.obj: $(SRC)\util\macros.h
$(WRK)\solver\convdiffe.obj: $(SRC)\util\module.h
$(WRK)\solver\convdiffe.obj: $(SRC)\util\mpi.h
$(WRK)\solver\convdiffe.obj: $(SRC)\util\suspender.h
$(WRK)\solver\convdiffi.obj: $(SRC)\debug\isnan.h
$(WRK)\solver\convdiffi.obj: $(SRC)\debug\linear.h
$(WRK)\solver\convdiffi.obj: $(SRC)\distr\reduce.h
$(WRK)\solver\convdiffi.obj: $(SRC)\geom\blockface.h
$(WRK)\solver\convdiffi.obj: $(SRC)\geom\block.h
$(WRK)\solver\convdiffi.obj: $(SRC)\geom\dir.h
$(WRK)\solver\convdiffi.obj: $(SRC)\geom\field.h
$(WRK)\solver\convdiffi.obj: $(SRC)\geom\filter.h
$(WRK)\solver\convdiffi.obj: $(SRC)\geom\idx.h
$(WRK)\solver\convdiffi.obj: $(SRC)\geom\loop.h
$(WRK)\solver\convdiffi.obj: $(SRC)\geom\map.h
$(WRK)\solver\convdiffi.obj: $(SRC)\geom\mesh.h
$(WRK)\solver\convdiffi.obj: $(SRC)\geom\notation.h
$(WRK)\solver\convdiffi.obj: $(SRC)\geom\range.h
$(WRK)\solver\convdiffi.obj: $(SRC)\geom\rangein.h
$(WRK)\solver\convdiffi.obj: $(SRC)\geom\rangemulti.h
$(WRK)\solver\convdiffi.obj: $(SRC)\geom\transform.h
$(WRK)\solver\convdiffi.obj: $(SRC)\geom\vect.h
$(WRK)\solver\convdiffi.obj: $(SRC)\linear\linear.h
$(WRK)\solver\convdiffi.obj: $(SRC)\parse\vars.h
$(WRK)\solver\convdiffi.obj: $(SRC)\solver\approx_eb.h
$(WRK)\solver\convdiffi.obj: $(SRC)\solver\approx.h
$(WRK)\solver\convdiffi.obj: $(SRC)\solver\cond.h
$(WRK)\solver\convdiffi.obj: $(SRC)\solver\convdiff.h
$(WRK)\solver\convdiffi.obj: $(SRC)\solver\convdiffi.h
$(WRK)\solver\convdiffi.obj: $(SRC)\solver\convdiffi.ipp
$(WRK)\solver\convdiffi.obj: $(SRC)\solver\convdiffvg.h
$(WRK)\solver\convdiffi.obj: $(SRC)\solver\convdiffv.h
$(WRK)\solver\convdiffi.obj: $(SRC)\solver\embed.h
$(WRK)\solver\convdiffi.obj: $(SRC)\solver\reconst.h
$(WRK)\solver\convdiffi.obj: $(SRC)\solver\solver.h
$(WRK)\solver\convdiffi.obj: $(SRC)\util\convdiff.h
$(WRK)\solver\convdiffi.obj: $(SRC)\util\format.h
$(WRK)\solver\convdiffi.obj: $(SRC)\util\logger.h
$(WRK)\solver\convdiffi.obj: $(SRC)\util\macros.h
$(WRK)\solver\convdiffi.obj: $(SRC)\util\module.h
$(WRK)\solver\convdiffi.obj: $(SRC)\util\mpi.h
$(WRK)\solver\convdiffi.obj: $(SRC)\util\suspender.h
$(WRK)\solver\convdiffvg.obj: $(SRC)\debug\linear.h
$(WRK)\solver\convdiffvg.obj: $(SRC)\distr\reduce.h
$(WRK)\solver\convdiffvg.obj: $(SRC)\geom\blockface.h
$(WRK)\solver\convdiffvg.obj: $(SRC)\geom\block.h
$(WRK)\solver\convdiffvg.obj: $(SRC)\geom\dir.h
$(WRK)\solver\convdiffvg.obj: $(SRC)\geom\field.h
$(WRK)\solver\convdiffvg.obj: $(SRC)\geom\filter.h
$(WRK)\solver\convdiffvg.obj: $(SRC)\geom\idx.h
$(WRK)\solver\convdiffvg.obj: $(SRC)\geom\loop.h
$(WRK)\solver\convdiffvg.obj: $(SRC)\geom\map.h
$(WRK)\solver\convdiffvg.obj: $(SRC)\geom\mesh.h
$(WRK)\solver\convdiffvg.obj: $(SRC)\geom\notation.h
$(WRK)\solver\convdiffvg.obj: $(SRC)\geom\range.h
$(WRK)\solver\convdiffvg.obj: $(SRC)\geom\rangein.h
$(WRK)\solver\convdiffvg.obj: $(SRC)\geom\rangemulti.h
$(WRK)\solver\convdiffvg.obj: $(SRC)\geom\transform.h
$(WRK)\solver\convdiffvg.obj: $(SRC)\geom\vect.h
$(WRK)\solver\convdiffvg.obj: $(SRC)\linear\linear.h
$(WRK)\solver\convdiffvg.obj: $(SRC)\parse\vars.h
$(WRK)\solver\convdiffvg.obj: $(SRC)\solver\cond.h
$(WRK)\solver\convdiffvg.obj: $(SRC)\solver\convdiffe.h
$(WRK)\solver\convdiffvg.obj: $(SRC)\solver\convdiff.h
$(WRK)\solver\convdiffvg.obj: $(SRC)\solver\convdiffi.h
$(WRK)\solver\convdiffvg.obj: $(SRC)\solver\convdiffvg.h
$(WRK)\solver\convdiffvg.obj: $(SRC)\solver\convdiffvg.ipp
$(WRK)\solver\convdiffvg.obj: $(SRC)\solver\convdiffv.h
$(WRK)\solver\convdiffvg.obj: $(SRC)\solver\embed.h
$(WRK)\solver\convdiffvg.obj: $(SRC)\solver\reconst.h
$(WRK)\solver\convdiffvg.obj: $(SRC)\solver\solver.h
$(WRK)\solver\convdiffvg.obj: $(SRC)\util\convdiff.h
$(WRK)\solver\convdiffvg.obj: $(SRC)\util\logger.h
$(WRK)\solver\convdiffvg.obj: $(SRC)\util\macros.h
$(WRK)\solver\convdiffvg.obj: $(SRC)\util\metrics.h
$(WRK)\solver\convdiffvg.obj: $(SRC)\util\module.h
$(WRK)\solver\convdiffvg.obj: $(SRC)\util\mpi.h
$(WRK)\solver\convdiffvg.obj: $(SRC)\util\suspender.h
$(WRK)\solver\convdiffvg.obj: $(SRC)\util\timer.h
$(WRK)\solver\curv.obj: $(SRC)\debug\isnan.h
$(WRK)\solver\curv.obj: $(SRC)\distr\reduce.h
$(WRK)\solver\curv.obj: $(SRC)\dump\dumper.h
$(WRK)\solver\curv.obj: $(SRC)\geom\blockface.h
$(WRK)\solver\curv.obj: $(SRC)\geom\block.h
$(WRK)\solver\curv.obj: $(SRC)\geom\dir.h
$(WRK)\solver\curv.obj: $(SRC)\geom\field.h
$(WRK)\solver\curv.obj: $(SRC)\geom\filter.h
$(WRK)\solver\curv.obj: $(SRC)\geom\idx.h
$(WRK)\solver\curv.obj: $(SRC)\geom\loop.h
$(WRK)\solver\curv.obj: $(SRC)\geom\map.h
$(WRK)\solver\curv.obj: $(SRC)\geom\mesh.h
$(WRK)\solver\curv.obj: $(SRC)\geom\notation.h
$(WRK)\solver\curv.obj: $(SRC)\geom\range.h
$(WRK)\solver\curv.obj: $(SRC)\geom\rangein.h
$(WRK)\solver\curv.obj: $(SRC)\geom\rangemulti.h
$(WRK)\solver\curv.obj: $(SRC)\geom\transform.h
$(WRK)\solver\curv.obj: $(SRC)\geom\vect.h
$(WRK)\solver\curv.obj: $(SRC)\parse\vars.h
$(WRK)\solver\curv.obj: $(SRC)\solver\advection.h
$(WRK)\solver\curv.obj: $(SRC)\solver\approx.h
$(WRK)\solver\curv.obj: $(SRC)\solver\cond.h
$(WRK)\solver\curv.obj: $(SRC)\solver\curv.h
$(WRK)\solver\curv.obj: $(SRC)\solver\curv.ipp
$(WRK)\solver\curv.obj: $(SRC)\solver\embed.h
$(WRK)\solver\curv.obj: $(SRC)\solver\multi.h
$(WRK)\solver\curv.obj: $(SRC)\solver\normal.h
$(WRK)\solver\curv.obj: $(SRC)\solver\partstr.h
$(WRK)\solver\curv.obj: $(SRC)\solver\partstrmeshm.h
$(WRK)\solver\curv.obj: $(SRC)\solver\reconst.h
$(WRK)\solver\curv.obj: $(SRC)\solver\solver.h
$(WRK)\solver\curv.obj: $(SRC)\solver\trackerm.h
$(WRK)\solver\curv.obj: $(SRC)\solver\vof.h
$(WRK)\solver\curv.obj: $(SRC)\solver\vofm.h
$(WRK)\solver\curv.obj: $(SRC)\util\format.h
$(WRK)\solver\curv.obj: $(SRC)\util\logger.h
$(WRK)\solver\curv.obj: $(SRC)\util\macros.h
$(WRK)\solver\curv.obj: $(SRC)\util\mpi.h
$(WRK)\solver\curv.obj: $(SRC)\util\suspender.h
$(WRK)\solver\curv.obj: $(SRC)\util\vof.h
$(WRK)\solver\electro.obj: $(SRC)\debug\linear.h
$(WRK)\solver\electro.obj: $(SRC)\distr\reduce.h
$(WRK)\solver\electro.obj: $(SRC)\geom\blockface.h
$(WRK)\solver\electro.obj: $(SRC)\geom\block.h
$(WRK)\solver\electro.obj: $(SRC)\geom\dir.h
$(WRK)\solver\electro.obj: $(SRC)\geom\field.h
$(WRK)\solver\electro.obj: $(SRC)\geom\filter.h
$(WRK)\solver\electro.obj: $(SRC)\geom\idx.h
$(WRK)\solver\electro.obj: $(SRC)\geom\loop.h
$(WRK)\solver\electro.obj: $(SRC)\geom\map.h
$(WRK)\solver\electro.obj: $(SRC)\geom\mesh.h
$(WRK)\solver\electro.obj: $(SRC)\geom\notation.h
$(WRK)\solver\electro.obj: $(SRC)\geom\range.h
$(WRK)\solver\electro.obj: $(SRC)\geom\rangein.h
$(WRK)\solver\electro.obj: $(SRC)\geom\rangemulti.h
$(WRK)\solver\electro.obj: $(SRC)\geom\transform.h
$(WRK)\solver\electro.obj: $(SRC)\geom\vect.h
$(WRK)\solver\electro.obj: $(SRC)\linear\linear.h
$(WRK)\solver\electro.obj: $(SRC)\parse\vars.h
$(WRK)\solver\electro.obj: $(SRC)\solver\advection.h
$(WRK)\solver\electro.obj: $(SRC)\solver\approx_eb.h
$(WRK)\solver\electro.obj: $(SRC)\solver\approx.h
$(WRK)\solver\electro.obj: $(SRC)\solver\cond.h
$(WRK)\solver\electro.obj: $(SRC)\solver\electro.h
$(WRK)\solver\electro.obj: $(SRC)\solver\electro.ipp
$(WRK)\solver\electro.obj: $(SRC)\solver\embed.h
$(WRK)\solver\electro.obj: $(SRC)\solver\multi.h
$(WRK)\solver\electro.obj: $(SRC)\solver\pois.h
$(WRK)\solver\electro.obj: $(SRC)\solver\reconst.h
$(WRK)\solver\electro.obj: $(SRC)\solver\solver.h
$(WRK)\solver\electro.obj: $(SRC)\util\logger.h
$(WRK)\solver\electro.obj: $(SRC)\util\macros.h
$(WRK)\solver\electro.obj: $(SRC)\util\module.h
$(WRK)\solver\electro.obj: $(SRC)\util\mpi.h
$(WRK)\solver\electro.obj: $(SRC)\util\suspender.h
$(WRK)\solver\electro.obj: $(SRC)\util\vof.h
$(WRK)\solver\embed.obj: $(SRC)\debug\isnan.h
$(WRK)\solver\embed.obj: $(SRC)\distr\reduce.h
$(WRK)\solver\embed.obj: $(SRC)\dump\dumper.h
$(WRK)\solver\embed.obj: $(SRC)\dump\hdf.h
$(WRK)\solver\embed.obj: $(SRC)\dump\vtk.h
$(WRK)\solver\embed.obj: $(SRC)\func\init_u.h
$(WRK)\solver\embed.obj: $(SRC)\func\primlist.h
$(WRK)\solver\embed.obj: $(SRC)\geom\blockface.h
$(WRK)\solver\embed.obj: $(SRC)\geom\block.h
$(WRK)\solver\embed.obj: $(SRC)\geom\dir.h
$(WRK)\solver\embed.obj: $(SRC)\geom\field.h
$(WRK)\solver\embed.obj: $(SRC)\geom\filter.h
$(WRK)\solver\embed.obj: $(SRC)\geom\idx.h
$(WRK)\solver\embed.obj: $(SRC)\geom\loop.h
$(WRK)\solver\embed.obj: $(SRC)\geom\map.h
$(WRK)\solver\embed.obj: $(SRC)\geom\mesh.h
$(WRK)\solver\embed.obj: $(SRC)\geom\notation.h
$(WRK)\solver\embed.obj: $(SRC)\geom\range.h
$(WRK)\solver\embed.obj: $(SRC)\geom\rangein.h
$(WRK)\solver\embed.obj: $(SRC)\geom\rangemulti.h
$(WRK)\solver\embed.obj: $(SRC)\geom\transform.h
$(WRK)\solver\embed.obj: $(SRC)\geom\vect.h
$(WRK)\solver\embed.obj: $(SRC)\parse\vars.h
$(WRK)\solver\embed.obj: $(SRC)\solver\embed.h
$(WRK)\solver\embed.obj: $(SRC)\solver\embed.ipp
$(WRK)\solver\embed.obj: $(SRC)\solver\reconst.h
$(WRK)\solver\embed.obj: $(SRC)\util\format.h
$(WRK)\solver\embed.obj: $(SRC)\util\logger.h
$(WRK)\solver\embed.obj: $(SRC)\util\macros.h
$(WRK)\solver\embed.obj: $(SRC)\util\mpi.h
$(WRK)\solver\embed.obj: $(SRC)\util\suspender.h
$(WRK)\solver\fluid_dummy.obj: $(SRC)\debug\isnan.h
$(WRK)\solver\fluid_dummy.obj: $(SRC)\debug\linear.h
$(WRK)\solver\fluid_dummy.obj: $(SRC)\distr\reduce.h
$(WRK)\solver\fluid_dummy.obj: $(SRC)\geom\blockface.h
$(WRK)\solver\fluid_dummy.obj: $(SRC)\geom\block.h
$(WRK)\solver\fluid_dummy.obj: $(SRC)\geom\dir.h
$(WRK)\solver\fluid_dummy.obj: $(SRC)\geom\field.h
$(WRK)\solver\fluid_dummy.obj: $(SRC)\geom\filter.h
$(WRK)\solver\fluid_dummy.obj: $(SRC)\geom\idx.h
$(WRK)\solver\fluid_dummy.obj: $(SRC)\geom\loop.h
$(WRK)\solver\fluid_dummy.obj: $(SRC)\geom\map.h
$(WRK)\solver\fluid_dummy.obj: $(SRC)\geom\mesh.h
$(WRK)\solver\fluid_dummy.obj: $(SRC)\geom\notation.h
$(WRK)\solver\fluid_dummy.obj: $(SRC)\geom\range.h
$(WRK)\solver\fluid_dummy.obj: $(SRC)\geom\rangein.h
$(WRK)\solver\fluid_dummy.obj: $(SRC)\geom\rangemulti.h
$(WRK)\solver\fluid_dummy.obj: $(SRC)\geom\transform.h
$(WRK)\solver\fluid_dummy.obj: $(SRC)\geom\vect.h
$(WRK)\solver\fluid_dummy.obj: $(SRC)\linear\linear.h
$(WRK)\solver\fluid_dummy.obj: $(SRC)\parse\vars.h
$(WRK)\solver\fluid_dummy.obj: $(SRC)\solver\approx_eb.h
$(WRK)\solver\fluid_dummy.obj: $(SRC)\solver\approx.h
$(WRK)\solver\fluid_dummy.obj: $(SRC)\solver\cond.h
$(WRK)\solver\fluid_dummy.obj: $(SRC)\solver\embed.h
$(WRK)\solver\fluid_dummy.obj: $(SRC)\solver\fluid_dummy.h
$(WRK)\solver\fluid_dummy.obj: $(SRC)\solver\fluid_dummy.ipp
$(WRK)\solver\fluid_dummy.obj: $(SRC)\solver\fluid.h
$(WRK)\solver\fluid_dummy.obj: $(SRC)\solver\reconst.h
$(WRK)\solver\fluid_dummy.obj: $(SRC)\solver\solver.h
$(WRK)\solver\fluid_dummy.obj: $(SRC)\util\format.h
$(WRK)\solver\fluid_dummy.obj: $(SRC)\util\logger.h
$(WRK)\solver\fluid_dummy.obj: $(SRC)\util\macros.h
$(WRK)\solver\fluid_dummy.obj: $(SRC)\util\module.h
$(WRK)\solver\fluid_dummy.obj: $(SRC)\util\mpi.h
$(WRK)\solver\fluid_dummy.obj: $(SRC)\util\posthook.h
$(WRK)\solver\fluid_dummy.obj: $(SRC)\util\suspender.h
$(WRK)\solver\normal.obj: $(SRC)\debug\isnan.h
$(WRK)\solver\normal.obj: $(SRC)\distr\reduce.h
$(WRK)\solver\normal.obj: $(SRC)\geom\blockface.h
$(WRK)\solver\normal.obj: $(SRC)\geom\block.h
$(WRK)\solver\normal.obj: $(SRC)\geom\dir.h
$(WRK)\solver\normal.obj: $(SRC)\geom\field.h
$(WRK)\solver\normal.obj: $(SRC)\geom\filter.h
$(WRK)\solver\normal.obj: $(SRC)\geom\idx.h
$(WRK)\solver\normal.obj: $(SRC)\geom\loop.h
$(WRK)\solver\normal.obj: $(SRC)\geom\map.h
$(WRK)\solver\normal.obj: $(SRC)\geom\mesh.h
$(WRK)\solver\normal.obj: $(SRC)\geom\notation.h
$(WRK)\solver\normal.obj: $(SRC)\geom\range.h
$(WRK)\solver\normal.obj: $(SRC)\geom\rangein.h
$(WRK)\solver\normal.obj: $(SRC)\geom\rangemulti.h
$(WRK)\solver\normal.obj: $(SRC)\geom\transform.h
$(WRK)\solver\normal.obj: $(SRC)\geom\vect.h
$(WRK)\solver\normal.obj: $(SRC)\parse\vars.h
$(WRK)\solver\normal.obj: $(SRC)\solver\approx_eb.h
$(WRK)\solver\normal.obj: $(SRC)\solver\approx.h
$(WRK)\solver\normal.obj: $(SRC)\solver\cond.h
$(WRK)\solver\normal.obj: $(SRC)\solver\embed.h
$(WRK)\solver\normal.obj: $(SRC)\solver\normal.h
$(WRK)\solver\normal.obj: $(SRC)\solver\normal.ipp
$(WRK)\solver\normal.obj: $(SRC)\solver\reconst.h
$(WRK)\solver\normal.obj: $(SRC)\solver\solver.h
$(WRK)\solver\normal.obj: $(SRC)\util\avx.h
$(WRK)\solver\normal.obj: $(SRC)\util\format.h
$(WRK)\solver\normal.obj: $(SRC)\util\height.h
$(WRK)\solver\normal.obj: $(SRC)\util\logger.h
$(WRK)\solver\normal.obj: $(SRC)\util\macros.h
$(WRK)\solver\normal.obj: $(SRC)\util\mpi.h
$(WRK)\solver\normal.obj: $(SRC)\util\suspender.h
$(WRK)\solver\particles.obj: $(SRC)\distr\reduce.h
$(WRK)\solver\particles.obj: $(SRC)\geom\blockface.h
$(WRK)\solver\particles.obj: $(SRC)\geom\block.h
$(WRK)\solver\particles.obj: $(SRC)\geom\dir.h
$(WRK)\solver\particles.obj: $(SRC)\geom\field.h
$(WRK)\solver\particles.obj: $(SRC)\geom\filter.h
$(WRK)\solver\particles.obj: $(SRC)\geom\idx.h
$(WRK)\solver\particles.obj: $(SRC)\geom\loop.h
$(WRK)\solver\particles.obj: $(SRC)\geom\map.h
$(WRK)\solver\particles.obj: $(SRC)\geom\mesh.h
$(WRK)\solver\particles.obj: $(SRC)\geom\notation.h
$(WRK)\solver\particles.obj: $(SRC)\geom\range.h
$(WRK)\solver\particles.obj: $(SRC)\geom\rangein.h
$(WRK)\solver\particles.obj: $(SRC)\geom\rangemulti.h
$(WRK)\solver\particles.obj: $(SRC)\geom\transform.h
$(WRK)\solver\particles.obj: $(SRC)\geom\vect.h
$(WRK)\solver\particles.obj: $(SRC)\parse\vars.h
$(WRK)\solver\particles.obj: $(SRC)\solver\advection.h
$(WRK)\solver\particles.obj: $(SRC)\solver\approx_eb.h
$(WRK)\solver\particles.obj: $(SRC)\solver\approx.h
$(WRK)\solver\particles.obj: $(SRC)\solver\cond.h
$(WRK)\solver\particles.obj: $(SRC)\solver\embed.h
$(WRK)\solver\particles.obj: $(SRC)\solver\multi.h
$(WRK)\solver\particles.obj: $(SRC)\solver\particles.h
$(WRK)\solver\particles.obj: $(SRC)\solver\particles.ipp
$(WRK)\solver\particles.obj: $(SRC)\solver\reconst.h
$(WRK)\solver\particles.obj: $(SRC)\solver\solver.h
$(WRK)\solver\particles.obj: $(SRC)\util\logger.h
$(WRK)\solver\particles.obj: $(SRC)\util\macros.h
$(WRK)\solver\particles.obj: $(SRC)\util\mpi.h
$(WRK)\solver\particles.obj: $(SRC)\util\suspender.h
$(WRK)\solver\particles.obj: $(SRC)\util\vof.h
$(WRK)\solver\partstrmeshm.obj: $(SRC)\debug\isnan.h
$(WRK)\solver\partstrmeshm.obj: $(SRC)\distr\reduce.h
$(WRK)\solver\partstrmeshm.obj: $(SRC)\dump\dumper.h
$(WRK)\solver\partstrmeshm.obj: $(SRC)\dump\vtk.h
$(WRK)\solver\partstrmeshm.obj: $(SRC)\geom\blockface.h
$(WRK)\solver\partstrmeshm.obj: $(SRC)\geom\block.h
$(WRK)\solver\partstrmeshm.obj: $(SRC)\geom\dir.h
$(WRK)\solver\partstrmeshm.obj: $(SRC)\geom\field.h
$(WRK)\solver\partstrmeshm.obj: $(SRC)\geom\filter.h
$(WRK)\solver\partstrmeshm.obj: $(SRC)\geom\idx.h
$(WRK)\solver\partstrmeshm.obj: $(SRC)\geom\loop.h
$(WRK)\solver\partstrmeshm.obj: $(SRC)\geom\map.h
$(WRK)\solver\partstrmeshm.obj: $(SRC)\geom\mesh.h
$(WRK)\solver\partstrmeshm.obj: $(SRC)\geom\notation.h
$(WRK)\solver\partstrmeshm.obj: $(SRC)\geom\range.h
$(WRK)\solver\partstrmeshm.obj: $(SRC)\geom\rangein.h
$(WRK)\solver\partstrmeshm.obj: $(SRC)\geom\rangemulti.h
$(WRK)\solver\partstrmeshm.obj: $(SRC)\geom\transform.h
$(WRK)\solver\partstrmeshm.obj: $(SRC)\geom\vect.h
$(WRK)\solver\partstrmeshm.obj: $(SRC)\parse\vars.h
$(WRK)\solver\partstrmeshm.obj: $(SRC)\solver\advection.h
$(WRK)\solver\partstrmeshm.obj: $(SRC)\solver\cond.h
$(WRK)\solver\partstrmeshm.obj: $(SRC)\solver\embed.h
$(WRK)\solver\partstrmeshm.obj: $(SRC)\solver\multi.h
$(WRK)\solver\partstrmeshm.obj: $(SRC)\solver\partstr.h
$(WRK)\solver\partstrmeshm.obj: $(SRC)\solver\partstrmeshm.h
$(WRK)\solver\partstrmeshm.obj: $(SRC)\solver\partstrmeshm.ipp
$(WRK)\solver\partstrmeshm.obj: $(SRC)\solver\reconst.h
$(WRK)\solver\partstrmeshm.obj: $(SRC)\solver\solver.h
$(WRK)\solver\partstrmeshm.obj: $(SRC)\solver\vof.h
$(WRK)\solver\partstrmeshm.obj: $(SRC)\util\format.h
$(WRK)\solver\partstrmeshm.obj: $(SRC)\util\logger.h
$(WRK)\solver\partstrmeshm.obj: $(SRC)\util\macros.h
$(WRK)\solver\partstrmeshm.obj: $(SRC)\util\mpi.h
$(WRK)\solver\partstrmeshm.obj: $(SRC)\util\suspender.h
$(WRK)\solver\proj.obj: $(SRC)\debug\isnan.h
$(WRK)\solver\proj.obj: $(SRC)\debug\linear.h
$(WRK)\solver\proj.obj: $(SRC)\distr\reduce.h
$(WRK)\solver\proj_eb.obj: $(SRC)\debug\isnan.h
$(WRK)\solver\proj_eb.obj: $(SRC)\debug\linear.h
$(WRK)\solver\proj_eb.obj: $(SRC)\distr\reduce.h
$(WRK)\solver\proj_eb.obj: $(SRC)\geom\blockface.h
$(WRK)\solver\proj_eb.obj: $(SRC)\geom\block.h
$(WRK)\solver\proj_eb.obj: $(SRC)\geom\dir.h
$(WRK)\solver\proj_eb.obj: $(SRC)\geom\field.h
$(WRK)\solver\proj_eb.obj: $(SRC)\geom\filter.h
$(WRK)\solver\proj_eb.obj: $(SRC)\geom\idx.h
$(WRK)\solver\proj_eb.obj: $(SRC)\geom\loop.h
$(WRK)\solver\proj_eb.obj: $(SRC)\geom\map.h
$(WRK)\solver\proj_eb.obj: $(SRC)\geom\mesh.h
$(WRK)\solver\proj_eb.obj: $(SRC)\geom\notation.h
$(WRK)\solver\proj_eb.obj: $(SRC)\geom\range.h
$(WRK)\solver\proj_eb.obj: $(SRC)\geom\rangein.h
$(WRK)\solver\proj_eb.obj: $(SRC)\geom\rangemulti.h
$(WRK)\solver\proj_eb.obj: $(SRC)\geom\transform.h
$(WRK)\solver\proj_eb.obj: $(SRC)\geom\vect.h
$(WRK)\solver\proj_eb.obj: $(SRC)\linear\linear.h
$(WRK)\solver\proj_eb.obj: $(SRC)\parse\vars.h
$(WRK)\solver\proj_eb.obj: $(SRC)\solver\approx_eb.h
$(WRK)\solver\proj_eb.obj: $(SRC)\solver\approx.h
$(WRK)\solver\proj_eb.obj: $(SRC)\solver\cond.h
$(WRK)\solver\proj_eb.obj: $(SRC)\solver\convdiff.h
$(WRK)\solver\proj_eb.obj: $(SRC)\solver\convdiffvg.h
$(WRK)\solver\proj_eb.obj: $(SRC)\solver\convdiffv.h
$(WRK)\solver\proj_eb.obj: $(SRC)\solver\embed.h
$(WRK)\solver\proj_eb.obj: $(SRC)\solver\fluid.h
$(WRK)\solver\proj_eb.obj: $(SRC)\solver\proj.h
$(WRK)\solver\proj_eb.obj: $(SRC)\solver\proj.ipp
$(WRK)\solver\proj_eb.obj: $(SRC)\solver\reconst.h
$(WRK)\solver\proj_eb.obj: $(SRC)\solver\solver.h
$(WRK)\solver\proj_eb.obj: $(SRC)\util\convdiff.h
$(WRK)\solver\proj_eb.obj: $(SRC)\util\fluid.h
$(WRK)\solver\proj_eb.obj: $(SRC)\util\format.h
$(WRK)\solver\proj_eb.obj: $(SRC)\util\logger.h
$(WRK)\solver\proj_eb.obj: $(SRC)\util\macros.h
$(WRK)\solver\proj_eb.obj: $(SRC)\util\metrics.h
$(WRK)\solver\proj_eb.obj: $(SRC)\util\module.h
$(WRK)\solver\proj_eb.obj: $(SRC)\util\mpi.h
$(WRK)\solver\proj_eb.obj: $(SRC)\util\suspender.h
$(WRK)\solver\proj_eb.obj: $(SRC)\util\timer.h
$(WRK)\solver\proj.obj: $(SRC)\geom\blockface.h
$(WRK)\solver\proj.obj: $(SRC)\geom\block.h
$(WRK)\solver\proj.obj: $(SRC)\geom\dir.h
$(WRK)\solver\proj.obj: $(SRC)\geom\field.h
$(WRK)\solver\proj.obj: $(SRC)\geom\filter.h
$(WRK)\solver\proj.obj: $(SRC)\geom\idx.h
$(WRK)\solver\proj.obj: $(SRC)\geom\loop.h
$(WRK)\solver\proj.obj: $(SRC)\geom\map.h
$(WRK)\solver\proj.obj: $(SRC)\geom\mesh.h
$(WRK)\solver\proj.obj: $(SRC)\geom\notation.h
$(WRK)\solver\proj.obj: $(SRC)\geom\range.h
$(WRK)\solver\proj.obj: $(SRC)\geom\rangein.h
$(WRK)\solver\proj.obj: $(SRC)\geom\rangemulti.h
$(WRK)\solver\proj.obj: $(SRC)\geom\transform.h
$(WRK)\solver\proj.obj: $(SRC)\geom\vect.h
$(WRK)\solver\proj.obj: $(SRC)\linear\linear.h
$(WRK)\solver\proj.obj: $(SRC)\parse\vars.h
$(WRK)\solver\proj.obj: $(SRC)\solver\approx_eb.h
$(WRK)\solver\proj.obj: $(SRC)\solver\approx.h
$(WRK)\solver\proj.obj: $(SRC)\solver\cond.h
$(WRK)\solver\proj.obj: $(SRC)\solver\convdiff.h
$(WRK)\solver\proj.obj: $(SRC)\solver\convdiffvg.h
$(WRK)\solver\proj.obj: $(SRC)\solver\convdiffv.h
$(WRK)\solver\proj.obj: $(SRC)\solver\embed.h
$(WRK)\solver\proj.obj: $(SRC)\solver\fluid.h
$(WRK)\solver\proj.obj: $(SRC)\solver\proj.h
$(WRK)\solver\proj.obj: $(SRC)\solver\proj.ipp
$(WRK)\solver\proj.obj: $(SRC)\solver\reconst.h
$(WRK)\solver\proj.obj: $(SRC)\solver\solver.h
$(WRK)\solver\proj.obj: $(SRC)\util\convdiff.h
$(WRK)\solver\proj.obj: $(SRC)\util\fluid.h
$(WRK)\solver\proj.obj: $(SRC)\util\format.h
$(WRK)\solver\proj.obj: $(SRC)\util\logger.h
$(WRK)\solver\proj.obj: $(SRC)\util\macros.h
$(WRK)\solver\proj.obj: $(SRC)\util\metrics.h
$(WRK)\solver\proj.obj: $(SRC)\util\module.h
$(WRK)\solver\proj.obj: $(SRC)\util\mpi.h
$(WRK)\solver\proj.obj: $(SRC)\util\suspender.h
$(WRK)\solver\proj.obj: $(SRC)\util\timer.h
$(WRK)\solver\simple.obj: $(SRC)\debug\isnan.h
$(WRK)\solver\simple.obj: $(SRC)\debug\linear.h
$(WRK)\solver\simple.obj: $(SRC)\distr\reduce.h
$(WRK)\solver\simple.obj: $(SRC)\geom\blockface.h
$(WRK)\solver\simple.obj: $(SRC)\geom\block.h
$(WRK)\solver\simple.obj: $(SRC)\geom\dir.h
$(WRK)\solver\simple.obj: $(SRC)\geom\field.h
$(WRK)\solver\simple.obj: $(SRC)\geom\filter.h
$(WRK)\solver\simple.obj: $(SRC)\geom\idx.h
$(WRK)\solver\simple.obj: $(SRC)\geom\loop.h
$(WRK)\solver\simple.obj: $(SRC)\geom\map.h
$(WRK)\solver\simple.obj: $(SRC)\geom\mesh.h
$(WRK)\solver\simple.obj: $(SRC)\geom\notation.h
$(WRK)\solver\simple.obj: $(SRC)\geom\range.h
$(WRK)\solver\simple.obj: $(SRC)\geom\rangein.h
$(WRK)\solver\simple.obj: $(SRC)\geom\rangemulti.h
$(WRK)\solver\simple.obj: $(SRC)\geom\transform.h
$(WRK)\solver\simple.obj: $(SRC)\geom\vect.h
$(WRK)\solver\simple.obj: $(SRC)\linear\linear.h
$(WRK)\solver\simple.obj: $(SRC)\parse\vars.h
$(WRK)\solver\simple.obj: $(SRC)\solver\approx_eb.h
$(WRK)\solver\simple.obj: $(SRC)\solver\approx.h
$(WRK)\solver\simple.obj: $(SRC)\solver\cond.h
$(WRK)\solver\simple.obj: $(SRC)\solver\convdiff.h
$(WRK)\solver\simple.obj: $(SRC)\solver\convdiffvg.h
$(WRK)\solver\simple.obj: $(SRC)\solver\convdiffv.h
$(WRK)\solver\simple.obj: $(SRC)\solver\embed.h
$(WRK)\solver\simple.obj: $(SRC)\solver\fluid.h
$(WRK)\solver\simple.obj: $(SRC)\solver\reconst.h
$(WRK)\solver\simple.obj: $(SRC)\solver\simple.h
$(WRK)\solver\simple.obj: $(SRC)\solver\simple.ipp
$(WRK)\solver\simple.obj: $(SRC)\solver\solver.h
$(WRK)\solver\simple.obj: $(SRC)\util\convdiff.h
$(WRK)\solver\simple.obj: $(SRC)\util\fluid.h
$(WRK)\solver\simple.obj: $(SRC)\util\format.h
$(WRK)\solver\simple.obj: $(SRC)\util\logger.h
$(WRK)\solver\simple.obj: $(SRC)\util\macros.h
$(WRK)\solver\simple.obj: $(SRC)\util\metrics.h
$(WRK)\solver\simple.obj: $(SRC)\util\module.h
$(WRK)\solver\simple.obj: $(SRC)\util\mpi.h
$(WRK)\solver\simple.obj: $(SRC)\util\suspender.h
$(WRK)\solver\simple.obj: $(SRC)\util\timer.h
$(WRK)\solver\solver.obj: $(SRC)\solver\solver.h
$(WRK)\solver\solver.obj: $(SRC)\util\logger.h
$(WRK)\solver\solver.obj: $(SRC)\util\macros.h
$(WRK)\solver\tracer.obj: $(SRC)\distr\reduce.h
$(WRK)\solver\tracer.obj: $(SRC)\geom\blockface.h
$(WRK)\solver\tracer.obj: $(SRC)\geom\block.h
$(WRK)\solver\tracer.obj: $(SRC)\geom\dir.h
$(WRK)\solver\tracer.obj: $(SRC)\geom\field.h
$(WRK)\solver\tracer.obj: $(SRC)\geom\filter.h
$(WRK)\solver\tracer.obj: $(SRC)\geom\idx.h
$(WRK)\solver\tracer.obj: $(SRC)\geom\loop.h
$(WRK)\solver\tracer.obj: $(SRC)\geom\map.h
$(WRK)\solver\tracer.obj: $(SRC)\geom\mesh.h
$(WRK)\solver\tracer.obj: $(SRC)\geom\notation.h
$(WRK)\solver\tracer.obj: $(SRC)\geom\range.h
$(WRK)\solver\tracer.obj: $(SRC)\geom\rangein.h
$(WRK)\solver\tracer.obj: $(SRC)\geom\rangemulti.h
$(WRK)\solver\tracer.obj: $(SRC)\geom\transform.h
$(WRK)\solver\tracer.obj: $(SRC)\geom\vect.h
$(WRK)\solver\tracer.obj: $(SRC)\parse\vars.h
$(WRK)\solver\tracer.obj: $(SRC)\solver\advection.h
$(WRK)\solver\tracer.obj: $(SRC)\solver\approx_eb.h
$(WRK)\solver\tracer.obj: $(SRC)\solver\approx.h
$(WRK)\solver\tracer.obj: $(SRC)\solver\cond.h
$(WRK)\solver\tracer.obj: $(SRC)\solver\embed.h
$(WRK)\solver\tracer.obj: $(SRC)\solver\multi.h
$(WRK)\solver\tracer.obj: $(SRC)\solver\reconst.h
$(WRK)\solver\tracer.obj: $(SRC)\solver\solver.h
$(WRK)\solver\tracer.obj: $(SRC)\solver\tracer.h
$(WRK)\solver\tracer.obj: $(SRC)\solver\tracer.ipp
$(WRK)\solver\tracer.obj: $(SRC)\util\logger.h
$(WRK)\solver\tracer.obj: $(SRC)\util\macros.h
$(WRK)\solver\tracer.obj: $(SRC)\util\mpi.h
$(WRK)\solver\tracer.obj: $(SRC)\util\suspender.h
$(WRK)\solver\tracer.obj: $(SRC)\util\vof.h
$(WRK)\solver\vof.obj: $(SRC)\debug\isnan.h
$(WRK)\solver\vof.obj: $(SRC)\debug\linear.h
$(WRK)\solver\vof.obj: $(SRC)\distr\reduce.h
$(WRK)\solver\vof.obj: $(SRC)\geom\blockface.h
$(WRK)\solver\vof.obj: $(SRC)\geom\block.h
$(WRK)\solver\vof.obj: $(SRC)\geom\dir.h
$(WRK)\solver\vof.obj: $(SRC)\geom\field.h
$(WRK)\solver\vof.obj: $(SRC)\geom\filter.h
$(WRK)\solver\vof.obj: $(SRC)\geom\idx.h
$(WRK)\solver\vof.obj: $(SRC)\geom\loop.h
$(WRK)\solver\vof.obj: $(SRC)\geom\map.h
$(WRK)\solver\vof.obj: $(SRC)\geom\mesh.h
$(WRK)\solver\vof.obj: $(SRC)\geom\notation.h
$(WRK)\solver\vof.obj: $(SRC)\geom\range.h
$(WRK)\solver\vof.obj: $(SRC)\geom\rangein.h
$(WRK)\solver\vof.obj: $(SRC)\geom\rangemulti.h
$(WRK)\solver\vof.obj: $(SRC)\geom\transform.h
$(WRK)\solver\vof.obj: $(SRC)\geom\vect.h
$(WRK)\solver\vof.obj: $(SRC)\linear\linear.h
$(WRK)\solver\vofm.obj: $(SRC)\debug\isnan.h
$(WRK)\solver\vofm.obj: $(SRC)\debug\linear.h
$(WRK)\solver\vofm.obj: $(SRC)\distr\reduce.h
$(WRK)\solver\vofm.obj: $(SRC)\dump\hdf.h
$(WRK)\solver\vofm.obj: $(SRC)\geom\blockface.h
$(WRK)\solver\vofm.obj: $(SRC)\geom\block.h
$(WRK)\solver\vofm.obj: $(SRC)\geom\dir.h
$(WRK)\solver\vofm.obj: $(SRC)\geom\field.h
$(WRK)\solver\vofm.obj: $(SRC)\geom\filter.h
$(WRK)\solver\vofm.obj: $(SRC)\geom\idx.h
$(WRK)\solver\vofm.obj: $(SRC)\geom\loop.h
$(WRK)\solver\vofm.obj: $(SRC)\geom\map.h
$(WRK)\solver\vofm.obj: $(SRC)\geom\mesh.h
$(WRK)\solver\vofm.obj: $(SRC)\geom\notation.h
$(WRK)\solver\vofm.obj: $(SRC)\geom\range.h
$(WRK)\solver\vofm.obj: $(SRC)\geom\rangein.h
$(WRK)\solver\vofm.obj: $(SRC)\geom\rangemulti.h
$(WRK)\solver\vofm.obj: $(SRC)\geom\transform.h
$(WRK)\solver\vofm.obj: $(SRC)\geom\vect.h
$(WRK)\solver\vofm.obj: $(SRC)\linear\linear.h
$(WRK)\solver\vofm.obj: $(SRC)\parse\vars.h
$(WRK)\solver\vofm.obj: $(SRC)\solver\advection.h
$(WRK)\solver\vofm.obj: $(SRC)\solver\approx_eb.h
$(WRK)\solver\vofm.obj: $(SRC)\solver\approx.h
$(WRK)\solver\vofm.obj: $(SRC)\solver\cond.h
$(WRK)\solver\vofm.obj: $(SRC)\solver\convdiff.h
$(WRK)\solver\vofm.obj: $(SRC)\solver\convdiffvg.h
$(WRK)\solver\vofm.obj: $(SRC)\solver\convdiffv.h
$(WRK)\solver\vofm.obj: $(SRC)\solver\embed.h
$(WRK)\solver\vofm.obj: $(SRC)\solver\multi.h
$(WRK)\solver\vofm.obj: $(SRC)\solver\normal.h
$(WRK)\solver\vofm.obj: $(SRC)\solver\reconst.h
$(WRK)\solver\vofm.obj: $(SRC)\solver\solver.h
$(WRK)\solver\vofm.obj: $(SRC)\solver\trackerm.h
$(WRK)\solver\vofm.obj: $(SRC)\solver\vof.h
$(WRK)\solver\vofm.obj: $(SRC)\solver\vofm.h
$(WRK)\solver\vofm.obj: $(SRC)\solver\vofm.ipp
$(WRK)\solver\vofm.obj: $(SRC)\util\convdiff.h
$(WRK)\solver\vofm.obj: $(SRC)\util\filesystem.h
$(WRK)\solver\vofm.obj: $(SRC)\util\format.h
$(WRK)\solver\vofm.obj: $(SRC)\util\logger.h
$(WRK)\solver\vofm.obj: $(SRC)\util\macros.h
$(WRK)\solver\vofm.obj: $(SRC)\util\module.h
$(WRK)\solver\vofm.obj: $(SRC)\util\mpi.h
$(WRK)\solver\vofm.obj: $(SRC)\util\suspender.h
$(WRK)\solver\vofm.obj: $(SRC)\util\vof.h
$(WRK)\solver\vof.obj: $(SRC)\parse\vars.h
$(WRK)\solver\vof.obj: $(SRC)\solver\advection.h
$(WRK)\solver\vof.obj: $(SRC)\solver\approx_eb.h
$(WRK)\solver\vof.obj: $(SRC)\solver\approx.h
$(WRK)\solver\vof.obj: $(SRC)\solver\cond.h
$(WRK)\solver\vof.obj: $(SRC)\solver\convdiff.h
$(WRK)\solver\vof.obj: $(SRC)\solver\convdiffvg.h
$(WRK)\solver\vof.obj: $(SRC)\solver\convdiffv.h
$(WRK)\solver\vof.obj: $(SRC)\solver\embed.h
$(WRK)\solver\vof.obj: $(SRC)\solver\multi.h
$(WRK)\solver\vof.obj: $(SRC)\solver\normal.h
$(WRK)\solver\vof.obj: $(SRC)\solver\reconst.h
$(WRK)\solver\vof.obj: $(SRC)\solver\solver.h
$(WRK)\solver\vof.obj: $(SRC)\solver\trackerm.h
$(WRK)\solver\vof.obj: $(SRC)\solver\vof.h
$(WRK)\solver\vof.obj: $(SRC)\solver\vof.ipp
$(WRK)\solver\vof.obj: $(SRC)\util\convdiff.h
$(WRK)\solver\vof.obj: $(SRC)\util\format.h
$(WRK)\solver\vof.obj: $(SRC)\util\logger.h
$(WRK)\solver\vof.obj: $(SRC)\util\macros.h
$(WRK)\solver\vof.obj: $(SRC)\util\module.h
$(WRK)\solver\vof.obj: $(SRC)\util\mpi.h
$(WRK)\solver\vof.obj: $(SRC)\util\suspender.h
$(WRK)\solver\vof.obj: $(SRC)\util\vof.h
$(WRK)\util\convdiff.obj: $(SRC)\debug\linear.h
$(WRK)\util\convdiff.obj: $(SRC)\distr\reduce.h
$(WRK)\util\convdiff.obj: $(SRC)\geom\blockface.h
$(WRK)\util\convdiff.obj: $(SRC)\geom\block.h
$(WRK)\util\convdiff.obj: $(SRC)\geom\dir.h
$(WRK)\util\convdiff.obj: $(SRC)\geom\field.h
$(WRK)\util\convdiff.obj: $(SRC)\geom\filter.h
$(WRK)\util\convdiff.obj: $(SRC)\geom\idx.h
$(WRK)\util\convdiff.obj: $(SRC)\geom\loop.h
$(WRK)\util\convdiff.obj: $(SRC)\geom\map.h
$(WRK)\util\convdiff.obj: $(SRC)\geom\mesh.h
$(WRK)\util\convdiff.obj: $(SRC)\geom\notation.h
$(WRK)\util\convdiff.obj: $(SRC)\geom\range.h
$(WRK)\util\convdiff.obj: $(SRC)\geom\rangein.h
$(WRK)\util\convdiff.obj: $(SRC)\geom\rangemulti.h
$(WRK)\util\convdiff.obj: $(SRC)\geom\transform.h
$(WRK)\util\convdiff.obj: $(SRC)\geom\vect.h
$(WRK)\util\convdiff.obj: $(SRC)\linear\linear.h
$(WRK)\util\convdiff.obj: $(SRC)\parse\vars.h
$(WRK)\util\convdiff.obj: $(SRC)\solver\cond.h
$(WRK)\util\convdiff.obj: $(SRC)\solver\convdiffe.h
$(WRK)\util\convdiff.obj: $(SRC)\solver\convdiff.h
$(WRK)\util\convdiff.obj: $(SRC)\solver\convdiffi.h
$(WRK)\util\convdiff.obj: $(SRC)\solver\convdiffvg.h
$(WRK)\util\convdiff.obj: $(SRC)\solver\convdiffv.h
$(WRK)\util\convdiff.obj: $(SRC)\solver\embed.h
$(WRK)\util\convdiff.obj: $(SRC)\solver\reconst.h
$(WRK)\util\convdiff.obj: $(SRC)\solver\solver.h
$(WRK)\util\convdiff.obj: $(SRC)\util\convdiff.h
$(WRK)\util\convdiff.obj: $(SRC)\util\logger.h
$(WRK)\util\convdiff.obj: $(SRC)\util\macros.h
$(WRK)\util\convdiff.obj: $(SRC)\util\module.h
$(WRK)\util\convdiff.obj: $(SRC)\util\mpi.h
$(WRK)\util\convdiff.obj: $(SRC)\util\suspender.h
$(WRK)\util\distr.obj: $(SRC)\geom\dir.h
$(WRK)\util\distr.obj: $(SRC)\geom\idx.h
$(WRK)\util\distr.obj: $(SRC)\geom\range.h
$(WRK)\util\distr.obj: $(SRC)\geom\vect.h
$(WRK)\util\distr.obj: $(SRC)\util\distr.h
$(WRK)\util\distr.obj: $(SRC)\util\distr.ipp
$(WRK)\util\distr.obj: $(SRC)\util\format.h
$(WRK)\util\distr.obj: $(SRC)\util\logger.h
$(WRK)\util\distr.obj: $(SRC)\util\macros.h
$(WRK)\util\events.obj: $(SRC)\parse\parser.h
$(WRK)\util\events.obj: $(SRC)\parse\vars.h
$(WRK)\util\events.obj: $(SRC)\util\events.h
$(WRK)\util\events.obj: $(SRC)\util\logger.h
$(WRK)\util\events.obj: $(SRC)\util\macros.h
$(WRK)\util\filesystem.obj: $(SRC)\util\filesystem.h
$(WRK)\util\filesystem.obj: $(SRC)\util\logger.h
$(WRK)\util\filesystem.obj: $(SRC)\util\macros.h
$(WRK)\util\filesystem.obj: $(SRC)\util\system.h
$(WRK)\util\fixed_allocator.obj: $(SRC)\util\fixed_allocator.h
$(WRK)\util\format.obj: $(SRC)\util\format.h
$(WRK)\util\format.obj: $(SRC)\util\logger.h
$(WRK)\util\format.obj: $(SRC)\util\macros.h
$(WRK)\util\git.obj: $(SRC)\util\git.h
$(WRK)\util\histogram.obj: $(SRC)\util\histogram.h
$(WRK)\util\histogram.obj: $(SRC)\util\logger.h
$(WRK)\util\histogram.obj: $(SRC)\util\macros.h
$(WRK)\util\histogram.obj: $(SRC)\util\mpi.h
$(WRK)\util\histogram.obj: $(SRC)\util\timer.h
$(WRK)\util\hydro.obj: $(SRC)\debug\isnan.h
$(WRK)\util\hydro.obj: $(SRC)\debug\linear.h
$(WRK)\util\hydro.obj: $(SRC)\distr\reduce.h
$(WRK)\util\hydro.obj: $(SRC)\dump\dumper.h
$(WRK)\util\hydro.obj: $(SRC)\dump\hdf.h
$(WRK)\util\hydro.obj: $(SRC)\dump\vtk.h
$(WRK)\util\hydro.obj: $(SRC)\func\init_bc.h
$(WRK)\util\hydro.obj: $(SRC)\func\init_u.h
$(WRK)\util\hydro.obj: $(SRC)\func\init_vel.h
$(WRK)\util\hydro.obj: $(SRC)\func\primlist.h
$(WRK)\util\hydro.obj: $(SRC)\geom\blockface.h
$(WRK)\util\hydro.obj: $(SRC)\geom\block.h
$(WRK)\util\hydro.obj: $(SRC)\geom\dir.h
$(WRK)\util\hydro.obj: $(SRC)\geom\field.h
$(WRK)\util\hydro.obj: $(SRC)\geom\filter.h
$(WRK)\util\hydro.obj: $(SRC)\geom\idx.h
$(WRK)\util\hydro.obj: $(SRC)\geom\loop.h
$(WRK)\util\hydro.obj: $(SRC)\geom\map.h
$(WRK)\util\hydro.obj: $(SRC)\geom\mesh.h
$(WRK)\util\hydro.obj: $(SRC)\geom\notation.h
$(WRK)\util\hydro.obj: $(SRC)\geom\range.h
$(WRK)\util\hydro.obj: $(SRC)\geom\rangein.h
$(WRK)\util\hydro.obj: $(SRC)\geom\rangemulti.h
$(WRK)\util\hydro.obj: $(SRC)\geom\transform.h
$(WRK)\util\hydro.obj: $(SRC)\geom\vect.h
$(WRK)\util\hydro.obj: $(SRC)\hydro.h
$(WRK)\util\hydro.obj: $(SRC)\linear\linear.h
$(WRK)\util\hydro.obj: $(SRC)\parse\codeblocks.h
$(WRK)\util\hydro.obj: $(SRC)\parse\util.h
$(WRK)\util\hydro.obj: $(SRC)\parse\vars.h
$(WRK)\util\hydro.obj: $(SRC)\solver\advection.h
$(WRK)\util\hydro.obj: $(SRC)\solver\approx_eb.h
$(WRK)\util\hydro.obj: $(SRC)\solver\approx.h
$(WRK)\util\hydro.obj: $(SRC)\solver\cond.h
$(WRK)\util\hydro.obj: $(SRC)\solver\convdiff.h
$(WRK)\util\hydro.obj: $(SRC)\solver\convdiffvg.h
$(WRK)\util\hydro.obj: $(SRC)\solver\convdiffv.h
$(WRK)\util\hydro.obj: $(SRC)\solver\embed.h
$(WRK)\util\hydro.obj: $(SRC)\solver\fluid.h
$(WRK)\util\hydro.obj: $(SRC)\solver\multi.h
$(WRK)\util\hydro.obj: $(SRC)\solver\pois.h
$(WRK)\util\hydro.obj: $(SRC)\solver\reconst.h
$(WRK)\util\hydro.obj: $(SRC)\solver\solver.h
$(WRK)\util\hydro.obj: $(SRC)\solver\sphavg.h
$(WRK)\util\hydro.obj: $(SRC)\solver\vof.h
$(WRK)\util\hydro.obj: $(SRC)\solver\vofm.h
$(WRK)\util\hydro.obj: $(SRC)\util\convdiff.h
$(WRK)\util\hydro.obj: $(SRC)\util\format.h
$(WRK)\util\hydro.obj: $(SRC)\util\hydro.ipp
$(WRK)\util\hydro.obj: $(SRC)\util\logger.h
$(WRK)\util\hydro.obj: $(SRC)\util\macros.h
$(WRK)\util\hydro.obj: $(SRC)\util\module.h
$(WRK)\util\hydro.obj: $(SRC)\util\mpi.h
$(WRK)\util\hydro.obj: $(SRC)\util\suspender.h
$(WRK)\util\linear.obj: $(SRC)\debug\linear.h
$(WRK)\util\linear.obj: $(SRC)\distr\reduce.h
$(WRK)\util\linear.obj: $(SRC)\geom\blockface.h
$(WRK)\util\linear.obj: $(SRC)\geom\block.h
$(WRK)\util\linear.obj: $(SRC)\geom\dir.h
$(WRK)\util\linear.obj: $(SRC)\geom\field.h
$(WRK)\util\linear.obj: $(SRC)\geom\idx.h
$(WRK)\util\linear.obj: $(SRC)\geom\loop.h
$(WRK)\util\linear.obj: $(SRC)\geom\map.h
$(WRK)\util\linear.obj: $(SRC)\geom\mesh.h
$(WRK)\util\linear.obj: $(SRC)\geom\notation.h
$(WRK)\util\linear.obj: $(SRC)\geom\range.h
$(WRK)\util\linear.obj: $(SRC)\geom\rangein.h
$(WRK)\util\linear.obj: $(SRC)\geom\rangemulti.h
$(WRK)\util\linear.obj: $(SRC)\geom\transform.h
$(WRK)\util\linear.obj: $(SRC)\geom\vect.h
$(WRK)\util\linear.obj: $(SRC)\linear\linear.h
$(WRK)\util\linear.obj: $(SRC)\parse\vars.h
$(WRK)\util\linear.obj: $(SRC)\util\linear.h
$(WRK)\util\linear.obj: $(SRC)\util\linear.ipp
$(WRK)\util\linear.obj: $(SRC)\util\logger.h
$(WRK)\util\linear.obj: $(SRC)\util\macros.h
$(WRK)\util\linear.obj: $(SRC)\util\module.h
$(WRK)\util\linear.obj: $(SRC)\util\mpi.h
$(WRK)\util\linear.obj: $(SRC)\util\suspender.h
$(WRK)\util\logger.obj: $(SRC)\util\logger.h
$(WRK)\util\logger.obj: $(SRC)\util\macros.h
$(WRK)\util\mpi.obj: $(SRC)\util\logger.h
$(WRK)\util\mpi.obj: $(SRC)\util\macros.h
$(WRK)\util\mpi.obj: $(SRC)\util\mpi.h
$(WRK)\util\posthook_default.obj: $(SRC)\distr\reduce.h
$(WRK)\util\posthook_default.obj: $(SRC)\geom\blockface.h
$(WRK)\util\posthook_default.obj: $(SRC)\geom\block.h
$(WRK)\util\posthook_default.obj: $(SRC)\geom\dir.h
$(WRK)\util\posthook_default.obj: $(SRC)\geom\field.h
$(WRK)\util\posthook_default.obj: $(SRC)\geom\filter.h
$(WRK)\util\posthook_default.obj: $(SRC)\geom\idx.h
$(WRK)\util\posthook_default.obj: $(SRC)\geom\loop.h
$(WRK)\util\posthook_default.obj: $(SRC)\geom\map.h
$(WRK)\util\posthook_default.obj: $(SRC)\geom\mesh.h
$(WRK)\util\posthook_default.obj: $(SRC)\geom\notation.h
$(WRK)\util\posthook_default.obj: $(SRC)\geom\range.h
$(WRK)\util\posthook_default.obj: $(SRC)\geom\rangein.h
$(WRK)\util\posthook_default.obj: $(SRC)\geom\rangemulti.h
$(WRK)\util\posthook_default.obj: $(SRC)\geom\transform.h
$(WRK)\util\posthook_default.obj: $(SRC)\geom\vect.h
$(WRK)\util\posthook_default.obj: $(SRC)\parse\vars.h
$(WRK)\util\posthook_default.obj: $(SRC)\solver\embed.h
$(WRK)\util\posthook_default.obj: $(SRC)\solver\reconst.h
$(WRK)\util\posthook_default.obj: $(SRC)\util\logger.h
$(WRK)\util\posthook_default.obj: $(SRC)\util\macros.h
$(WRK)\util\posthook_default.obj: $(SRC)\util\mpi.h
$(WRK)\util\posthook_default.obj: $(SRC)\util\posthook.h
$(WRK)\util\posthook_default.obj: $(SRC)\util\suspender.h
$(WRK)\util\subcomm_dummy.obj: $(SRC)\util\logger.h
$(WRK)\util\subcomm_dummy.obj: $(SRC)\util\macros.h
$(WRK)\util\subcomm_dummy.obj: $(SRC)\util\mpi.h
$(WRK)\util\subcomm_dummy.obj: $(SRC)\util\subcomm.h
$(WRK)\util\subcomm.obj: $(SRC)\util\logger.h
$(WRK)\util\subcomm.obj: $(SRC)\util\macros.h
$(WRK)\util\subcomm.obj: $(SRC)\util\mpi.h
$(WRK)\util\subcomm.obj: $(SRC)\util\subcomm.h
$(WRK)\util\subcomm.obj: $(SRC)\util\sysinfo.h
$(WRK)\util\suspender.obj: $(SRC)\util\logger.h
$(WRK)\util\suspender.obj: $(SRC)\util\macros.h
$(WRK)\util\suspender.obj: $(SRC)\util\suspender.h
$(WRK)\util\sysinfo.obj: $(SRC)\util\logger.h
$(WRK)\util\sysinfo.obj: $(SRC)\util\macros.h
$(WRK)\util\sysinfo.obj: $(SRC)\util\mpi.h
$(WRK)\util\sysinfo.obj: $(SRC)\util\sysinfo.h
$(WRK)\util\sysinfo.obj: $(SRC)\util\system.h
$(WRK)\util\system.obj: $(SRC)\util\system.h
$(WRK)\util\system.obj: $(SRC)\util\system_unix.inc
$(WRK)\util\system.obj: $(SRC)\util\system_windows.inc
$(WRK)\util\timer.obj: $(SRC)\util\timer.h
$(WRK)\util\vof.obj: $(SRC)\debug\isnan.h
$(WRK)\util\vof.obj: $(SRC)\distr\reduce.h
$(WRK)\util\vof.obj: $(SRC)\dump\vtk.h
$(WRK)\util\vof.obj: $(SRC)\geom\blockface.h
$(WRK)\util\vof.obj: $(SRC)\geom\block.h
$(WRK)\util\vof.obj: $(SRC)\geom\dir.h
$(WRK)\util\vof.obj: $(SRC)\geom\field.h
$(WRK)\util\vof.obj: $(SRC)\geom\filter.h
$(WRK)\util\vof.obj: $(SRC)\geom\idx.h
$(WRK)\util\vof.obj: $(SRC)\geom\loop.h
$(WRK)\util\vof.obj: $(SRC)\geom\map.h
$(WRK)\util\vof.obj: $(SRC)\geom\mesh.h
$(WRK)\util\vof.obj: $(SRC)\geom\notation.h
$(WRK)\util\vof.obj: $(SRC)\geom\range.h
$(WRK)\util\vof.obj: $(SRC)\geom\rangein.h
$(WRK)\util\vof.obj: $(SRC)\geom\rangemulti.h
$(WRK)\util\vof.obj: $(SRC)\geom\transform.h
$(WRK)\util\vof.obj: $(SRC)\geom\vect.h
$(WRK)\util\vof.obj: $(SRC)\march\march.h
$(WRK)\util\vof.obj: $(SRC)\solver\advection.h
$(WRK)\util\vof.obj: $(SRC)\solver\approx.h
$(WRK)\util\vof.obj: $(SRC)\solver\cond.h
$(WRK)\util\vof.obj: $(SRC)\solver\embed.h
$(WRK)\util\vof.obj: $(SRC)\solver\multi.h
$(WRK)\util\vof.obj: $(SRC)\solver\reconst.h
$(WRK)\util\vof.obj: $(SRC)\solver\solver.h
$(WRK)\util\vof.obj: $(SRC)\solver\trackerm.h
$(WRK)\util\vof.obj: $(SRC)\util\format.h
$(WRK)\util\vof.obj: $(SRC)\util\logger.h
$(WRK)\util\vof.obj: $(SRC)\util\macros.h
$(WRK)\util\vof.obj: $(SRC)\util\mpi.h
$(WRK)\util\vof.obj: $(SRC)\util\suspender.h
$(WRK)\util\vof.obj: $(SRC)\util\vof.h
$(WRK)\util\vof.obj: $(SRC)\util\vof.ipp
$(WRK)\young\main.obj: $(SRC)\young\young.h
