$(WRK)\aphros_c\git.obj: $(WRK)\.dir
$(WRK)\aphros_c\main.obj: $(WRK)\.dir
$(WRK)\aphros_c\parser.obj: $(WRK)\.dir
$(WRK)\color\color.obj: $(WRK)\.dir
$(WRK)\distr\comm_manager.obj: $(WRK)\.dir
$(WRK)\distr\distrbasic.obj: $(WRK)\.dir
$(WRK)\distr\distr.obj: $(WRK)\.dir
$(WRK)\distr\distrsolver.obj: $(WRK)\.dir
$(WRK)\distr\local.obj: $(WRK)\.dir
$(WRK)\distr\native.obj: $(WRK)\.dir
$(WRK)\distr\report.obj: $(WRK)\.dir
$(WRK)\dump\dump.obj: $(WRK)\.dir
$(WRK)\dump\dumper.obj: $(WRK)\.dir
$(WRK)\dump\hdf.obj: $(WRK)\.dir
$(WRK)\dump\raw.obj: $(WRK)\.dir
$(WRK)\dump\xmf.obj: $(WRK)\.dir
$(WRK)\func\init_contang.obj: $(WRK)\.dir
$(WRK)\func\init.obj: $(WRK)\.dir
$(WRK)\func\init_vel.obj: $(WRK)\.dir
$(WRK)\func\primlist.obj: $(WRK)\.dir
$(WRK)\geom\mesh.obj: $(WRK)\.dir
$(WRK)\inside\bbox.obj: $(WRK)\.dir
$(WRK)\inside\err.obj: $(WRK)\.dir
$(WRK)\inside\main.obj: $(WRK)\.dir
$(WRK)\inside\memory.obj: $(WRK)\.dir
$(WRK)\inside\off.obj: $(WRK)\.dir
$(WRK)\inside\ply.obj: $(WRK)\.dir
$(WRK)\inside\predicate.obj: $(WRK)\.dir
$(WRK)\inside\stl.obj: $(WRK)\.dir
$(WRK)\kernel\hydro.obj: $(WRK)\.dir
$(WRK)\linear\linear.obj: $(WRK)\.dir
$(WRK)\march\main.obj: $(WRK)\.dir
$(WRK)\parse\argparse.obj: $(WRK)\.dir
$(WRK)\parse\codeblocks.obj: $(WRK)\.dir
$(WRK)\parse\conf2py.obj: $(WRK)\.dir
$(WRK)\parse\parser.obj: $(WRK)\.dir
$(WRK)\parse\template.obj: $(WRK)\.dir
$(WRK)\parse\vars.obj: $(WRK)\.dir
$(WRK)\solver\approx_eb.obj: $(WRK)\.dir
$(WRK)\solver\approx.obj: $(WRK)\.dir
$(WRK)\solver\convdiffe.obj: $(WRK)\.dir
$(WRK)\solver\convdiffi.obj: $(WRK)\.dir
$(WRK)\solver\convdiffvg.obj: $(WRK)\.dir
$(WRK)\solver\curv.obj: $(WRK)\.dir
$(WRK)\solver\electro.obj: $(WRK)\.dir
$(WRK)\solver\embed.obj: $(WRK)\.dir
$(WRK)\solver\fluid_dummy.obj: $(WRK)\.dir
$(WRK)\solver\normal.obj: $(WRK)\.dir
$(WRK)\solver\particles.obj: $(WRK)\.dir
$(WRK)\solver\partstrmeshm.obj: $(WRK)\.dir
$(WRK)\solver\proj_eb.obj: $(WRK)\.dir
$(WRK)\solver\proj.obj: $(WRK)\.dir
$(WRK)\solver\simple.obj: $(WRK)\.dir
$(WRK)\solver\solver.obj: $(WRK)\.dir
$(WRK)\solver\tracer.obj: $(WRK)\.dir
$(WRK)\solver\vofm.obj: $(WRK)\.dir
$(WRK)\solver\vof.obj: $(WRK)\.dir
$(WRK)\util\convdiff.obj: $(WRK)\.dir
$(WRK)\util\distr.obj: $(WRK)\.dir
$(WRK)\util\events.obj: $(WRK)\.dir
$(WRK)\util\filesystem.obj: $(WRK)\.dir
$(WRK)\util\fixed_allocator.obj: $(WRK)\.dir
$(WRK)\util\fluid.obj: $(WRK)\.dir
$(WRK)\util\format.obj: $(WRK)\.dir
$(WRK)\util\gitgen.obj: $(WRK)\.dir
$(WRK)\util\git.obj: $(WRK)\.dir
$(WRK)\util\histogram.obj: $(WRK)\.dir
$(WRK)\util\hydro.obj: $(WRK)\.dir
$(WRK)\util\linear.obj: $(WRK)\.dir
$(WRK)\util\logger.obj: $(WRK)\.dir
$(WRK)\util\mpi.obj: $(WRK)\.dir
$(WRK)\util\posthook_default.obj: $(WRK)\.dir
$(WRK)\util\subcomm_dummy.obj: $(WRK)\.dir
$(WRK)\util\suspender.obj: $(WRK)\.dir
$(WRK)\util\sysinfo.obj: $(WRK)\.dir
$(WRK)\util\system.obj: $(WRK)\.dir
$(WRK)\util\timer.obj: $(WRK)\.dir
$(WRK)\util\vof.obj: $(WRK)\.dir
$(WRK)\young\main.obj: $(WRK)\.dir
