O = \
$(WRK)\aphros_c\git.obj\
$(WRK)\aphros_c\main.obj\
$(WRK)\aphros_c\parser.obj\
$(WRK)\color\color.obj\
$(WRK)\distr\comm_manager.obj\
$(WRK)\distr\distrbasic.obj\
$(WRK)\distr\distr.obj\
$(WRK)\distr\distrsolver.obj\
$(WRK)\distr\local.obj\
$(WRK)\distr\native.obj\
$(WRK)\distr\report.obj\
$(WRK)\dump\dump.obj\
$(WRK)\dump\dumper.obj\
$(WRK)\dump\hdf.obj\
$(WRK)\dump\raw.obj\
$(WRK)\dump\xmf.obj\
$(WRK)\func\init_contang.obj\
$(WRK)\func\init.obj\
$(WRK)\func\init_vel.obj\
$(WRK)\func\primlist.obj\
$(WRK)\geom\mesh.obj\
$(WRK)\inside\bbox.obj\
$(WRK)\inside\err.obj\
$(WRK)\inside\main.obj\
$(WRK)\inside\memory.obj\
$(WRK)\inside\off.obj\
$(WRK)\inside\ply.obj\
$(WRK)\inside\predicate.obj\
$(WRK)\inside\stl.obj\
$(WRK)\kernel\hydro.obj\
$(WRK)\linear\linear.obj\
$(WRK)\march\main.obj\
$(WRK)\parse\argparse.obj\
$(WRK)\parse\codeblocks.obj\
$(WRK)\parse\conf2py.obj\
$(WRK)\parse\parser.obj\
$(WRK)\parse\template.obj\
$(WRK)\parse\vars.obj\
$(WRK)\solver\approx_eb.obj\
$(WRK)\solver\approx.obj\
$(WRK)\solver\convdiffe.obj\
$(WRK)\solver\convdiffi.obj\
$(WRK)\solver\convdiffvg.obj\
$(WRK)\solver\curv.obj\
$(WRK)\solver\electro.obj\
$(WRK)\solver\embed.obj\
$(WRK)\solver\fluid_dummy.obj\
$(WRK)\solver\normal.obj\
$(WRK)\solver\particles.obj\
$(WRK)\solver\partstrmeshm.obj\
$(WRK)\solver\proj_eb.obj\
$(WRK)\solver\proj.obj\
$(WRK)\solver\simple.obj\
$(WRK)\solver\solver.obj\
$(WRK)\solver\tracer.obj\
$(WRK)\solver\vofm.obj\
$(WRK)\solver\vof.obj\
$(WRK)\util\convdiff.obj\
$(WRK)\util\distr.obj\
$(WRK)\util\events.obj\
$(WRK)\util\filesystem.obj\
$(WRK)\util\fixed_allocator.obj\
$(WRK)\util\fluid.obj\
$(WRK)\util\format.obj\
$(WRK)\util\gitgen.obj\
$(WRK)\util\git.obj\
$(WRK)\util\histogram.obj\
$(WRK)\util\hydro.obj\
$(WRK)\util\linear.obj\
$(WRK)\util\logger.obj\
$(WRK)\util\mpi.obj\
$(WRK)\util\posthook_default.obj\
$(WRK)\util\subcomm_dummy.obj\
$(WRK)\util\suspender.obj\
$(WRK)\util\sysinfo.obj\
$(WRK)\util\system.obj\
$(WRK)\util\timer.obj\
$(WRK)\util\vof.obj\
$(WRK)\young\main.obj\

