aphros_c\git.obj: aphros_c\git.cpp; $(CXX_RULE) aphros_c\git.cpp
aphros_c\main.obj: aphros_c\main.cpp; $(CXX_RULE) aphros_c\main.cpp
aphros_c\parser.obj: aphros_c\parser.cpp; $(CXX_RULE) aphros_c\parser.cpp
color\color.obj: color\color.c; $(CC_RULE) color\color.c
distr\comm_manager.obj: distr\comm_manager.cpp; $(CXX_RULE) distr\comm_manager.cpp
distr\cubismnc.obj: distr\cubismnc.cpp; $(CXX_RULE) distr\cubismnc.cpp
distr\distrbasic.obj: distr\distrbasic.cpp; $(CXX_RULE) distr\distrbasic.cpp
distr\distr.obj: distr\distr.cpp; $(CXX_RULE) distr\distr.cpp
distr\distrsolver.obj: distr\distrsolver.cpp; $(CXX_RULE) distr\distrsolver.cpp
distr\local.obj: distr\local.cpp; $(CXX_RULE) distr\local.cpp
distr\native.obj: distr\native.cpp; $(CXX_RULE) distr\native.cpp
distr\report.obj: distr\report.cpp; $(CXX_RULE) distr\report.cpp
dump\dump.obj: dump\dump.cpp; $(CXX_RULE) dump\dump.cpp
dump\dumper.obj: dump\dumper.cpp; $(CXX_RULE) dump\dumper.cpp
dump\hdf.obj: dump\hdf.cpp; $(CXX_RULE) dump\hdf.cpp
dump\raw.obj: dump\raw.cpp; $(CXX_RULE) dump\raw.cpp
dump\xmf.obj: dump\xmf.cpp; $(CXX_RULE) dump\xmf.cpp
func\init_contang.obj: func\init_contang.cpp; $(CXX_RULE) func\init_contang.cpp
func\init.obj: func\init.cpp; $(CXX_RULE) func\init.cpp
func\init_vel.obj: func\init_vel.cpp; $(CXX_RULE) func\init_vel.cpp
func\primlist.obj: func\primlist.cpp; $(CXX_RULE) func\primlist.cpp
gen\wave_lamb.obj: gen\wave_lamb.c; $(CC_RULE) gen\wave_lamb.c
geom\mesh.obj: geom\mesh.cpp; $(CXX_RULE) geom\mesh.cpp
inside\bbox.obj: inside\bbox.c; $(CC_RULE) inside\bbox.c
inside\err.obj: inside\err.c; $(CC_RULE) inside\err.c
inside\main.obj: inside\main.c; $(CC_RULE) inside\main.c
inside\memory.obj: inside\memory.c; $(CC_RULE) inside\memory.c
inside\off.obj: inside\off.c; $(CC_RULE) inside\off.c
inside\ply.obj: inside\ply.c; $(CC_RULE) inside\ply.c
inside\predicate.obj: inside\predicate.c; $(CC_RULE) inside\predicate.c
inside\stl.obj: inside\stl.c; $(CC_RULE) inside\stl.c
kernel\hydro.obj: kernel\hydro.cpp; $(CXX_RULE) kernel\hydro.cpp
linear\hypre.obj: linear\hypre.cpp; $(CXX_RULE) linear\hypre.cpp
linear\hypresub.obj: linear\hypresub.cpp; $(CXX_RULE) linear\hypresub.cpp
linear\linear_amgx.obj: linear\linear_amgx.cpp; $(CXX_RULE) linear\linear_amgx.cpp
linear\linear_hypre.obj: linear\linear_hypre.cpp; $(CXX_RULE) linear\linear_hypre.cpp
linear\linear.obj: linear\linear.cpp; $(CXX_RULE) linear\linear.cpp
main.obj: main.c; $(CC_RULE) main.c
march\main.obj: march\main.c; $(CC_RULE) march\main.c
overlap\overlap.obj: overlap\overlap.cpp; $(CXX_RULE) overlap\overlap.cpp
parse\argparse.obj: parse\argparse.cpp; $(CXX_RULE) parse\argparse.cpp
parse\codeblocks.obj: parse\codeblocks.cpp; $(CXX_RULE) parse\codeblocks.cpp
parse\conf2py.obj: parse\conf2py.cpp; $(CXX_RULE) parse\conf2py.cpp
parse\parser.obj: parse\parser.cpp; $(CXX_RULE) parse\parser.cpp
parse\template.obj: parse\template.cpp; $(CXX_RULE) parse\template.cpp
parse\vars.obj: parse\vars.cpp; $(CXX_RULE) parse\vars.cpp
solver\approx_eb.obj: solver\approx_eb.cpp; $(CXX_RULE) solver\approx_eb.cpp
solver\approx.obj: solver\approx.cpp; $(CXX_RULE) solver\approx.cpp
solver\convdiffe.obj: solver\convdiffe.cpp; $(CXX_RULE) solver\convdiffe.cpp
solver\convdiffi.obj: solver\convdiffi.cpp; $(CXX_RULE) solver\convdiffi.cpp
solver\convdiffvg.obj: solver\convdiffvg.cpp; $(CXX_RULE) solver\convdiffvg.cpp
solver\curv.obj: solver\curv.cpp; $(CXX_RULE) solver\curv.cpp
solver\electro.obj: solver\electro.cpp; $(CXX_RULE) solver\electro.cpp
solver\embed.obj: solver\embed.cpp; $(CXX_RULE) solver\embed.cpp
solver\fluid_dummy.obj: solver\fluid_dummy.cpp; $(CXX_RULE) solver\fluid_dummy.cpp
solver\normal.obj: solver\normal.cpp; $(CXX_RULE) solver\normal.cpp
solver\particles.obj: solver\particles.cpp; $(CXX_RULE) solver\particles.cpp
solver\partstrmeshm.obj: solver\partstrmeshm.cpp; $(CXX_RULE) solver\partstrmeshm.cpp
solver\proj_eb.obj: solver\proj_eb.cpp; $(CXX_RULE) solver\proj_eb.cpp
solver\proj.obj: solver\proj.cpp; $(CXX_RULE) solver\proj.cpp
solver\simple.obj: solver\simple.cpp; $(CXX_RULE) solver\simple.cpp
solver\solver.obj: solver\solver.cpp; $(CXX_RULE) solver\solver.cpp
solver\tracer.obj: solver\tracer.cpp; $(CXX_RULE) solver\tracer.cpp
solver\vofm.obj: solver\vofm.cpp; $(CXX_RULE) solver\vofm.cpp
solver\vof.obj: solver\vof.cpp; $(CXX_RULE) solver\vof.cpp
test\advection\main.obj: test\advection\main.cpp; $(CXX_RULE) test\advection\main.cpp
test\approx\linear.obj: test\approx\linear.cpp; $(CXX_RULE) test\approx\linear.cpp
test\approx\main.obj: test\approx\main.cpp; $(CXX_RULE) test\approx\main.cpp
test\benchmark_diffusion\main.obj: test\benchmark_diffusion\main.cpp; $(CXX_RULE) test\benchmark_diffusion\main.cpp
test\benchmark\main.obj: test\benchmark\main.cpp; $(CXX_RULE) test\benchmark\main.cpp
test\benchmark_mpi\main.obj: test\benchmark_mpi\main.cpp; $(CXX_RULE) test\benchmark_mpi\main.cpp
test\benchmark_mpiraw\main.obj: test\benchmark_mpiraw\main.cpp; $(CXX_RULE) test\benchmark_mpiraw\main.cpp
test\benchmark_normal\main.obj: test\benchmark_normal\main.cpp; $(CXX_RULE) test\benchmark_normal\main.cpp
test\color\main.obj: test\color\main.cpp; $(CXX_RULE) test\color\main.cpp
test\commhalo\main.obj: test\commhalo\main.cpp; $(CXX_RULE) test\commhalo\main.cpp
test\comm\main.obj: test\comm\main.cpp; $(CXX_RULE) test\comm\main.cpp
test\commmap\main.obj: test\commmap\main.cpp; $(CXX_RULE) test\commmap\main.cpp
test\commmap\manager.obj: test\commmap\manager.cpp; $(CXX_RULE) test\commmap\manager.cpp
test\condface\main.obj: test\condface\main.cpp; $(CXX_RULE) test\condface\main.cpp
test\debug\main.obj: test\debug\main.cpp; $(CXX_RULE) test\debug\main.cpp
test\dump\dump_diff.obj: test\dump\dump_diff.cpp; $(CXX_RULE) test\dump\dump_diff.cpp
test\dump\dump_gen.obj: test\dump\dump_gen.cpp; $(CXX_RULE) test\dump\dump_gen.cpp
test\dump\dump_meta.obj: test\dump\dump_meta.cpp; $(CXX_RULE) test\dump\dump_meta.cpp
test\dump\dump_util.obj: test\dump\dump_util.cpp; $(CXX_RULE) test\dump\dump_util.cpp
test\embed_approx\main.obj: test\embed_approx\main.cpp; $(CXX_RULE) test\embed_approx\main.cpp
test\embed_convdiff\main.obj: test\embed_convdiff\main.cpp; $(CXX_RULE) test\embed_convdiff\main.cpp
test\embed_grad\main.obj: test\embed_grad\main.cpp; $(CXX_RULE) test\embed_grad\main.cpp
test\embed_interpolate\main.obj: test\embed_interpolate\main.cpp; $(CXX_RULE) test\embed_interpolate\main.cpp
test\embed\main.obj: test\embed\main.cpp; $(CXX_RULE) test\embed\main.cpp
test\embed_potential\main.obj: test\embed_potential\main.cpp; $(CXX_RULE) test\embed_potential\main.cpp
test\fluid\main.obj: test\fluid\main.cpp; $(CXX_RULE) test\fluid\main.cpp
test\grad\main.obj: test\grad\main.cpp; $(CXX_RULE) test\grad\main.cpp
test\hook\hook\hook.obj: test\hook\hook\hook.cpp; $(CXX_RULE) test\hook\hook\hook.cpp
test\hypre\main.obj: test\hypre\main.cpp; $(CXX_RULE) test\hypre\main.cpp
test\hypresub\main.obj: test\hypresub\main.cpp; $(CXX_RULE) test\hypresub\main.cpp
test\init\main.obj: test\init\main.cpp; $(CXX_RULE) test\init\main.cpp
test\inner\main.obj: test\inner\main.cpp; $(CXX_RULE) test\inner\main.cpp
test\linear\main.obj: test\linear\main.cpp; $(CXX_RULE) test\linear\main.cpp
test\mesh\main.obj: test\mesh\main.cpp; $(CXX_RULE) test\mesh\main.cpp
test\openmp\main.obj: test\openmp\main.cpp; $(CXX_RULE) test\openmp\main.cpp
test\parser\codeblocks.obj: test\parser\codeblocks.cpp; $(CXX_RULE) test\parser\codeblocks.cpp
test\parser\main.obj: test\parser\main.cpp; $(CXX_RULE) test\parser\main.cpp
test\primlist\getmap.obj: test\primlist\getmap.cpp; $(CXX_RULE) test\primlist\getmap.cpp
test\primlist\parse.obj: test\primlist\parse.cpp; $(CXX_RULE) test\primlist\parse.cpp
test\range\main.obj: test\range\main.cpp; $(CXX_RULE) test\range\main.cpp
test\recolor\main.obj: test\recolor\main.cpp; $(CXX_RULE) test\recolor\main.cpp
test\reconst\levelset.obj: test\reconst\levelset.cpp; $(CXX_RULE) test\reconst\levelset.cpp
test\reconst\main.obj: test\reconst\main.cpp; $(CXX_RULE) test\reconst\main.cpp
test\reconst\plane.obj: test\reconst\plane.cpp; $(CXX_RULE) test\reconst\plane.cpp
test\reflect\main.obj: test\reflect\main.cpp; $(CXX_RULE) test\reflect\main.cpp
test\stat\main.obj: test\stat\main.cpp; $(CXX_RULE) test\stat\main.cpp
test\subcomm\main.obj: test\subcomm\main.cpp; $(CXX_RULE) test\subcomm\main.cpp
test\suspender\main.obj: test\suspender\main.cpp; $(CXX_RULE) test\suspender\main.cpp
test\sysinfo\main.obj: test\sysinfo\main.cpp; $(CXX_RULE) test\sysinfo\main.cpp
test\sysinfo\realpath.obj: test\sysinfo\realpath.cpp; $(CXX_RULE) test\sysinfo\realpath.cpp
test\sysinfo\splitext.obj: test\sysinfo\splitext.cpp; $(CXX_RULE) test\sysinfo\splitext.cpp
test\tracker\main.obj: test\tracker\main.cpp; $(CXX_RULE) test\tracker\main.cpp
test\util\main.obj: test\util\main.cpp; $(CXX_RULE) test\util\main.cpp
test\vars\main.obj: test\vars\main.cpp; $(CXX_RULE) test\vars\main.cpp
test\visual\main.obj: test\visual\main.cpp; $(CXX_RULE) test\visual\main.cpp
util\convdiff.obj: util\convdiff.cpp; $(CXX_RULE) util\convdiff.cpp
util\distr.obj: util\distr.cpp; $(CXX_RULE) util\distr.cpp
util\events.obj: util\events.cpp; $(CXX_RULE) util\events.cpp
util\filesystem.obj: util\filesystem.cpp; $(CXX_RULE) util\filesystem.cpp
util\fixed_allocator.obj: util\fixed_allocator.cpp; $(CXX_RULE) util\fixed_allocator.cpp
util\fluid.obj: util\fluid.cpp; $(CXX_RULE) util\fluid.cpp
util\format.obj: util\format.cpp; $(CXX_RULE) util\format.cpp
util\gitgen.obj: util\gitgen.cpp; $(CXX_RULE) util\gitgen.cpp
util\git.obj: util\git.cpp; $(CXX_RULE) util\git.cpp
util\histogram.obj: util\histogram.cpp; $(CXX_RULE) util\histogram.cpp
util\hydro.obj: util\hydro.cpp; $(CXX_RULE) util\hydro.cpp
util\linear.obj: util\linear.cpp; $(CXX_RULE) util\linear.cpp
util\logger.obj: util\logger.cpp; $(CXX_RULE) util\logger.cpp
util\mpi.obj: util\mpi.cpp; $(CXX_RULE) util\mpi.cpp
util\posthook_default.obj: util\posthook_default.cpp; $(CXX_RULE) util\posthook_default.cpp
util\subcomm_dummy.obj: util\subcomm_dummy.cpp; $(CXX_RULE) util\subcomm_dummy.cpp
util\subcomm.obj: util\subcomm.cpp; $(CXX_RULE) util\subcomm.cpp
util\suspender.obj: util\suspender.cpp; $(CXX_RULE) util\suspender.cpp
util\sysinfo.obj: util\sysinfo.cpp; $(CXX_RULE) util\sysinfo.cpp
util\system.obj: util\system.c; $(CC_RULE) util\system.c
util\timer.obj: util\timer.cpp; $(CXX_RULE) util\timer.cpp
util\vof.obj: util\vof.cpp; $(CXX_RULE) util\vof.cpp
young\main.obj: young\main.c; $(CC_RULE) young\main.c
