#!/usr/bin/awk -f

BEGIN {
    t = "	"
    for (i = 0; i <= 1; i++)
        for (j = 0; j <= 1; j++)
            for (k = 0; k <= 1; k++)
                if (i != 0 || j != 0 || k != 0)
                    printf "%s{%d, %d, %d},\n", t, i, j, k
}
