#!/usr/bin/awk -f

function f() {
    print x, y, z | "cat >&2"
    return sph(-0.5, -0.5, 0, 0.7) || sph(0.5, 0, 0, 0.2)
}

BEGIN {
    n = 9
    for (m = i = 0; i < n; i++)
        for (j = 0; j < n; j++)
            for (k = 0; k < n; k++) {
                x = c(i); y = c(j); z = c(k)
                a[m++] = f() ? 0 :  -1
            }
    print n
    for (i = 0; i in a; i++)
        print a[i]
}

function c(i) { return i/(n-1) - 1/2 }
function sph(u, v, w, r) {
    u -= x
    v -= y
    w -= z
    return u*u + v*v + w*w < r*r
}

