#!/usr/bin/env python

# Prints curvature sorted by cell index.

import numpy as np
import sys

ukk = np.loadtxt("k_0000.dat", skiprows=1).flatten()
ukk = [k for k in ukk if np.isfinite(k)]

np.savetxt(sys.stdout, ukk)
