#!/bin/bash

set -eu

dim=`cat dim`
nx=`cat nx`

make clean

echo "set int dim $dim" > par.conf

if [ "$dim" == 2 ] ; then
  make run m="$nx $nx 1" bs="$nx $nx 1"
else
  make run m="$nx $nx $nx" bs="$nx $nx $nx"
fi


./curv > ok
ch.getcol m2 | head -n 1 > ovf
