#!/bin/bash

set -eu

(cd ch ; ./plot)

./plot.py

d=plot
dp=$d/pdf
dt=$d/dat

#rm -rf $d
mkdir -p $dp

mv -f *.pdf $dp

for s in ch ge ; do
  mkdir -p $dp/$s
  mv $s/*.{pdf,png} $dp/$s 2> /dev/null || true
done

mkdir -p $dt
mv -f {ang,hist}_*.dat $dt 2> /dev/null || true

