#!/usr/bin/env python

import os
import itertools as it
import numpy as np
import sys
import ch

sh = ch.sh

a = ch.GetStdPar('out')
c = ch.GetArgs(a)
o = os.path.realpath(c.out)
sh("mkdir -p '{:}'".format(o))

ddim = [2,3]
for dim,cpr in it.product(ddim, 2 ** np.arange(0,5,0.5)):
    sf = "dim{:}_cpr{:06.02f}".format(dim, cpr)
    ot = os.path.join(o, "run_{:}".format(sf))
    od = os.path.join(o, "dat_{:}".format(sf))

    cf = './gen -cpr {cpr} -dim {dim}'.format(**locals())

    sh("ch.task {:} > {:} <<< '{:}'".format(od, ot, cf))
    sh("chmod +x {:}".format(ot))
