#!/bin/bash -l

#BSUB -J mfer
#BSUB -W 1:00

echo running > job.status

./clean
./cleandat

n=`cat np`
mpirun ../mfer cub$n.conf &> out

mv -vf job.id job.id.last

./statcopy

echo "Done."
echo done > job.status

