#!/bin/sh -eu

log=run.log

ev () {
  echo "$@" | tee -a "$log"
  eval "$@ 2>&1" >> "$log"
}

run () {
  rho=$1
  shift
  dir=rho${rho}
  if [ -d "$dir" ] ; then
    echo "skip existing $dir"
    return
  fi
  cat > add.conf << EOF
set double tmax 0.1
set double rho2 $rho
set double cflst $(echo "1/sqrt($rho)" | bc -l)
EOF
  ev "make nx=64 bsx=64 np=1 cleanrun"
  ev "mkdir -p $dir && rsync -a {gen,{s,sm}_*.vtk,std.conf,out,out.conf,stat.dat} $dir/"
}

run 0.16000
run 0.08000
run 0.04000
run 0.02000
run 0.01000
run 0.00500
run 0.00250
run 0.00125
