#!/bin/bash

set -eu

# test name
t=$1
# config file
c=_${t}.conf
# reference
r=ref${t}

cp "$c" add.conf

# run 
make -f sim.makefile cleanrun

a=0
for f in $r/* ; do
  echo $f
  eps=2e-12
  if [ "${f##*.}" = "vts" ] ; then eps=1e-5; fi
  if ! ch.diffnum "${f#$r/}" "$f" $eps; then a=1; fi
done

exit $a
