#!/usr/bin/env python

import h5py
import numpy as np
import os
import re
import sys

me = "volume"
eps = 1e-2
av = sys.argv
if '-h' in av:
  sys.stderr.write("%s [hdf ..]\n" % me)
  exit(1)

for file in av[1:]:
  time = os.path.basename(file)
  time = os.path.splitext(time)[0]
  time = re.sub(".*_", "", time)
  try:
    time = int(time)
  except ValueError:
    sys.stderr.write("%s: no time in filename '%s'\n" % (me, file))
    sys.exit(2)

  h = h5py.File(file, 'r')
  u = h['data']
  u = np.array(u)
  h.close()

  i = np.where(u < 1 - eps)
  n = u.size
  vf = np.sum(u[i])/n
  print("%d %.16g" % (time, vf))
