#!/usr/bin/env python

import h5py
import numpy as np
import os
import re
import sys

eps = 1e-2
av = sys.argv
if '-h' in av:
  print("{:} [hdf ..]".format(os.path.basename(av[0])))
  exit(1)

for f in av[1:]:
  time = os.path.basename(f)
  time = os.path.splitext(time)[0]
  time = re.sub(".*_", "", time)
  time = int(time)

  h = h5py.File(f, 'r')
  u = h['data']
  u = np.array(u)
  h.close()

  i = np.where(u < 1 - eps)
  n = u.size
  vf = np.sum(u[i])/n
  print("%d %.16g" % (time, vf))
