#!/bin/bash

set -eu

ev () {
  echo "$@"
  eval "$@"
}

# exp top bubble radius x [mm]
b1rx=`bc -l <<< "0.0013177 * 1000"`
# sim top bubble radius x [-]
s_b1rx=0.1622
# length ratio sim[-]/exp[mm]
lse=`bc -l <<< "${s_b1rx} / ${b1rx}"`
# length ratio imgexp[px]/exp[mm]
lie=`bc -l <<< "68"`
# length ratio imgsim[px]/sim[-]
lis=`bc -l <<< "1000"`
# length ratio imgsim[px]/imgexp[px]
lise=`bc -l <<< $lis*$lse/$lie`

echo $lise

cmd () {
  a=$1 ; b=$2
  f=`basename $a`
  f=a_${f#*_}
  if [ -f $f ] ; then
    echo "skip existing $f"
  else
    # shift to center in imgsim[px]
    ev convert "'$b'[200%] \( '$a'[`bc -l <<< "200. / $lise"`%] -background none \
    \) \
     -geometry -112-22 \
     -gravity center \
     -compose over -composite -depth 8 '$f'"
  fi
}

# sim0
#    -alpha set -channel a -evaluate set 50% +channel \
#     -geometry +0-22 \

rm -f a_*.png

fr=frames

./frsc sim exp 1 > $fr

d=""
while read f ; do
  cmd $f
done < $fr

montage a_*.png -mode concatenate -tile 6x2 tile.png
