#!/bin/sh
set -eu
d=stepwise
echo "include stepwise.conf" > add.conf
make cleanrun
(cd vis && rm -vf *.png && ./vis_vf.py ../s_*.vtk)
(cd vis && mkdir -p "$d" && mv -v a_*.png "$d")
(vis/plot_volume_error.py --output vis/$d/volume_error.pdf)
