#!/bin/sh
set -eu
d=smooth
echo > add.conf
make cleanrun
mkdir -p $d
mv stat.dat $d/
(cd $d && ../vis/plot_volume_error.py --output volume_error.pdf)
(cd vis && rm -vf *.png && ./vis_vf.py ../s_*.vtk)
mv vis/a_*.png $d/
