#!/usr/bin/env python

import h5py
import numpy as np
import matplotlib.pyplot as plt
import sys
import os

av = sys.argv

if len(av) != 3 or av[1] == '-h':
  print("""usage: ./{:} HDF OUT
Computes mean in z-direction.
HDF: hdf-file of dimensions (nx,ny,nz,1)
OUT: new hdf-file of dimensions (nx,ny,1,1)
""".format(os.path.basename(av[0])))
  exit(1)

f = av[1]
fo = av[2]

h = h5py.File(f, 'r')
u = h['data']
u = np.array(u)
h.close()

print(u.shape)
u = np.mean(u, axis=0)[np.newaxis,:,:,:]
print(u.shape)

print(fo)
o = h5py.File(fo, 'w')
o.create_dataset('data', data=u)
o.close()
