#!/bin/bash

set -eu

for f in ../vf_*.h5 ; do
  echo "$f"
  h=`basename "$f"`
  h=vfz_${h#vf_}
  x=${h%.h5}.xmf
  if [ -f "$x" ] ; then
    echo "skip existing $x"
    continue
  fi
  ./meanhdfz $f $h
  ap-genxmf $h 2
done
