#!/bin/bash

set -eu

trajr=$1
cl=$(basename "$trajr")
cl=${cl#*_}
cl=${cl%.csv}
: ${vtkin=../sm_%04d.vtk}
: ${vtkout=smcl_${cl}_%.vtk}

ap-cawk -v vtkin="$vtkin" -v vtkout="$vtkout" '
  { 
    R($n, $cl)
    mn = max(mn, $n)
    nn[$n]
  }
  END {
    for (n = 0; n < mn; ++n) {
      if (n in nn) continue
      R(n, -2)
    }
  }
  function max(a, b) {
    return a > b ? a : b
  }
  function R(n, cl,   s, err) {
    s = sprintf("ap-filter -f cl -p %%s -- %%d -- %s", vtkin)
    s = sprintf(s, vtkout, cl, n)
    print s | "cat >&2"
    err=system(s) 
    if (err) {
      print "error: " , s | "cat >&2"
      exit 2
    }
  }
' "$trajr"
