#!/usr/bin/env python3

import os

import aphros


class Test(aphros.TestBase):
    def __init__(self):
        super().__init__(cases=["2d", "3d", "embed_2d", "embed_3d"])

    def run(self, case):
        self.runcmd("make -f sim.makefile {}".format(case))
        return ["c2x"]

    def check(self, outdir, refdir, output_files):
        r = True
        for f in output_files:
            out = os.path.join(outdir, f)
            ref = os.path.join(refdir, f)
            self.runcmd("ap.diffnum '{}' '{}' 1e-2".format(out, ref))
        return r

    def plot(self, datadir, output_files):
        gnu = "a.gnu"
        assert os.path.isfile(gnu), "{} not found".format(gnu)
        gnurel = os.path.relpath(gnu, datadir)
        refrel = os.path.relpath(self.refdir, datadir)
        self.runcmd("cd '{}' && gnuplot -c '{}' '{}'".format(
            datadir, gnurel, refrel))


Test().main()
