#!/bin/bash -l

set -eu

echo running > job.status

export OMP_NUM_THREADS=1
n=4
time mpirun -n $n --oversubscribe valgrind --leak-check=full ../mfer localc$n.conf

echo "Done."
echo done > job.status

