#!/usr/bin/env python

# save current defined variables
dir0 = set(dir()) | {"dir0"}

Red = 10.
alpha = 8.
gamma = 8.
We = 0.5
zeta = 0.125

rhoo = 1.
Uc = 1.
H = 1.
x0 = 0.5 * H
y0 = 0.825 * H

a = zeta * H
d = 2 * a
rhoi = alpha * rhoo
muo = rhoo * Uc * d / Red
mui = gamma * muo
sigma = rhoo * Uc ** 2 * d / We
pgrad = 8 * Uc * muo / H ** 2

T0 = 40
dt0 = 1e-6
T = T0 * H / Uc
dt = dt0 * H / Uc
max_step = int(T / dt)

# print newly defined variables
dir1 = set(dir())
dird = dir1 - dir0
for v in sorted(dird):
    print("{:} \t=\t {:}".format(v, globals()[v]))


out='''\
# domain
set double extent {H}

# time
set double tmax {T}

# initial velocity
set string vel_init pois
set double poisvel {Uc}

# initial volume fraction
set string init_vf circle
set vect circle_c {x0} {y0} 0
set double circle_r {a}

# physical 
set vect force {pgrad} 0 0 
set double rho1 {rhoo}
set double rho2 {rhoi}
set double mu1 {muo}
set double mu2 {mui}
set double sigma {sigma}

'''.format(**globals())

with open("par.conf", 'w') as f:
    f.write(out)
