#!/bin/bash

set -eu

: ${np=64}
: ${nx=064}
: ${r=0.01}
: ${ns=2}
: ${symm=0}
: ${nfr=40}
: ${ba=1}
: ${ch=1}
: ${suff=}

d="nx${nx}_ns${ns}_symm${symm}${suff}"
[ $ch == "1" ] && runch= || runch="echo > r_ch"
[ $ba == "1" ] && runba= || runba="echo > r_ba"

echo $d
mkdir $d

rsync -aL dummy/. $d

cd $d

o=gen1

cat > $o << EOG
#!/bin/bash

set -eu

echo $np > np
echo 1440 > tl

# $0 $@
# np=$np
# nx=$nx
# r=$r
# ns=$ns
# symm=$symm
# nfr=$nfr
# ba=$ba
# ch=$ch

./gen -nx $nx -np $np -mode osc -dim 3 -pos center\
  -We 0 -La 40000 -tmax 0.4 -br 0.15\
  -mu $r -rho $r \
  -symmxy $symm -wallz 0 \
  -bcod 0 0 0 -bcor 0 0 0 \
  -b2xr 2 0 0 -b2rr 1 \
  -nb 2 -nfr $nfr 


cat > ch/add.conf << EOF
set string dumpformat default
set string dumplist vf omz
set int part_ns $ns
EOF

$runch
$runba

EOG

chmod +x $o

./$o
