#!/bin/bash

set -eu

eval "$@"

: ${np=64}
: ${nx=064}
: ${r=0.01}
: ${ns=2}
: ${symm=0}
: ${nfr=40}
: ${ba=1}
: ${ch=1}
: ${suff=}
: ${tmax=0.4}
: ${wall=0}
: ${tl=1440}
: ${Oh=0.005}
: ${vert=0}

d="nx${nx}_ns${ns}_Oh${Oh}_symm${symm}_tmax${tmax}${suff}"
[ $ch == "1" ] && runch= || runch="echo > r_ch"
[ $ba == "1" ] && runba= || runba="echo > r_ba"

if [ "$wall" == "1" ] ; then
  bcod=-0.5
  bcor=1
  d=${d}_wall
else
  bcod=0
  bcor=0
fi

if [ "$vert" == "1" ] ; then
  d=${d}_vert
  b2xr="0 0 2"
  if [ "$wall" == "1" ] ; then
    bcor=2
  fi
else
  b2xr="2 0 0"
fi



echo $d
mkdir $d

rsync -aL dummy/. $d

cd $d

o=gen1

cat > $o << EOG
#!/bin/bash

set -eu

echo $np > np
echo $tl > tl

# $0 $@
# np=$np
# nx=$nx
# r=$r
# ns=$ns
# symm=$symm
# nfr=$nfr
# ba=$ba
# ch=$ch
# tmax=$tmax
# wall=$wall
# Oh=$Oh

./gen -nx $nx -np $np -mode osc -dim 3 -pos center \\
  -We 0 -Oh $Oh -tmax $tmax -br 0.15 \\
  -mu $r -rho $r \\
  -symmxy $symm -wallz $wall \\
  -bcod 0 0 $bcod -bcor 0 0 $bcor \\
  -b2xr $b2xr -b2rr 1 \\
  -nb 2 -nfr $nfr 


cat > ch/add.conf << EOF
set string dumpformat default
set string dumplist vf omz
set int part_ns $ns
EOF

$runch
$runba

EOG

chmod +x $o

./$o
