#!/usr/bin/env bash

export PATH=$(pwd)/bin:$PATH
export REPO=/code/aphros

# Prevents OpenMPI errors: Read -1, expected 8192, errno = 1
# MPICH would work without errors, but ParaView depends on OpenMPI
export OMPI_MCA_btl_vader_single_copy_mechanism=none

./build.sh
. $HOME/.local/bin/ap.setenv

#./test.sh

./bidisperse.sh
./crystal.sh
./waterfall.sh
./clustering.sh
