#!/bin/bash 

set -eu

. ch.prefix
. ../util

rsync -aPR --update ../.././sim/partstr/randc "$P"
rsync -aPR --update ../.././sim/sim04_univel "$P"
rsync -aPR --update ../.././sim/partstr/curv3d "$P"
rsync -aPR --update ../.././sim/ba "$P"
