#!/bin/bash

set -eu

R=`realpath randc`
for d in dim* ; do
  echo $d
  for f in ch ba bap ge ; do
    df=$d/$f
    if [ -f $df/dim ] ; then
      echo $df
      (cd $df ; $R/_gather)
      (cd $df ; $R/_gatheravg)
    fi
  done
done

