#!/bin/bash

set -eu

export nbi=3
export nri=15

dim=2 ./runcase
./runcase

export solver="ch bap"

np=3 ./runcase
np=5 ./runcase
np=7 ./runcase

ns=1 ./runcase
ns=2 ./runcase
ns=4 ./runcase

hp=2 ./runcase
hp=3 ./runcase
hp=5 ./runcase

