#!/bin/bash

set -eu

dim=2 ./runcase
./runcase

solver='ch' np=3 ./runcase
solver='ch' np=5 ./runcase
solver='ch' np=7 ./runcase

solver='ch' ns=1 ./runcase
solver='ch' ns=3 ./runcase

solver='ch' hp=2 ./runcase
solver='ch' hp=3 ./runcase
solver='ch' hp=5 ./runcase

