#!/bin/bash

set -eu

# test name
t=$1  
# config file
c=_${t}.conf
# reference
r=ref${t}

cp "$c" add.conf

# run 
make -f sim.makefile cleanrun

# cut pressure
cutp() {
  cut -d',' -f 10 --complement
}

cutpsh() {
  cut -d',' -f 22 --complement
}

eps=1e-6

if [ "$t" == "gravity" ] ; then
  eps=1e-5
fi

a=0
for f in $r/traj_* ; do
  echo $f
  s=$(basename $f)
  q="ch.diffnum <( cutp < $s ) <( cutp < $f ) $eps"
  if ! eval "${q}" ; then
    a=$((a+1))
  fi
done

for f in $r/trajsh_* ; do
  echo $f
  s=$(basename $f)
  q="ch.diffnum <( cutpsh < $s ) <( cutpsh < $f ) $eps"
  if ! eval "${q}" ; then
    a=$((a+1))
  fi
done

exit $a
